define(['durandal/system', 'pkg_linxtraining001-bv-spa/services/DataDomains', 'services/logger', 'breeze', 'durandal/app', 'managers/__auth', 'viewmodels/shared/modal', 'viewmodels/shared/modal2'],
function (system, dataDomains, logger, breeze, app, managerAuth, modal, modal2) {
var result = function () {
    var getPivotLayouts = function (params, success, error) {
        return $.ajax({
            messageUser: 'Busca dos layouts exportados',
            contentType: 'application/json; charset=UTF-8',
            headers: managerAuth.getHeaders(),
            url: getServiceAddress('linxframeworkobjeto') + '/GetPivotLayouts?' +
                                                                   'rootNameSpace=' + params.rootNamespace +
                                                                   '&viewName=' + params.viewName +
                                                                   '&pivotName=' + params.pivotName +
                                                                   '&pivotDataSource=' + params.pivotDataSource,
            async: true,
            cache: false,
            error: error,
            success: success
        });
    };
    
    var getSelectedLayoutContent = function (params, success, error) {
        return $.ajax({
            messageUser: 'Busca de layout selecionado',
            contentType: 'application/json; charset=UTF-8',
            headers: managerAuth.getHeaders(),
            url: getServiceAddress('linxframeworkobjeto') + '/GetPivotLayout?uidObjetoConteudo=' + params.uidObjetoConteudo,
            async: true,
            cache: false,
            error: error,
            success: success
        });
    };
    var getServiceAddress = function(apiPart) {
       return managerAuth.getServiceAddress(apiPart, businessAssemblyName);
    };
    var getAccessGroup = function() {
       return '00000000-0000-0000-0000-000000000000';
    };
    var getNewGuid = function() {
       return breeze.core.getUuid();
    };
    var getDataFeedUrl = function() {
       return getServiceAddress('LinxTraining001DetalhamentoVendaOData');
    };
    var getDataServiceUrl = function () {
       return getServiceAddress(controllerName);
    };
    var setServiceBusUrl = function (url) {
       if (dataService) { dataService.serviceName = (isNullOrEmpty(url) ? getDataServiceUrl() : url + controllerName); }
    };
    var initializePOCO = function(ownerReference, entityName) {
       if (ownerReference && !ownerReference.RowDataId) { eval(entityName + 'Initializer(ownerReference, true);'); }
    };
    var businessAssemblyName = 'LinxTraining001.BV';
    var controllerName = 'LinxTraining001DetalhamentoVenda';
    var dataService = new breeze.DataService({
        serviceName: getDataServiceUrl(),
        hasServerMetadata: false // don't ask the server for metadata
    });
    var manager = new breeze.EntityManager({ dataService: dataService });
    manager.entityChanged.subscribe(function(changeArgs) {
        if (changeArgs.entityAction === breeze.EntityAction.PropertyChange) {
            if ((typeof changeArgs.args.newValue) === 'number' && changeArgs.args.oldValue < 0 && changeArgs.args.newValue > 0 && changeArgs.entity.isPrimaryKey(changeArgs.args.propertyName)) vm.replaceInnerUIsKeys(changeArgs.entity, changeArgs.args.propertyName, changeArgs.args.oldValue, changeArgs.args.newValue);
            if (typeof changeArgs.entity.OnPropertyChanged == 'function')
                changeArgs.entity.OnPropertyChanged(changeArgs.args.propertyName, changeArgs.args.oldValue, changeArgs.args.newValue);
        }
    });
    var enableChangeTrack = true;
    var entityPropChanged = function(entity, propName, oldVal, newVal) {
        if (!enableChangeTrack) return true;
        var result = true;
        if ((typeof entity.OnPropertyChanged == 'function') && oldVal !== newVal)
            result = (entity.OnPropertyChanged(propName, oldVal, newVal) !== false);
        if (result && ['U', 'I', 'D'].indexOf(entity.ChangeState) < 0) { entity.createOriginal(propName, oldVal); entity.ChangeState = 'U'; if (entity.setParentAsModified) entity.setParentAsModified(); }
        if (result && (typeof newVal) === 'number' && oldVal < 0 && newVal > 0 && entity.isPrimaryKey(propName)) vm.replaceInnerUIsKeys(entity, propName, oldVal, newVal);
        return result;
    }
    var metadataStore = manager.metadataStore;
    var EntityQuery = breeze.EntityQuery;
    // Extract Breeze metadata definition types
    var DataType = breeze.DataType;
    var AutoGeneratedKeyType = breeze.AutoGeneratedKeyType;
    var Validator = breeze.Validator;
    Validator.hasValueValidator = new breeze.Validator('hasValueValidator', hasValueValidationFn, { messageTemplate: "'%displayName%' é requerido" });
    //#region Metadata Info
    var metadataInfo = [];
    var dataExportInfo = [];
    var entityNames = [];
    var lookUpNames = [];
    var entitylookUps = [];
    entityNames.push('VendasView');
    metadataInfo['VendasView'] = [
        { key: 'Data', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'Data', width: '120px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
        { key: 'IDClientes', isDomain: false, domainName: '', lookupPropertyName: 'IDClientes', lookupVisibleColumns: '', isRequired: true, maxLength: 36, isPartOfKey: false, headerText: 'ID Clientes', width: '271px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'IDVendas', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: true, headerText: 'GOSTOSAOPai', width: '179px', dataType: 'number', format: 'int', hidden: true, unbound: false, group: null },
        { key: 'Nome', isDomain: false, domainName: '', lookupPropertyName: 'Nome', lookupVisibleColumns: '', maxLength: 40, validateMaxLength: true, isPartOfKey: false, headerText: 'Nome2', width: '421px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'Origem', isDomain: true, domainName: 'LXOrigem', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: false, headerText: 'Origem', width: '200px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'OrigemName', isDomain: true, domainName: 'LXOrigem', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Origem (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'ValorTotal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'ValorTotal', width: '166px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'VendaVip', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'VendaVip', width: '140px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null }
    ];
    dataExportInfo['VendasView'] = [ 
        { name: 'VendasView', canExportMedia: true , canExportReport: true, actionExport: 'LinxTraining001DetalhamentoVenda/GetVendasViewToExcel', actionReport: 'LinxTraining001DetalhamentoVenda/GetVendasViewToReportXml', actionFeed: 'LinxTraining001DetalhamentoVendaOData/VendasView', actionName: 'LinxTraining001DetalhamentoVenda/GetVendasViewByEntitySearchNoAssociations', display: 'VendasView',  metaData: function() { return metadataInfo['VendasView']; } }
        , { name: 'VendaDetalheView', canExportMedia: true , canExportReport: true, actionExport: 'LinxTraining001DetalhamentoVenda/GetVendaDetalheViewParentCompositionToExcel', actionReport: 'LinxTraining001DetalhamentoVenda/GetVendaDetalheViewParentCompositionToReportXml', actionFeed: 'LinxTraining001DetalhamentoVendaOData/VendaDetalheViewParentComposition', actionName: 'LinxTraining001DetalhamentoVenda/GetVendaDetalheViewParentCompositionByEntitySearchNoAssociations', display: 'VendaDetalheView',  metaData: function() { return metadataInfo['VendaDetalheViewParentComposition']; } }
    ];
    entitylookUps.push('VendasView');
    entitylookUps['VendasView'] = [];
    entitylookUps['VendasView'].push('LookUpClientes');
    lookUpNames.push('LookUpClientes');
    metadataInfo['LookUpClientes'] = [
        { key: 'IDClientes', relatedKey: 'IDClientes', maxLength: 36, isPartOfKey: true, headerText: 'ID Clientes', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'Nome', relatedKey: 'Nome', maxLength: 40, isPartOfKey: false, headerText: 'Nome', width: '400px', dataType: 'string', format: '', hidden: false, unbound: false, group: null }
    ];
    entityNames.push('VendaDetalheView');
    metadataInfo['VendaDetalheView'] = [
        { key: 'Hora', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Hora', width: '120px', dataType: 'date', format: 'dd/MM/yyyy', hidden: true, unbound: false, group: null },
        { key: 'IDVendaDetalhe', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: true, headerText: 'ID VendaDetalhe', width: '231px', dataType: 'number', format: 'int', hidden: true, unbound: false, group: null },
        { key: 'IDVendas', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'GOSTOSAOFIlho', width: '205px', dataType: 'number', format: 'int', hidden: true, unbound: false, group: null },
        { key: 'Preco', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Preço', width: '110px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'Produto', isDomain: true, domainName: 'ProdutoDomain', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'Produto', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'ProdutoName', isDomain: true, domainName: 'ProdutoDomain', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Produto (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'Quantidade', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Quantidade', width: '166px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null }
    ];
    entityNames.push('VendaDetalheViewParentComposition');
    metadataInfo['VendaDetalheViewParentComposition'] = [
        { key: 'Hora', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Hora', width: '120px', dataType: 'date', format: 'dd/MM/yyyy', hidden: true, unbound: false, group: null },
        { key: 'IDVendaDetalhe', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: true, headerText: 'ID VendaDetalhe', width: '231px', dataType: 'number', format: 'int', hidden: true, unbound: false, group: null },
        { key: 'IDVendas', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'GOSTOSAOFIlho', width: '205px', dataType: 'number', format: 'int', hidden: true, unbound: false, group: null },
        { key: 'Preco', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Preço', width: '110px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'Produto', isDomain: true, domainName: 'ProdutoDomain', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'Produto', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'ProdutoName', isDomain: true, domainName: 'ProdutoDomain', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Produto (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'Quantidade', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Quantidade', width: '166px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Data', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'Data', width: '120px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
        { key: 'IDClientes', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 36, isPartOfKey: false, headerText: 'ID Clientes', width: '271px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'Nome', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 40, validateMaxLength: true, isPartOfKey: false, headerText: 'Nome2', width: '421px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'Origem', isDomain: true, domainName: 'LXOrigem', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: false, headerText: 'Origem', width: '200px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'OrigemName', isDomain: true, domainName: 'LXOrigem', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Origem (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'ValorTotal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'ValorTotal', width: '166px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'VendaVip', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'VendaVip', width: '140px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null }
    ];
    dataExportInfo['VendaDetalheView'] = [ 
        { name: 'VendaDetalheView', canExportMedia: true , canExportReport: true, actionExport: 'LinxTraining001DetalhamentoVenda/GetVendaDetalheViewToExcel', actionReport: 'LinxTraining001DetalhamentoVenda/GetVendaDetalheViewToReportXml', actionFeed: 'LinxTraining001DetalhamentoVendaOData/VendaDetalheView', actionName: 'LinxTraining001DetalhamentoVenda/GetVendaDetalheViewByEntitySearchNoAssociations', display: 'VendaDetalheView',  metaData: function() { return metadataInfo['VendaDetalheView']; } }
    ];
    entitylookUps.push('VendaDetalheView');
    entitylookUps['VendaDetalheView'] = [];
    var lookUpProperties = [];
    //#endregion Metadata Info
    //#region dataParameters
    var dataParameters = {
        isLoaded: false,
        parameters: [],
        registerParameters: function (parameterList, complete) {
            if (parameterList !== '') {
                var variation = '{TBC_GRUPO_ECONOMICO|' + managerAuth.loginInfo.IdLinxGrupoEconomico.toString() + '|TCS_USUARIO|' + managerAuth.loginInfo.UidUsuario + (vm != null && vm.getBandeiraRede() > 0 ? '|TBC_BANDEIRA_REDE|' + vm.getBandeiraRede().toString() : '') + '}';
                $.ajax({
                    type: 'GET',
                    url: getServiceAddress('LinxFrameworkParametro') + '/GetParameterValue?serializedParameterList=' + stringReplace(parameterList, '{}', variation),
                    dataType: 'json',
                    cache: false,
                    headers: managerAuth.getHeaders(),
                    error: function (jqXHR, textStatus, errorThrown) {
                        var msg = 'Os seguintes parâmetros não foram pesquisados: [' + parameterList + ']';
                        app.showMessage(msg, 'Alerta', ['Ok']);
                        dataParameters.isLoaded = true;
                    },
                    success: function (data) {
                        var parametersName = '';
                        var parameters = data.split('#');
                        for (var idx in parameters) {
                            var values = parameters[idx].split('|');
                            var pName = values[0];
                            var pValue = values[1];
                            dataParameters.parameters[pName] = pValue;
                        }
                        dataParameters.isLoaded = true;
                        if (complete) complete();
                    }
                });
            }
        }
    };
    //#endregion dataParameters
    //#region Classes Map
    var sequences = [];
    var getNextSequence = function(entityName) {
        if (!sequences[entityName]) resetSequence(entityName);
        sequence = sequences[entityName];
        sequences[entityName]++;
        return sequence;
    };
    var resetSequence = function(entityName) {
        sequences[entityName] = 0;
    };
    var getSequence = function(entityName) {
        if (!sequences[entityName]) resetSequence(entityName);
        return sequences[entityName];
    };
    
    // Configure VendasView data type
    metadataStore.addEntityType({
    shortName: "VendasView",
    namespace: "LinxTraining001.BV.DetalhamentoVenda",
    autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
    dataProperties: {
    Data: { dataType: DataType.DateTime, isNullable: false, isPartOfKey: false, defaultValue: '', validators: [ Validator.hasValueValidator]  }
    ,IDClientes: { dataType: DataType.Guid, isNullable: false, isPartOfKey: false, validators: [ Validator.hasValueValidator]  }
    ,IDVendas: { dataType: DataType.Int32, isNullable: false, isPartOfKey: true, validators: [ Validator.hasValueValidator]  }
    ,Nome: { dataType: DataType.String, maxLength: 40, isNullable: true, isPartOfKey: false, validators: [ Validator.maxLength( {maxLength: 40})]  }
    ,Origem: { dataType: DataType.Int32, isNullable: true, isPartOfKey: false, validators: [ Validator.hasValueValidator]  }
    ,OrigemName: { dataType: DataType.String, isNullable: false, isPartOfKey: false, validators: [] }
    ,ValorTotal: { dataType: DataType.Decimal, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,VendaVip: { dataType: DataType.Boolean, isNullable: true, isPartOfKey: false, validators: [ ]  }
                    },
    navigationProperties: {
    // Returns collections of details and associates with Parent
    VendaDetalheViewList: { entityTypeName: "VendaDetalheView:#LinxTraining001.BV.DetalhamentoVenda", isScalar: false, invForeignKeyNames: ["IDVendas"], associationName: "FK_VendasView_VendaDetalheView" }
                          }
    });
    lookUpProperties['VendasView'] = {IDClientes: 'LookUpClientes', Nome: 'LookUpClientes'};
    var VendasViewInitializer = function (ownerReference, isPOCO) {
       ownerReference.RowDataId = (isPOCO === true ? getNextSequence('VendasView') : ko.observable(getNextSequence('VendasView')));
       ownerReference.currentVendaDetalheView = ko.observable(null);
       //Adjust details for a POCO reference
       if (isPOCO === true) {
           ownerReference.VendaDetalheViewList = ko.observableArray(ownerReference.VendaDetalheViewList);
       }
       ownerReference.setRemovedLookupFields = function(removedFields) {
           for (var idxLUp in entitylookUps[ownerReference.typeName]) {
               var hasKeyValue = false;
               var luName = entitylookUps[ownerReference.typeName][idxLUp];
               var luMeta = metadataInfo[luName];
               for (var idxProp in luMeta) {
                   var prop = luMeta[idxProp];
                   if (!isNullOrEmpty(prop.relatedKey) && prop.isPartOfKey) {
                       hasKeyValue = !isNullOrEmpty(getAbsoluteValue(ownerReference[prop.relatedKey]));
                       break;
                   }
               }
               if (hasKeyValue) {
                   for (var idxProp in luMeta) {
                       var prop = luMeta[idxProp];
                       if (!isNullOrEmpty(prop.relatedKey) && !prop.isPartOfKey) {
                           removedFields.push(prop.relatedKey);
                       }
                   }
               }
           }
       }
       ownerReference.getJExpression = function(listFilterRange, removedFields, noDetails) {
           if (ownerReference.excludedFilters && ownerReference.excludedFilters.length > 0) { if (removedFields instanceof Array) removedFields = removedFields.concat(ownerReference.excludedFilters); else removedFields = ownerReference.excludedFilters; }
           ownerReference.setRemovedLookupFields(removedFields);
           var jExpression = getJEntityExpression(ownerReference, app, listFilterRange, removedFields);
           if (jExpression === 'Error') return jExpression;
           if (noDetails !== true && ownerReference.VendaDetalheViewList && ownerReference.VendaDetalheViewList().length > 0) {
             var detailExpr = ownerReference.VendaDetalheViewList()[0].getJExpression(listFilterRange, ['IDVendas']);
             if (detailExpr === 'Error') return detailExpr;
             jExpression += detailExpr;
           }
           return jExpression;
      };
       ownerReference.createOriginal = function(propertyName, oldValue) {
           ownerReference.original = ownerReference.getPrimitiveDTO();
           if (propertyName) ownerReference.original[propertyName] = oldValue;
       }
       ownerReference.restoreOriginal = function() {
           if (!isNullOrEmpty(ownerReference.original)) {
              enableChangeTrack = false;
              var properties = metadataInfo[ownerReference.typeName];
              for (var i = 0; i < properties.length; i++) {
                  var propertyName = properties[i].key;
                  if ((typeof ownerReference.original[propertyName]) !== 'undefined') ownerReference[propertyName] = ownerReference.original[propertyName];
              }
              delete ownerReference.original;
              enableChangeTrack = true;
           }
       }
       if (isPOCO === true) {
           ownerReference.getValidationErrors = function(propertyName) {
               var errors = [];
               if (!vm.canReportErrors) return errors;
               if (!ownerReference.ChangeState || ['I', 'U'].indexOf(ownerReference.ChangeState) < 0) return errors;
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                   var prop = properties[i];
                   if (isNullOrEmpty(propertyName) || prop.key == propertyName) {
                       if (prop.isRequired === true && !prop.isPartOfKey && isNullOrEmpty(ownerReference[prop.key])) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] é requerido.');
                       if (prop.validateMaxLength === true && prop.maxLength > 0 && !isNullOrEmpty(ownerReference[prop.key]) && ownerReference[prop.key].length > prop.maxLength) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] permite no máximo ' + prop.maxLength.toString() + ' caractere(s).');
                   }
               }
               if (isNullOrEmpty(propertyName)) {
                   for (var i = 0; i < ownerReference.VendaDetalheViewList().length; i++) {
                       var detail = ownerReference.VendaDetalheViewList()[i];
                       errors = errors.concat(detail.getValidationErrors());
                   }
               }
               return errors;
           }
       }
       ownerReference.getPrimitiveDTO = function(loadDetails) {
           var command = '';
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
               command += (command === '' ? '' : ', ') + properties[i].key + ': getAbsoluteValue(ownerReference.' + properties[i].key + ')';
               if (properties[i].isDomain && properties[i].key.length > 4) command += (command === '' ? '' : ', ') + strLeft(properties[i].key, properties[i].key.length - 4) + ': getAbsoluteValue(ownerReference.' + strLeft(properties[i].key, properties[i].key.length - 4) + ')';
           }
           eval('var result = { ' + command + ' };');
           if (loadDetails) {
               result.VendaDetalheViewList = [];
               var sourceList = getAbsoluteValue(ownerReference.VendaDetalheViewList);
               if (sourceList && sourceList.length > 0) {
                   for (var i = 0; i < sourceList.length; i++) {
                       if (['U', 'I', 'D'].indexOf(sourceList[i].ChangeState) >= 0) result.VendaDetalheViewList.push(sourceList[i].getPrimitiveDTO(sourceList[i].ChangeState != 'D'));
                   }
               }
           }
           return result;
       };
       ownerReference.getAllDetailChanges = function() {
           var result = [];
           var _VendaDetalheViewList = getAbsoluteValue(ownerReference.VendaDetalheViewList);
           if (_VendaDetalheViewList && _VendaDetalheViewList.length > 0) {
               for (var i = 0; i < _VendaDetalheViewList.length; i++) {
                   var detail = _VendaDetalheViewList[i];
                   if (['U', 'I', 'D'].indexOf(detail.ChangeState) >= 0) {
                       result.push(detail);
                       result = result.concat(detail.getAllDetailChanges());
                   }
               }
           }
           return result;
       };
       ownerReference.copyDataFrom = function(originData, copyDetails) {
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
                setAbsoluteValue(ownerReference, properties[i].key, getAbsoluteValue(originData[properties[i].key]));
           }
           if (copyDetails) {
               if (ownerReference.VendaDetalheViewList && originData.VendaDetalheViewList) {
                   var toList = getAbsoluteValue(ownerReference.VendaDetalheViewList);
                   var fromList = getAbsoluteValue(originData.VendaDetalheViewList);
                   for (var idxElem = toList.length - 1; idxElem >= 0; idxElem--) {
                      if (toList[idxElem].ChangeState === 'D') toList.splice(idxElem, 1);
                   }
                   for (var idxElem = toList.length - 1; idxElem >= 0; idxElem--) {
                          if (toList[idxElem].ChangeState !== 'N') {
                               var fromObj = [];
                               if (toList[idxElem].ChangeState == 'I') {
                                   fromObj = _.where(fromList, { TemporaryIDVendaDetalhe: toList[idxElem]['IDVendaDetalhe'] });
                               } else {
                                   fromObj = _.where(fromList, { IDVendaDetalhe: toList[idxElem]['IDVendaDetalhe'] });
                               }
                               if (fromObj.length > 0) toList[idxElem].copyDataFrom(fromObj[0], true);
                          }
                   }
               }
           }
       };
          ownerReference.commitDetailsVisualPendings = function() {
              vm.dataBind('VendaDetalheViewList', true);
              if (ownerReference.currentVendaDetalheView()) ownerReference.currentVendaDetalheView().commitDetailsVisualPendings();
          }
          ownerReference.refreshData = function(noWait, succeeded) {
             var filterByKey = 'VendasView{' + 'IDVendas#==#I' + getAbsoluteValue(ownerReference.IDVendas).toString() + '}';
             if (!ownerReference.isPOCO && ownerReference.entityAspect && !ownerReference.isDetached() && !ownerReference.isUnchanged()) ownerReference.entityAspect.setUnchanged();
             return dataContext.getVendasViewByEntitySearchNoAssociations(filterByKey, 0, 0, false, true, ownerReference.isPOCO === true).then(querySucceeded);
             function querySucceeded(data) {
                if (succeeded) { succeeded(data); }
                if (data.results.length == 0) { return; }
                if (ownerReference.isPOCO) { for (var idx = 0; idx < data.results.length; idx++) { ownerReference.copyDataFrom(data.results[idx]); } }
                if (!noWait || ownerReference.atLeastOneDetailLoaded()) { vm.clearInnerUIs(ownerReference); ownerReference.fillDetails(true, '', false, noWait); }
           }
          }
       if (isPOCO === true) {
           ownerReference.isPOCO = true;
           ownerReference.enableDetailsDataTack = function(breezeReference) {
              breezeReference.VendaDetalheViewIsLoaded = ownerReference.VendaDetalheViewIsLoaded;
              for (var idx = 0; idx < ownerReference.VendaDetalheViewList().length; idx++) {
                  var entity = ownerReference.VendaDetalheViewList()[idx];
                  if (entity.isPOCO)  {
                      var newReference = createEntity(entity.typeName, entity.getPrimitiveDTO(), true);
                      entity.enableDetailsDataTack(newReference);
                  }
              }
              if (breezeReference) breezeReference.setCurrentDetails();
           };
       }
       ownerReference.isAdded = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Added;
       });
       ownerReference.isDeleted = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Deleted;
       });
       ownerReference.isModified = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Modified;
       });
       ownerReference.isDetached = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Detached;
       });
       ownerReference.isUnchanged = (isPOCO === true ? function() { return true; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Unchanged;
       });
       ownerReference.setModified = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setModified();
       });
       ownerReference.setUnchanged = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setUnchanged();
       });
       ownerReference.serverDataType = [];
       ownerReference.serverDataType['Data'] = 'T';
       ownerReference.serverDataType['IDClientes'] = 'G';
       ownerReference.serverDataType['IDVendas'] = 'I';
       ownerReference.serverDataType['Nome'] = 'S';
       ownerReference.serverDataType['Origem'] = 'I';
       ownerReference.serverDataType['ValorTotal'] = 'D';
       ownerReference.serverDataType['VendaVip'] = 'B';
       ownerReference.typeName = 'VendasView';
       ownerReference.isPrimaryKey = function(propertyName) {
           var keys = [ 'IDVendas' ];
           return keys.indexOf(propertyName) >= 0;
       }
       ownerReference.getDisplayName = function(propertyName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          return (property != null ? property.headerText : propertyName);
       }
       ownerReference.setDisplayName = function(propertyName, displayName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          if (property != null) property.headerText = displayName;
       }
       ownerReference.setBandeiraRede = function (idBandeiraRede) {
       };
       ownerReference.setGpecon = function (idGpecon) {
       };
       ownerReference.UpdateIndependentRelation = function(detailName) {
           var cacheElements = dataContext.getEntities(detailName);
           for (var idxR = 0; idxR < cacheElements.length; idxR++) {
               if (typeof cacheElements[idxR].VendasView !== 'function') { return; }
               else  if (cacheElements[idxR].VendasView() != ownerReference) { cacheElements[idxR].VendasView(ownerReference); }
           }
       }
       //#region Lookup Extended Methods
       if (isPOCO !== true) {
           ownerReference.getLookupPropertyName = function(propertyName) {
              var property = getEntityProperty(ownerReference.typeName, propertyName);
              return (property != null && !isNullOrEmpty(property.lookupPropertyName) ? property.lookupPropertyName : propertyName);
           }
           ownerReference.getLookupVisibleColumns = function(propertyName) {
              var property = getEntityProperty(ownerReference.typeName, propertyName);
              return (property != null ? property.lookupVisibleColumns : '');
           }
           ownerReference.getLookUpClientFilterExpressions = function (lookupName, lookupInfo) {
               return '';
           };
        
           ownerReference.getLookupDisplay = function (lookupName) {
               var displayName = '';
               if (lookupName === 'LookUpClientes') {
                   displayName = ' de Clientes';
               }
               return 'Seleção' + displayName;
           };
        
           ownerReference.getSpecializedLookup = function (lookupName, lookupInfo, fieldToSearch, valueToSearch, ownerReference, allowMultiSelectionInSearch) {
               var specializedLookup = '';
               return specializedLookup;
           };
        
           ownerReference.getSubQueryFilterFromLookUpClientes = function (propertyName) {
               var filter = '';
               return filter;
           }
           ownerReference.canGetClientFilter = function (lookupName) {
               return true;
           }
           ownerReference.validatedlookupsArray = [];
           ownerReference.internalLookupSearch = function (lookupName, fieldToSearch, operation, querySucceeded, lookupInfo, valueToSearch, beforeGettingLookup, referencefield) {
               if (!lookupName || !fieldToSearch) { console.warn('lookupName or fieldToSearch is Empty!'); querySucceeded(null); return lookupInfo; }
               if (isNullOrEmpty(lookupInfo.lastJEntityExpression)) {
                   if (isNullOrEmpty(referencefield)) referencefield = fieldToSearch;
                   if ((typeof valueToSearch) === 'undefined')
                       valueToSearch = ownerReference[referencefield]();
                   var extraFilters = '';
                   if (ownerReference.canGetClientFilter(lookupName)) {
                       extraFilters = ownerReference.getLookUpClientFilterExpressions(lookupName, lookupInfo);
                       if (extraFilters === 'Error') { querySucceeded(null); return lookupInfo; }
                       if (typeof ownerReference['BeforeGet' + lookupName + 'Query'] == 'function') {
                           var customFilter = ownerReference['BeforeGet' + lookupName + 'Query']();
                           if (customFilter === 'Error') { querySucceeded(null); return lookupInfo; }
                           if (!isNullOrEmpty(customFilter)) { extraFilters = (isNullOrEmpty(extraFilters) ? '' : extraFilters + ';') + customFilter; }
                       }
                       if (typeof ownerReference['getSubQueryFilterFrom' + lookupName] == 'function') {
                           var customFilter = ownerReference['getSubQueryFilterFrom' + lookupName](referencefield);
                           if (customFilter === 'Error') { querySucceeded(null); return lookupInfo; }
                           if (!isNullOrEmpty(customFilter)) { extraFilters = (isNullOrEmpty(extraFilters) ? '' : extraFilters + ';') + customFilter; }
                       }
                   }
                   var completeExpression = getLookUpJEntityExpression(lookupName, ownerReference, fieldToSearch, valueToSearch, extraFilters, referencefield, app);
                   if (completeExpression === 'Error') { querySucceeded(null); return lookupInfo; }
                   lookupInfo.lastJEntityExpression = completeExpression;
               }
               switch (operation) {
                   case 'F':
                       lookupInfo.pageSkip = 0;
                       break;
                   case 'B':
                       lookupInfo.pageSkip = lookupInfo.pageSkip - 1;
                       break;
                   case 'N':
                       lookupInfo.pageSkip = lookupInfo.pageSkip + 1;
                       break;
                   case 'L':
                       lookupInfo.pageSkip = lookupInfo.totalPages();
                       break;
                   default:
               }
        
               var e = { cancel: false, lookupName: lookupName, jEntitySearch: lookupInfo.lastJEntityExpression, entity: ownerReference, viewModel: lookupInfo.vm };
               if (beforeGettingLookup) beforeGettingLookup(e);
               if (e.cancel) { querySucceeded(null); return lookupInfo; }
               if(lookupInfo.lastJEntityExpression !== e.jEntitySearch)
                   lookupInfo.lastJEntityExpression = e.jEntitySearch;
               if (lookupInfo.vm) lookupInfo.vm.dataToolbar.isBusy(true);
               var returnQueryResult = function (data) { lookupInfo.totalRecords = (isNullOrEmpty(data.inlineCount) ? data.results.length : data.inlineCount); querySucceeded(data); };
               eval('dataContext.get' + lookupName + 'ByEntitySearch(lookupInfo.lastJEntityExpression, (isNullOrEmpty(lookupInfo.fieldToSort) ? fieldToSearch : lookupInfo.fieldToSort), lookupInfo.pageSize*lookupInfo.pageSkip, lookupInfo.pageSize, lookupInfo.sortDirection).then(returnQueryResult).fail(queryFailed)').fin(function(){ if (lookupInfo.vm) lookupInfo.vm.dataToolbar.isBusy(false); });
               return lookupInfo;
           };
        
           ownerReference.hasValidClientFilter = function (lookupName, lookupInfo) {
               var checkClientFilter = ownerReference.getLookUpClientFilterExpressions(lookupName, lookupInfo);
               if (checkClientFilter === 'Error') { return false; }
               if (typeof ownerReference['BeforeGet' + lookupName + 'Query'] == 'function') {
                   checkClientFilter = ownerReference['BeforeGet' + lookupName + 'Query']();
                   if (checkClientFilter === 'Error') { return false; }
               }
               return true;
           }
        
           ownerReference.executeLookUp = function (lookupName, fieldToSearch, beforeGettingLookup, vm, valueToSearch, finished, comboCallBack, allowMultiSelectionInSearch) {
               if (!lookupName || !fieldToSearch) { console.warn('lookupName or fieldToSearch is Empty!'); if (finished) finished(false, null); return; }
               var lookupFieldName = ownerReference.getLookupPropertyName(fieldToSearch);
               vm.dataBind('', true);
               var lookupInfo = new lookupInformation();
               lookupInfo.visibleColumns = ownerReference.getLookupVisibleColumns(fieldToSearch);
               lookupInfo.vm = vm;
               lookupInfo.isMultiSelection = lookupName.in([]);
               var specializedLookup = ownerReference.getSpecializedLookup(lookupName, lookupInfo, lookupFieldName, valueToSearch, ownerReference, allowMultiSelectionInSearch);
               if (isNullOrEmpty(specializedLookup)) {
                       ownerReference.internalLookupSearch(lookupName, lookupFieldName, 'F',
                           function querySucceeded(data) {
                               if (typeof ownerReference['OnLoading' + lookupName + 'Query'] == 'function') {
                                   ownerReference['OnLoading' + lookupName + 'Query'](data);
                               }
                               if ((typeof comboCallBack) === 'function') {
                                   return comboCallBack(data ? data.results : null);
                               }
                               else if (data == null || data.results == null || data.results.length == 0) {
                                   if (finished) finished(false, null);
                                   ownerReference.clearLookUp(lookupName);
                                   if (data != null) app.showMessage('A informação de Lookup [' + ownerReference.getDisplayName(fieldToSearch) + '] não foi encontrada!', 'Informação', ['Ok']);
                                   return;
                               }
                               lookupInfo.totalRecords = (isNullOrEmpty(data.inlineCount) ? data.results.length : data.inlineCount);
                               showLookUp(dataContext, ownerReference, ownerReference.getLookupDisplay(lookupName), lookupName, lookupFieldName, ownerReference.internalLookupSearch, lookupInfo, 
                                   function (confirm, values) {
                                       var results = '';
                                       if (values != null && values.length > 1) {
                                           $.each(values, function (index, item) { results += (index == 0 ? '' : ',') + item[lookupFieldName].toString().trim() });
                                           results = '[' + results + ']';
                                           ownerReference[fieldToSearch](results);
                                           if (vm.entitySearchRange[ownerReference.typeName + fieldToSearch] === undefined)
                                               vm.entitySearchRange[ownerReference.typeName + fieldToSearch] = ko.observable(results);
                                           else vm.entitySearchRange[ownerReference.typeName + fieldToSearch](results);
                                           document.dispatchEvent(dataUpdateEvent);
                                       }
                                       if (finished) finished(confirm, results);
                                   }, data.results, allowMultiSelectionInSearch);
                       }, lookupInfo, valueToSearch, beforeGettingLookup, fieldToSearch);
               }
               else {
                       var currentModal = (modal.inUse ? modal2 : modal);
                       if (currentModal.inUse === false) {
                           //Check Client Validations
                           if (!ownerReference.hasValidClientFilter(lookupName, lookupInfo)) { if (finished) finished(false); return; }
                           //Show External Lookup
                           currentModal.showModal(specializedLookup.moduleName, specializedLookup.uiSettings, ownerReference.getLookupDisplay(lookupName), ['Ok', 'Cancelar'], 'large').then(function (r, data) {
                           if (r == 'Ok') {
                               if (!currentModal.internalUIs || currentModal.internalUIs.length != 1) { if (finished) finished(false); return; }
                               var lookupVM = currentModal[currentModal.internalUIs[0]]; 
                               if (!lookupVM) return; 
                               if (typeof lookupVM == 'function') lookupVM = lookupVM(); 
                               currentModal[currentModal.internalUIs[0]] = null; 
                               var selectedItems = lookupVM.getSpecializedLookupItems(); 
                               if (vm.status() == 'C' && selectedItems != null && selectedItems.length > 1) { 
                               	var results = '';
                               	$.each(selectedItems, function (index, item) { results += (index == 0 ? '' : ',') + (typeof item[lookupFieldName] == 'function' ? item[lookupFieldName]() : item[lookupFieldName]).toString().trim() });
                               	results = '[' + results + ']'
                               	ownerReference[fieldToSearch](results);
                                   if (vm.entitySearchRange[ownerReference.typeName + fieldToSearch] === undefined)
                                       vm.entitySearchRange[ownerReference.typeName + fieldToSearch] = ko.observable(results);
                                   else vm.entitySearchRange[ownerReference.typeName + fieldToSearch](results);
                                   document.dispatchEvent(dataUpdateEvent);
                               	if (finished) finished(true, results);
                               }
                               else if (selectedItems.length > 0) { dataContext['finalizeAll' + lookupName](ownerReference, selectedItems, '', lookupInfo); }
                           }
                           if (finished) finished(r === 'Ok');
                       });
                   }
                   if (finished) finished(false);
               }
           };
           ownerReference.clearLookUp = function (lookupName) {
               return eval('dataContext.clear' + lookupName + '(ownerReference)');
           };
       }
       //#endregion Lookup Extended Methods
       ownerReference.setDefaults = function () {
       };
       ownerReference.delete = function() {
           if (ownerReference.isDetached()) {
               app.showMessage('A informação selecionada não pode ser excluída!', 'Alerta', ['Ok']);
               return;
           }
           if (ownerReference.setParentAsModified) ownerReference.setParentAsModified();
           if (!isNullOrEmpty(ownerReference.VendaDetalheViewList()) && ownerReference.VendaDetalheViewList().length > 0) {
              var details = [].concat(ownerReference.VendaDetalheViewList());
              for (var idx = 0; idx < details.length; idx++) {
                details[idx].delete();
              }
           }
           if (ownerReference.entityAspect) ownerReference.entityAspect.setDeleted(); // mark for deletion
       };
       ownerReference.setParentAsModified = function() {
       };
       ownerReference.getParent = function() {
           return null;
       };
       ownerReference.getSelfList = function() {
           return vm.dataView();
       };
       ownerReference.namespace = 'LinxTraining001.BV.DetalhamentoVenda';
       ownerReference.myProperties = [ 'Data','IDClientes','IDVendas','Nome','Origem','ValorTotal','VendaVip' ];
       ownerReference.queryRequiredProperties = {  };
       ownerReference.excludedFilters = [];
       ownerReference.getCurrentElements = function() {
           var result = [ ownerReference ];
       if (!isNullOrEmpty(ownerReference.currentVendaDetalheView())) { result = result.concat(ownerReference.currentVendaDetalheView().getCurrentElements()); }
           return result;
       };
       ownerReference.checkForSendingAllRowsToServer = function() {
       };
       ownerReference.GetJsWhereDetailRelationForVendaDetalheView = function(customParentRelation) {
       return 'VendaDetalheView{' + (!isNullOrEmpty(customParentRelation) ? customParentRelation : 'IDVendas#==#' + ownerReference.serverDataType['IDVendas'] + getAbsoluteValue(ownerReference.IDVendas).toString()) + '}';    
       }
       ownerReference.VendaDetalheViewIsLoaded = false;
       ownerReference.detailsLoaded = function() {
           return ownerReference.VendaDetalheViewIsLoaded;
       }
       ownerReference.atLeastOneDetailLoaded = function() {
           return ownerReference.VendaDetalheViewIsLoaded;
       }
       ownerReference.adjustDetailsLoaded = function(value) {
           ownerReference.VendaDetalheViewIsLoaded = value;
           if (value === false && ownerReference.isPOCO)
               ownerReference.VendaDetalheViewList([]);
       }
       ownerReference.fillDetails = function(force, detailName, noInnerUIs, noWait, callback, customParentRelation) {
          if (typeof force === 'undefined') force = false;
          if (force) vm.clearInnerUIs(ownerReference);
          if (!noInnerUIs) vm.queryInnerUIs(ownerReference);
          if (ownerReference.isAdded()) return;
          var _VendaDetalheViewRemoteComplete = false;
          var detachList_VendaDetalheView = [];
          if (force) {
               if (isNullOrEmpty(detailName) || detailName == 'VendaDetalheView') ownerReference.VendaDetalheViewIsLoaded = false;
               if ((isNullOrEmpty(detailName) || detailName == 'VendaDetalheView') && ownerReference.VendaDetalheViewList && ownerReference.VendaDetalheViewList().length > 0) {
                   if (ownerReference.isPOCO) {
                       ownerReference.VendaDetalheViewList([]);
                   } else {
                       var detailList = ownerReference.VendaDetalheViewList();
                       for (var idx = detailList.length - 1; idx >= 0; idx--) {
                           detachList_VendaDetalheView.push(detailList[idx]);
                       }
                   }
               }
          }
    
          if (!ownerReference.VendaDetalheViewIsLoaded) {
            //Load VendaDetalheViewList
            if (isNullOrEmpty(detailName) || detailName === 'VendaDetalheView') {
              ownerReference.VendaDetalheViewIsLoaded = true;
              _VendaDetalheViewRemoteComplete = (ownerReference.VendaDetalheViewList && ownerReference.VendaDetalheViewList().length > 0);
              if ((force || !ownerReference.VendaDetalheViewList || ownerReference.VendaDetalheViewList().length === 0) && (!isNullOrEmpty(getAbsoluteValue(ownerReference.IDVendas)))) {
                var navQuery = EntityQuery.from('GetVendaDetalheViewByEntitySearchNoAssociations').noTracking(ownerReference.isPOCO === true)
                .orderBy('IDVendaDetalhe asc')
                    .withParameters({ jEntitySearch: ownerReference.GetJsWhereDetailRelationForVendaDetalheView(customParentRelation) })    ;
                vm.showProcessing('Pesquisando detalhes...');
                manager.executeQuery(navQuery).then(function (data) { if (ownerReference.isPOCO) { for (var idx = 0; idx < data.results.length; idx++) { initializePOCO(data.results[idx], 'VendaDetalheView'); data.results[idx].VendasView = ko.observable(ownerReference); } ownerReference.VendaDetalheViewList(data.results); } 
                   if (!ownerReference.isPOCO && detachList_VendaDetalheView.length > 0)
                   {
                       for (var idx = 0; idx < detachList_VendaDetalheView.length; idx++)
                       {
                           if (!data.results.contains(detachList_VendaDetalheView[idx]))
                               detachEntity(detachList_VendaDetalheView[idx]);
                           else {
                               if (force && detachList_VendaDetalheView[idx].atLeastOneDetailLoaded())
                                   detachList_VendaDetalheView[idx].fillDetails(force, '', false, noWait);
                           }
                       }
                   }
                   ownerReference.setCurrentDetails('VendaDetalheView'); notifyPresentation('VendaDetalheViewList');
                   _VendaDetalheViewRemoteComplete = true;
                   if (callback && (!isNullOrEmpty(detailName) || (_VendaDetalheViewRemoteComplete))) { callback(); }
                }).fail(queryFailed).fin(function() { vm.closeProcessing(); });
              } else { ownerReference.setCurrentDetails('VendaDetalheView'); notifyPresentation('VendaDetalheViewList'); }
            } else { if (!ownerReference.VendaDetalheViewIsLoaded && ownerReference.VendaDetalheViewList && ownerReference.VendaDetalheViewList().length > 0) { ownerReference.VendaDetalheViewIsLoaded = true; } notifyPresentation('VendaDetalheViewList'); }
          } else { 
            if (isNullOrEmpty(detailName) || detailName == 'VendaDetalheView') {
               notifyPresentation('VendaDetalheViewList');
               ownerReference.setCurrentDetails('VendaDetalheView');
            }
            _VendaDetalheViewRemoteComplete = true;
          }
          if (callback && ((!isNullOrEmpty(detailName) && (eval('_' + detailName + 'RemoteComplete && ownerReference.' + detailName + 'IsLoaded') == true)) || (isNullOrEmpty(detailName) && (_VendaDetalheViewRemoteComplete)))) { callback(); }
       };
       //Select first element as a current item of each detail
       ownerReference.setCurrentDetails = function(detailName) {
          if ((isNullOrEmpty(detailName) || detailName === 'VendaDetalheView')) {
               if (ownerReference.VendaDetalheViewList().length > 0) { ownerReference.currentVendaDetalheView(ownerReference.VendaDetalheViewList()[0]); ownerReference.currentVendaDetalheView().fillDetails(); }
               else { ownerReference.currentVendaDetalheView(null); ownerReference.notifyEmptyDetails('VendaDetalheView'); }
          }
       };
       ownerReference.notifyEmptyDetails = function(detailName) {
          if (detailName === 'VendaDetalheView') {
               notifyPresentation('VendaDetalheViewList');
               vm.queryInnerUIs(null, 'VendaDetalheView');
          }
       };
    //#region Extended Domain Names
       if (isPOCO !== true) {
           ownerReference.OrigemName.subscribe(
               function (newValue) {
                   if (newValue == null) { ownerReference.OrigemName(''); return; }
                   var value = (dataDomains.getId('LXOrigem', newValue));
                   if (value != ownerReference.Origem()) {
                       ownerReference.Origem(value);
                   }
            });
    
           ownerReference.Origem.subscribe(
           function (newValue) {
                   var value = isNullOrEmpty(newValue) ? '' : dataDomains.getName('LXOrigem', newValue);
                   if (value != ownerReference.OrigemName()) {
                       ownerReference.OrigemName(value);
               }
           });
       }
    //#endregion Extended Domain Names
    //#region Adjust details already loaded for a POCO reference
       if (isPOCO === true) {
           if ((typeof ownerReference.VendaDetalheViewList === 'function') && ownerReference.VendaDetalheViewList().length > 0) {
                for(var idx = 0; idx < ownerReference.VendaDetalheViewList().length; idx++) { VendaDetalheViewInitializer(ownerReference.VendaDetalheViewList()[idx], isPOCO); }
           }
       }
    //#endregion Adjust details already loaded for a POCO reference
    };
    metadataStore.registerEntityTypeCtor("VendasView", null, VendasViewInitializer);
    
    // Configure VendaDetalheView data type
    metadataStore.addEntityType({
    shortName: "VendaDetalheView",
    namespace: "LinxTraining001.BV.DetalhamentoVenda",
    autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
    dataProperties: {
    Hora: { dataType: DataType.DateTime, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,IDVendaDetalhe: { dataType: DataType.Int32, isNullable: false, isPartOfKey: true, validators: [ Validator.hasValueValidator]  }
    ,IDVendas: { dataType: DataType.Int32, isNullable: false, isPartOfKey: false, validators: [ ]  }
    ,Preco: { dataType: DataType.Decimal, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Produto: { dataType: DataType.String, maxLength: 10, isNullable: true, isPartOfKey: false, validators: [ Validator.hasValueValidator, Validator.maxLength( {maxLength: 10})]  }
    ,ProdutoName: { dataType: DataType.String, isNullable: false, isPartOfKey: false, validators: [] }
    ,Quantidade: { dataType: DataType.Int32, isNullable: true, isPartOfKey: false, validators: [ ]  }
                    },
    navigationProperties: {
    // Returns a single parent and associates with Details
    VendasView: { entityTypeName: "VendasView:#LinxTraining001.BV.DetalhamentoVenda", isScalar: true, foreignKeyNames: ["IDVendas"], associationName: "FK_VendasView_VendaDetalheView" }
    // Returns collections of details and associates with Parent
                          }
    });
    lookUpProperties['VendaDetalheView'] = {};
    var VendaDetalheViewInitializer = function (ownerReference, isPOCO) {
       ownerReference.RowDataId = (isPOCO === true ? getNextSequence('VendaDetalheView') : ko.observable(getNextSequence('VendaDetalheView')));
       ownerReference.setRemovedLookupFields = function(removedFields) {
           for (var idxLUp in entitylookUps[ownerReference.typeName]) {
               var hasKeyValue = false;
               var luName = entitylookUps[ownerReference.typeName][idxLUp];
               var luMeta = metadataInfo[luName];
               for (var idxProp in luMeta) {
                   var prop = luMeta[idxProp];
                   if (!isNullOrEmpty(prop.relatedKey) && prop.isPartOfKey) {
                       hasKeyValue = !isNullOrEmpty(getAbsoluteValue(ownerReference[prop.relatedKey]));
                       break;
                   }
               }
               if (hasKeyValue) {
                   for (var idxProp in luMeta) {
                       var prop = luMeta[idxProp];
                       if (!isNullOrEmpty(prop.relatedKey) && !prop.isPartOfKey) {
                           removedFields.push(prop.relatedKey);
                       }
                   }
               }
           }
       }
       ownerReference.getJExpression = function(listFilterRange, removedFields, noDetails) {
           if (ownerReference.excludedFilters && ownerReference.excludedFilters.length > 0) { if (removedFields instanceof Array) removedFields = removedFields.concat(ownerReference.excludedFilters); else removedFields = ownerReference.excludedFilters; }
           ownerReference.setRemovedLookupFields(removedFields);
           var jExpression = getJEntityExpression(ownerReference, app, listFilterRange, removedFields);
           if (jExpression === 'Error') return jExpression;
           return jExpression;
      };
       ownerReference.createOriginal = function(propertyName, oldValue) {
           ownerReference.original = ownerReference.getPrimitiveDTO();
           if (propertyName) ownerReference.original[propertyName] = oldValue;
       }
       ownerReference.restoreOriginal = function() {
           if (!isNullOrEmpty(ownerReference.original)) {
              enableChangeTrack = false;
              var properties = metadataInfo[ownerReference.typeName];
              for (var i = 0; i < properties.length; i++) {
                  var propertyName = properties[i].key;
                  if ((typeof ownerReference.original[propertyName]) !== 'undefined') ownerReference[propertyName] = ownerReference.original[propertyName];
              }
              delete ownerReference.original;
              enableChangeTrack = true;
           }
       }
       if (isPOCO === true) {
           ownerReference.getValidationErrors = function(propertyName) {
               var errors = [];
               if (!vm.canReportErrors) return errors;
               if (!ownerReference.ChangeState || ['I', 'U'].indexOf(ownerReference.ChangeState) < 0) return errors;
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                   var prop = properties[i];
                   if (isNullOrEmpty(propertyName) || prop.key == propertyName) {
                       if (prop.isRequired === true && !prop.isPartOfKey && isNullOrEmpty(ownerReference[prop.key])) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] é requerido.');
                       if (prop.validateMaxLength === true && prop.maxLength > 0 && !isNullOrEmpty(ownerReference[prop.key]) && ownerReference[prop.key].length > prop.maxLength) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] permite no máximo ' + prop.maxLength.toString() + ' caractere(s).');
                   }
               }
               return errors;
           }
       }
       ownerReference.getPrimitiveDTO = function(loadDetails) {
           var command = '';
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
               command += (command === '' ? '' : ', ') + properties[i].key + ': getAbsoluteValue(ownerReference.' + properties[i].key + ')';
               if (properties[i].isDomain && properties[i].key.length > 4) command += (command === '' ? '' : ', ') + strLeft(properties[i].key, properties[i].key.length - 4) + ': getAbsoluteValue(ownerReference.' + strLeft(properties[i].key, properties[i].key.length - 4) + ')';
           }
           eval('var result = { ' + command + ' };');
           return result;
       };
       ownerReference.getAllDetailChanges = function() {
           var result = [];
           return result;
       };
       ownerReference.copyDataFrom = function(originData, copyDetails) {
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
                setAbsoluteValue(ownerReference, properties[i].key, getAbsoluteValue(originData[properties[i].key]));
           }
       };
          ownerReference.commitDetailsVisualPendings = function() {
          }
          ownerReference.refreshData = function(noWait, succeeded) {
             var filterByKey = 'VendaDetalheView{' + 'IDVendaDetalhe#==#I' + getAbsoluteValue(ownerReference.IDVendaDetalhe).toString() + '}';
             if (!ownerReference.isPOCO && ownerReference.entityAspect && !ownerReference.isDetached() && !ownerReference.isUnchanged()) ownerReference.entityAspect.setUnchanged();
             return dataContext.getVendaDetalheViewByEntitySearchNoAssociations(filterByKey, 0, 0, false, true, ownerReference.isPOCO === true).then(querySucceeded);
             function querySucceeded(data) {
                if (succeeded) { succeeded(data); }
                if (data.results.length == 0) { return; }
                if (ownerReference.isPOCO) { for (var idx = 0; idx < data.results.length; idx++) { ownerReference.copyDataFrom(data.results[idx]); } }
                if (!noWait || ownerReference.atLeastOneDetailLoaded()) { vm.clearInnerUIs(ownerReference); ownerReference.fillDetails(true, '', false, noWait); }
           }
          }
       if (isPOCO === true) {
           ownerReference.isPOCO = true;
           ownerReference.enableDetailsDataTack = function(breezeReference) {
              if (breezeReference) breezeReference.setCurrentDetails();
           };
       }
       ownerReference.isAdded = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Added;
       });
       ownerReference.isDeleted = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Deleted;
       });
       ownerReference.isModified = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Modified;
       });
       ownerReference.isDetached = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Detached;
       });
       ownerReference.isUnchanged = (isPOCO === true ? function() { return true; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Unchanged;
       });
       ownerReference.setModified = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setModified();
       });
       ownerReference.setUnchanged = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setUnchanged();
       });
       ownerReference.serverDataType = [];
       ownerReference.serverDataType['Hora'] = 'T';
       ownerReference.serverDataType['IDVendaDetalhe'] = 'I';
       ownerReference.serverDataType['IDVendas'] = 'I';
       ownerReference.serverDataType['Preco'] = 'D';
       ownerReference.serverDataType['Produto'] = 'S';
       ownerReference.serverDataType['Quantidade'] = 'I';
       ownerReference.typeName = 'VendaDetalheView';
       ownerReference.isPrimaryKey = function(propertyName) {
           var keys = [ 'IDVendaDetalhe' ];
           return keys.indexOf(propertyName) >= 0;
       }
       ownerReference.getDisplayName = function(propertyName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          return (property != null ? property.headerText : propertyName);
       }
       ownerReference.setDisplayName = function(propertyName, displayName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          if (property != null) property.headerText = displayName;
       }
       ownerReference.setBandeiraRede = function (idBandeiraRede) {
       };
       ownerReference.setGpecon = function (idGpecon) {
       };
       ownerReference.UpdateIndependentRelation = function(detailName) {
           var cacheElements = dataContext.getEntities(detailName);
           for (var idxR = 0; idxR < cacheElements.length; idxR++) {
               if (typeof cacheElements[idxR].VendaDetalheView !== 'function') { return; }
               else  if (cacheElements[idxR].VendaDetalheView() != ownerReference) { cacheElements[idxR].VendaDetalheView(ownerReference); }
           }
       }
       ownerReference.setDefaults = function () {
       };
       ownerReference.delete = function() {
           if (ownerReference.isDetached()) {
               app.showMessage('A informação selecionada não pode ser excluída!', 'Alerta', ['Ok']);
               return;
           }
           if (ownerReference.setParentAsModified) ownerReference.setParentAsModified();
           var parent = getAbsoluteValue(ownerReference.VendasView);
           if (ownerReference.entityAspect) ownerReference.entityAspect.setDeleted(); // mark for deletion
           if (parent && (typeof parent.setCurrentDetails === 'function') && (typeof parent.VendaDetalheViewList === 'function') && parent.VendaDetalheViewList().length == 0) parent.setCurrentDetails('VendaDetalheView');
       };
       ownerReference.setParentAsModified = function() {
       var parent = getAbsoluteValue(ownerReference.VendasView);
       if (parent) {
           if (parent.isUnchanged()) {
               parent.setModified(); 
           }
           parent.setParentAsModified();
       }
       };
       ownerReference.getParent = function() {
           return getAbsoluteValue(ownerReference.VendasView);
       };
       ownerReference.getSelfList = function() {
           var parent = ownerReference.getParent();
           if (!isNullOrEmpty(parent)) {
               return getAbsoluteValue(parent.VendaDetalheViewList);
           } else { return null; }
       };
       ownerReference.namespace = 'LinxTraining001.BV.DetalhamentoVenda';
       ownerReference.myProperties = [ 'Hora','IDVendaDetalhe','IDVendas','Preco','Produto','Quantidade' ];
       ownerReference.queryRequiredProperties = {  };
       ownerReference.excludedFilters = [];
       ownerReference.getCurrentElements = function() {
           var result = [ ownerReference ];
           return result;
       };
       ownerReference.checkForSendingAllRowsToServer = function() {
       };
       ownerReference.detailsLoaded = function() {
           return true;
       }
       ownerReference.atLeastOneDetailLoaded = function() {
           return true;
       }
       ownerReference.adjustDetailsLoaded = function(value) {
       }
       ownerReference.fillDetails = function(force, detailName, noInnerUIs, noWait, callback, customParentRelation) {
          if (typeof force === 'undefined') force = false;
          if (force) vm.clearInnerUIs(ownerReference);
          if (!noInnerUIs) vm.queryInnerUIs(ownerReference);
          if (callback) { callback(); }
       };
       //Select first element as a current item of each detail
       ownerReference.setCurrentDetails = function(detailName) {
       };
       ownerReference.notifyEmptyDetails = function(detailName) {
       };
    //#region Extended Domain Names
       if (isPOCO !== true) {
           ownerReference.ProdutoName.subscribe(
               function (newValue) {
                   if (newValue == null) { ownerReference.ProdutoName(''); return; }
                   var value = (dataDomains.getId('ProdutoDomain', newValue));
                   if (value != ownerReference.Produto()) {
                       ownerReference.Produto(value);
                   }
            });
    
           ownerReference.Produto.subscribe(
           function (newValue) {
                   if (newValue == null) { ownerReference.Produto(''); return; }
                   var value = dataDomains.getName('ProdutoDomain', newValue);
                   if (value != ownerReference.ProdutoName()) {
                       ownerReference.ProdutoName(value);
               }
           });
       }
    //#endregion Extended Domain Names
    };
    metadataStore.registerEntityTypeCtor("VendaDetalheView", null, VendaDetalheViewInitializer);
    //#endregion Classes Map
    //#region Context Definition
    
    //#region Get LookUps
    
    var getLookUpClientesByEntitySearch = function (jEntitySearch, order, skip, take, direction) {
        var query = EntityQuery.from('GetLookUpClientesByEntitySearch').noTracking(true);
        query = (direction === 'descending' ? query.orderByDesc(order) : query.orderBy(order));
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ propertyName: order, jEntitySearch: jEntitySearch });
    
        if (take > 0)
           query = query.skip(skip).take(take);
        query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    var lookUpExternalManagers = [];
    //#endregion
    //#region Get KPI Ranges
    //#endregion
    
    //#region Get Combo LookUp
    var getResultsCombo = function (lookupName, fieldName, current, callback) {
        if (typeof current.executeLookUp === 'function') {
           current.executeLookUp(lookupName, fieldName, null, vm, null, null, function (result) {
               if (callback) callback(result);
           });
        }
    };
    //#endregion Get Combo LookUp
    
    //#region Get Business Entities
    
    var getBmEntityProperties = function (entityName, parentDataPath) {
        return manager.executeQuery(EntityQuery.from('GetBmEntityProperties').withParameters({ entityName: entityName, parentDataPath: parentDataPath }).noTracking(true))
        .fail(queryFailed);
    };
    
    var clearVendasView = function (idBandeiraRede, complete) {
        clearAll();
        resetSequence('VendasView');
        var refVendasView = manager.createEntity('VendasView', {}, breeze.EntityState.Unchanged);
        resetSequence('VendaDetalheView');
        var refVendaDetalheView = manager.createEntity('VendaDetalheView', {}, breeze.EntityState.Unchanged);
        refVendasView.currentVendaDetalheView(refVendaDetalheView);
        if (complete) complete({ results: [ refVendasView ] });
        return true;
    };
    
    var getVendasView = function (predicate, preserveCurrentState, noTracking) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetVendasView').noTracking(noTracking)
        .orderBy('IDVendas asc')
        ;
    
        if ((typeof predicate !== 'undefined') && predicate !== null)
            query = query.where(predicate);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    var getVendasViewByEntitySearchNoAssociations = function (jEntitySearch, skip, take, returnInlineCount, preserveCurrentState, noTracking, orderByDef) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetVendasViewByEntitySearchNoAssociations').noTracking(noTracking)
        .orderBy((isNullOrEmpty(orderByDef) ? 'IDVendas asc' : orderByDef))
        ;
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ jEntitySearch: jEntitySearch });
        if (take > 0)
           query = query.skip(skip).take(take);
        if (returnInlineCount)
            query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    var clearVendaDetalheView = function (idBandeiraRede, complete) {
        clearAll();
        resetSequence('VendaDetalheView');
        var refVendaDetalheView = manager.createEntity('VendaDetalheView', {}, breeze.EntityState.Unchanged);
        if (complete) complete({ results: [ refVendaDetalheView ] });
        return true;
    };
    
    var getVendaDetalheView = function (predicate, preserveCurrentState, noTracking) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetVendaDetalheView').noTracking(noTracking)
        .orderBy('IDVendaDetalhe asc')
        ;
    
        if ((typeof predicate !== 'undefined') && predicate !== null)
            query = query.where(predicate);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    var getVendaDetalheViewByEntitySearchNoAssociations = function (jEntitySearch, skip, take, returnInlineCount, preserveCurrentState, noTracking, orderByDef) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetVendaDetalheViewByEntitySearchNoAssociations').noTracking(noTracking)
        .orderBy((isNullOrEmpty(orderByDef) ? 'IDVendaDetalhe asc' : orderByDef))
        ;
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ jEntitySearch: jEntitySearch });
        if (take > 0)
           query = query.skip(skip).take(take);
        if (returnInlineCount)
            query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    //#endregion
    
    // Create the data update event.
    var dataUpdateEvent = document.createEvent('Event');
    // Define that the event name is 'DetalhamentoVendaContext_DataUpdate'.
    var contextUpdtEvt = 'DetalhamentoVendaContext_DataUpdate_' + getNewGuid();
    dataUpdateEvent.initEvent(contextUpdtEvt, true, true);
    
    //#region LookUps Finalizers
     var finalizeAllLookUpClientes = function (replaceTo, selectedElements, propertyName, lookupInfo) {
        if (!replaceTo || !selectedElements)
            return;
        if (!Array.isArray(selectedElements)) {
            selectedElements = [selectedElements];
        }
        isFinalizingLookup(true);
        if (!propertyName)
            propertyName = '';
        var isUsedOriginalRow = false;
        for (var i = 0; i < selectedElements.length; i++)
        {
            var selectedElement = selectedElements[i];
            if (propertyName === '' || propertyName === 'IDClientes') {
               if (selectedElement.hasOwnProperty('IDClientes') && replaceTo.hasOwnProperty('IDClientes'))
               {
                   setAbsoluteValue(replaceTo, 'IDClientes', getAbsoluteValue(selectedElement['IDClientes']));
               }
               else if (replaceTo.hasOwnProperty('IDClientes')) {
                   setAbsoluteValue(replaceTo, 'IDClientes', '');
               }
            }
            if (propertyName === '' || propertyName === 'Nome') {
               if (selectedElement.hasOwnProperty('Nome') && replaceTo.hasOwnProperty('Nome'))
               {
                   setAbsoluteValue(replaceTo, 'Nome', getAbsoluteValue(selectedElement['Nome']));
               }
               else if (replaceTo.hasOwnProperty('Nome')) {
                   setAbsoluteValue(replaceTo, 'Nome', null);
               }
            }
            if (replaceTo.validatedlookupsArray && !replaceTo.validatedlookupsArray.contains('LookUpClientes'))
                replaceTo.validatedlookupsArray.push('LookUpClientes');
        }
        //Trigger context data update event
        if (replaceTo.isPOCO) vm.refreshCurrentBind();
        document.dispatchEvent(dataUpdateEvent);
        isFinalizingLookup(false);
    };
    
    function clearLookUpClientes(replaceTo) {
        if (!replaceTo)
            return;
        isClearingLookup(true);
        setAbsoluteValue(replaceTo, 'IDClientes', '');
        setAbsoluteValue(replaceTo, 'Nome', null);
        isClearingLookup(false);
        //Trigger context data update event
        if (replaceTo.isPOCO) vm.refreshCurrentBind();
        setTimeout(function () {document.dispatchEvent(dataUpdateEvent);}, 100);
    }
    //#endregion
    
    var cancelChanges = function() {
        manager.rejectChanges();
    };
    
    var hasEmptyRequiredFilters = function() {
        return false;
    };
    
    var getEntityProperty = function (entityName, propertyName) {
        for (var i = 0; i < metadataInfo[entityName].length; i++) {
            if (metadataInfo[entityName][i].key === propertyName)
                return metadataInfo[entityName][i];
        }
        return null;
    };
    var getViewInfo = function (entityName) {
        var result = [];
        if (metadataInfo[entityName])
        {
            var viewInfoElements = metadataInfo[entityName];
            for (var i = 0; i < viewInfoElements.length; i++) {
                var selectedElement = viewInfoElements[i];
                if (!selectedElement.hidden && (selectedElement.dataType === 'string' || selectedElement.dataType === 'number'))
                {
                    if (strLeft(selectedElement.key, 3) === 'Cod' || strLeft(selectedElement.key, 2) === 'Id' || strLeft(selectedElement.key, 6) === 'Numero' || strLeft(selectedElement.key, 6) === 'Number') {
                        result.push(selectedElement);
                    }
                }
            }
            for (var i = 0; i < viewInfoElements.length; i++) {
                var selectedElement = viewInfoElements[i];
                if (!selectedElement.hidden && (selectedElement.dataType === 'string')) {
                    if (strLeft(selectedElement.key, 4) === 'Nome' || strLeft(selectedElement.key, 4) === 'Name' || strLeft(selectedElement.key, 4) === 'Desc' || strLeft(selectedElement.key, 6) === 'Titulo' || strLeft(selectedElement.key, 5) === 'Title') {
                        result.push(selectedElement);
                    }
                }
            }
            for (var i = 0; i < viewInfoElements.length; i++) {
                var selectedElement = viewInfoElements[i];
                if (!selectedElement.hidden && selectedElement.dataType === 'date')
                {                
                   result.push(selectedElement);
                }
            }
        }
        return result;
    };
    
    var getChanges = function() {
       return manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified, breeze.EntityState.Deleted]);
    };
    
    var hasValidationErrors = function(savingData) {
        if (savingData instanceof Array) {
           for (var idx = 0; idx < savingData.length; idx++) {
               var entity = savingData[idx];
               if (entity.ChangeState && entity.getValidationErrors && ['I', 'U'].indexOf(entity.ChangeState) >=0) {
                  var errors = entity.getValidationErrors();
                  if (errors.length > 0) {
                       showModalAlert('Campos obrigatórios não estão preenchidos.', errors);
                       return true;
                   }
               }
           }
        }
        else {
           var changes = manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified]);
           for (var idxChange = 0; idxChange < changes.length; idxChange++) {
              changes[idxChange].setParentAsModified();
           }
           changes = manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified]);
           for (var idxChange = 0; idxChange < changes.length; idxChange++) {
              var entity = changes[idxChange];
              var isOk = entity.entityAspect.validateEntity();
              if (!isOk) {
                  var errors = entity.entityAspect.getValidationErrors();
                  var strErrors = [];
                  for (var idx = 0; idx < errors.length; idx++) {
                      var errorMsg = errors[idx].errorMessage;
                      var propName = strExtract(errorMsg, "'", "'");
                      var propDisplay = entity.getDisplayName(propName);
                      errorMsg = errorMsg.replace("'" + propName + "'", "'" + propDisplay + "'" + (managerAuth.shellMode=='DEV' ? " (" + entity.typeName + "." + propName + ")": ""));
                      strErrors.push(translateError(errorMsg));
                  }
                  showModalAlert('Campos obrigatórios não estão preenchidos.', strErrors);
                  return true;
              }
           }
        }
        return false;
    };
    
    var saveChanges = function(saveSucceeded, saveFailed, fin, saveNoTRack) {
        if (saveNoTRack === true) {
            var dataForSaving = JSON.stringify(_.map(vm.getDataForSaving(), function(entity){ return entity.getPrimitiveDTO(entity.ChangeState != 'D'); }));
            return $.ajax({
               type: 'POST',
               crossDomain: true,
               url: getServiceAddress('LinxTraining001DetalhamentoVenda/Save' + vm.rootDataTypeName),
               globalError: true,
               contentType: 'application/json',
               async: true,
               cache: false,
               data: dataForSaving,
               success: function (response) {
                      success(response);
               },
               error: function (jqXHR, textStatus, errorThrown) {
                      failed({ message: jqXHR.responseJSON.ExceptionMessage });
               }
            });
        }
        else {
            return manager.saveChanges()
                   .fail(failed).then(success);
        }
    
        function success(result) {
            if (fin) fin();
            if (saveNoTRack === true && result.length > 0) {
               for (var idx = 0; idx < result.length; idx++) { dataContext.initializePOCO(result[idx], vm.rootDataTypeName); }
            }
            else if (result != null && result.keyMappings != null && result.keyMappings.length > 0) {
                for (var idx = 0; idx < result.keyMappings.length; idx++) {
                    if (result.keyMappings[idx].realValue == null) {
                       var entity = manager.getEntityByKey(result.keyMappings[idx].entityTypeName, result.keyMappings[idx].tempValue);
                       if (entity) manager.detachEntity(entity);
                    }
                }
                manager.acceptChanges();
            }
            if (saveSucceeded)
                saveSucceeded(result);
        }
    
        function failed(error) {
            if (fin) fin();
            if (error.message.indexOf('Internal Error in key fixup - unable to locate entity') == -1 && error.message.indexOf('An entity with this key is already in the cache:') == -1) {
               if (saveFailed)
                   saveFailed(error);
               var msg = error.message.replace('Fail by saving data:', '');
               showModalAlert('Falha ao salvar informações.', [ msg ]);
               error.message = msg;
               throw error;
           } else {
               manager.acceptChanges();
           }
        }
    };
    
    var acceptChanges = function () {
        return manager.acceptChanges();
    };
    
    var getEntities = function (entityName) {
        return manager.getEntities(entityName);
    };
    
    var notifyPresentation = function(dataSourceName) {
          if (dataContext.dataForUpdate !== '') {
           setTimeout(function () { notifyPresentation(dataSourceName); }, 100);
           return;
          }
          dataContext.dataForUpdate = dataSourceName;
          document.dispatchEvent(dataUpdateEvent);
          dataContext.dataForUpdate = '';
    };
    
    var getEntityInCache = function (entityName, propertiesReference) {
        var keys = [];
        if (!isNullOrEmpty(propertiesReference)) {
            for (var i = 0; i < metadataInfo[entityName].length; i++) {
                if (metadataInfo[entityName][i].isPartOfKey && !isNullOrEmpty(propertiesReference[metadataInfo[entityName][i].key]))
                    keys.push(propertiesReference[metadataInfo[entityName][i].key]);
            }
            if (keys.length == 0)
                return null;
            else {
                return manager.getEntityByKey(entityName, (keys.length == 1 ? keys[0] : keys));
            }
        }
        else
            return null;
    }
    
    var createEntity = function(entityName, initialValues, unchanged) {
        var entity = getEntityInCache(entityName, initialValues);
        if (!isNullOrEmpty(entity))
            entity.entityAspect.entityState == (unchanged === true ? breeze.EntityState.Unchanged : breeze.EntityState.Added);
        else 
            entity = manager.createEntity(entityName, initialValues, (unchanged === true ? breeze.EntityState.Unchanged : breeze.EntityState.Added));
        return entity;
    };
    
    var createFreeEntity = function(entityName) {
       return manager.createEntity(entityName, {}, breeze.EntityState.Detached);
    }
    
    var createVendasView = function() {
        //Create entity instance
        var entity = createEntity('VendasView', { VendaVip: false });
        entity.setDefaults();
        return entity;
    };
    
    var createVendaDetalheView = function(parent, noCurrent) {
        //Create entity instance
        var entity = createEntity('VendaDetalheView', { VendasView: parent });
        entity.setDefaults();
        if (noCurrent !== true) parent.currentVendaDetalheView(entity);
        if (parent && (typeof parent.setCurrentDetails === 'function') && (typeof parent.VendaDetalheViewList === 'function') && parent.VendaDetalheViewList().length == 0) parent.setCurrentDetails('VendaDetalheView');
        if (entity.setParentAsModified) entity.setParentAsModified();
        return entity;
    };
    
    var deleteEntity = function (entity) {
        entity.delete();
    };
    
    var detachEntity = function (entity) {
        if (!entity.isDetached()) entity.entityAspect.setDetached();
    };
    
    var attachEntity = function (entity) {
        manager.attachEntity(entity);
    };
    
    var clearAll = function () {
        manager.rejectChanges();
        manager.clear();
    };
    
    var executeQuery = function (getMethod, jEntitySearch, order, skip, take, noTracking, callBack) {
        var query = EntityQuery.from(getMethod).noTracking(noTracking)
        .orderBy(order);
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ jEntitySearch: jEntitySearch });
    
        if (take > 0)
           query = query.skip(skip).take(take);
        query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed).then(function (data) {
            if (callBack) {
                callBack(data.results);
            }
        });
    };
    var exportToExcel = function(entityName, jEntitySearch, translatedJEntitySearch, complete, columnsVisible) {
        var info = jQuery.grep(dataExportInfo[vm.rootDataTypeName], function (item, i) { return (item.name === entityName);});
        if (info == null || info.length === 0) {
            app.showMessage('Erro na exportação', 'Alerta', ['Ok']);
            return;
        }
        $.ajax({
           type: 'POST',
           crossDomain: true,
           url: getServiceAddress(info[0].actionExport),
           globalError: true,
           headers: managerAuth.getHeaders(),
           contentType: 'application/json',
           async: true,
           cache: false,
           data: JSON.stringify([jEntitySearch, translatedJEntitySearch, columnsVisible]),
           success: function (response) {
                  saveExcelBlob(entityName + '.xlsx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
           }
        });
    };
    var exportReportDataSource = function(complete) {
        $.ajax({
           type: 'GET',
           crossDomain: true,
           headers: managerAuth.getHeaders(),
           url: getServiceAddress("LinxTraining001DetalhamentoVenda/GetReportDataSource"),
           success: function (response) {
                  saveExcelBlob('datasource.ldsx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
                  alert('Erro na exportação do data source');
           }
        });
    };
    var exportTemplateReport = function(reportPath, complete) {
        $.ajax({
           type: 'GET',
           crossDomain: true,
           headers: managerAuth.getHeaders(),
           url: getServiceAddress("LinxTraining001DetalhamentoVenda/GetTemplateReport"),
           data: { reportPath: reportPath },
           success: function (response) {
                  saveExcelBlob(reportPath + '.lrtx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
                  alert('Erro na exportação do data source');
           }
        });
    };
    var exportToReport = function(reportName, entityName, jEntitySearch, translatedJEntitySearch, complete, columnsVisible, exportMedia) {
        var info = jQuery.grep(dataExportInfo[vm.rootDataTypeName], function (item, i) { return (item.name === entityName);});
        if (info == null || info.length === 0) {
            app.showMessage('Erro na exportação', 'Alerta', ['Ok']);
            return;
        }
        $.ajax({
           type: 'POST',
           crossDomain: true,
           headers: managerAuth.getHeaders(),
           url: getServiceAddress(info[0].actionReport),
           globalError: true,
           contentType: 'application/json',
           async: true,
           cache: false,
           data: JSON.stringify([ reportName, jEntitySearch, translatedJEntitySearch, columnsVisible, getServiceAddress(''), exportMedia ]),
           success: function (response) {
                  saveExcelBlob(entityName + '.lrtx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
           }
        });
    };
    
    var hasChanges = ko.observable(false);
    
    manager.hasChangesChanged.subscribe(function(eventArgs) {
        hasChanges(eventArgs.hasChanges);
    });
    
    //#region Internal methods
    
    function queryFailed(error) {
        var msg = error.message;
        if (isNullOrEmpty(msg)) return;
        showModalAlert('Falha ao pesquisar informações.', [ msg ]);
        error.message = msg;
        throw error;
    }
    
    function log(msg, data) {
        logger.log(msg, data, system.getModuleId(dataContext), true);
    }
    
    function logError(msg, error) {
         logger.logError(msg, error, system.getModuleId(dataContext), true);
    }
    
    function loadParameters() {
     dataParameters.isLoaded = true;
    }
    
    //#endregion Internal methods
    //#region getWithBinding
    var createDTOEmpty = function (entityName) {
        var entityType = manager.metadataStore.getEntityType(entityName);
        var entity = {};
        for (var idx = 0; idx < entityType.dataProperties.length; idx++) {
            var prop = entityType.dataProperties[idx];
            entity[prop.name] = prop.defaultValue;
        }
        for (var idx = 0; idx < entityType.navigationProperties.length; idx++) {
            var navigationName = entityType.navigationProperties[idx].name;
            if (navigationName.endsWith('List'))
                entity['current' + navigationName.replace('List', '')] = null;
        }
        entity.isEmptyEntity = true;
        return entity;
    };
    var getWithBinding = function (binding, entityName) {
        if (typeof binding === 'function' && binding() != null)
            return binding;
        else
            return createDTOEmpty(entityName);
    }
    //#endregion getWithBinding
    
        var vm = null;
        var dataContext = {
            dataForUpdate: '',
            getPivotLayouts: getPivotLayouts,
            getSelectedLayoutContent: getSelectedLayoutContent,
            getServiceAddress: getServiceAddress,
            getDataFeedUrl: getDataFeedUrl,
            getDataServiceUrl: getDataServiceUrl,
            setServiceBusUrl: setServiceBusUrl,
            initializePOCO: initializePOCO,
            getWithBinding: getWithBinding,
            managerAuth: managerAuth,
            hasDataFeed: true,
            getAccessGroup: getAccessGroup,
            getNewGuid: getNewGuid,
            metadataInfo: metadataInfo,
            dataExportInfo: dataExportInfo,
            entityNames: entityNames,
            lookUpNames: lookUpNames,
            lookUpProperties: lookUpProperties,
            metadataStore: metadataStore,
            cancelChanges: cancelChanges,
            saveChanges: saveChanges,
            getChanges: getChanges,
            hasValidationErrors: hasValidationErrors,
            getEntityProperty: getEntityProperty,
            getViewInfo: getViewInfo,
            createEntity: createEntity,
            notifyPresentation: notifyPresentation,
            createFreeEntity: createFreeEntity,
            createVendasView: createVendasView,
            createVendaDetalheView: createVendaDetalheView,
            deleteEntity: deleteEntity,
            acceptChanges: acceptChanges,
            getEntities: getEntities,
            detachEntity: detachEntity,
            attachEntity: attachEntity,
            executeQuery: executeQuery,
            sharedData: [],
            clearAll: clearAll,
            hasChanges: hasChanges,
            dataDomains: dataDomains,
            dataParameters: dataParameters,
            loadParameters: loadParameters,
            exportToExcel: exportToExcel,
            exportToReport: exportToReport,
            exportReportDataSource: exportReportDataSource,
            exportTemplateReport: exportTemplateReport,
            businessAssemblyName: businessAssemblyName,
            controllerName: controllerName,
            getResultsCombo: getResultsCombo,
            breeze: breeze,
            contextUpdtEvt: contextUpdtEvt,
            setCurrentViewModel: function(vModel) { vm = vModel; },
                getLookUpClientesByEntitySearch: getLookUpClientesByEntitySearch,
            getBmEntityProperties: getBmEntityProperties,
            clearVendasView: clearVendasView,
            getVendasView: getVendasView,
            getVendasViewByEntitySearchNoAssociations: getVendasViewByEntitySearchNoAssociations,
            clearVendaDetalheView: clearVendaDetalheView,
            getVendaDetalheView: getVendaDetalheView,
            getVendaDetalheViewByEntitySearchNoAssociations: getVendaDetalheViewByEntitySearchNoAssociations,
                finalizeAllLookUpClientes: finalizeAllLookUpClientes,
            clearLookUpClientes: clearLookUpClientes
        };
    loadParameters();
    return dataContext;
    //#endregion Context Definition
}
return result;
});
