define(['durandal/system', 'pkg_linxtraining001-bv-spa/services/DataDomains', 'services/logger', 'breeze', 'durandal/app', 'managers/__auth', 'viewmodels/shared/modal', 'viewmodels/shared/modal2'],
function (system, dataDomains, logger, breeze, app, managerAuth, modal, modal2) {
var result = function () {
    var getPivotLayouts = function (params, success, error) {
        return $.ajax({
            messageUser: 'Busca dos layouts exportados',
            contentType: 'application/json; charset=UTF-8',
            headers: managerAuth.getHeaders(),
            url: getServiceAddress('linxframeworkobjeto') + '/GetPivotLayouts?' +
                                                                   'rootNameSpace=' + params.rootNamespace +
                                                                   '&viewName=' + params.viewName +
                                                                   '&pivotName=' + params.pivotName +
                                                                   '&pivotDataSource=' + params.pivotDataSource,
            async: true,
            cache: false,
            error: error,
            success: success
        });
    };
    
    var getSelectedLayoutContent = function (params, success, error) {
        return $.ajax({
            messageUser: 'Busca de layout selecionado',
            contentType: 'application/json; charset=UTF-8',
            headers: managerAuth.getHeaders(),
            url: getServiceAddress('linxframeworkobjeto') + '/GetPivotLayout?uidObjetoConteudo=' + params.uidObjetoConteudo,
            async: true,
            cache: false,
            error: error,
            success: success
        });
    };
    var getServiceAddress = function(apiPart) {
       return managerAuth.getServiceAddress(apiPart, businessAssemblyName);
    };
    var getAccessGroup = function() {
       return '00000000-0000-0000-0000-000000000000';
    };
    var getNewGuid = function() {
       return breeze.core.getUuid();
    };
    var getDataFeedUrl = function() {
       return getServiceAddress('LinxTraining001TiposCamposOData');
    };
    var getDataServiceUrl = function () {
       return getServiceAddress(controllerName);
    };
    var setServiceBusUrl = function (url) {
       if (dataService) { dataService.serviceName = (isNullOrEmpty(url) ? getDataServiceUrl() : url + controllerName); }
    };
    var initializePOCO = function(ownerReference, entityName) {
       if (ownerReference && !ownerReference.RowDataId) { eval(entityName + 'Initializer(ownerReference, true);'); }
    };
    var businessAssemblyName = 'LinxTraining001.BV';
    var controllerName = 'LinxTraining001TiposCampos';
    var dataService = new breeze.DataService({
        serviceName: getDataServiceUrl(),
        hasServerMetadata: false // don't ask the server for metadata
    });
    var manager = new breeze.EntityManager({ dataService: dataService });
    manager.entityChanged.subscribe(function(changeArgs) {
        if (changeArgs.entityAction === breeze.EntityAction.PropertyChange) {
            if ((typeof changeArgs.args.newValue) === 'number' && changeArgs.args.oldValue < 0 && changeArgs.args.newValue > 0 && changeArgs.entity.isPrimaryKey(changeArgs.args.propertyName)) vm.replaceInnerUIsKeys(changeArgs.entity, changeArgs.args.propertyName, changeArgs.args.oldValue, changeArgs.args.newValue);
            if (typeof changeArgs.entity.OnPropertyChanged == 'function')
                changeArgs.entity.OnPropertyChanged(changeArgs.args.propertyName, changeArgs.args.oldValue, changeArgs.args.newValue);
        }
    });
    var enableChangeTrack = true;
    var entityPropChanged = function(entity, propName, oldVal, newVal) {
        if (!enableChangeTrack) return true;
        var result = true;
        if ((typeof entity.OnPropertyChanged == 'function') && oldVal !== newVal)
            result = (entity.OnPropertyChanged(propName, oldVal, newVal) !== false);
        if (result && ['U', 'I', 'D'].indexOf(entity.ChangeState) < 0) { entity.createOriginal(propName, oldVal); entity.ChangeState = 'U'; if (entity.setParentAsModified) entity.setParentAsModified(); }
        if (result && (typeof newVal) === 'number' && oldVal < 0 && newVal > 0 && entity.isPrimaryKey(propName)) vm.replaceInnerUIsKeys(entity, propName, oldVal, newVal);
        return result;
    }
    var metadataStore = manager.metadataStore;
    var EntityQuery = breeze.EntityQuery;
    // Extract Breeze metadata definition types
    var DataType = breeze.DataType;
    var AutoGeneratedKeyType = breeze.AutoGeneratedKeyType;
    var Validator = breeze.Validator;
    Validator.hasValueValidator = new breeze.Validator('hasValueValidator', hasValueValidationFn, { messageTemplate: "'%displayName%' é requerido" });
    //#region Metadata Info
    var metadataInfo = [];
    var dataExportInfo = [];
    var entityNames = [];
    var lookUpNames = [];
    var entitylookUps = [];
    entityNames.push('TiposCamposView');
    metadataInfo['TiposCamposView'] = [
        { key: 'Boolean', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Boolean', width: '127px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null },
        { key: 'Byte', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 3, isPartOfKey: false, headerText: 'Byte', width: '88px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'DateTime', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'DateTime', width: '140px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
        { key: 'Decimal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Decimal', width: '127px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'Guid', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 36, isPartOfKey: false, headerText: 'Guid', width: '250px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'IDTiposCampos', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: true, headerText: 'ID TiposCampos', width: '218px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Int', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Int', width: '130px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Long', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 24, isPartOfKey: false, headerText: 'Long', width: '250px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Short', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 6, isPartOfKey: false, headerText: 'Short', width: '101px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'String', isDomain: true, domainName: 'TstDomainString', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'String', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'StringName', isDomain: true, domainName: 'TstDomainString', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'String (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'StringChar', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, validateMaxLength: true, isPartOfKey: false, headerText: 'StringChar', width: '166px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'StringText', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'StringText', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'DecimalKpiInfo', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 20, validateMaxLength: true, isPartOfKey: false, headerText: 'Decimal (KPI)', width: '205px', dataType: 'string', format: '', hidden: false, unbound: false, group: null }
    ];
    dataExportInfo['TiposCamposView'] = [ 
        { name: 'TiposCamposView', canExportMedia: true , canExportReport: true, actionExport: 'LinxTraining001TiposCampos/GetTiposCamposViewToExcel', actionReport: 'LinxTraining001TiposCampos/GetTiposCamposViewToReportXml', actionFeed: 'LinxTraining001TiposCamposOData/TiposCamposView', actionName: 'LinxTraining001TiposCampos/GetTiposCamposViewByEntitySearchNoAssociations', display: 'TiposCamposView',  metaData: function() { return metadataInfo['TiposCamposView']; } }
        , { name: 'TiposCamposFilhaView', canExportMedia: true , canExportReport: true, actionExport: 'LinxTraining001TiposCampos/GetTiposCamposFilhaViewParentCompositionToExcel', actionReport: 'LinxTraining001TiposCampos/GetTiposCamposFilhaViewParentCompositionToReportXml', actionFeed: 'LinxTraining001TiposCamposOData/TiposCamposFilhaViewParentComposition', actionName: 'LinxTraining001TiposCampos/GetTiposCamposFilhaViewParentCompositionByEntitySearchNoAssociations', display: 'TiposCamposFilhaView',  metaData: function() { return metadataInfo['TiposCamposFilhaViewParentComposition']; } }
    ];
    entitylookUps.push('TiposCamposView');
    entitylookUps['TiposCamposView'] = [];
    entityNames.push('TiposCamposFilhaView');
    metadataInfo['TiposCamposFilhaView'] = [
        { key: 'Boolean', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Boolean', width: '127px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null },
        { key: 'DateTime', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'DateTime', width: '140px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
        { key: 'Decimal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Decimal', width: '127px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'Guid', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 36, isPartOfKey: false, headerText: 'Guid', width: '250px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'IDTiposCampos', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'ID TiposCampos', width: '218px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'IDTiposCamposFilha', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: true, headerText: 'ID TiposCamposFilha', width: '283px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Int', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Int', width: '130px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Long', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 24, isPartOfKey: false, headerText: 'Long', width: '250px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Short', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 6, isPartOfKey: false, headerText: 'Short', width: '101px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'String', isDomain: true, domainName: 'DomainString', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'String', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'StringName', isDomain: true, domainName: 'DomainString', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'String (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'StringChar', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, validateMaxLength: true, isPartOfKey: false, headerText: 'StringChar', width: '166px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'StringText', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'StringText', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null }
    ];
    entityNames.push('TiposCamposFilhaViewParentComposition');
    metadataInfo['TiposCamposFilhaViewParentComposition'] = [
        { key: 'Boolean', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'Boolean', width: '127px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null },
        { key: 'DateTime', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'DateTime', width: '140px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
        { key: 'Decimal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Decimal', width: '127px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
        { key: 'Guid', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 36, isPartOfKey: false, headerText: 'Guid', width: '250px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'IDTiposCampos', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'ID TiposCampos', width: '218px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'IDTiposCamposFilha', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 12, isPartOfKey: true, headerText: 'ID TiposCamposFilha', width: '283px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Int', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Int', width: '130px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Long', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 24, isPartOfKey: false, headerText: 'Long', width: '250px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'Short', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 6, isPartOfKey: false, headerText: 'Short', width: '101px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
        { key: 'String', isDomain: true, domainName: 'DomainString', lookupPropertyName: '', lookupVisibleColumns: '', isRequired: true, maxLength: 10, isPartOfKey: false, headerText: 'String', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'StringName', isDomain: true, domainName: 'DomainString', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'String (Name)', width: '0px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
        { key: 'StringChar', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, validateMaxLength: true, isPartOfKey: false, headerText: 'StringChar', width: '166px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'StringText', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'StringText', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
        { key: 'Byte', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 3, isPartOfKey: false, headerText: 'Byte', width: '88px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null }
    ];
    dataExportInfo['TiposCamposFilhaView'] = [ 
        { name: 'TiposCamposFilhaView', canExportMedia: true , canExportReport: true, actionExport: 'LinxTraining001TiposCampos/GetTiposCamposFilhaViewToExcel', actionReport: 'LinxTraining001TiposCampos/GetTiposCamposFilhaViewToReportXml', actionFeed: 'LinxTraining001TiposCamposOData/TiposCamposFilhaView', actionName: 'LinxTraining001TiposCampos/GetTiposCamposFilhaViewByEntitySearchNoAssociations', display: 'TiposCamposFilhaView',  metaData: function() { return metadataInfo['TiposCamposFilhaView']; } }
    ];
    entitylookUps.push('TiposCamposFilhaView');
    entitylookUps['TiposCamposFilhaView'] = [];
    var lookUpProperties = [];
    //#endregion Metadata Info
    //#region dataParameters
    var dataParameters = {
        isLoaded: false,
        parameters: [],
        registerParameters: function (parameterList, complete) {
            if (parameterList !== '') {
                var variation = '{TBC_GRUPO_ECONOMICO|' + managerAuth.loginInfo.IdLinxGrupoEconomico.toString() + '|TCS_USUARIO|' + managerAuth.loginInfo.UidUsuario + (vm != null && vm.getBandeiraRede() > 0 ? '|TBC_BANDEIRA_REDE|' + vm.getBandeiraRede().toString() : '') + '}';
                $.ajax({
                    type: 'GET',
                    url: getServiceAddress('LinxFrameworkParametro') + '/GetParameterValue?serializedParameterList=' + stringReplace(parameterList, '{}', variation),
                    dataType: 'json',
                    cache: false,
                    headers: managerAuth.getHeaders(),
                    error: function (jqXHR, textStatus, errorThrown) {
                        var msg = 'Os seguintes parâmetros não foram pesquisados: [' + parameterList + ']';
                        app.showMessage(msg, 'Alerta', ['Ok']);
                        dataParameters.isLoaded = true;
                    },
                    success: function (data) {
                        var parametersName = '';
                        var parameters = data.split('#');
                        for (var idx in parameters) {
                            var values = parameters[idx].split('|');
                            var pName = values[0];
                            var pValue = values[1];
                            dataParameters.parameters[pName] = pValue;
                        }
                        dataParameters.isLoaded = true;
                        if (complete) complete();
                    }
                });
            }
        }
    };
    //#endregion dataParameters
    //#region Classes Map
    var sequences = [];
    var getNextSequence = function(entityName) {
        if (!sequences[entityName]) resetSequence(entityName);
        sequence = sequences[entityName];
        sequences[entityName]++;
        return sequence;
    };
    var resetSequence = function(entityName) {
        sequences[entityName] = 0;
    };
    var getSequence = function(entityName) {
        if (!sequences[entityName]) resetSequence(entityName);
        return sequences[entityName];
    };
    
    // Configure TiposCamposView data type
    metadataStore.addEntityType({
    shortName: "TiposCamposView",
    namespace: "LinxTraining001.BV.TiposCampos",
    autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
    dataProperties: {
    Boolean: { dataType: DataType.Boolean, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Byte: { dataType: DataType.Byte, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,DateTime: { dataType: DataType.DateTime, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Decimal: { dataType: DataType.Decimal, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Guid: { dataType: DataType.Guid, isNullable: false, isPartOfKey: false, validators: [ Validator.hasValueValidator]  }
    ,IDTiposCampos: { dataType: DataType.Int32, isNullable: false, isPartOfKey: true, validators: [ Validator.hasValueValidator]  }
    ,Int: { dataType: DataType.Int32, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Long: { dataType: DataType.Int64, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Short: { dataType: DataType.Int16, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,String: { dataType: DataType.String, maxLength: 10, isNullable: true, isPartOfKey: false, validators: [ Validator.hasValueValidator, Validator.maxLength( {maxLength: 10})]  }
    ,StringName: { dataType: DataType.String, isNullable: false, isPartOfKey: false, validators: [] }
    ,StringChar: { dataType: DataType.String, maxLength: 10, isNullable: true, isPartOfKey: false, validators: [ Validator.maxLength( {maxLength: 10})]  }
    ,StringText: { dataType: DataType.String, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,DecimalKpiInfo: { dataType: DataType.String, maxLength: 20, isNullable: false, isPartOfKey: false, validators: [ Validator.hasValueValidator, Validator.maxLength( {maxLength: 20})]  }
                    },
    navigationProperties: {
    // Returns collections of details and associates with Parent
    TiposCamposFilhaViewList: { entityTypeName: "TiposCamposFilhaView:#LinxTraining001.BV.TiposCampos", isScalar: false, invForeignKeyNames: ["IDTiposCampos"], associationName: "FK_TiposCamposView_TiposCamposFilhaView" }
                          }
    });
    lookUpProperties['TiposCamposView'] = {};
    var TiposCamposViewInitializer = function (ownerReference, isPOCO) {
       ownerReference.RowDataId = (isPOCO === true ? getNextSequence('TiposCamposView') : ko.observable(getNextSequence('TiposCamposView')));
       ownerReference.currentTiposCamposFilhaView = ko.observable(null);
       //Adjust details for a POCO reference
       if (isPOCO === true) {
           ownerReference.TiposCamposFilhaViewList = ko.observableArray(ownerReference.TiposCamposFilhaViewList);
       }
       ownerReference.setRemovedLookupFields = function(removedFields) {
           for (var idxLUp in entitylookUps[ownerReference.typeName]) {
               var hasKeyValue = false;
               var luName = entitylookUps[ownerReference.typeName][idxLUp];
               var luMeta = metadataInfo[luName];
               for (var idxProp in luMeta) {
                   var prop = luMeta[idxProp];
                   if (!isNullOrEmpty(prop.relatedKey) && prop.isPartOfKey) {
                       hasKeyValue = !isNullOrEmpty(getAbsoluteValue(ownerReference[prop.relatedKey]));
                       break;
                   }
               }
               if (hasKeyValue) {
                   for (var idxProp in luMeta) {
                       var prop = luMeta[idxProp];
                       if (!isNullOrEmpty(prop.relatedKey) && !prop.isPartOfKey) {
                           removedFields.push(prop.relatedKey);
                       }
                   }
               }
           }
       }
       ownerReference.getJExpression = function(listFilterRange, removedFields, noDetails) {
           if (ownerReference.excludedFilters && ownerReference.excludedFilters.length > 0) { if (removedFields instanceof Array) removedFields = removedFields.concat(ownerReference.excludedFilters); else removedFields = ownerReference.excludedFilters; }
           ownerReference.setRemovedLookupFields(removedFields);
           var jExpression = getJEntityExpression(ownerReference, app, listFilterRange, removedFields);
           if (jExpression === 'Error') return jExpression;
           if (noDetails !== true && ownerReference.TiposCamposFilhaViewList && ownerReference.TiposCamposFilhaViewList().length > 0) {
             var detailExpr = ownerReference.TiposCamposFilhaViewList()[0].getJExpression(listFilterRange, ['IDTiposCampos']);
             if (detailExpr === 'Error') return detailExpr;
             jExpression += detailExpr;
           }
           return jExpression;
      };
       ownerReference.createOriginal = function(propertyName, oldValue) {
           ownerReference.original = ownerReference.getPrimitiveDTO();
           if (propertyName) ownerReference.original[propertyName] = oldValue;
       }
       ownerReference.restoreOriginal = function() {
           if (!isNullOrEmpty(ownerReference.original)) {
              enableChangeTrack = false;
              var properties = metadataInfo[ownerReference.typeName];
              for (var i = 0; i < properties.length; i++) {
                  var propertyName = properties[i].key;
                  if ((typeof ownerReference.original[propertyName]) !== 'undefined') ownerReference[propertyName] = ownerReference.original[propertyName];
              }
              delete ownerReference.original;
              enableChangeTrack = true;
           }
       }
       if (isPOCO === true) {
           ownerReference.getValidationErrors = function(propertyName) {
               var errors = [];
               if (!vm.canReportErrors) return errors;
               if (!ownerReference.ChangeState || ['I', 'U'].indexOf(ownerReference.ChangeState) < 0) return errors;
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                   var prop = properties[i];
                   if (isNullOrEmpty(propertyName) || prop.key == propertyName) {
                       if (prop.isRequired === true && !prop.isPartOfKey && isNullOrEmpty(ownerReference[prop.key])) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] é requerido.');
                       if (prop.validateMaxLength === true && prop.maxLength > 0 && !isNullOrEmpty(ownerReference[prop.key]) && ownerReference[prop.key].length > prop.maxLength) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] permite no máximo ' + prop.maxLength.toString() + ' caractere(s).');
                   }
               }
               if (isNullOrEmpty(propertyName)) {
                   for (var i = 0; i < ownerReference.TiposCamposFilhaViewList().length; i++) {
                       var detail = ownerReference.TiposCamposFilhaViewList()[i];
                       errors = errors.concat(detail.getValidationErrors());
                   }
               }
               return errors;
           }
       }
       ownerReference.getPrimitiveDTO = function(loadDetails) {
           var command = '';
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
               command += (command === '' ? '' : ', ') + properties[i].key + ': getAbsoluteValue(ownerReference.' + properties[i].key + ')';
               if (properties[i].isDomain && properties[i].key.length > 4) command += (command === '' ? '' : ', ') + strLeft(properties[i].key, properties[i].key.length - 4) + ': getAbsoluteValue(ownerReference.' + strLeft(properties[i].key, properties[i].key.length - 4) + ')';
           }
           eval('var result = { ' + command + ' };');
           if (loadDetails) {
               result.TiposCamposFilhaViewList = [];
               var sourceList = getAbsoluteValue(ownerReference.TiposCamposFilhaViewList);
               if (sourceList && sourceList.length > 0) {
                   for (var i = 0; i < sourceList.length; i++) {
                       if (['U', 'I', 'D'].indexOf(sourceList[i].ChangeState) >= 0) result.TiposCamposFilhaViewList.push(sourceList[i].getPrimitiveDTO(sourceList[i].ChangeState != 'D'));
                   }
               }
           }
           return result;
       };
       ownerReference.getAllDetailChanges = function() {
           var result = [];
           var _TiposCamposFilhaViewList = getAbsoluteValue(ownerReference.TiposCamposFilhaViewList);
           if (_TiposCamposFilhaViewList && _TiposCamposFilhaViewList.length > 0) {
               for (var i = 0; i < _TiposCamposFilhaViewList.length; i++) {
                   var detail = _TiposCamposFilhaViewList[i];
                   if (['U', 'I', 'D'].indexOf(detail.ChangeState) >= 0) {
                       result.push(detail);
                       result = result.concat(detail.getAllDetailChanges());
                   }
               }
           }
           return result;
       };
       ownerReference.copyDataFrom = function(originData, copyDetails) {
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
                setAbsoluteValue(ownerReference, properties[i].key, getAbsoluteValue(originData[properties[i].key]));
           }
           if (copyDetails) {
               if (ownerReference.TiposCamposFilhaViewList && originData.TiposCamposFilhaViewList) {
                   var toList = getAbsoluteValue(ownerReference.TiposCamposFilhaViewList);
                   var fromList = getAbsoluteValue(originData.TiposCamposFilhaViewList);
                   for (var idxElem = toList.length - 1; idxElem >= 0; idxElem--) {
                      if (toList[idxElem].ChangeState === 'D') toList.splice(idxElem, 1);
                   }
                   for (var idxElem = toList.length - 1; idxElem >= 0; idxElem--) {
                          if (toList[idxElem].ChangeState !== 'N') {
                               var fromObj = [];
                               if (toList[idxElem].ChangeState == 'I') {
                                   fromObj = _.where(fromList, { TemporaryIDTiposCamposFilha: toList[idxElem]['IDTiposCamposFilha'] });
                               } else {
                                   fromObj = _.where(fromList, { IDTiposCamposFilha: toList[idxElem]['IDTiposCamposFilha'] });
                               }
                               if (fromObj.length > 0) toList[idxElem].copyDataFrom(fromObj[0], true);
                          }
                   }
               }
           }
       };
          ownerReference.commitDetailsVisualPendings = function() {
              vm.dataBind('TiposCamposFilhaViewList', true);
              if (ownerReference.currentTiposCamposFilhaView()) ownerReference.currentTiposCamposFilhaView().commitDetailsVisualPendings();
          }
          ownerReference.refreshData = function(noWait, succeeded) {
             var filterByKey = 'TiposCamposView{' + 'IDTiposCampos#==#I' + getAbsoluteValue(ownerReference.IDTiposCampos).toString() + '}';
             if (!ownerReference.isPOCO && ownerReference.entityAspect && !ownerReference.isDetached() && !ownerReference.isUnchanged()) ownerReference.entityAspect.setUnchanged();
             return dataContext.getTiposCamposViewByEntitySearchNoAssociations(filterByKey, 0, 0, false, true, ownerReference.isPOCO === true).then(querySucceeded);
             function querySucceeded(data) {
                if (succeeded) { succeeded(data); }
                if (data.results.length == 0) { return; }
                if (ownerReference.isPOCO) { for (var idx = 0; idx < data.results.length; idx++) { ownerReference.copyDataFrom(data.results[idx]); } }
                if (!noWait || ownerReference.atLeastOneDetailLoaded()) { vm.clearInnerUIs(ownerReference); ownerReference.fillDetails(true, '', false, noWait); }
           }
          }
       if (isPOCO === true) {
           ownerReference.isPOCO = true;
           ownerReference.enableDetailsDataTack = function(breezeReference) {
              breezeReference.TiposCamposFilhaViewIsLoaded = ownerReference.TiposCamposFilhaViewIsLoaded;
              for (var idx = 0; idx < ownerReference.TiposCamposFilhaViewList().length; idx++) {
                  var entity = ownerReference.TiposCamposFilhaViewList()[idx];
                  if (entity.isPOCO)  {
                      var newReference = createEntity(entity.typeName, entity.getPrimitiveDTO(), true);
                      entity.enableDetailsDataTack(newReference);
                  }
              }
              if (breezeReference) breezeReference.setCurrentDetails();
           };
       }
       ownerReference.isAdded = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Added;
       });
       ownerReference.isDeleted = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Deleted;
       });
       ownerReference.isModified = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Modified;
       });
       ownerReference.isDetached = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Detached;
       });
       ownerReference.isUnchanged = (isPOCO === true ? function() { return true; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Unchanged;
       });
       ownerReference.setModified = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setModified();
       });
       ownerReference.setUnchanged = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setUnchanged();
       });
       ownerReference.serverDataType = [];
       ownerReference.serverDataType['Boolean'] = 'B';
       ownerReference.serverDataType['Byte'] = 'Y';
       ownerReference.serverDataType['DateTime'] = 'T';
       ownerReference.serverDataType['Decimal'] = 'D';
       ownerReference.serverDataType['Guid'] = 'G';
       ownerReference.serverDataType['IDTiposCampos'] = 'I';
       ownerReference.serverDataType['Int'] = 'I';
       ownerReference.serverDataType['Long'] = 'L';
       ownerReference.serverDataType['Short'] = 'H';
       ownerReference.serverDataType['String'] = 'S';
       ownerReference.serverDataType['StringChar'] = 'S';
       ownerReference.serverDataType['StringText'] = 'S';
       ownerReference.serverDataType['DecimalKpiInfo'] = 'S';
       ownerReference.typeName = 'TiposCamposView';
       ownerReference.isPrimaryKey = function(propertyName) {
           var keys = [ 'IDTiposCampos' ];
           return keys.indexOf(propertyName) >= 0;
       }
       ownerReference.getDisplayName = function(propertyName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          return (property != null ? property.headerText : propertyName);
       }
       ownerReference.setDisplayName = function(propertyName, displayName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          if (property != null) property.headerText = displayName;
       }
       ownerReference.setBandeiraRede = function (idBandeiraRede) {
       };
       ownerReference.setGpecon = function (idGpecon) {
       };
       ownerReference.UpdateIndependentRelation = function(detailName) {
           var cacheElements = dataContext.getEntities(detailName);
           for (var idxR = 0; idxR < cacheElements.length; idxR++) {
               if (typeof cacheElements[idxR].TiposCamposView !== 'function') { return; }
               else  if (cacheElements[idxR].TiposCamposView() != ownerReference) { cacheElements[idxR].TiposCamposView(ownerReference); }
           }
       }
       ownerReference.setDefaults = function () {
           setAbsoluteValue(ownerReference, 'Guid', getNewGuid());
       };
       ownerReference.delete = function() {
           if (ownerReference.isDetached()) {
               app.showMessage('A informação selecionada não pode ser excluída!', 'Alerta', ['Ok']);
               return;
           }
           if (ownerReference.setParentAsModified) ownerReference.setParentAsModified();
           if (!isNullOrEmpty(ownerReference.TiposCamposFilhaViewList()) && ownerReference.TiposCamposFilhaViewList().length > 0) {
              var details = [].concat(ownerReference.TiposCamposFilhaViewList());
              for (var idx = 0; idx < details.length; idx++) {
                details[idx].delete();
              }
           }
           if (ownerReference.entityAspect) ownerReference.entityAspect.setDeleted(); // mark for deletion
       };
       ownerReference.setParentAsModified = function() {
       };
       ownerReference.getParent = function() {
           return null;
       };
       ownerReference.getSelfList = function() {
           return vm.dataView();
       };
       ownerReference.namespace = 'LinxTraining001.BV.TiposCampos';
       ownerReference.myProperties = [ 'Boolean','Byte','DateTime','Decimal','Guid','IDTiposCampos','Int','Long','Short','String','StringChar','StringText','DecimalKpiInfo' ];
       ownerReference.queryRequiredProperties = {  };
       ownerReference.excludedFilters = [];
       ownerReference.getCurrentElements = function() {
           var result = [ ownerReference ];
       if (!isNullOrEmpty(ownerReference.currentTiposCamposFilhaView())) { result = result.concat(ownerReference.currentTiposCamposFilhaView().getCurrentElements()); }
           return result;
       };
       ownerReference.checkForSendingAllRowsToServer = function() {
       };
       ownerReference.GetJsWhereDetailRelationForTiposCamposFilhaView = function(customParentRelation) {
       return 'TiposCamposFilhaView{' + (!isNullOrEmpty(customParentRelation) ? customParentRelation : 'IDTiposCampos#==#' + ownerReference.serverDataType['IDTiposCampos'] + getAbsoluteValue(ownerReference.IDTiposCampos).toString()) + '}';    
       }
       ownerReference.TiposCamposFilhaViewIsLoaded = false;
       ownerReference.detailsLoaded = function() {
           return ownerReference.TiposCamposFilhaViewIsLoaded;
       }
       ownerReference.atLeastOneDetailLoaded = function() {
           return ownerReference.TiposCamposFilhaViewIsLoaded;
       }
       ownerReference.adjustDetailsLoaded = function(value) {
           ownerReference.TiposCamposFilhaViewIsLoaded = value;
           if (value === false && ownerReference.isPOCO)
               ownerReference.TiposCamposFilhaViewList([]);
       }
       ownerReference.fillDetails = function(force, detailName, noInnerUIs, noWait, callback, customParentRelation) {
          if (typeof force === 'undefined') force = false;
          if (force) vm.clearInnerUIs(ownerReference);
          if (!noInnerUIs) vm.queryInnerUIs(ownerReference);
          if (ownerReference.isAdded()) return;
          var _TiposCamposFilhaViewRemoteComplete = false;
          var detachList_TiposCamposFilhaView = [];
          if (force) {
               if (isNullOrEmpty(detailName) || detailName == 'TiposCamposFilhaView') ownerReference.TiposCamposFilhaViewIsLoaded = false;
               if ((isNullOrEmpty(detailName) || detailName == 'TiposCamposFilhaView') && ownerReference.TiposCamposFilhaViewList && ownerReference.TiposCamposFilhaViewList().length > 0) {
                   if (ownerReference.isPOCO) {
                       ownerReference.TiposCamposFilhaViewList([]);
                   } else {
                       var detailList = ownerReference.TiposCamposFilhaViewList();
                       for (var idx = detailList.length - 1; idx >= 0; idx--) {
                           detachList_TiposCamposFilhaView.push(detailList[idx]);
                       }
                   }
               }
          }
    
          if (!ownerReference.TiposCamposFilhaViewIsLoaded) {
            //Load TiposCamposFilhaViewList
            if (isNullOrEmpty(detailName) || detailName === 'TiposCamposFilhaView') {
              ownerReference.TiposCamposFilhaViewIsLoaded = true;
              _TiposCamposFilhaViewRemoteComplete = (ownerReference.TiposCamposFilhaViewList && ownerReference.TiposCamposFilhaViewList().length > 0);
              if ((force || !ownerReference.TiposCamposFilhaViewList || ownerReference.TiposCamposFilhaViewList().length === 0) && (!isNullOrEmpty(getAbsoluteValue(ownerReference.IDTiposCampos)))) {
                var navQuery = EntityQuery.from('GetTiposCamposFilhaViewByEntitySearchNoAssociations').noTracking(ownerReference.isPOCO === true)
                .orderBy('IDTiposCamposFilha asc')
                    .withParameters({ jEntitySearch: ownerReference.GetJsWhereDetailRelationForTiposCamposFilhaView(customParentRelation) })    ;
                vm.showProcessing('Pesquisando detalhes...');
                manager.executeQuery(navQuery).then(function (data) { if (ownerReference.isPOCO) { for (var idx = 0; idx < data.results.length; idx++) { initializePOCO(data.results[idx], 'TiposCamposFilhaView'); data.results[idx].TiposCamposView = ko.observable(ownerReference); } ownerReference.TiposCamposFilhaViewList(data.results); } 
                   if (!ownerReference.isPOCO && detachList_TiposCamposFilhaView.length > 0)
                   {
                       for (var idx = 0; idx < detachList_TiposCamposFilhaView.length; idx++)
                       {
                           if (!data.results.contains(detachList_TiposCamposFilhaView[idx]))
                               detachEntity(detachList_TiposCamposFilhaView[idx]);
                           else {
                               if (force && detachList_TiposCamposFilhaView[idx].atLeastOneDetailLoaded())
                                   detachList_TiposCamposFilhaView[idx].fillDetails(force, '', false, noWait);
                           }
                       }
                   }
                   ownerReference.setCurrentDetails('TiposCamposFilhaView'); notifyPresentation('TiposCamposFilhaViewList');
                   _TiposCamposFilhaViewRemoteComplete = true;
                   if (callback && (!isNullOrEmpty(detailName) || (_TiposCamposFilhaViewRemoteComplete))) { callback(); }
                }).fail(queryFailed).fin(function() { vm.closeProcessing(); });
              } else { ownerReference.setCurrentDetails('TiposCamposFilhaView'); notifyPresentation('TiposCamposFilhaViewList'); }
            } else { if (!ownerReference.TiposCamposFilhaViewIsLoaded && ownerReference.TiposCamposFilhaViewList && ownerReference.TiposCamposFilhaViewList().length > 0) { ownerReference.TiposCamposFilhaViewIsLoaded = true; } notifyPresentation('TiposCamposFilhaViewList'); }
          } else { 
            if (isNullOrEmpty(detailName) || detailName == 'TiposCamposFilhaView') {
               notifyPresentation('TiposCamposFilhaViewList');
               ownerReference.setCurrentDetails('TiposCamposFilhaView');
            }
            _TiposCamposFilhaViewRemoteComplete = true;
          }
          if (callback && ((!isNullOrEmpty(detailName) && (eval('_' + detailName + 'RemoteComplete && ownerReference.' + detailName + 'IsLoaded') == true)) || (isNullOrEmpty(detailName) && (_TiposCamposFilhaViewRemoteComplete)))) { callback(); }
       };
       //Select first element as a current item of each detail
       ownerReference.setCurrentDetails = function(detailName) {
          if ((isNullOrEmpty(detailName) || detailName === 'TiposCamposFilhaView')) {
               if (ownerReference.TiposCamposFilhaViewList().length > 0) { ownerReference.currentTiposCamposFilhaView(ownerReference.TiposCamposFilhaViewList()[0]); ownerReference.currentTiposCamposFilhaView().fillDetails(); }
               else { ownerReference.currentTiposCamposFilhaView(null); ownerReference.notifyEmptyDetails('TiposCamposFilhaView'); }
          }
       };
       ownerReference.notifyEmptyDetails = function(detailName) {
          if (detailName === 'TiposCamposFilhaView') {
               notifyPresentation('TiposCamposFilhaViewList');
               vm.queryInnerUIs(null, 'TiposCamposFilhaView');
          }
       };
    //#region Extended Domain Names
       if (isPOCO !== true) {
           ownerReference.StringName.subscribe(
               function (newValue) {
                   if (newValue == null) { ownerReference.StringName(''); return; }
                   var value = (dataDomains.getId('TstDomainString', newValue));
                   if (value != ownerReference.String()) {
                       ownerReference.String(value);
                   }
            });
    
           ownerReference.String.subscribe(
           function (newValue) {
                   if (newValue == null) { ownerReference.String(''); return; }
                   var value = dataDomains.getName('TstDomainString', newValue);
                   if (value != ownerReference.StringName()) {
                       ownerReference.StringName(value);
               }
           });
       }
    //#endregion Extended Domain Names
    //#region Adjust details already loaded for a POCO reference
       if (isPOCO === true) {
           if ((typeof ownerReference.TiposCamposFilhaViewList === 'function') && ownerReference.TiposCamposFilhaViewList().length > 0) {
                for(var idx = 0; idx < ownerReference.TiposCamposFilhaViewList().length; idx++) { TiposCamposFilhaViewInitializer(ownerReference.TiposCamposFilhaViewList()[idx], isPOCO); }
           }
       }
    //#endregion Adjust details already loaded for a POCO reference
    };
    metadataStore.registerEntityTypeCtor("TiposCamposView", null, TiposCamposViewInitializer);
    
    // Configure TiposCamposFilhaView data type
    metadataStore.addEntityType({
    shortName: "TiposCamposFilhaView",
    namespace: "LinxTraining001.BV.TiposCampos",
    autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
    dataProperties: {
    Boolean: { dataType: DataType.Boolean, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,DateTime: { dataType: DataType.DateTime, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Decimal: { dataType: DataType.Decimal, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Guid: { dataType: DataType.Guid, isNullable: false, isPartOfKey: false, validators: [ Validator.hasValueValidator]  }
    ,IDTiposCampos: { dataType: DataType.Int32, isNullable: false, isPartOfKey: false, validators: [ ]  }
    ,IDTiposCamposFilha: { dataType: DataType.Int32, isNullable: false, isPartOfKey: true, validators: [ Validator.hasValueValidator]  }
    ,Int: { dataType: DataType.Int32, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Long: { dataType: DataType.Int64, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,Short: { dataType: DataType.Int16, isNullable: true, isPartOfKey: false, validators: [ ]  }
    ,String: { dataType: DataType.String, maxLength: 10, isNullable: true, isPartOfKey: false, validators: [ Validator.hasValueValidator, Validator.maxLength( {maxLength: 10})]  }
    ,StringName: { dataType: DataType.String, isNullable: false, isPartOfKey: false, validators: [] }
    ,StringChar: { dataType: DataType.String, maxLength: 10, isNullable: true, isPartOfKey: false, validators: [ Validator.maxLength( {maxLength: 10})]  }
    ,StringText: { dataType: DataType.String, isNullable: true, isPartOfKey: false, validators: [ ]  }
                    },
    navigationProperties: {
    // Returns a single parent and associates with Details
    TiposCamposView: { entityTypeName: "TiposCamposView:#LinxTraining001.BV.TiposCampos", isScalar: true, foreignKeyNames: ["IDTiposCampos"], associationName: "FK_TiposCamposView_TiposCamposFilhaView" }
    // Returns collections of details and associates with Parent
                          }
    });
    lookUpProperties['TiposCamposFilhaView'] = {};
    var TiposCamposFilhaViewInitializer = function (ownerReference, isPOCO) {
       ownerReference.RowDataId = (isPOCO === true ? getNextSequence('TiposCamposFilhaView') : ko.observable(getNextSequence('TiposCamposFilhaView')));
       ownerReference.setRemovedLookupFields = function(removedFields) {
           for (var idxLUp in entitylookUps[ownerReference.typeName]) {
               var hasKeyValue = false;
               var luName = entitylookUps[ownerReference.typeName][idxLUp];
               var luMeta = metadataInfo[luName];
               for (var idxProp in luMeta) {
                   var prop = luMeta[idxProp];
                   if (!isNullOrEmpty(prop.relatedKey) && prop.isPartOfKey) {
                       hasKeyValue = !isNullOrEmpty(getAbsoluteValue(ownerReference[prop.relatedKey]));
                       break;
                   }
               }
               if (hasKeyValue) {
                   for (var idxProp in luMeta) {
                       var prop = luMeta[idxProp];
                       if (!isNullOrEmpty(prop.relatedKey) && !prop.isPartOfKey) {
                           removedFields.push(prop.relatedKey);
                       }
                   }
               }
           }
       }
       ownerReference.getJExpression = function(listFilterRange, removedFields, noDetails) {
           if (ownerReference.excludedFilters && ownerReference.excludedFilters.length > 0) { if (removedFields instanceof Array) removedFields = removedFields.concat(ownerReference.excludedFilters); else removedFields = ownerReference.excludedFilters; }
           ownerReference.setRemovedLookupFields(removedFields);
           var jExpression = getJEntityExpression(ownerReference, app, listFilterRange, removedFields);
           if (jExpression === 'Error') return jExpression;
           return jExpression;
      };
       ownerReference.createOriginal = function(propertyName, oldValue) {
           ownerReference.original = ownerReference.getPrimitiveDTO();
           if (propertyName) ownerReference.original[propertyName] = oldValue;
       }
       ownerReference.restoreOriginal = function() {
           if (!isNullOrEmpty(ownerReference.original)) {
              enableChangeTrack = false;
              var properties = metadataInfo[ownerReference.typeName];
              for (var i = 0; i < properties.length; i++) {
                  var propertyName = properties[i].key;
                  if ((typeof ownerReference.original[propertyName]) !== 'undefined') ownerReference[propertyName] = ownerReference.original[propertyName];
              }
              delete ownerReference.original;
              enableChangeTrack = true;
           }
       }
       if (isPOCO === true) {
           ownerReference.getValidationErrors = function(propertyName) {
               var errors = [];
               if (!vm.canReportErrors) return errors;
               if (!ownerReference.ChangeState || ['I', 'U'].indexOf(ownerReference.ChangeState) < 0) return errors;
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                   var prop = properties[i];
                   if (isNullOrEmpty(propertyName) || prop.key == propertyName) {
                       if (prop.isRequired === true && !prop.isPartOfKey && isNullOrEmpty(ownerReference[prop.key])) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] é requerido.');
                       if (prop.validateMaxLength === true && prop.maxLength > 0 && !isNullOrEmpty(ownerReference[prop.key]) && ownerReference[prop.key].length > prop.maxLength) errors.push('O campo [' + prop.headerText + (managerAuth.shellMode=='DEV' ? ' (' + ownerReference.typeName + '.' + prop.key + ')' : '') + '] permite no máximo ' + prop.maxLength.toString() + ' caractere(s).');
                   }
               }
               return errors;
           }
       }
       ownerReference.getPrimitiveDTO = function(loadDetails) {
           var command = '';
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
               command += (command === '' ? '' : ', ') + properties[i].key + ': getAbsoluteValue(ownerReference.' + properties[i].key + ')';
               if (properties[i].isDomain && properties[i].key.length > 4) command += (command === '' ? '' : ', ') + strLeft(properties[i].key, properties[i].key.length - 4) + ': getAbsoluteValue(ownerReference.' + strLeft(properties[i].key, properties[i].key.length - 4) + ')';
           }
           eval('var result = { ' + command + ' };');
           return result;
       };
       ownerReference.getAllDetailChanges = function() {
           var result = [];
           return result;
       };
       ownerReference.copyDataFrom = function(originData, copyDetails) {
           var properties = metadataInfo[ownerReference.typeName];
           for (var i = 0; i < properties.length; i++) {
                setAbsoluteValue(ownerReference, properties[i].key, getAbsoluteValue(originData[properties[i].key]));
           }
       };
          ownerReference.commitDetailsVisualPendings = function() {
          }
          ownerReference.refreshData = function(noWait, succeeded) {
             var filterByKey = 'TiposCamposFilhaView{' + 'IDTiposCamposFilha#==#I' + getAbsoluteValue(ownerReference.IDTiposCamposFilha).toString() + '}';
             if (!ownerReference.isPOCO && ownerReference.entityAspect && !ownerReference.isDetached() && !ownerReference.isUnchanged()) ownerReference.entityAspect.setUnchanged();
             return dataContext.getTiposCamposFilhaViewByEntitySearchNoAssociations(filterByKey, 0, 0, false, true, ownerReference.isPOCO === true).then(querySucceeded);
             function querySucceeded(data) {
                if (succeeded) { succeeded(data); }
                if (data.results.length == 0) { return; }
                if (ownerReference.isPOCO) { for (var idx = 0; idx < data.results.length; idx++) { ownerReference.copyDataFrom(data.results[idx]); } }
                if (!noWait || ownerReference.atLeastOneDetailLoaded()) { vm.clearInnerUIs(ownerReference); ownerReference.fillDetails(true, '', false, noWait); }
           }
          }
       if (isPOCO === true) {
           ownerReference.isPOCO = true;
           ownerReference.enableDetailsDataTack = function(breezeReference) {
              if (breezeReference) breezeReference.setCurrentDetails();
           };
       }
       ownerReference.isAdded = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Added;
       });
       ownerReference.isDeleted = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Deleted;
       });
       ownerReference.isModified = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Modified;
       });
       ownerReference.isDetached = (isPOCO === true ? function() { return false; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Detached;
       });
       ownerReference.isUnchanged = (isPOCO === true ? function() { return true; } : function() {
           return ownerReference.entityAspect.entityState === breeze.EntityState.Unchanged;
       });
       ownerReference.setModified = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setModified();
       });
       ownerReference.setUnchanged = (isPOCO === true ? function() {  } : function() {
           ownerReference.entityAspect.setUnchanged();
       });
       ownerReference.serverDataType = [];
       ownerReference.serverDataType['Boolean'] = 'B';
       ownerReference.serverDataType['DateTime'] = 'T';
       ownerReference.serverDataType['Decimal'] = 'D';
       ownerReference.serverDataType['Guid'] = 'G';
       ownerReference.serverDataType['IDTiposCampos'] = 'I';
       ownerReference.serverDataType['IDTiposCamposFilha'] = 'I';
       ownerReference.serverDataType['Int'] = 'I';
       ownerReference.serverDataType['Long'] = 'L';
       ownerReference.serverDataType['Short'] = 'H';
       ownerReference.serverDataType['String'] = 'S';
       ownerReference.serverDataType['StringChar'] = 'S';
       ownerReference.serverDataType['StringText'] = 'S';
       ownerReference.typeName = 'TiposCamposFilhaView';
       ownerReference.isPrimaryKey = function(propertyName) {
           var keys = [ 'IDTiposCamposFilha' ];
           return keys.indexOf(propertyName) >= 0;
       }
       ownerReference.getDisplayName = function(propertyName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          return (property != null ? property.headerText : propertyName);
       }
       ownerReference.setDisplayName = function(propertyName, displayName) {
          var property = getEntityProperty(ownerReference.typeName, propertyName);
          if (property != null) property.headerText = displayName;
       }
       ownerReference.setBandeiraRede = function (idBandeiraRede) {
       };
       ownerReference.setGpecon = function (idGpecon) {
       };
       ownerReference.UpdateIndependentRelation = function(detailName) {
           var cacheElements = dataContext.getEntities(detailName);
           for (var idxR = 0; idxR < cacheElements.length; idxR++) {
               if (typeof cacheElements[idxR].TiposCamposFilhaView !== 'function') { return; }
               else  if (cacheElements[idxR].TiposCamposFilhaView() != ownerReference) { cacheElements[idxR].TiposCamposFilhaView(ownerReference); }
           }
       }
       ownerReference.setDefaults = function () {
           setAbsoluteValue(ownerReference, 'Guid', getNewGuid());
       };
       ownerReference.delete = function() {
           if (ownerReference.isDetached()) {
               app.showMessage('A informação selecionada não pode ser excluída!', 'Alerta', ['Ok']);
               return;
           }
           if (ownerReference.setParentAsModified) ownerReference.setParentAsModified();
           var parent = getAbsoluteValue(ownerReference.TiposCamposView);
           if (ownerReference.entityAspect) ownerReference.entityAspect.setDeleted(); // mark for deletion
           if (parent && (typeof parent.setCurrentDetails === 'function') && (typeof parent.TiposCamposFilhaViewList === 'function') && parent.TiposCamposFilhaViewList().length == 0) parent.setCurrentDetails('TiposCamposFilhaView');
       };
       ownerReference.setParentAsModified = function() {
       var parent = getAbsoluteValue(ownerReference.TiposCamposView);
       if (parent) {
           if (parent.isUnchanged()) {
               parent.setModified(); 
           }
           parent.setParentAsModified();
       }
       };
       ownerReference.getParent = function() {
           return getAbsoluteValue(ownerReference.TiposCamposView);
       };
       ownerReference.getSelfList = function() {
           var parent = ownerReference.getParent();
           if (!isNullOrEmpty(parent)) {
               return getAbsoluteValue(parent.TiposCamposFilhaViewList);
           } else { return null; }
       };
       ownerReference.namespace = 'LinxTraining001.BV.TiposCampos';
       ownerReference.myProperties = [ 'Boolean','DateTime','Decimal','Guid','IDTiposCampos','IDTiposCamposFilha','Int','Long','Short','String','StringChar','StringText' ];
       ownerReference.queryRequiredProperties = {  };
       ownerReference.excludedFilters = [];
       ownerReference.getCurrentElements = function() {
           var result = [ ownerReference ];
           return result;
       };
       ownerReference.checkForSendingAllRowsToServer = function() {
       };
       ownerReference.detailsLoaded = function() {
           return true;
       }
       ownerReference.atLeastOneDetailLoaded = function() {
           return true;
       }
       ownerReference.adjustDetailsLoaded = function(value) {
       }
       ownerReference.fillDetails = function(force, detailName, noInnerUIs, noWait, callback, customParentRelation) {
          if (typeof force === 'undefined') force = false;
          if (force) vm.clearInnerUIs(ownerReference);
          if (!noInnerUIs) vm.queryInnerUIs(ownerReference);
          if (callback) { callback(); }
       };
       //Select first element as a current item of each detail
       ownerReference.setCurrentDetails = function(detailName) {
       };
       ownerReference.notifyEmptyDetails = function(detailName) {
       };
    //#region Extended Domain Names
       if (isPOCO !== true) {
           ownerReference.StringName.subscribe(
               function (newValue) {
                   if (newValue == null) { ownerReference.StringName(''); return; }
                   var value = (dataDomains.getId('DomainString', newValue));
                   if (value != ownerReference.String()) {
                       ownerReference.String(value);
                   }
            });
    
           ownerReference.String.subscribe(
           function (newValue) {
                   if (newValue == null) { ownerReference.String(''); return; }
                   var value = dataDomains.getName('DomainString', newValue);
                   if (value != ownerReference.StringName()) {
                       ownerReference.StringName(value);
               }
           });
       }
    //#endregion Extended Domain Names
    };
    metadataStore.registerEntityTypeCtor("TiposCamposFilhaView", null, TiposCamposFilhaViewInitializer);
    //#endregion Classes Map
    //#region Context Definition
    
    //#region Get LookUps
    var lookUpExternalManagers = [];
    //#endregion
    //#region Get KPI Ranges
    
    
    var getKpiTesteRanges = function () {
        var query = EntityQuery.from('GetKpiTesteRanges').noTracking(true)
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    //#endregion
    
    //#region Get Combo LookUp
    var getResultsCombo = function (lookupName, fieldName, current, callback) {
        if (typeof current.executeLookUp === 'function') {
           current.executeLookUp(lookupName, fieldName, null, vm, null, null, function (result) {
               if (callback) callback(result);
           });
        }
    };
    //#endregion Get Combo LookUp
    
    //#region Get Business Entities
    
    var getBmEntityProperties = function (entityName, parentDataPath) {
        return manager.executeQuery(EntityQuery.from('GetBmEntityProperties').withParameters({ entityName: entityName, parentDataPath: parentDataPath }).noTracking(true))
        .fail(queryFailed);
    };
    
    var clearTiposCamposView = function (idBandeiraRede, complete) {
        clearAll();
        resetSequence('TiposCamposView');
        var refTiposCamposView = manager.createEntity('TiposCamposView', {}, breeze.EntityState.Unchanged);
        resetSequence('TiposCamposFilhaView');
        var refTiposCamposFilhaView = manager.createEntity('TiposCamposFilhaView', {}, breeze.EntityState.Unchanged);
        refTiposCamposView.currentTiposCamposFilhaView(refTiposCamposFilhaView);
        if (complete) complete({ results: [ refTiposCamposView ] });
        return true;
    };
    
    var getTiposCamposView = function (predicate, preserveCurrentState, noTracking) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetTiposCamposView').noTracking(noTracking)
        .orderBy('IDTiposCampos asc')
        ;
    
        if ((typeof predicate !== 'undefined') && predicate !== null)
            query = query.where(predicate);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    var getTiposCamposViewByEntitySearchNoAssociations = function (jEntitySearch, skip, take, returnInlineCount, preserveCurrentState, noTracking, orderByDef) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetTiposCamposViewByEntitySearchNoAssociations').noTracking(noTracking)
        .orderBy((isNullOrEmpty(orderByDef) ? 'IDTiposCampos asc' : orderByDef))
        ;
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ jEntitySearch: jEntitySearch });
        if (take > 0)
           query = query.skip(skip).take(take);
        if (returnInlineCount)
            query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    var clearTiposCamposFilhaView = function (idBandeiraRede, complete) {
        clearAll();
        resetSequence('TiposCamposFilhaView');
        var refTiposCamposFilhaView = manager.createEntity('TiposCamposFilhaView', {}, breeze.EntityState.Unchanged);
        if (complete) complete({ results: [ refTiposCamposFilhaView ] });
        return true;
    };
    
    var getTiposCamposFilhaView = function (predicate, preserveCurrentState, noTracking) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetTiposCamposFilhaView').noTracking(noTracking)
        .orderBy('IDTiposCamposFilha asc')
        ;
    
        if ((typeof predicate !== 'undefined') && predicate !== null)
            query = query.where(predicate);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    
    var getTiposCamposFilhaViewByEntitySearchNoAssociations = function (jEntitySearch, skip, take, returnInlineCount, preserveCurrentState, noTracking, orderByDef) {
        if (!preserveCurrentState) clearAll();
        var query = EntityQuery.from('GetTiposCamposFilhaViewByEntitySearchNoAssociations').noTracking(noTracking)
        .orderBy((isNullOrEmpty(orderByDef) ? 'IDTiposCamposFilha asc' : orderByDef))
        ;
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ jEntitySearch: jEntitySearch });
        if (take > 0)
           query = query.skip(skip).take(take);
        if (returnInlineCount)
            query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed);
    };
    //#endregion
    
    // Create the data update event.
    var dataUpdateEvent = document.createEvent('Event');
    // Define that the event name is 'TiposCamposContext_DataUpdate'.
    var contextUpdtEvt = 'TiposCamposContext_DataUpdate_' + getNewGuid();
    dataUpdateEvent.initEvent(contextUpdtEvt, true, true);
    
    //#region LookUps Finalizers
    //#endregion
    
    var cancelChanges = function() {
        manager.rejectChanges();
    };
    
    var hasEmptyRequiredFilters = function() {
        return false;
    };
    
    var getEntityProperty = function (entityName, propertyName) {
        for (var i = 0; i < metadataInfo[entityName].length; i++) {
            if (metadataInfo[entityName][i].key === propertyName)
                return metadataInfo[entityName][i];
        }
        return null;
    };
    var getViewInfo = function (entityName) {
        var result = [];
        if (metadataInfo[entityName])
        {
            var viewInfoElements = metadataInfo[entityName];
            for (var i = 0; i < viewInfoElements.length; i++) {
                var selectedElement = viewInfoElements[i];
                if (!selectedElement.hidden && (selectedElement.dataType === 'string' || selectedElement.dataType === 'number'))
                {
                    if (strLeft(selectedElement.key, 3) === 'Cod' || strLeft(selectedElement.key, 2) === 'Id' || strLeft(selectedElement.key, 6) === 'Numero' || strLeft(selectedElement.key, 6) === 'Number') {
                        result.push(selectedElement);
                    }
                }
            }
            for (var i = 0; i < viewInfoElements.length; i++) {
                var selectedElement = viewInfoElements[i];
                if (!selectedElement.hidden && (selectedElement.dataType === 'string')) {
                    if (strLeft(selectedElement.key, 4) === 'Nome' || strLeft(selectedElement.key, 4) === 'Name' || strLeft(selectedElement.key, 4) === 'Desc' || strLeft(selectedElement.key, 6) === 'Titulo' || strLeft(selectedElement.key, 5) === 'Title') {
                        result.push(selectedElement);
                    }
                }
            }
            for (var i = 0; i < viewInfoElements.length; i++) {
                var selectedElement = viewInfoElements[i];
                if (!selectedElement.hidden && selectedElement.dataType === 'date')
                {                
                   result.push(selectedElement);
                }
            }
        }
        return result;
    };
    
    var getChanges = function() {
       return manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified, breeze.EntityState.Deleted]);
    };
    
    var hasValidationErrors = function(savingData) {
        if (savingData instanceof Array) {
           for (var idx = 0; idx < savingData.length; idx++) {
               var entity = savingData[idx];
               if (entity.ChangeState && entity.getValidationErrors && ['I', 'U'].indexOf(entity.ChangeState) >=0) {
                  var errors = entity.getValidationErrors();
                  if (errors.length > 0) {
                       showModalAlert('Campos obrigatórios não estão preenchidos.', errors);
                       return true;
                   }
               }
           }
        }
        else {
           var changes = manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified]);
           for (var idxChange = 0; idxChange < changes.length; idxChange++) {
              changes[idxChange].setParentAsModified();
           }
           changes = manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified]);
           for (var idxChange = 0; idxChange < changes.length; idxChange++) {
              var entity = changes[idxChange];
              var isOk = entity.entityAspect.validateEntity();
              if (!isOk) {
                  var errors = entity.entityAspect.getValidationErrors();
                  var strErrors = [];
                  for (var idx = 0; idx < errors.length; idx++) {
                      var errorMsg = errors[idx].errorMessage;
                      var propName = strExtract(errorMsg, "'", "'");
                      var propDisplay = entity.getDisplayName(propName);
                      errorMsg = errorMsg.replace("'" + propName + "'", "'" + propDisplay + "'" + (managerAuth.shellMode=='DEV' ? " (" + entity.typeName + "." + propName + ")": ""));
                      strErrors.push(translateError(errorMsg));
                  }
                  showModalAlert('Campos obrigatórios não estão preenchidos.', strErrors);
                  return true;
              }
           }
        }
        return false;
    };
    
    var saveChanges = function(saveSucceeded, saveFailed, fin, saveNoTRack) {
        if (saveNoTRack === true) {
            var dataForSaving = JSON.stringify(_.map(vm.getDataForSaving(), function(entity){ return entity.getPrimitiveDTO(entity.ChangeState != 'D'); }));
            return $.ajax({
               type: 'POST',
               crossDomain: true,
               url: getServiceAddress('LinxTraining001TiposCampos/Save' + vm.rootDataTypeName),
               globalError: true,
               contentType: 'application/json',
               async: true,
               cache: false,
               data: dataForSaving,
               success: function (response) {
                      success(response);
               },
               error: function (jqXHR, textStatus, errorThrown) {
                      failed({ message: jqXHR.responseJSON.ExceptionMessage });
               }
            });
        }
        else {
            return manager.saveChanges()
                   .fail(failed).then(success);
        }
    
        function success(result) {
            if (fin) fin();
            if (saveNoTRack === true && result.length > 0) {
               for (var idx = 0; idx < result.length; idx++) { dataContext.initializePOCO(result[idx], vm.rootDataTypeName); }
            }
            else if (result != null && result.keyMappings != null && result.keyMappings.length > 0) {
                for (var idx = 0; idx < result.keyMappings.length; idx++) {
                    if (result.keyMappings[idx].realValue == null) {
                       var entity = manager.getEntityByKey(result.keyMappings[idx].entityTypeName, result.keyMappings[idx].tempValue);
                       if (entity) manager.detachEntity(entity);
                    }
                }
                manager.acceptChanges();
            }
            if (saveSucceeded)
                saveSucceeded(result);
        }
    
        function failed(error) {
            if (fin) fin();
            if (error.message.indexOf('Internal Error in key fixup - unable to locate entity') == -1 && error.message.indexOf('An entity with this key is already in the cache:') == -1) {
               if (saveFailed)
                   saveFailed(error);
               var msg = error.message.replace('Fail by saving data:', '');
               showModalAlert('Falha ao salvar informações.', [ msg ]);
               error.message = msg;
               throw error;
           } else {
               manager.acceptChanges();
           }
        }
    };
    
    var acceptChanges = function () {
        return manager.acceptChanges();
    };
    
    var getEntities = function (entityName) {
        return manager.getEntities(entityName);
    };
    
    var notifyPresentation = function(dataSourceName) {
          if (dataContext.dataForUpdate !== '') {
           setTimeout(function () { notifyPresentation(dataSourceName); }, 100);
           return;
          }
          dataContext.dataForUpdate = dataSourceName;
          document.dispatchEvent(dataUpdateEvent);
          dataContext.dataForUpdate = '';
    };
    
    var getEntityInCache = function (entityName, propertiesReference) {
        var keys = [];
        if (!isNullOrEmpty(propertiesReference)) {
            for (var i = 0; i < metadataInfo[entityName].length; i++) {
                if (metadataInfo[entityName][i].isPartOfKey && !isNullOrEmpty(propertiesReference[metadataInfo[entityName][i].key]))
                    keys.push(propertiesReference[metadataInfo[entityName][i].key]);
            }
            if (keys.length == 0)
                return null;
            else {
                return manager.getEntityByKey(entityName, (keys.length == 1 ? keys[0] : keys));
            }
        }
        else
            return null;
    }
    
    var createEntity = function(entityName, initialValues, unchanged) {
        var entity = getEntityInCache(entityName, initialValues);
        if (!isNullOrEmpty(entity))
            entity.entityAspect.entityState == (unchanged === true ? breeze.EntityState.Unchanged : breeze.EntityState.Added);
        else 
            entity = manager.createEntity(entityName, initialValues, (unchanged === true ? breeze.EntityState.Unchanged : breeze.EntityState.Added));
        return entity;
    };
    
    var createFreeEntity = function(entityName) {
       return manager.createEntity(entityName, {}, breeze.EntityState.Detached);
    }
    
    var createTiposCamposView = function() {
        //Create entity instance
        var entity = createEntity('TiposCamposView', { Boolean: false });
        entity.setDefaults();
        return entity;
    };
    
    var createTiposCamposFilhaView = function(parent, noCurrent) {
        //Create entity instance
        var entity = createEntity('TiposCamposFilhaView', { TiposCamposView: parent, Boolean: false });
        entity.setDefaults();
        if (noCurrent !== true) parent.currentTiposCamposFilhaView(entity);
        if (parent && (typeof parent.setCurrentDetails === 'function') && (typeof parent.TiposCamposFilhaViewList === 'function') && parent.TiposCamposFilhaViewList().length == 0) parent.setCurrentDetails('TiposCamposFilhaView');
        if (entity.setParentAsModified) entity.setParentAsModified();
        return entity;
    };
    
    var deleteEntity = function (entity) {
        entity.delete();
    };
    
    var detachEntity = function (entity) {
        if (!entity.isDetached()) entity.entityAspect.setDetached();
    };
    
    var attachEntity = function (entity) {
        manager.attachEntity(entity);
    };
    
    var clearAll = function () {
        manager.rejectChanges();
        manager.clear();
    };
    
    var executeQuery = function (getMethod, jEntitySearch, order, skip, take, noTracking, callBack) {
        var query = EntityQuery.from(getMethod).noTracking(noTracking)
        .orderBy(order);
    
        if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
            query = query.withParameters({ jEntitySearch: jEntitySearch });
    
        if (take > 0)
           query = query.skip(skip).take(take);
        query = query.inlineCount(true);
    
        return manager.executeQuery(query)
        .fail(queryFailed).then(function (data) {
            if (callBack) {
                callBack(data.results);
            }
        });
    };
    var exportToExcel = function(entityName, jEntitySearch, translatedJEntitySearch, complete, columnsVisible) {
        var info = jQuery.grep(dataExportInfo[vm.rootDataTypeName], function (item, i) { return (item.name === entityName);});
        if (info == null || info.length === 0) {
            app.showMessage('Erro na exportação', 'Alerta', ['Ok']);
            return;
        }
        $.ajax({
           type: 'POST',
           crossDomain: true,
           url: getServiceAddress(info[0].actionExport),
           globalError: true,
           headers: managerAuth.getHeaders(),
           contentType: 'application/json',
           async: true,
           cache: false,
           data: JSON.stringify([jEntitySearch, translatedJEntitySearch, columnsVisible]),
           success: function (response) {
                  saveExcelBlob(entityName + '.xlsx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
           }
        });
    };
    var exportReportDataSource = function(complete) {
        $.ajax({
           type: 'GET',
           crossDomain: true,
           headers: managerAuth.getHeaders(),
           url: getServiceAddress("LinxTraining001TiposCampos/GetReportDataSource"),
           success: function (response) {
                  saveExcelBlob('datasource.ldsx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
                  alert('Erro na exportação do data source');
           }
        });
    };
    var exportTemplateReport = function(reportPath, complete) {
        $.ajax({
           type: 'GET',
           crossDomain: true,
           headers: managerAuth.getHeaders(),
           url: getServiceAddress("LinxTraining001TiposCampos/GetTemplateReport"),
           data: { reportPath: reportPath },
           success: function (response) {
                  saveExcelBlob(reportPath + '.lrtx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
                  alert('Erro na exportação do data source');
           }
        });
    };
    var exportToReport = function(reportName, entityName, jEntitySearch, translatedJEntitySearch, complete, columnsVisible, exportMedia) {
        var info = jQuery.grep(dataExportInfo[vm.rootDataTypeName], function (item, i) { return (item.name === entityName);});
        if (info == null || info.length === 0) {
            app.showMessage('Erro na exportação', 'Alerta', ['Ok']);
            return;
        }
        $.ajax({
           type: 'POST',
           crossDomain: true,
           headers: managerAuth.getHeaders(),
           url: getServiceAddress(info[0].actionReport),
           globalError: true,
           contentType: 'application/json',
           async: true,
           cache: false,
           data: JSON.stringify([ reportName, jEntitySearch, translatedJEntitySearch, columnsVisible, getServiceAddress(''), exportMedia ]),
           success: function (response) {
                  saveExcelBlob(entityName + '.lrtx', response);
           },
           complete: function (jqXHR, textStatus) {
                  if(complete) complete();
           },
           error: function (jqXHR, textStatus, errorThrown) {
           }
        });
    };
    
    var hasChanges = ko.observable(false);
    
    manager.hasChangesChanged.subscribe(function(eventArgs) {
        hasChanges(eventArgs.hasChanges);
    });
    
    //#region Internal methods
    
    function queryFailed(error) {
        var msg = error.message;
        if (isNullOrEmpty(msg)) return;
        showModalAlert('Falha ao pesquisar informações.', [ msg ]);
        error.message = msg;
        throw error;
    }
    
    function log(msg, data) {
        logger.log(msg, data, system.getModuleId(dataContext), true);
    }
    
    function logError(msg, error) {
         logger.logError(msg, error, system.getModuleId(dataContext), true);
    }
    
    function loadParameters() {
     dataParameters.isLoaded = true;
    }
    
    //#endregion Internal methods
    //#region getWithBinding
    var createDTOEmpty = function (entityName) {
        var entityType = manager.metadataStore.getEntityType(entityName);
        var entity = {};
        for (var idx = 0; idx < entityType.dataProperties.length; idx++) {
            var prop = entityType.dataProperties[idx];
            entity[prop.name] = prop.defaultValue;
        }
        for (var idx = 0; idx < entityType.navigationProperties.length; idx++) {
            var navigationName = entityType.navigationProperties[idx].name;
            if (navigationName.endsWith('List'))
                entity['current' + navigationName.replace('List', '')] = null;
        }
        entity.isEmptyEntity = true;
        return entity;
    };
    var getWithBinding = function (binding, entityName) {
        if (typeof binding === 'function' && binding() != null)
            return binding;
        else
            return createDTOEmpty(entityName);
    }
    //#endregion getWithBinding
    
        var vm = null;
        var dataContext = {
            dataForUpdate: '',
            getPivotLayouts: getPivotLayouts,
            getSelectedLayoutContent: getSelectedLayoutContent,
            getServiceAddress: getServiceAddress,
            getDataFeedUrl: getDataFeedUrl,
            getDataServiceUrl: getDataServiceUrl,
            setServiceBusUrl: setServiceBusUrl,
            initializePOCO: initializePOCO,
            getWithBinding: getWithBinding,
            managerAuth: managerAuth,
            hasDataFeed: true,
            getAccessGroup: getAccessGroup,
            getNewGuid: getNewGuid,
            metadataInfo: metadataInfo,
            dataExportInfo: dataExportInfo,
            entityNames: entityNames,
            lookUpNames: lookUpNames,
            lookUpProperties: lookUpProperties,
            metadataStore: metadataStore,
            cancelChanges: cancelChanges,
            saveChanges: saveChanges,
            getChanges: getChanges,
            hasValidationErrors: hasValidationErrors,
            getEntityProperty: getEntityProperty,
            getViewInfo: getViewInfo,
            createEntity: createEntity,
            notifyPresentation: notifyPresentation,
            createFreeEntity: createFreeEntity,
            createTiposCamposView: createTiposCamposView,
            createTiposCamposFilhaView: createTiposCamposFilhaView,
            deleteEntity: deleteEntity,
            acceptChanges: acceptChanges,
            getEntities: getEntities,
            detachEntity: detachEntity,
            attachEntity: attachEntity,
            executeQuery: executeQuery,
            sharedData: [],
            clearAll: clearAll,
            hasChanges: hasChanges,
            dataDomains: dataDomains,
            dataParameters: dataParameters,
            loadParameters: loadParameters,
            exportToExcel: exportToExcel,
            exportToReport: exportToReport,
            exportReportDataSource: exportReportDataSource,
            exportTemplateReport: exportTemplateReport,
            businessAssemblyName: businessAssemblyName,
            controllerName: controllerName,
            getResultsCombo: getResultsCombo,
            breeze: breeze,
            contextUpdtEvt: contextUpdtEvt,
            setCurrentViewModel: function(vModel) { vm = vModel; },
            getKpiTesteRanges: getKpiTesteRanges,
            getBmEntityProperties: getBmEntityProperties,
            clearTiposCamposView: clearTiposCamposView,
            getTiposCamposView: getTiposCamposView,
            getTiposCamposViewByEntitySearchNoAssociations: getTiposCamposViewByEntitySearchNoAssociations,
            clearTiposCamposFilhaView: clearTiposCamposFilhaView,
            getTiposCamposFilhaView: getTiposCamposFilhaView,
            getTiposCamposFilhaViewByEntitySearchNoAssociations: getTiposCamposFilhaViewByEntitySearchNoAssociations
        };
    loadParameters();
    return dataContext;
    //#endregion Context Definition
}
return result;
});
