define([
        'appModule'
], function (module) {
    'use strict';

    var name = 'LinxTraining001_venda02Service';
    
    var dependencies = [
            '$http',
            '$log',
            'breeze',
            'commonFactory',
            'dialogFactory',
            'messengerFactory',
            'authService',
            'LinxTraining001_MobileDataDomains'
    ];
    
    var serviceAPI = function ($http, $log, breeze, common, dialog, messenger, authService, dataDomains) {
       var ctrContext = function () { return new dataContextConstructor($http, $log, breeze, common, dialog, messenger, authService, dataDomains); };
       return ctrContext;
    }
    var dataContextConstructor = function ($http, $log, breeze, common, dialog, messenger, authService, dataDomains) {
        var getServiceAddress = function(apiPart) {
           var serviceBus = authService.getServiceAddress(businessAssemblyName, controllerName);
           return serviceBus + (common.strRight(serviceBus, 1) == '/' ? '' : '/') + apiPart;
        };
        var getAccessGroup = function() {
           return (authService.userInfo.currentEnvironment ? authService.userInfo.currentEnvironment.UidGrupoAcesso : '');
        };
        var getNewGuid = function() {
           return breeze.core.getUuid();
        };
        var getDataFeedUrl = function() {
           var baseApi = getDataServiceUrl();
           return common.strLeft(baseApi, baseApi.length - 1) + 'OData/';
        };
        var getDataServiceUrl = function (reset) {
           var baseApi = (!reset && dataService && !common.isNullOrEmpty(dataService.serviceName) ? dataService.serviceName : getServiceAddress(controllerName));
           return baseApi + (common.strRight(baseApi, 1) == '/' ? '' : '/');
        };
        var setServiceBusUrl = function (url) {
           if (dataService) { dataService.serviceName = (common.isNullOrEmpty(url) ? getDataServiceUrl(true) : url + (common.strRight(url, 1) == '/' ? '' : '/') + controllerName + '/'); }
        };
        var initializePOCO = function(ownerReference, entityName) {
           if (ownerReference) { eval(entityName + 'Initializer(ownerReference, true);'); }
        };
        var businessAssemblyName = 'LinxTraining001.BV';
        var controllerName = 'LinxTraining001Venda02';
        var dataService = new breeze.DataService({ serviceName: getDataServiceUrl(true) /*WebApi Service Address*/, hasServerMetadata: false /*don't ask the server for metadata*/ });
        var manager = new breeze.EntityManager({ dataService: dataService });
        var metadataStore = manager.metadataStore;
        var EntityQuery = breeze.EntityQuery;
        // Extract Breeze metadata definition types
        var DataType = breeze.DataType;
        DataType.parseDateFromServer = function (source) {
            return new Date(Date.parse(source));
        };
        var AutoGeneratedKeyType = breeze.AutoGeneratedKeyType;
        var Validator = breeze.Validator;
        //#region Metadata Info
        var metadataInfo = [];
        var dataExportInfo = [];
        var entityNames = [];
        var lookUpNames = [];
        var entitylookUps = [];
        entityNames.push('ClientesView');
        metadataInfo['ClientesView'] = [
            { key: 'EntityUniqueKey', maxLength: 0, isPartOfKey: true, headerText: 'EntityUniqueKey', width: '50px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
            { key: 'IDClientes', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 36, isPartOfKey: false, headerText: 'ID Clientes', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'Nome', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 40, isPartOfKey: false, headerText: 'Nome', width: '400px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'TipoName', isDomain: true, domainName: 'LXTipoClientes', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Tipo', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'Tipo', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Tipo', width: '0px', dataType: 'number', format: '', hidden: true, unbound: false, group: null }
        ];
        dataExportInfo['ClientesView'] = [ 
            { name: 'ClientesView', canExportMedia: false , canExportReport: true, actionExport: 'LinxTraining001Venda02/GetClientesViewToExcel', actionReport: 'LinxTraining001Venda02/GetClientesViewToReportXml', actionFeed: 'LinxTraining001Venda02OData/ClientesView', actionName: 'LinxTraining001Venda02/GetClientesViewByEntitySearchNoAssociations', display: 'ClientesView',  metaData: function() { return metadataInfo['ClientesView']; } }
            , { name: 'VendasView', canExportMedia: false , canExportReport: true, actionExport: 'LinxTraining001Venda02/GetVendasViewParentCompositionToExcel', actionReport: 'LinxTraining001Venda02/GetVendasViewParentCompositionToReportXml', actionFeed: 'LinxTraining001Venda02OData/VendasViewParentComposition', actionName: 'LinxTraining001Venda02/GetVendasViewParentCompositionByEntitySearchNoAssociations', display: 'VendasView',  metaData: function() { return metadataInfo['VendasViewParentComposition']; } }
        ];
        entitylookUps.push('ClientesView');
        entitylookUps['ClientesView'] = [];
        entityNames.push('VendasView');
        metadataInfo['VendasView'] = [
            { key: 'EntityUniqueKey', maxLength: 0, isPartOfKey: true, headerText: 'EntityUniqueKey', width: '50px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
            { key: 'EntityParentUniqueKey', maxLength: 0, isPartOfKey: false, headerText: 'EntityUniqueKey', width: '50px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
            { key: 'Data', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Data', width: '120px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
            { key: 'IDClientes', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 36, isPartOfKey: false, headerText: 'ID Clientes', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'IDVendas', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'ID Vendas', width: '153px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
            { key: 'OrigemName', isDomain: true, domainName: 'LXOrigem', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Origem', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'Origem', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Origem', width: '0px', dataType: 'number', format: '', hidden: true, unbound: false, group: null },
            { key: 'ValorTotal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'ValorTotal', width: '166px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
            { key: 'VendaVip', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'VendaVip', width: '140px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null }
        ];
        entityNames.push('VendasViewParentComposition');
        metadataInfo['VendasViewParentComposition'] = [
            { key: 'EntityUniqueKey', maxLength: 0, isPartOfKey: true, headerText: 'EntityUniqueKey', width: '50px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
            { key: 'EntityParentUniqueKey', maxLength: 0, isPartOfKey: false, headerText: 'EntityUniqueKey', width: '50px', dataType: 'string', format: '', hidden: true, unbound: false, group: null },
            { key: 'Data', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'Data', width: '120px', dataType: 'date', format: 'dd/MM/yyyy', hidden: false, unbound: false, group: null },
            { key: 'IDClientes', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 36, isPartOfKey: false, headerText: 'ID Clientes', width: '250px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'IDVendas', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'ID Vendas', width: '153px', dataType: 'number', format: 'int', hidden: false, unbound: false, group: null },
            { key: 'OrigemName', isDomain: true, domainName: 'LXOrigem', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Origem', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'Origem', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Origem', width: '0px', dataType: 'number', format: '', hidden: true, unbound: false, group: null },
            { key: 'ValorTotal', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 10, isPartOfKey: false, headerText: 'ValorTotal', width: '166px', dataType: 'number', format: '0.00', hidden: false, unbound: false, group: null },
            { key: 'VendaVip', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 0, isPartOfKey: false, headerText: 'VendaVip', width: '140px', dataType: 'bool', format: 'checkbox', hidden: false, unbound: false, group: null },
            { key: 'Nome', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 40, isPartOfKey: false, headerText: 'Nome', width: '400px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'TipoName', isDomain: true, domainName: 'LXTipoClientes', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Tipo', width: '200px', dataType: 'string', format: '', hidden: false, unbound: false, group: null },
            { key: 'Tipo', isDomain: false, domainName: '', lookupPropertyName: '', lookupVisibleColumns: '', maxLength: 12, isPartOfKey: false, headerText: 'Tipo', width: '0px', dataType: 'number', format: '', hidden: true, unbound: false, group: null }
        ];
        dataExportInfo['VendasView'] = [ 
            { name: 'VendasView', canExportMedia: false , canExportReport: true, actionExport: 'LinxTraining001Venda02/GetVendasViewToExcel', actionReport: 'LinxTraining001Venda02/GetVendasViewToReportXml', actionFeed: 'LinxTraining001Venda02OData/VendasView', actionName: 'LinxTraining001Venda02/GetVendasViewByEntitySearchNoAssociations', display: 'VendasView',  metaData: function() { return metadataInfo['VendasView']; } }
        ];
        entitylookUps.push('VendasView');
        entitylookUps['VendasView'] = [];
        var lookUpProperties = [];
        //#endregion Metadata Info
        //#region dataParameters
        var dataParameters = {
            isLoaded: false,
            parameters: [],
            registerParameters: function (parameterList, complete) {
                if (parameterList !== '') {
                    var variation = '{TBC_GRUPO_ECONOMICO|' + (authService.userInfo.currentEnvironment ? authService.userInfo.currentEnvironment.IdLinxGpecon.toString() : '0') + '|TCS_USUARIO|' + (authService.userInfo.currentEnvironment ? authService.userInfo.currentEnvironment.UidUsuario : '') + (dataBusiness != null && dataBusiness.getBandeiraRede() > 0 ? '|TBC_BANDEIRA_REDE|' + dataBusiness.getBandeiraRede().toString() : '') + '}';
                    $.ajax({
                        type: 'GET',
                        url: getServiceAddress('LinxFrameworkParametro') + '/GetParameterValue?serializedParameterList=' + common.stringReplace(parameterList, '{}', variation),
                        dataType: 'json',
                        cache: false,
                        error: function (jqXHR, textStatus, errorThrown) {
                            var msg = 'Os seguintes parâmetros não foram pesquisados: [' + parameterList + ']';
                            dialog.showAlert(msg, 'Alerta');
                            dataParameters.isLoaded = true;
                        },
                        success: function (data) {
                            var parametersName = '';
                            var parameters = data.split('#');
                            for (var idx in parameters) {
                                var values = parameters[idx].split('|');
                                var pName = values[0];
                                var pValue = values[1];
                                dataParameters.parameters[pName] = pValue;
                            }
                            dataParameters.isLoaded = true;
                            if (complete) complete();
                        }
                    });
                }
            }
        };
        //#endregion dataParameters
        //#region Classes Map
        var sequences = [];
        var resetSequence = function(entityName) {
            sequences[entityName] = 0;
        };
        var getSequence = function(entityName) {
            if ((typeof sequences[entityName]) === 'undefined') resetSequence(entityName);
            return (++sequences[entityName]);
        };
        
        // Configure ClientesView data type
        metadataStore.addEntityType({
        shortName: "ClientesView",
        namespace: "LinxTraining001.BV.Venda02",
        autoGeneratedKeyType: AutoGeneratedKeyType.None,
        dataProperties: {
        EntityUniqueKey: { dataType: DataType.Guid, isNullable: false, isPartOfKey: true, validators: [ ]  }
        ,IDClientes: { dataType: DataType.Guid, isNullable: false, isPartOfKey: false, validators: [ Validator.required()]  }
        ,Nome: { dataType: DataType.String, maxLength: 40, isNullable: true, isPartOfKey: false, validators: [ Validator.maxLength( {maxLength: 40})]  }
        ,Tipo: { dataType: DataType.Int32, isNullable: true, isPartOfKey: false, validators: [ ]  }
                        },
        navigationProperties: {
        // Returns collections of details and associates with Parent
        VendasViewList: { entityTypeName: "VendasView:#LinxTraining001.BV.Venda02", isScalar: false, invForeignKeyNames: ["EntityUniqueKey"], associationName: "FK_ClientesView_VendasView" }
                              }
        });
        lookUpProperties['ClientesView'] = {};
        var ClientesViewInitializer = function (ownerReference, isPOCO) {
           ownerReference.currentVendasView = null;
           ownerReference.setRemovedLookupFields = function(removedFields) {
               for (var idxLUp in entitylookUps[ownerReference.typeName]) {
                   var hasKeyValue = false;
                   var luName = entitylookUps[ownerReference.typeName][idxLUp];
                   var luMeta = metadataInfo[luName];
                   for (var idxProp in luMeta) {
                       var prop = luMeta[idxProp];
                       if (!common.isNullOrEmpty(prop.relatedKey) && prop.isPartOfKey) {
                           hasKeyValue = !common.isNullOrEmpty(ownerReference[prop.relatedKey]);
                           break;
                       }
                   }
                   if (hasKeyValue) {
                       for (var idxProp in luMeta) {
                           var prop = luMeta[idxProp];
                           if (!common.isNullOrEmpty(prop.relatedKey) && !prop.isPartOfKey) {
                               removedFields.push(prop.relatedKey);
                           }
                       }
                   }
               }
           }
           ownerReference.getJExpression = function(listFilterRange, removedFields, noDetails) {
               if (ownerReference.excludedFilters && ownerReference.excludedFilters.length > 0) { if (removedFields instanceof Array) removedFields = removedFields.concat(ownerReference.excludedFilters); else removedFields = ownerReference.excludedFilters; }
               ownerReference.setRemovedLookupFields(removedFields);
               var jExpression = common.getJEntityExpression(ownerReference, dialog, listFilterRange, removedFields);
               if (jExpression === 'Error') return jExpression;
               if (noDetails !== true && ownerReference.VendasViewList && ownerReference.VendasViewList.length > 0) {
                 var detailExpr = ownerReference.VendasViewList[0].getJExpression(listFilterRange, ['IDClientes']);
                 if (detailExpr === 'Error') return detailExpr;
                 jExpression += detailExpr;
               }
               return jExpression;
          };
           ownerReference.getPrimitiveDTO = function() {
               var command = '';
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                   command += (command === '' ? '' : ', ') + properties[i].key + ': ownerReference.' + properties[i].key;
                   if (properties[i].isDomain && properties[i].key.length > 4) command += (command === '' ? '' : ', ') + common.strLeft(properties[i].key, properties[i].key.length - 4) + ': ownerReference.' + common.strLeft(properties[i].key, properties[i].key.length - 4);
               }
               var result = {};
               eval('result = { ' + command + ' };');
               return result;
           };
           ownerReference.copyDataFrom = function(originData) {
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                    ownerReference[properties[i].key] = originData[properties[i].key];
               }
           };
              ownerReference.refreshData = function() {
               return { then: function(thenMethod) { if (thenMethod) thenMethod(); }, fin: function(finMethod) { if (finMethod) finMethod(); } }; 
              }
           if (isPOCO === true) {
               ownerReference.isPOCO = true;
               ownerReference.enableDetailsDataTack = function(breezeReference) {
                  for (var idx = 0; idx < ownerReference.VendasViewList.length; idx++) {
                      var entity = ownerReference.VendasViewList[idx];
                      if (entity.isPOCO)  {
                          var newReference = createEntity(entity.typeName, entity.getPrimitiveDTO(), true);
                          entity.enableDetailsDataTack(newReference);
                      }
                  }
                  if (breezeReference) breezeReference.setCurrentDetails();
               };
           }
           ownerReference.isAdded = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Added;
           });
           ownerReference.isDeleted = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Deleted;
           });
           ownerReference.isModified = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Modified;
           });
           ownerReference.isDetached = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Detached;
           });
           ownerReference.isUnchanged = (isPOCO === true ? function() { return true; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Unchanged;
           });
           ownerReference.serverDataType = [];
           ownerReference.serverDataType['IDClientes'] = 'G';
           ownerReference.serverDataType['Nome'] = 'S';
           ownerReference.serverDataType['Tipo'] = 'I';
           ownerReference.typeName = 'ClientesView';
           ownerReference.isPrimaryKey = function(propertyName) {
               var keys = [  ];
               return keys.indexOf(propertyName) >= 0;
           }
           ownerReference.getDisplayName = function(propertyName) {
              var property = getEntityProperty(ownerReference.typeName, propertyName);
              return (property != null ? property.headerText : propertyName);
           }
           ownerReference.setDisplayName = function(propertyName, displayName) {
              var property = getEntityProperty(ownerReference.typeName, propertyName);
              if (property != null) property.headerText = displayName;
           }
           ownerReference.setBandeiraRede = function (idBandeiraRede) {
           };
           ownerReference.setGpecon = function (idGpecon) {
           };
           ownerReference.UpdateIndependentRelation = function(detailName) {
               var cacheElements = dataContext.getEntities(detailName);
               for (var idxR = 0; idxR < cacheElements.length; idxR++) {
                   if (cacheElements[idxR].ClientesView != ownerReference) { cacheElements[idxR].ClientesView = ownerReference; }
               }
           }
           if (isPOCO !== true) {
               ownerReference.Namespace = 'LinxTraining001.BV.Venda02';
               ownerReference.myProperties = [ ,'IDClientes','Nome','Tipo' ];
               ownerReference.queryRequiredProperties = {  };
               ownerReference.excludedFilters = [];
               ownerReference.setDefaults = function () {
                   ownerReference.IDClientes = getNewGuid();
               };
               ownerReference.getCurrentElements = function() {
                   var result = [ ownerReference ];
               if (!common.isNullOrEmpty(ownerReference.currentVendasView)) { result = result.concat(ownerReference.currentVendasView.getCurrentElements()); }
                   return result;
               };
               ownerReference.setParentAsModified = function() {
               };
               ownerReference.delete = function() {
                   if (ownerReference.isDetached()) {
                       dialog.showAlert('A informação selecionada não pode ser excluída!', 'Alerta');
                       return;
                   }
                   ownerReference.setParentAsModified();
                   if (!common.isNullOrEmpty(ownerReference.VendasViewList) && ownerReference.VendasViewList.length > 0) {
                      var details = [].concat(ownerReference.VendasViewList);
                      for (var idx = 0; idx < details.length; idx++) {
                        details[idx].delete();
                      }
                   }
                   ownerReference.entityAspect.setDeleted(); // mark for deletion
               };
               ownerReference.getParent = function() {
                   return null;
               };
               ownerReference.getSelfList = function() {
                   return dataBusiness.dataView();
               };
               ownerReference.checkForSendingAllRowsToServer = function() {
               };
           }
           ownerReference.GetJsWhereDetailRelationForVendasView = function(customParentRelation) {
       return 'VendasView{' + (!isNullOrEmpty(customParentRelation) ? customParentRelation : 'IDClientes#==#' + ownerReference.serverDataType['IDClientes'] + common.getAbsoluteValue(ownerReference.IDClientes).toString()) + '}';        
           }
           ownerReference.VendasViewIsLoaded = false;
           ownerReference.detailsLoaded = function() {
               return ownerReference.VendasViewIsLoaded;
           }
           ownerReference.adjustDetailsLoaded = function(value) {
               ownerReference.VendasViewIsLoaded = value;
           }
           ownerReference.fillDetails = function(force, detailName, callback) {
              if (typeof force === 'undefined') force = false;
              if (callback && ownerReference.detailsLoaded()) callback();
              var _VendasViewRemoteComplete = false;
              var detachList_VendasView = [];
              if (force) {
                   if (common.isNullOrEmpty(detailName) || detailName == 'VendasView') ownerReference.VendasViewIsLoaded = false;
                   if ((common.isNullOrEmpty(detailName) || detailName == 'VendasView') && ownerReference.VendasViewList && ownerReference.VendasViewList.length > 0) {
                       if (ownerReference.isPOCO) {
                           ownerReference.VendasViewList([]);
                       } else {
                           var detailList = ownerReference.VendasViewList;
                           for (var idx = detailList.length - 1; idx >= 0; idx--) {
                               detachList_VendasView.push(detailList[idx]);
                           }
                       }
                   }
              }
        
              if (!ownerReference.VendasViewIsLoaded) {
                //Load VendasViewList
                if (common.isNullOrEmpty(detailName) || detailName === 'VendasView') {
                  dataBusiness.showProcessing('Pesquisando detalhes...');
                  ownerReference.VendasViewIsLoaded = true;
                  if ((force || !ownerReference.VendasViewList || ownerReference.VendasViewList.length === 0) && (!common.isNullOrEmpty(common.getAbsoluteValue(ownerReference.IDClientes)))) {
                    var navQuery = EntityQuery.from('GetVendasViewByEntitySearchNoAssociations').noTracking(ownerReference.isPOCO === true)
                    .orderBy('Data asc')
                    .withParameters({ jEntitySearch: ownerReference.GetJsWhereDetailRelationForVendasView(customParentRelation) })        ;
                    manager.executeQuery(navQuery)
                    .to$q(
                        function (data) {
                           if (ownerReference.isPOCO) { 
                              for (var idx = 0; idx < data.results.length; idx++) {
                                  initializePOCO(data.results[idx], 'VendasView'); 
                                  data.results[idx].ClientesView = ownerReference; 
                              } 
                              ownerReference.VendasViewList = data.results; 
                           } 
                           for (var idx = 0; idx < data.results.length; idx++) { data.results[idx].EntityParentUniqueKey = ownerReference.EntityUniqueKey; if (!ownerReference.isPOCO) { data.results[idx].ClientesView = ownerReference; data.results[idx].entityAspect.entityState === breeze.EntityState.Unchanged; } }
                           if (!ownerReference.isPOCO && detachList_VendasView.length > 0)
                           {
                               for (var idx = 0; idx < detachList_VendasView.length; idx++)
                               {
                                   if (!data.results.contains(detachList_VendasView[idx]))
                                       detachEntity(detachList_VendasView[idx]);
                                   else
                                       detachList_VendasView[idx].adjustDetailsLoaded(false);
                               }
                           }
                           ownerReference.setCurrentDetails('VendasView');
                           dataBusiness.closeProcessing();
                           _VendasViewRemoteComplete = true;
                           if (callback && (!common.isNullOrEmpty(detailName) || (_VendasViewRemoteComplete))) callback();
                        }, 
                        function (error) {
                            dataBusiness.closeProcessing();
                            queryFailed(error);
                        });
                  } else { ownerReference.setCurrentDetails('VendasView'); dataBusiness.closeProcessing(); }
                } else { if (!ownerReference.VendasViewIsLoaded && ownerReference.VendasViewList && ownerReference.VendasViewList.length > 0) { ownerReference.VendasViewIsLoaded = true; } if (ownerReference.VendasViewIsLoaded) { dataBusiness.closeProcessing(); } }
              } else { 
                if (common.isNullOrEmpty(detailName) || detailName == 'VendasView') {
                   ownerReference.setCurrentDetails('VendasView');
                }
                _VendasViewRemoteComplete = true;
              }
           };
           //Select first element as a current item of each detail
           ownerReference.setCurrentDetails = function(detailName) {
              if ((common.isNullOrEmpty(detailName) || detailName === 'VendasView')) {
                   if (ownerReference.VendasViewList.length > 0) { ownerReference.currentVendasView = ownerReference.VendasViewList[0]; ownerReference.currentVendasView.fillDetails(); }
                   else { ownerReference.currentVendasView = null; }
              }
           };
        //#region Adjust details already loaded for a POCO reference
           if (isPOCO === true) {
               if ((typeof ownerReference.VendasViewList === 'function') && ownerReference.VendasViewList.length > 0) {
                    for(var idx = 0; idx < ownerReference.VendasViewList.length; idx++) {  VendasViewInitializer(ownerReference.VendasViewList[idx], isPOCO); }
               }
           }
        //#endregion Adjust details already loaded for a POCO reference
        };
        metadataStore.registerEntityTypeCtor("ClientesView", null, ClientesViewInitializer);
        
        // Configure VendasView data type
        metadataStore.addEntityType({
        shortName: "VendasView",
        namespace: "LinxTraining001.BV.Venda02",
        autoGeneratedKeyType: AutoGeneratedKeyType.None,
        dataProperties: {
        EntityUniqueKey: { dataType: DataType.Guid, isNullable: false, isPartOfKey: true, validators: [ ]  }
        ,EntityParentUniqueKey: { dataType: DataType.Guid, isNullable: false, isPartOfKey: false, validators: [ ]  }
        ,Data: { dataType: DataType.DateTime, isNullable: false, isPartOfKey: false, defaultValue: '', validators: [ Validator.required()]  }
        ,IDClientes: { dataType: DataType.Guid, isNullable: false, isPartOfKey: false, validators: [ Validator.required()]  }
        ,IDVendas: { dataType: DataType.Int32, isNullable: false, isPartOfKey: false, validators: [ Validator.required()]  }
        ,Origem: { dataType: DataType.Int32, isNullable: true, isPartOfKey: false, validators: [ ]  }
        ,ValorTotal: { dataType: DataType.Decimal, isNullable: true, isPartOfKey: false, validators: [ ]  }
        ,VendaVip: { dataType: DataType.Boolean, isNullable: true, isPartOfKey: false, validators: [ ]  }
                        },
        navigationProperties: {
        // Returns a single parent and associates with Details
        ClientesView: { entityTypeName: "ClientesView:#LinxTraining001.BV.Venda02", isScalar: true, foreignKeyNames: ["EntityParentUniqueKey"], associationName: "FK_ClientesView_VendasView" }
        // Returns collections of details and associates with Parent
                              }
        });
        lookUpProperties['VendasView'] = {};
        var VendasViewInitializer = function (ownerReference, isPOCO) {
           ownerReference.setRemovedLookupFields = function(removedFields) {
               for (var idxLUp in entitylookUps[ownerReference.typeName]) {
                   var hasKeyValue = false;
                   var luName = entitylookUps[ownerReference.typeName][idxLUp];
                   var luMeta = metadataInfo[luName];
                   for (var idxProp in luMeta) {
                       var prop = luMeta[idxProp];
                       if (!common.isNullOrEmpty(prop.relatedKey) && prop.isPartOfKey) {
                           hasKeyValue = !common.isNullOrEmpty(ownerReference[prop.relatedKey]);
                           break;
                       }
                   }
                   if (hasKeyValue) {
                       for (var idxProp in luMeta) {
                           var prop = luMeta[idxProp];
                           if (!common.isNullOrEmpty(prop.relatedKey) && !prop.isPartOfKey) {
                               removedFields.push(prop.relatedKey);
                           }
                       }
                   }
               }
           }
           ownerReference.getJExpression = function(listFilterRange, removedFields, noDetails) {
               if (ownerReference.excludedFilters && ownerReference.excludedFilters.length > 0) { if (removedFields instanceof Array) removedFields = removedFields.concat(ownerReference.excludedFilters); else removedFields = ownerReference.excludedFilters; }
               ownerReference.setRemovedLookupFields(removedFields);
               var jExpression = common.getJEntityExpression(ownerReference, dialog, listFilterRange, removedFields);
               if (jExpression === 'Error') return jExpression;
               return jExpression;
          };
           ownerReference.getPrimitiveDTO = function() {
               var command = '';
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                   command += (command === '' ? '' : ', ') + properties[i].key + ': ownerReference.' + properties[i].key;
                   if (properties[i].isDomain && properties[i].key.length > 4) command += (command === '' ? '' : ', ') + common.strLeft(properties[i].key, properties[i].key.length - 4) + ': ownerReference.' + common.strLeft(properties[i].key, properties[i].key.length - 4);
               }
               var result = {};
               eval('result = { ' + command + ' };');
               return result;
           };
           ownerReference.copyDataFrom = function(originData) {
               var properties = metadataInfo[ownerReference.typeName];
               for (var i = 0; i < properties.length; i++) {
                    ownerReference[properties[i].key] = originData[properties[i].key];
               }
           };
              ownerReference.refreshData = function() {
               return { then: function(thenMethod) { if (thenMethod) thenMethod(); }, fin: function(finMethod) { if (finMethod) finMethod(); } }; 
              }
           if (isPOCO === true) {
               ownerReference.isPOCO = true;
               ownerReference.enableDetailsDataTack = function(breezeReference) {
                  if (breezeReference) breezeReference.setCurrentDetails();
               };
           }
           ownerReference.isAdded = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Added;
           });
           ownerReference.isDeleted = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Deleted;
           });
           ownerReference.isModified = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Modified;
           });
           ownerReference.isDetached = (isPOCO === true ? function() { return false; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Detached;
           });
           ownerReference.isUnchanged = (isPOCO === true ? function() { return true; } : function() {
               return ownerReference.entityAspect.entityState === breeze.EntityState.Unchanged;
           });
           ownerReference.serverDataType = [];
           ownerReference.serverDataType['Data'] = 'T';
           ownerReference.serverDataType['IDClientes'] = 'G';
           ownerReference.serverDataType['IDVendas'] = 'I';
           ownerReference.serverDataType['Origem'] = 'I';
           ownerReference.serverDataType['ValorTotal'] = 'D';
           ownerReference.serverDataType['VendaVip'] = 'B';
           ownerReference.typeName = 'VendasView';
           ownerReference.isPrimaryKey = function(propertyName) {
               var keys = [  ];
               return keys.indexOf(propertyName) >= 0;
           }
           ownerReference.getDisplayName = function(propertyName) {
              var property = getEntityProperty(ownerReference.typeName, propertyName);
              return (property != null ? property.headerText : propertyName);
           }
           ownerReference.setDisplayName = function(propertyName, displayName) {
              var property = getEntityProperty(ownerReference.typeName, propertyName);
              if (property != null) property.headerText = displayName;
           }
           ownerReference.setBandeiraRede = function (idBandeiraRede) {
           };
           ownerReference.setGpecon = function (idGpecon) {
           };
           ownerReference.UpdateIndependentRelation = function(detailName) {
               var cacheElements = dataContext.getEntities(detailName);
               for (var idxR = 0; idxR < cacheElements.length; idxR++) {
                   if (cacheElements[idxR].VendasView != ownerReference) { cacheElements[idxR].VendasView = ownerReference; }
               }
           }
           if (isPOCO !== true) {
               ownerReference.Namespace = 'LinxTraining001.BV.Venda02';
               ownerReference.myProperties = [ ,'Data','IDClientes','IDVendas','Origem','ValorTotal','VendaVip' ];
               ownerReference.queryRequiredProperties = {  };
               ownerReference.excludedFilters = [];
               ownerReference.setDefaults = function () {
                   ownerReference.IDClientes = getNewGuid();
                   ownerReference.execute('', 'IDClientes', 0, 10);
                   ownerReference.IDClientes = ownerReference.ClientesView.IDClientes;
               };
               ownerReference.getCurrentElements = function() {
                   var result = [ ownerReference ];
                   return result;
               };
               ownerReference.setParentAsModified = function() {
               if (ownerReference.entityAspect && ownerReference.ClientesView) {
                   if (ownerReference.ClientesView.isUnchanged()) {
                       ownerReference.ClientesView.entityAspect.setModified();
                   }
                   ownerReference.ClientesView.setParentAsModified();
               }
               };
               ownerReference.delete = function() {
                   if (ownerReference.isDetached()) {
                       dialog.showAlert('A informação selecionada não pode ser excluída!', 'Alerta');
                       return;
                   }
                   ownerReference.setParentAsModified();
                   var parent = ownerReference.ClientesView;
                   ownerReference.entityAspect.setDeleted(); // mark for deletion
                   if (parent && (typeof parent.setCurrentDetails === 'function') && (typeof parent.VendasViewList === 'function') && parent.VendasViewList.length == 0) parent.setCurrentDetails('VendasView');
               };
               ownerReference.getParent = function() {
                   return ownerReference.ClientesView;
               };
               ownerReference.getSelfList = function() {
                   return ownerReference.ClientesView.VendasViewList;
               };
               ownerReference.checkForSendingAllRowsToServer = function() {
               };
           }
           ownerReference.detailsLoaded = function() {
               return true;
           }
           ownerReference.adjustDetailsLoaded = function(value) {
           }
           ownerReference.fillDetails = function(force, detailName, callback) {
              if (typeof force === 'undefined') force = false;
           };
           //Select first element as a current item of each detail
           ownerReference.setCurrentDetails = function(detailName) {
           };
        };
        metadataStore.registerEntityTypeCtor("VendasView", null, VendasViewInitializer);
        //#endregion Classes Map
        //#region Context Definition
        
        //#region Get LookUps
        var lookUpExternalManagers = [];
        //#endregion
        //#region Get KPI Ranges
        //#endregion
        
        //#region Get Combo LookUp
        var getResultsCombo = function (lookupName, fieldName, current, callback) {
            eval('if (current.execute' + lookupName + ') { current.execute' + lookupName + '(fieldName, fieldName, 0, -1, function (hasError, resultsArray, inlineCount) {  if (callback) callback(resultsArray); }); }');
        };
        //#endregion Get Combo LookUp
        
        //#region Get Business Entities
        
        var getBmEntityProperties = function (entityName, parentDataPath, qSucceeded, qFin, qFailed) {
            return manager.executeQuery(EntityQuery.from('GetBmEntityProperties').withParameters({ entityName: entityName, parentDataPath: parentDataPath }).noTracking(true))
            .to$q(localQuerySucceeded, localQueryFailed);
        
            function localQuerySucceeded(data) {
                if (qSucceeded)
                    qSucceeded(data);
                if (qFin)
                    qFin();
            }
        
            function localQueryFailed(error) {
                if (qFin)
                    qFin();
                if (qFailed)
                    qFailed(error);
                else
                    queryFailed(error);
            }
        };
        
        var clearClientesView = function (idBandeiraRede, complete) {
            clearAll();
            var refClientesView = manager.createEntity('ClientesView', {}, breeze.EntityState.Unchanged);
            var refVendasView = manager.createEntity('VendasView', {}, breeze.EntityState.Unchanged);
            refClientesView.currentVendasView = refVendasView;
            if (complete) complete({ results: [ refClientesView ] });
            return true;
        };
        
        var getClientesView = function (predicate, preserveCurrentState, noTracking, qSucceeded, qFin, qFailed) {
            if (!preserveCurrentState) clearAll();
            var query = EntityQuery.from('GetClientesView').noTracking(noTracking)
            .orderBy('IDClientes asc')
            ;
        
            if ((typeof predicate !== 'undefined') && predicate !== null)
                query = query.where(predicate);
        
            return manager.executeQuery(query)
            .to$q(localQuerySucceeded, localQueryFailed);
        
            function localQuerySucceeded(data) {
                if (qSucceeded)
                    qSucceeded(data);
                if (qFin)
                    qFin();
            }
        
            function localQueryFailed(error) {
                if (qFin)
                    qFin();
                if (qFailed)
                    qFailed(error);
                else
                    queryFailed(error);
            }
        };
        
        var getClientesViewByEntitySearchNoAssociations = function (jEntitySearch, skip, take, returnInlineCount, preserveCurrentState, noTracking, orderByDef, qSucceeded, qFin, qFailed) {
            if (!preserveCurrentState) clearAll();
            var query = EntityQuery.from('GetClientesViewByEntitySearchNoAssociations').noTracking(noTracking)
            .orderBy((common.isNullOrEmpty(orderByDef) ? 'IDClientes asc' : orderByDef))
;        
        
            if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
                query = query.withParameters({ jEntitySearch: jEntitySearch });
            if (take > 0)
               query = query.skip(skip).take(take);
            if (returnInlineCount)
                query = query.inlineCount(true);
        
            return manager.executeQuery(query)
            .to$q(localQuerySucceeded, localQueryFailed);
        
            function localQuerySucceeded(data) {
                if (qSucceeded)
                    qSucceeded(data);
                if (qFin)
                    qFin();
            }
        
            function localQueryFailed(error) {
                if (qFin)
                    qFin();
                if (qFailed)
                    qFailed(error);
                else
                    queryFailed(error);
            }
        };
        
        var clearVendasView = function (idBandeiraRede, complete) {
            clearAll();
            var refVendasView = manager.createEntity('VendasView', {}, breeze.EntityState.Unchanged);
            if (complete) complete({ results: [ refVendasView ] });
            return true;
        };
        
        var getVendasView = function (predicate, preserveCurrentState, noTracking, qSucceeded, qFin, qFailed) {
            if (!preserveCurrentState) clearAll();
            var query = EntityQuery.from('GetVendasView').noTracking(noTracking)
            .orderBy('Data asc')
            ;
        
            if ((typeof predicate !== 'undefined') && predicate !== null)
                query = query.where(predicate);
        
            return manager.executeQuery(query)
            .to$q(localQuerySucceeded, localQueryFailed);
        
            function localQuerySucceeded(data) {
                if (qSucceeded)
                    qSucceeded(data);
                if (qFin)
                    qFin();
            }
        
            function localQueryFailed(error) {
                if (qFin)
                    qFin();
                if (qFailed)
                    qFailed(error);
                else
                    queryFailed(error);
            }
        };
        
        var getVendasViewByEntitySearchNoAssociations = function (jEntitySearch, skip, take, returnInlineCount, preserveCurrentState, noTracking, orderByDef, qSucceeded, qFin, qFailed) {
            if (!preserveCurrentState) clearAll();
            var query = EntityQuery.from('GetVendasViewByEntitySearchNoAssociations').noTracking(noTracking)
            .orderBy((common.isNullOrEmpty(orderByDef) ? 'Data asc' : orderByDef))
;        
        
            if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
                query = query.withParameters({ jEntitySearch: jEntitySearch });
            if (take > 0)
               query = query.skip(skip).take(take);
            if (returnInlineCount)
                query = query.inlineCount(true);
        
            return manager.executeQuery(query)
            .to$q(localQuerySucceeded, localQueryFailed);
        
            function localQuerySucceeded(data) {
                if (qSucceeded)
                    qSucceeded(data);
                if (qFin)
                    qFin();
            }
        
            function localQueryFailed(error) {
                if (qFin)
                    qFin();
                if (qFailed)
                    qFailed(error);
                else
                    queryFailed(error);
            }
        };
        //#endregion
        
        // Create the data update event.
        var dataUpdateEvent = document.createEvent('Event');
        // Define that the event name is 'venda02Service_DataUpdate'.
        
        var cancelChanges = function() {
            manager.rejectChanges();
        };
        
        var hasEmptyRequiredFilters = function() {
            return false;
        };
        
        var getEntityProperty = function (entityName, propertyName) {
            for (var i = 0; i < metadataInfo[entityName].length; i++) {
                if (metadataInfo[entityName][i].key === propertyName)
                    return metadataInfo[entityName][i];
            }
            return null;
        };
        var getViewInfo = function (entityName) {
            var result = [];
            if (metadataInfo[entityName])
            {
                var viewInfoElements = metadataInfo[entityName];
                for (var i = 0; i < viewInfoElements.length; i++) {
                    var selectedElement = viewInfoElements[i];
                    if (!selectedElement.hidden && (selectedElement.dataType === 'string' || selectedElement.dataType === 'number'))
                    {
                        if (common.strLeft(selectedElement.key, 3) === 'Cod' || common.strLeft(selectedElement.key, 2) === 'Id' || common.strLeft(selectedElement.key, 6) === 'Numero' || common.strLeft(selectedElement.key, 6) === 'Number') {
                            result.push(selectedElement);
                        }
                    }
                }
                for (var i = 0; i < viewInfoElements.length; i++) {
                    var selectedElement = viewInfoElements[i];
                    if (!selectedElement.hidden && (selectedElement.dataType === 'string')) {
                        if (common.strLeft(selectedElement.key, 4) === 'Nome' || common.strLeft(selectedElement.key, 4) === 'Name' || common.strLeft(selectedElement.key, 4) === 'Desc' || common.strLeft(selectedElement.key, 6) === 'Titulo' || common.strLeft(selectedElement.key, 5) === 'Title') {
                            result.push(selectedElement);
                        }
                    }
                }
                for (var i = 0; i < viewInfoElements.length; i++) {
                    var selectedElement = viewInfoElements[i];
                    if (!selectedElement.hidden && selectedElement.dataType === 'date')
                    {                
                       result.push(selectedElement);
                    }
                }
            }
            return result;
        };
        
        var getChanges = function() {
           return manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified, breeze.EntityState.Deleted]);
        };
        
        var hasValidationErrors = function() {
            var changes = manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified]);
            for (var idxChange = 0; idxChange < changes.length; idxChange++) {
               changes[idxChange].setParentAsModified();
            }
            changes = manager.getEntities(null, [breeze.EntityState.Added, breeze.EntityState.Modified]);
            for (var idxChange = 0; idxChange < changes.length; idxChange++) {
               var entity = changes[idxChange];
               var isOk = entity.entityAspect.validateEntity();
               if (!isOk) {
                   var errors = entity.entityAspect.getValidationErrors();
                   var strErrors = '';
                   for (var idx = 0; idx < errors.length; idx++) {
                       var errorMsg = errors[idx].errorMessage;
                       var propName = common.strExtract(errorMsg, "'", "'");
                       var propDisplay = entity.getDisplayName(propName);
                       errorMsg = errorMsg.replace("'" + propName + "'", "'" + propDisplay + "'" + (authService.shellMode=='DEV' ? " (" + entity.typeName + "." + propName + ")": ""));
                       strErrors += ' - ' + errorMsg;
                   }
                   dialog.showAlert('Campos obrigatórios não estão preenchidos.', strErrors);
                   return true;
               }
            }
            return false;
        };
        
        var saveChanges = function(saveSucceeded, saveFin, saveFailed) {
            return manager.saveChanges()
                .to$q(success, failed);
        
            function success(result) {
                if (result != null && result.keyMappings != null && result.keyMappings.length > 0) {
                    for (var idx = 0; idx < result.keyMappings.length; idx++) {
                        if (result.keyMappings[idx].realValue == null) {
                           var entity = manager.getEntityByKey(result.keyMappings[idx].entityTypeName, result.keyMappings[idx].tempValue);
                           if (entity) manager.detachEntity(entity);
                        }
                    }
                    manager.acceptChanges();
                }
                if (saveSucceeded)
                    saveSucceeded(result);
                if (saveFin)
                    saveFin();
            }
        
            function failed(error) {
                if (saveFin)
                    saveFin();
                if (error.message.indexOf('Internal Error in key fixup - unable to locate entity') == -1 && error.message.indexOf('An entity with this key is already in the cache:') == -1) {
                   if (saveFailed)
                       saveFailed(error);
               } else {
                   manager.acceptChanges();
               }
            }
        };
        
        var acceptChanges = function () {
            return manager.acceptChanges();
        };
        
        var getEntities = function (entityName) {
            return manager.getEntities(entityName);
        };
        
        var getEntityInCache = function (entityName, propertiesReference) {
            var keys = [];
            if (!common.isNullOrEmpty(propertiesReference)) {
                for (var i = 0; i < metadataInfo[entityName].length; i++) {
                    if (metadataInfo[entityName][i].isPartOfKey && !common.isNullOrEmpty(propertiesReference[metadataInfo[entityName][i].key]))
                        keys.push(propertiesReference[metadataInfo[entityName][i].key]);
                }
                if (keys.length == 0)
                    return null;
                else {
                    return manager.getEntityByKey(entityName, (keys.length == 1 ? keys[0] : keys));
                }
            }
            else
                return null;
        }
        
        var createEntity = function(entityName, initialValues, unchanged) {
            var entity = getEntityInCache(entityName, initialValues);
            if (!common.isNullOrEmpty(entity))
                entity.entityAspect.entityState == (unchanged === true ? breeze.EntityState.Unchanged : breeze.EntityState.Added);
            else 
                entity = manager.createEntity(entityName, initialValues, (unchanged === true ? breeze.EntityState.Unchanged : breeze.EntityState.Added));
            return entity;
        };
        
        var createFreeEntity = function(entityName) {
           return manager.createEntity(entityName, {}, breeze.EntityState.Detached);
        }
        
        var createClientesView = function() {
            var entity = createEntity('ClientesView', { EntityUniqueKey: getNewGuid() });
            entity.setDefaults();
            return entity;
        };
        
        var createVendasView = function(parent) {
            var entity = createEntity('VendasView', { ClientesView: parent, EntityUniqueKey: getNewGuid(), VendaVip: false });
            entity.setDefaults();
            parent.currentVendasView = entity;
            if (parent && (typeof parent.setCurrentDetails === 'function') && parent.VendasViewList && parent.VendasViewList.length == 0) parent.setCurrentDetails('VendasView');
            return entity;
        };
        
        var deleteEntity = function (entity) {
            entity.delete();
        };
        
        var detachEntity = function (entity) {
            if (!entity.isDetached()) entity.entityAspect.setDetached();
        };
        
        var attachEntity = function (entity) {
            manager.attachEntity(entity);
        };
        
        var clearAll = function () {
            manager.rejectChanges();
            manager.clear();
        };
        
        var executeQuery = function (getMethod, jEntitySearch, order, skip, take, noTracking, qSucceeded, qFin, qFailed) {
            var query = EntityQuery.from(getMethod).noTracking(noTracking)
            .orderBy(order);
        
            if ((typeof jEntitySearch !== 'undefined') && jEntitySearch !== null)
                query = query.withParameters({ jEntitySearch: jEntitySearch });
        
            if (take > 0)
               query = query.skip(skip).take(take);
            query = query.inlineCount(true);
        
            return manager.executeQuery(query)
            .to$q(localQuerySucceeded, localQueryFailed);
        
            function localQuerySucceeded(data) {
                if (qSucceeded)
                    qSucceeded(data);
                if (qFin)
                    qFin();
            }
        
            function localQueryFailed(error) {
                if (qFin)
                    qFin();
                if (qFailed)
                    qFailed(error);
                else
                    queryFailed(error);
            }
        };
        var httpGet = function(apiCall, complete) {
            $http({
               type: 'GET',
               crossDomain: true,
               lxType: 'API',
               lxUserMessage: 'Aguarde...',
               url: getDataServiceUrl() + apiCall
            }).then(function (response) { if (complete) complete(response); });
        };
        var httpPost = function(apiCall, dataObject, complete) {
            $http({
               type: 'POST',
               data: dataObject,
               crossDomain: true,
               lxType: 'API',
               lxUserMessage: 'Aguarde...',
               url: getDataServiceUrl() + apiCall
            }).then(function (response) { if (complete) complete(response); });
        };
        var exportToExcel = function(entityName, jEntitySearch, translatedJEntitySearch, complete, columnsVisible) {
            var info = jQuery.grep(dataExportInfo[dataBusiness.rootDataTypeName], function (item, i) { return (item.name === entityName);});
            if (info == null || info.length === 0) {
                dialog.showAlert('Erro na exportação', 'Alerta');
                return;
            }
            $.ajax({
               type: 'GET',
               crossDomain: true,
               url: getServiceAddress(info[0].actionExport),
               data: { jEntitySearch: jEntitySearch, translatedJEntitySearch: translatedJEntitySearch, columnsDefinition: columnsVisible },
               success: function (response) {
                      saveExcelBlob(entityName + '.xlsx', response);
               },
               complete: function (jqXHR, textStatus) {
                      if(complete) complete();
               },
               error: function (jqXHR, textStatus, errorThrown) {
                      alert('Erro na exportação para o excel');
               }
            });
        };
        var exportReportDataSource = function(complete) {
            $.ajax({
               type: 'GET',
               crossDomain: true,
               url: getServiceAddress("LinxTraining001Venda02/GetReportDataSource"),
               success: function (response) {
                      saveExcelBlob('datasource.ldsx', response);
               },
               complete: function (jqXHR, textStatus) {
                      if(complete) complete();
               },
               error: function (jqXHR, textStatus, errorThrown) {
                      alert('Erro na exportação do data source');
               }
            });
        };
        var exportTemplateReport = function(reportPath, complete) {
            $.ajax({
               type: 'GET',
               crossDomain: true,
               url: getServiceAddress("LinxTraining001Venda02/GetTemplateReport"),
               data: { reportPath: reportPath },
               success: function (response) {
                      saveExcelBlob(reportPath + '.lrtx', response);
               },
               complete: function (jqXHR, textStatus) {
                      if(complete) complete();
               },
               error: function (jqXHR, textStatus, errorThrown) {
                      alert('Erro na exportação do data source');
               }
            });
        };
        var exportToReport = function(reportName, entityName, jEntitySearch, translatedJEntitySearch, complete, columnsVisible, exportMedia) {
            var info = jQuery.grep(dataExportInfo[dataBusiness.rootDataTypeName], function (item, i) { return (item.name === entityName);});
            if (info == null || info.length === 0) {
                dialog.showAlert('Erro na exportação', 'Alerta');
                return;
            }
            $.ajax({
               type: 'GET',
               crossDomain: true,
               url: getServiceAddress(info[0].actionReport),
               data: { reportName: reportName, jEntitySearch: jEntitySearch, translatedJEntitySearch: translatedJEntitySearch, columnsDefinition: columnsVisible, serviceBusUrl: getServiceAddress(''), exportMedia: exportMedia },
               success: function (response) {
                      saveExcelBlob(entityName + '.lrtx', response);
               },
               complete: function (jqXHR, textStatus) {
                      if(complete) complete();
               },
               error: function (jqXHR, textStatus, errorThrown) {
                      alert('Erro na exportação do Relatório');
               }
            });
        };
        
        var _hasChanges = false;
        var hasChanges = function (value) {
            if (typeof value !== 'undefined')
                _hasChanges = value;
            return _hasChanges;
        };
        
        manager.hasChangesChanged.subscribe(function(eventArgs) {
            hasChanges(eventArgs.hasChanges);
        });
        
        //#region Internal methods
        
        function queryFailed(error) {
            dataBusiness.closeProcessing();
        }
        
        function loadParameters() {
         dataParameters.isLoaded = true;
        }
        
        //#endregion Internal methods
        var dataBusiness = null;
        var extendedDataBusiness = null;
        var dataContext = {
                dataForUpdate: '',
                getServiceAddress: getServiceAddress,
                getDataFeedUrl: getDataFeedUrl,
                getDataServiceUrl: getDataServiceUrl,
                setServiceBusUrl: setServiceBusUrl,
                initializePOCO: initializePOCO,
                authService: authService,
                hasDataFeed: true,
                getAccessGroup: getAccessGroup,
                getNewGuid: getNewGuid,
                metadataInfo: metadataInfo,
                dataExportInfo: dataExportInfo,
                entityNames: entityNames,
                lookUpNames: lookUpNames,
                lookUpProperties: lookUpProperties,
                metadataStore: metadataStore,
                cancelChanges: cancelChanges,
                saveChanges: saveChanges,
                getChanges: getChanges,
                hasValidationErrors: hasValidationErrors,
                getEntityProperty: getEntityProperty,
                getViewInfo: getViewInfo,
                createEntity: createEntity,
                createFreeEntity: createFreeEntity,
                createClientesView: createClientesView,
                createVendasView: createVendasView,
                deleteEntity: deleteEntity,
                acceptChanges: acceptChanges,
                getEntities: getEntities,
                detachEntity: detachEntity,
                attachEntity: attachEntity,
                executeQuery: executeQuery,
                sharedData: [],
                clearAll: clearAll,
                hasChanges: hasChanges,
                dataDomains: dataDomains,
                dataParameters: dataParameters,
                loadParameters: loadParameters,
                exportToExcel: exportToExcel,
                exportToReport: exportToReport,
                exportReportDataSource: exportReportDataSource,
                exportTemplateReport: exportTemplateReport,
                businessAssemblyName: businessAssemblyName,
                controllerName: controllerName,
                getResultsCombo: getResultsCombo,
                breeze: breeze,
                httpGet: httpGet,
                httpPost: httpPost,
                setCurrentDataBusiness: function(curDataBusiness) { dataBusiness = curDataBusiness; extendedDataBusiness = curDataBusiness.getExtendedDataBusiness(); },
                        getBmEntityProperties: getBmEntityProperties,
                clearClientesView: clearClientesView,
                getClientesView: getClientesView,
                getClientesViewByEntitySearchNoAssociations: getClientesViewByEntitySearchNoAssociations,
                clearVendasView: clearVendasView,
                getVendasView: getVendasView,
                getVendasViewByEntitySearchNoAssociations: getVendasViewByEntitySearchNoAssociations
        };
        loadParameters();
        return dataContext;
        //#endregion Context Definition
    };
    
    module.service(name, dependencies.concat(serviceAPI));
});
