//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Demo.BM
{

    [Table("PRODUTO", Schema = "dbo")]
    public partial class PRODUTO 
    {
		
		#region Query Methods
		#endregion

		#region Data Properties	
        [Key]
        [Column("ID_PRODUTO",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_PRODUTO { get; set; }

        [Column("NOME_PRODUTO",  TypeName = "varchar", Order=1 )]
        [MaxLength(50)]
        public string NOME_PRODUTO { get; set; }

        [Column("COMBOBOX_PRODUTO",  TypeName = "tinyint", Order=2 )]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_PRODUTO]")]
        public System.Nullable<byte> COMBOBOX_PRODUTO { get; set; }

        [Column("DECIMAL_PRODUTO",  TypeName = "numeric", Order=3 )]
        [Precision(13)]
        [Scale(2)]
        public System.Nullable<decimal> DECIMAL_PRODUTO { get; set; }

        [Column("DATE_TIME_PRODUTO",  TypeName = "datetime", Order=4 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATE_TIME_PRODUTO { get; set; }

		#endregion

		#region Navigation
        

        
		#endregion
    }
	

    public class PRODUTOConfiguration : EntityTypeConfiguration<PRODUTO>
    {
        public PRODUTOConfiguration()
            : base()
        {

            Property(p => p.DECIMAL_PRODUTO).HasPrecision(13,2).IsOptional();
        }
    }

}
