<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Microsoft.AspNetCore.OData</Description>
    <AssemblyTitle>Microsoft.AspNetCore.OData</AssemblyTitle>
    <VersionPrefix>6.0.0-linx</VersionPrefix>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>Microsoft.AspNetCore.OData</AssemblyName>
    <PackageId>Microsoft.AspNetCore.OData</PackageId>
	<PostBuildEvent>xcopy "Microsoft.AspNetCore.OData.*" "C:\Linx Workspace\Linx Framework\Dev\Common\LinxHostCore\src\OData\Microsoft.AspNetCore.OData\..\..\..\..\..\Binary\Library\Common\Linx\Nuget\Libs\" /Y /R</PostBuildEvent>
	<Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.OData.Core" Version="7.3.1" />
    <PackageReference Include="Microsoft.OData.Edm" Version="7.3.1" />
    <PackageReference Include="Microsoft.Spatial" Version="7.3.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
  </ItemGroup>


</Project>
