//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace VAREJO.BM
{

    [Table("ESTADO", Schema = "dbo")]
    public partial class ESTADO 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_PAIS",  TypeName = "int", Order=0 )]
        [Required]
        [ForeignKey("PAIS")]
        [Precision(10)]
        public int ID_PAIS { get; set; }

        [Key]
        [Column("ID_ESTADO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_ESTADO { get; set; }

        [Column("STRING_ESTADO",  TypeName = "varchar", Order=2 )]
        [MaxLength(50)]
        public string STRING_ESTADO { get; set; }

        [Column("COMBOBOX_ESTADO",  TypeName = "tinyint", Order=3 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_ESTADO]")]
        public byte COMBOBOX_ESTADO { get; set; }

        [Column("DECIMAL_ESTADO",  TypeName = "numeric", Order=4 )]
        [Precision(13)]
        [Scale(2)]
        public System.Nullable<decimal> DECIMAL_ESTADO { get; set; }

        [Column("INT_ESTADO",  TypeName = "int", Order=5 )]
        [Precision(10)]
        public System.Nullable<int> INT_ESTADO { get; set; }

        [Column("DATETIME_ESTADO",  TypeName = "datetime", Order=6 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATETIME_ESTADO { get; set; }

        [Column("BIT_ESTADO",  TypeName = "bit", Order=7 )]
        [Precision(1)]
        public System.Nullable<bool> BIT_ESTADO { get; set; }

        [Column("BIG_INT_ESTADO",  TypeName = "bigint", Order=8 )]
        [Precision(19)]
        public System.Nullable<long> BIG_INT_ESTADO { get; set; }

        [Column("SMALL_INT_ESTADO",  TypeName = "smallint", Order=9 )]
        [Precision(5)]
        public System.Nullable<short> SMALL_INT_ESTADO { get; set; }

        [Column("GUID_ESTADO",  TypeName = "uniqueidentifier", Order=10 )]
        public System.Nullable<Guid> GUID_ESTADO { get; set; }

		#endregion

		#region Navigation
                
        public virtual PAIS PAIS { get; set; }


                
        //Origin Document: ModelItem.bmd
        [InverseProperty("ESTADO")]
        public virtual ICollection<CLIENTE> CLIENTE_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class ESTADOConfiguration : EntityTypeConfiguration<ESTADO>
    {
		partial void Init();

        public ESTADOConfiguration()
            : base()
        {

            Property(p => p.DECIMAL_ESTADO).HasPrecision(13,2).IsOptional();

            Init();
        }
    }

}
