//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace VAREJO.BM
{

    [Table("VENDA_ATACADO", Schema = "dbo")]
    public partial class VENDA_ATACADO 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_CLIENTE",  TypeName = "int", Order=0 )]
        [Required]
        [ForeignKey("CLIENTE")]
        [Precision(10)]
        public int ID_CLIENTE { get; set; }

        [Key]
        [Column("ID_VENDA_ATACADO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_VENDA_ATACADO { get; set; }

        [Column("STRING_VENDA_ATACADO",  TypeName = "varchar", Order=2 )]
        [MaxLength(50)]
        public string STRING_VENDA_ATACADO { get; set; }

        [Column("COMBOBOX_VENDA_ATACADO",  TypeName = "tinyint", Order=3 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_VENDA_ATACADO]")]
        public byte COMBOBOX_VENDA_ATACADO { get; set; }

        [Column("DECIMAL_VENDA_ATACADO",  TypeName = "numeric", Order=4 )]
        [Precision(13)]
        [Scale(2)]
        public System.Nullable<decimal> DECIMAL_VENDA_ATACADO { get; set; }

        [Column("INT_VENDA_ATACADO",  TypeName = "int", Order=5 )]
        [Precision(10)]
        public System.Nullable<int> INT_VENDA_ATACADO { get; set; }

        [Column("DATETIME_VENDA_ATACADO",  TypeName = "datetime", Order=6 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATETIME_VENDA_ATACADO { get; set; }

        [Column("BIT_VENDA_ATACADO",  TypeName = "bit", Order=7 )]
        [Precision(1)]
        public System.Nullable<bool> BIT_VENDA_ATACADO { get; set; }

        [Column("BIG_INT_VENDA_ATACADO",  TypeName = "bigint", Order=8 )]
        [Precision(19)]
        public System.Nullable<long> BIG_INT_VENDA_ATACADO { get; set; }

        [Column("SMALL_INT_VENDA_ATACADO",  TypeName = "smallint", Order=9 )]
        [Precision(5)]
        public System.Nullable<short> SMALL_INT_VENDA_ATACADO { get; set; }

        [Column("GUID_VENDA_ATACADO",  TypeName = "uniqueidentifier", Order=10 )]
        public System.Nullable<Guid> GUID_VENDA_ATACADO { get; set; }

		#endregion

		#region Navigation
                
        public virtual CLIENTE CLIENTE { get; set; }


        

		
		
		#endregion
    }
	

    public partial class VENDA_ATACADOConfiguration : EntityTypeConfiguration<VENDA_ATACADO>
    {
		partial void Init();

        public VENDA_ATACADOConfiguration()
            : base()
        {

            Property(p => p.DECIMAL_VENDA_ATACADO).HasPrecision(13,2).IsOptional();

            Init();
        }
    }

}
