//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_FID_LANCAMENTO_SUBTRACOES", Schema = "LX_CRM")]
    public partial class CRM_FID_LANCAMENTO_SUBTRACOES : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_FID_LANCAMENTO_SUBTRACAO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("CRM_FID_LANCAMENTO1")]
        [Precision(10)]
        public int ID_FID_LANCAMENTO_SUBTRACAO { get; set; }

        [Key]
        [Column("ID_FID_LANCAMENTO_PONTO",  TypeName = "int", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("CRM_FID_LANCAMENTO")]
        [Precision(10)]
        public int ID_FID_LANCAMENTO_PONTO { get; set; }

        [Column("PONTOS_SUBTRAIDOS",  TypeName = "int", Order=3 )]
        [Required]
        [Precision(10)]
        public int PONTOS_SUBTRAIDOS { get; set; }

        [Column("DATA_ATUAL",  TypeName = "datetime", Order=4 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATUAL { get; set; }

		#endregion

		#region Navigation
                
        public virtual CRM_FID_LANCAMENTO CRM_FID_LANCAMENTO { get; set; }
        
        public virtual CRM_FID_LANCAMENTO CRM_FID_LANCAMENTO1 { get; set; }


        

		
		
		#endregion
    }
	

    public partial class CRM_FID_LANCAMENTO_SUBTRACOESConfiguration : EntityTypeConfiguration<CRM_FID_LANCAMENTO_SUBTRACOES>
    {
		partial void Init();

        public CRM_FID_LANCAMENTO_SUBTRACOESConfiguration()
            : base()
        {


            Init();
        }
    }

}
