//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_SUBTIPO_CLIENTE", Schema = "LX_CRM")]
    public partial class CRM_SUBTIPO_CLIENTE : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Column("ID_BANDEIRA_REDE",  TypeName = "int", Order=1 )]
        [Required]
        [ForeignKey("TBC_BANDEIRA_REDE")]
        [Precision(10)]
        public int ID_BANDEIRA_REDE { get; set; }

        [Key]
        [Column("ID_CRM_SUBTIPO_CLIENTE",  TypeName = "int", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Crm Subtipo Cliente")]
        public int ID_CRM_SUBTIPO_CLIENTE { get; set; }

        [Column("ID_CRM_TIPO_CLIENTE",  TypeName = "int", Order=3 )]
        [Required]
        [Display(Name="Id Crm Tipo Cliente")]
        [ForeignKey("CRM_TIPO_CLIENTE")]
        public int ID_CRM_TIPO_CLIENTE { get; set; }

        [Column("DESC_SUBTIPO_CLIENTE",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_SUBTIPO_CLIENTE { get; set; }

		#endregion

		#region Navigation
                
        public virtual TBC_BANDEIRA_REDE TBC_BANDEIRA_REDE { get; set; }
        
        public virtual CRM_TIPO_CLIENTE CRM_TIPO_CLIENTE { get; set; }


                
        //Origin Document: Cliente.bmd
        [InverseProperty("CRM_SUBTIPO_CLIENTE")]
        public virtual ICollection<CRM_PFJ> CRM_PFJ_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class CRM_SUBTIPO_CLIENTEConfiguration : EntityTypeConfiguration<CRM_SUBTIPO_CLIENTE>
    {
		partial void Init();

        public CRM_SUBTIPO_CLIENTEConfiguration()
            : base()
        {


            Init();
        }
    }

}
