//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_BANDEIRA_REDE_CONFIG_PARCEIRO_ENVIO", Schema = "LX_CRM")]
    public partial class CRM_BANDEIRA_REDE_CONFIG_PARCEIRO_ENVIO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_CONFIG_PARCEIRO_ENVIO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_CONFIG_PARCEIRO_ENVIO { get; set; }

        [Column("ID_CREDENCIAL_PARCEIRO_ENVIO",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("CRM_BANDEIRA_REDE_CREDENCIAL_PARCEIRO_ENVIO")]
        [Precision(10)]
        public int ID_CREDENCIAL_PARCEIRO_ENVIO { get; set; }

        [Column("NOME_COLUNA_PARCEIRO",  TypeName = "varchar", Order=3 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string NOME_COLUNA_PARCEIRO { get; set; }

        [Column("NOME_TABELA_LOCAL",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string NOME_TABELA_LOCAL { get; set; }

        [Column("NOME_COLUNA_LOCAL",  TypeName = "varchar", Order=5 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string NOME_COLUNA_LOCAL { get; set; }

		#endregion

		#region Navigation
                
        public virtual CRM_BANDEIRA_REDE_CREDENCIAL_PARCEIRO_ENVIO CRM_BANDEIRA_REDE_CREDENCIAL_PARCEIRO_ENVIO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class CRM_BANDEIRA_REDE_CONFIG_PARCEIRO_ENVIOConfiguration : EntityTypeConfiguration<CRM_BANDEIRA_REDE_CONFIG_PARCEIRO_ENVIO>
    {
		partial void Init();

        public CRM_BANDEIRA_REDE_CONFIG_PARCEIRO_ENVIOConfiguration()
            : base()
        {


            Init();
        }
    }

}
