//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_CAMPANHA_GERACAO_AUTOMATICA", Schema = "LX_CRM")]
    public partial class CRM_CAMPANHA_GERACAO_AUTOMATICA : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_CAMPANHA",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("CRM_CAMPANHA")]
        [Precision(10)]
        public int ID_CAMPANHA { get; set; }

        [Column("ID_ACAO_BASE",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("CRM_CAMPANHA_ACAO1")]
        [Precision(10)]
        public int ID_ACAO_BASE { get; set; }

        [Column("ID_ACAO_CAMPANHA",  TypeName = "int", Order=3 )]
        [ForeignKey("CRM_CAMPANHA_ACAO")]
        [Precision(10)]
        public System.Nullable<int> ID_ACAO_CAMPANHA { get; set; }

        [Column("DATA_INICIO",  TypeName = "datetime", Order=4 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_INICIO { get; set; }

        [Column("DATA_FIM",  TypeName = "datetime", Order=5 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_FIM { get; set; }

        [Column("DESC_ACAO_CAMPANHA",  TypeName = "varchar", Order=6 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(200)]
        public string DESC_ACAO_CAMPANHA { get; set; }

        [Column("MSG_PARA_OPERADOR",  TypeName = "varchar", Order=7 )]
        [MaxLength(250)]
        public string MSG_PARA_OPERADOR { get; set; }

        [Column("DATA_GERACAO_LISTA",  TypeName = "datetime", Order=8 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_GERACAO_LISTA { get; set; }

		#endregion

		#region Navigation
                
        public virtual CRM_CAMPANHA CRM_CAMPANHA { get; set; }
        
        public virtual CRM_CAMPANHA_ACAO CRM_CAMPANHA_ACAO { get; set; }
        
        public virtual CRM_CAMPANHA_ACAO CRM_CAMPANHA_ACAO1 { get; set; }


        

		
		
		#endregion
    }
	

    public partial class CRM_CAMPANHA_GERACAO_AUTOMATICAConfiguration : EntityTypeConfiguration<CRM_CAMPANHA_GERACAO_AUTOMATICA>
    {
		partial void Init();

        public CRM_CAMPANHA_GERACAO_AUTOMATICAConfiguration()
            : base()
        {


            Init();
        }
    }

}
