//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_PFJ_ATRIBUTO", Schema = "LX_CRM")]
    public partial class CRM_PFJ_ATRIBUTO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_CRM_PFJ_ATRIBUTO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_CRM_PFJ_ATRIBUTO { get; set; }

        [Column("ID_CRM_PFJ",  TypeName = "bigint", Order=2 )]
        [Required]
        [Display(Name="Id Crm Pfj Dados")]
        [ForeignKey("CRM_PFJ")]
        public long ID_CRM_PFJ { get; set; }

        [Column("ID_ATRIBUTO_DEFINICAO",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("TCS_ATRIBUTO_DEFINICAO")]
        [Precision(10)]
        public int ID_ATRIBUTO_DEFINICAO { get; set; }

        [Column("ID_ATRIBUTO",  TypeName = "int", Order=4 )]
        [ForeignKey("TCS_ATRIBUTO")]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO { get; set; }

        [Column("VALOR_INFORMADO",  TypeName = "varchar", Order=5 )]
        [MaxLength(70)]
        public string VALOR_INFORMADO { get; set; }

		#endregion

		#region Navigation
                
        public virtual TCS_ATRIBUTO TCS_ATRIBUTO { get; set; }
        
        public virtual TCS_ATRIBUTO_DEFINICAO TCS_ATRIBUTO_DEFINICAO { get; set; }
        
        public virtual CRM_PFJ CRM_PFJ { get; set; }


        

		
		
		#endregion
    }
	

    public partial class CRM_PFJ_ATRIBUTOConfiguration : EntityTypeConfiguration<CRM_PFJ_ATRIBUTO>
    {
		partial void Init();

        public CRM_PFJ_ATRIBUTOConfiguration()
            : base()
        {


            Init();
        }
    }

}
