//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_CAMPANHA_ACAO", Schema = "LX_CRM")]
    public partial class CRM_CAMPANHA_ACAO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_ACAO_CAMPANHA",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_ACAO_CAMPANHA { get; set; }

        [Column("ID_BANDEIRA_REDE",  TypeName = "int", Order=2 )]
        [ForeignKey("TBC_BANDEIRA_REDE")]
        [Precision(10)]
        public System.Nullable<int> ID_BANDEIRA_REDE { get; set; }

        [Column("ID_TIPO_OFERTA",  TypeName = "int", Order=3 )]
        [ForeignKey("CRM_TIPO_OFERTA")]
        [Precision(10)]
        public System.Nullable<int> ID_TIPO_OFERTA { get; set; }

        [Column("ID_LISTA",  TypeName = "int", Order=4 )]
        [ForeignKey("CRM_LISTA")]
        [Precision(10)]
        public System.Nullable<int> ID_LISTA { get; set; }

        [Column("ID_CAMPANHA",  TypeName = "int", Order=5 )]
        [ForeignKey("CRM_CAMPANHA")]
        [Precision(10)]
        public System.Nullable<int> ID_CAMPANHA { get; set; }

        [Column("ID_PROMOCAO",  TypeName = "int", Order=6 )]
        [ForeignKey("PRM_PROMOCAO")]
        [Precision(10)]
        public System.Nullable<int> ID_PROMOCAO { get; set; }

        [Column("ID_VEICULO_ACAO",  TypeName = "int", Order=7 )]
        [Required]
        [ForeignKey("CRM_CAMPANHA_ACAO_VEICULO")]
        [Precision(10)]
        public int ID_VEICULO_ACAO { get; set; }

        [Column("ID_OBJETIVO_ACAO",  TypeName = "int", Order=8 )]
        [Required]
        [ForeignKey("CRM_CAMPANHA_ACAO_OBJETIVO_ACAO")]
        [Precision(10)]
        public int ID_OBJETIVO_ACAO { get; set; }

        [Column("DESC_ACAO_CAMPANHA",  TypeName = "varchar", Order=9 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(200)]
        public string DESC_ACAO_CAMPANHA { get; set; }

        [Column("DATA_CADASTRAMENTO",  TypeName = "datetime", Order=10 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_CADASTRAMENTO { get; set; }

        [Column("LX_STATUS",  TypeName = "tinyint", Order=11 )]
        [Required]
        [Precision(3)]
        public byte LX_STATUS_ACAO { get; set; }

        [Column("MSG_PARA_OPERADOR",  TypeName = "varchar", Order=12 )]
        [MaxLength(250)]
        public string MSG_PARA_OPERADOR { get; set; }

        [Column("NAO_GERA_ITEM",  TypeName = "bit", Order=13 )]
        [Required]
        [Precision(1)]
        public bool NAO_GERA_ITEM { get; set; }

        [Column("CUSTO",  TypeName = "numeric", Order=14 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> CUSTO { get; set; }

        [Column("RECEITA",  TypeName = "numeric", Order=15 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> RECEITA { get; set; }

        [Column("DATA_INICIO",  TypeName = "datetime", Order=16 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_INICIO { get; set; }

        [Column("DATA_FIM",  TypeName = "datetime", Order=17 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_FIM { get; set; }

        [Column("DATA_GERACAO_LISTA",  TypeName = "datetime", Order=18 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_GERACAO_LISTA { get; set; }

        [Column("META",  TypeName = "int", Order=19 )]
        [Required]
        [Precision(10)]
        public int META { get; set; }

        [Column("VALOR_COMPRA_MINIMA",  TypeName = "numeric", Order=20 )]
        [Required]
        [Precision(14)]
        [Scale(2)]
        public decimal VALOR_COMPRA_MINIMA { get; set; }

        [Column("VALOR_OFERTA",  TypeName = "numeric", Order=21 )]
        [Required]
        [Precision(14)]
        [Scale(2)]
        public decimal VALOR_OFERTA { get; set; }

        [Column("VALOR_CRIACAO",  TypeName = "numeric", Order=22 )]
        [Required]
        [Precision(14)]
        [Scale(2)]
        public decimal VALOR_CRIACAO { get; set; }

        [Column("VALOR_PRODUCAO",  TypeName = "numeric", Order=23 )]
        [Required]
        [Precision(14)]
        [Scale(2)]
        public decimal VALOR_PRODUCAO { get; set; }

        [Column("VALOR_ENVIO",  TypeName = "numeric", Order=24 )]
        [Required]
        [Precision(14)]
        [Scale(3)]
        public decimal VALOR_ENVIO { get; set; }

        [Column("CODIGO_LISTA_PARCEIRO",  TypeName = "int", Order=25 )]
        [Precision(10)]
        public System.Nullable<int> CODIGO_LISTA_PARCEIRO { get; set; }

        [Column("CODIGO_ENVIO_PARCEIRO",  TypeName = "int", Order=26 )]
        [Precision(10)]
        public System.Nullable<int> CODIGO_ENVIO_PARCEIRO { get; set; }

        [Column("OBS",  TypeName = "varchar(max)", Order=27 )]
        public string OBS { get; set; }

        [Column("GRUPO_DE_CONTROLE",  TypeName = "int", Order=28 )]
        [Required]
        [Precision(10)]
        public int GRUPO_DE_CONTROLE { get; set; }

        [Column("CONTAGEM_TOTAL",  TypeName = "int", Order=29 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_TOTAL { get; set; }

        [Column("CONTAGEM_COM_EMAIL",  TypeName = "int", Order=30 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_COM_EMAIL { get; set; }

        [Column("CONTAGEM_COM_TELEFONE",  TypeName = "int", Order=31 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_COM_TELEFONE { get; set; }

        [Column("CONTAGEM_COM_ENDERECO",  TypeName = "int", Order=32 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_COM_ENDERECO { get; set; }

        [Column("CONTAGEM_ACEITA_EMAIL",  TypeName = "int", Order=33 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_ACEITA_EMAIL { get; set; }

        [Column("CONTAGEM_ACEITA_SMS",  TypeName = "int", Order=34 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_ACEITA_SMS { get; set; }

        [Column("CONTAGEM_ACEITA_TELEFONEMA",  TypeName = "int", Order=35 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_ACEITA_TELEFONEMA { get; set; }

        [Column("CONTAGEM_ACEITA_EMAILS_PARCEIROS",  TypeName = "int", Order=36 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_ACEITA_EMAILS_PARCEIROS { get; set; }

        [Column("CONTAGEM_ACEITA_CORRESPONDENCIA",  TypeName = "int", Order=37 )]
        [Required]
        [Precision(10)]
        public int CONTAGEM_ACEITA_CORRESPONDENCIA { get; set; }

        [Column("QTD_RESPOSTAS_TOTAL",  TypeName = "int", Order=38 )]
        [Required]
        [Precision(10)]
        public int QTD_RESPOSTAS_TOTAL { get; set; }

        [Column("QTD_COMPRAS_TOTAL",  TypeName = "int", Order=39 )]
        [Required]
        [Precision(10)]
        public int QTD_COMPRAS_TOTAL { get; set; }

        [Column("QTD_ITENS_TOTAL",  TypeName = "int", Order=40 )]
        [Required]
        [Precision(10)]
        public int QTD_ITENS_TOTAL { get; set; }

        [Column("VLR_COMPRAS_TOTAL",  TypeName = "numeric", Order=41 )]
        [Required]
        [Precision(14)]
        [Scale(2)]
        public decimal VLR_COMPRAS_TOTAL { get; set; }

        [Column("QTD_RESPOSTAS_GRUPO_DE_CONTROLE",  TypeName = "int", Order=42 )]
        [Required]
        [Precision(10)]
        public int QTD_RESPOSTAS_GRUPO_DE_CONTROLE { get; set; }

        [Column("QTD_COMPRAS_GRUPO_DE_CONTROLE",  TypeName = "int", Order=43 )]
        [Required]
        [Precision(10)]
        public int QTD_COMPRAS_GRUPO_DE_CONTROLE { get; set; }

        [Column("QTD_ITENS_GRUPO_DE_CONTROLE",  TypeName = "int", Order=44 )]
        [Required]
        [Precision(10)]
        public int QTD_ITENS_GRUPO_DE_CONTROLE { get; set; }

        [Column("VLR_COMPRAS_GRUPO_DE_CONTROLE",  TypeName = "numeric", Order=45 )]
        [Required]
        [Precision(14)]
        [Scale(2)]
        public decimal VLR_COMPRAS_GRUPO_DE_CONTROLE { get; set; }

        [Column("LX_LIMITADOR_LOJA_CARTEIRA",  TypeName = "tinyint", Order=46 )]
        [Required]
        [Precision(3)]
        public byte LX_LIMITADOR_LOJA_CARTEIRA { get; set; }

        [Column("LIMITADOR_LISTA",  TypeName = "int", Order=47 )]
        [Precision(10)]
        public System.Nullable<int> LIMITADOR_LISTA { get; set; }

		#endregion

		#region Navigation
                
        public virtual CRM_CAMPANHA CRM_CAMPANHA { get; set; }
        
        public virtual CRM_CAMPANHA_ACAO_OBJETIVO_ACAO CRM_CAMPANHA_ACAO_OBJETIVO_ACAO { get; set; }
        
        public virtual CRM_CAMPANHA_ACAO_VEICULO CRM_CAMPANHA_ACAO_VEICULO { get; set; }
        
        public virtual CRM_TIPO_OFERTA CRM_TIPO_OFERTA { get; set; }
        
        public virtual CRM_LISTA CRM_LISTA { get; set; }
        
        public virtual TBC_BANDEIRA_REDE TBC_BANDEIRA_REDE { get; set; }
        
        public virtual PRM_PROMOCAO PRM_PROMOCAO { get; set; }


                
        //Origin Document: CampanhaAcao.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<CRM_CAMPANHA_ACAO_ITEM_ACOMPANHAMENTO> CRM_CAMPANHA_ACAO_ITEM_ACOMPANHAMENTO_LISTA { get; set; }
        
        //Origin Document: CampanhaAcao.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<CRM_CAMPANHA_ACAO_ITEM> CRM_CAMPANHA_ACAO_ITEM_LISTA { get; set; }
        
        //Origin Document: CampanhaAcao.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<CRM_CAMPANHA_ACAO_LIMITADOR> CRM_CAMPANHA_ACAO_LIMITADOR_LISTA { get; set; }
        
        //Origin Document: CampanhaAcao.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<CRM_CAMPANHA_GERACAO_AUTOMATICA> CRM_CAMPANHA_GERACAO_AUTOMATICA_LISTA { get; set; }
        
        //Origin Document: CampanhaAcao.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO1")]
        public virtual ICollection<CRM_CAMPANHA_GERACAO_AUTOMATICA> CRM_CAMPANHA_GERACAO_AUTOMATICA_LISTA1 { get; set; }
        
        //Origin Document: VendaHistorica.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<CRM_CARGA_LOJA_VENDA_PROMOCAO> CRM_CARGA_LOJA_VENDA_PROMOCAO_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<LJV_ATENDIMENTO_ACAO_PROMOCAO> LJV_ATENDIMENTO_ACAO_PROMOCAO_LISTA { get; set; }
        
        //Origin Document: PreVenda.bmd
        [InverseProperty("CRM_CAMPANHA_ACAO")]
        public virtual ICollection<LJV_PEDIDO_ACAO_PROMOCAO> LJV_PEDIDO_ACAO_PROMOCAO_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class CRM_CAMPANHA_ACAOConfiguration : EntityTypeConfiguration<CRM_CAMPANHA_ACAO>
    {
		partial void Init();

        public CRM_CAMPANHA_ACAOConfiguration()
            : base()
        {

            Property(p => p.CUSTO).HasPrecision(14,2).IsOptional();
            Property(p => p.RECEITA).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_COMPRA_MINIMA).HasPrecision(14,2);
            Property(p => p.VALOR_OFERTA).HasPrecision(14,2);
            Property(p => p.VALOR_CRIACAO).HasPrecision(14,2);
            Property(p => p.VALOR_PRODUCAO).HasPrecision(14,2);
            Property(p => p.VALOR_ENVIO).HasPrecision(14,3);
            Property(p => p.VLR_COMPRAS_TOTAL).HasPrecision(14,2);
            Property(p => p.VLR_COMPRAS_GRUPO_DE_CONTROLE).HasPrecision(14,2);

            Init();
        }
    }

}
