//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_PFJ_END_ELETRONICO", Schema = "LX_CRM")]
    public partial class CRM_PFJ_END_ELETRONICO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PFJ_END_ELETRONICO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Crm Pfj End Eletronico")]
        public int ID_PFJ_END_ELETRONICO { get; set; }

        [Column("ID_CRM_PFJ",  TypeName = "bigint", Order=2 )]
        [Required]
        [Display(Name="Id Crm Pfj Dados")]
        [ForeignKey("CRM_PFJ")]
        public long ID_CRM_PFJ { get; set; }

        [Column("LX_TIPO_END_ELETRONICO",  TypeName = "tinyint", Order=3 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_END_ELETRONICO]")]
        public byte LX_TIPO_END_ELETRONICO { get; set; }

        [Column("ENDERECO_ELETRONICO",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(250)]
        public string ENDERECO_ELETRONICO { get; set; }

        [Column("DATA_ULTIMO_ACESSO",  TypeName = "datetime", Order=5 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_ULTIMO_ACESSO { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=6 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

		#endregion

		#region Navigation
                
        public virtual CRM_PFJ CRM_PFJ { get; set; }


        

		
		
		#endregion
    }
	

    public partial class CRM_PFJ_END_ELETRONICOConfiguration : EntityTypeConfiguration<CRM_PFJ_END_ELETRONICO>
    {
		partial void Init();

        public CRM_PFJ_END_ELETRONICOConfiguration()
            : base()
        {


            Init();
        }
    }

}
