//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("CRM_FID_PROGRAMA_OPERACAO_VENDA", Schema = "LX_CRM")]
    public partial class CRM_FID_PROGRAMA_OPERACAO_VENDA : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("OPERACAO_VENDA",  TypeName = "varchar", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(3)]
        public string OPERACAO_VENDA { get; set; }

        [Key]
        [Column("ID_FID_PROGRAMA",  TypeName = "int", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("CRM_FID_PROGRAMA")]
        [Precision(10)]
        public int ID_FID_PROGRAMA { get; set; }

        [Column("EVENTO_GERADO",  TypeName = "tinyint", Order=3 )]
        [Precision(3)]
        public System.Nullable<byte> EVENTO_GERADO { get; set; }

		#endregion

		#region Navigation
                
        public virtual CRM_FID_PROGRAMA CRM_FID_PROGRAMA { get; set; }


        

		
		
		#endregion
    }
	

    public partial class CRM_FID_PROGRAMA_OPERACAO_VENDAConfiguration : EntityTypeConfiguration<CRM_FID_PROGRAMA_OPERACAO_VENDA>
    {
		partial void Init();

        public CRM_FID_PROGRAMA_OPERACAO_VENDAConfiguration()
            : base()
        {


            Init();
        }
    }

}
