//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("DOC_MULTIMIDIA_TABELA", Schema = "LX_DOC")]
    public partial class DOC_MULTIMIDIA_TABELA : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("UID_DOCUMENTO",  TypeName = "uniqueidentifier", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("DOC_MULTIMIDIA")]
        public Guid UID_DOCUMENTO { get; set; }

        [Key]
        [Column("ID_CHAVE",  TypeName = "bigint", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Precision(10)]
        public long ID_CHAVE { get; set; }

        [Key]
        [Column("UID_CHAVE",  TypeName = "uniqueidentifier", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public Guid UID_CHAVE { get; set; }

        [Column("ORDEM_APRESENTACAO",  TypeName = "smallint", Order=3 )]
        [Required]
        [Precision(5)]
        public short ORDEM_APRESENTACAO { get; set; }

        [Key]
        [Column("UID_TABELA",  TypeName = "uniqueidentifier", Order=4 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public Guid UID_TABELA { get; set; }

        [Column("ID_LINX",  TypeName = "int", Order=5 )]
        [Required]
        public int ID_LINX { get; set; }

		#endregion

		#region Navigation
                
        public virtual DOC_MULTIMIDIA DOC_MULTIMIDIA { get; set; }


        

		
		
		#endregion
    }
	

    public partial class DOC_MULTIMIDIA_TABELAConfiguration : EntityTypeConfiguration<DOC_MULTIMIDIA_TABELA>
    {
		partial void Init();

        public DOC_MULTIMIDIA_TABELAConfiguration()
            : base()
        {


            Init();
        }
    }

}
