//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("DOC_MULTIMIDIA_CONFIG", Schema = "LX_DOC")]
    public partial class DOC_MULTIMIDIA_CONFIG : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_TCS_APLICATIVO",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Display(Name="Id Tcs Aplicativo")]
        public int ID_TCS_APLICATIVO { get; set; }

        [Key]
        [Column("LX_USO_MULTIMIDIA",  TypeName = "tinyint", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[UsoMultimidia]")]
        public byte LX_USO_MULTIMIDIA { get; set; }

        [Column("DOC_LARGURA",  TypeName = "int", Order=2 )]
        [Precision(10)]
        public System.Nullable<int> DOC_LARGURA { get; set; }

        [Column("DOC_ALTURA",  TypeName = "int", Order=3 )]
        [Precision(10)]
        public System.Nullable<int> DOC_ALTURA { get; set; }

        [Column("DOC_TAMANHO",  TypeName = "char", Order=4 )]
        [MaxLength(10)]
        public string DOC_TAMANHO { get; set; }

        [Column("DOC_FORMATO_VISUALIZACAO",  TypeName = "char", Order=5 )]
        [MaxLength(10)]
        public string DOC_FORMATO_VISUALIZACAO { get; set; }

        [Column("DOC_DURACAO",  TypeName = "char", Order=6 )]
        [MaxLength(10)]
        public string DOC_DURACAO { get; set; }

        [Column("ID_LINX",  TypeName = "int", Order=7 )]
        [Required]
        public int ID_LINX { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class DOC_MULTIMIDIA_CONFIGConfiguration : EntityTypeConfiguration<DOC_MULTIMIDIA_CONFIG>
    {
		partial void Init();

        public DOC_MULTIMIDIA_CONFIGConfiguration()
            : base()
        {


            Init();
        }
    }

}
