//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    public partial class Endereco 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name="ID Endereco")]
        public int IdPfjEndereco { get; set; }

        public int IdPfj { get; set; }

        [MaxLength(20)]
        public string CnpjCpfPfj { get; set; }

        public byte LxTipoEndereco { get; set; }

        [MaxLength(30)]
        public string NomeEndereco { get; set; }

        [MaxLength(20)]
        public string CnpjCpfColetaEntrega { get; set; }

        [MaxLength(20)]
        public string InscricaoEstadual { get; set; }

        [MaxLength(20)]
        public string InscricaoMunicipal { get; set; }

        public byte LxTipoLogradouro { get; set; }

        [MaxLength(60)]
        public string Logradouro { get; set; }

        [MaxLength(60)]
        public string Numero { get; set; }

        [MaxLength(60)]
        public string Complemento { get; set; }

        [MaxLength(60)]
        public string Bairro { get; set; }

        public System.Nullable<int> IdMunicipio { get; set; }

        [MaxLength(60)]
        public string Municipio { get; set; }

        public System.Nullable<short> IdUF { get; set; }

        [MaxLength(4)]
        public string UF { get; set; }

        public System.Nullable<int> IdCep { get; set; }

        [MaxLength(10)]
        public string Cep { get; set; }

        public System.Nullable<short> IdPais { get; set; }

        [MaxLength(60)]
        public string Pais { get; set; }

        [MaxLength(250)]
        public string ObsEndereco { get; set; }

        public bool IndicaPrincipal { get; set; }

        public bool Inativo { get; set; }

        public System.Nullable<int> ExIdPfjEndereco { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class EnderecoConfiguration : EntityTypeConfiguration<Endereco>
    {
		partial void Init();

        public EnderecoConfiguration()
            : base()
        {


            Init();
        }
    }

}
