//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LGE_PEDIDO_STATUS", Schema = "LX_LGE")]
    public partial class LGE_PEDIDO_STATUS : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PEDIDO_STATUS",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Documento Status")]
        public int ID_PEDIDO_STATUS { get; set; }

        [Column("DESC_STATUS",  TypeName = "varchar", Order=2 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(40)]
        public string DESC_STATUS { get; set; }

        [Column("LX_STATUS_LGE_PEDIDO",  TypeName = "int", Order=3 )]
        [Required]
        [FunctionalPoint("DomainName[LX_STATUS_LGE_PEDIDO]")]
        public int LX_STATUS_LGE_PEDIDO { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=4 )]
        [Required]
        public bool INATIVO { get; set; }

        [Column("INDICA_STATUS_PEDIDO",  TypeName = "bit", Order=5 )]
        [Required]
        public bool INDICA_STATUS_PEDIDO { get; set; }

        [Column("INDICA_STATUS_ITEM",  TypeName = "bit", Order=6 )]
        [Required]
        public bool INDICA_STATUS_ITEM { get; set; }

		#endregion

		#region Navigation
        

                
        //Origin Document: PedidoEntrada.bmd
        [InverseProperty("LGE_PEDIDO_STATUS")]
        public virtual ICollection<LGE_PEDIDO_ITEM> LGE_PEDIDO_ITEM_LISTA { get; set; }
        
        //Origin Document: PedidoEntrada.bmd
        [InverseProperty("LGE_PEDIDO_STATUS1")]
        public virtual ICollection<LGE_PEDIDO_ITEM> LGE_PEDIDO_ITEM_LISTA1 { get; set; }
        
        //Origin Document: PedidoEntrada.bmd
        [InverseProperty("LGE_PEDIDO_STATUS")]
        public virtual ICollection<LGE_PEDIDO> LGE_PEDIDO_LISTA { get; set; }
        
        //Origin Document: PedidoEntrada.bmd
        [InverseProperty("LGE_PEDIDO_STATUS1")]
        public virtual ICollection<LGE_PEDIDO> LGE_PEDIDO_LISTA1 { get; set; }


		
		
		#endregion
    }
	

    public partial class LGE_PEDIDO_STATUSConfiguration : EntityTypeConfiguration<LGE_PEDIDO_STATUS>
    {
		partial void Init();

        public LGE_PEDIDO_STATUSConfiguration()
            : base()
        {


            Init();
        }
    }

}
