//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_GIFT_CARD_DADO_ADICIONAL", Schema = "LX_LJV")]
    public partial class LJV_GIFT_CARD_DADO_ADICIONAL : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_GIFT_CARD_DADO_ADICIONAL",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Ljv Gift Card Dado Adicional")]
        public int ID_GIFT_CARD_DADO_ADICIONAL { get; set; }

        [Column("ID_GIFT_CARD_TRANSACAO",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("LJV_GIFT_CARD_TRANSACAO")]
        public int ID_GIFT_CARD_TRANSACAO { get; set; }

        [Column("CODIGO",  TypeName = "smallint", Order=3 )]
        [Required]
        public short CODIGO { get; set; }

        [Column("TEXTO",  TypeName = "varchar", Order=4 )]
        [MaxLength(100)]
        public string TEXTO { get; set; }

        [Column("TIPO",  TypeName = "varchar", Order=5 )]
        [MaxLength(2)]
        public string TIPO { get; set; }

        [Column("TAMANHO_MINIMO",  TypeName = "smallint", Order=6 )]
        public System.Nullable<short> TAMANHO_MINIMO { get; set; }

        [Column("TAMANHO_MAXIMO",  TypeName = "smallint", Order=7 )]
        public System.Nullable<short> TAMANHO_MAXIMO { get; set; }

        [Column("OBRIGATORIO",  TypeName = "bit", Order=8 )]
        public System.Nullable<bool> OBRIGATORIO { get; set; }

        [Column("VALOR",  TypeName = "varchar", Order=9 )]
        [MaxLength(100)]
        public string VALOR { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_GIFT_CARD_TRANSACAO LJV_GIFT_CARD_TRANSACAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class LJV_GIFT_CARD_DADO_ADICIONALConfiguration : EntityTypeConfiguration<LJV_GIFT_CARD_DADO_ADICIONAL>
    {
		partial void Init();

        public LJV_GIFT_CARD_DADO_ADICIONALConfiguration()
            : base()
        {


            Init();
        }
    }

}
