//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_COMISSAO_REGRA_PRODUTO", Schema = "LX_LJV")]
    public partial class LJV_COMISSAO_REGRA_PRODUTO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_COMISSAO_REGRA_PRODUTO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Ljv Comissao Regra")]
        public int ID_COMISSAO_REGRA_PRODUTO { get; set; }

        [Column("ID_COMISSAO_REGRA",  TypeName = "int", Order=2 )]
        [Required]
        [Display(Name="Id Ljv Comissao Regra")]
        [ForeignKey("LJV_COMISSAO_REGRA")]
        public int ID_COMISSAO_REGRA { get; set; }

        [Column("ID_COMISSAO_REGRA_VENDEDOR",  TypeName = "int", Order=3 )]
        [Display(Name="Id Ljv Loja Comissao Regra Vendedor")]
        [ForeignKey("LJV_COMISSAO_REGRA_BASE")]
        public System.Nullable<int> ID_COMISSAO_REGRA_VENDEDOR { get; set; }

        [Column("ID_ARTIGO",  TypeName = "int", Order=4 )]
        [ForeignKey("PRD_ARTIGO")]
        [Precision(10)]
        public System.Nullable<int> ID_ARTIGO { get; set; }

        [Column("ID_SKU",  TypeName = "int", Order=5 )]
        [ForeignKey("PRD_SKU_PRODUTO")]
        [Precision(10)]
        public System.Nullable<int> ID_SKU { get; set; }

        [Column("ID_VENDEDOR",  TypeName = "int", Order=6 )]
        [ForeignKey("LJV_VENDEDOR")]
        [Precision(10)]
        public System.Nullable<int> ID_VENDEDOR { get; set; }

        [Column("LX_FUNCAO_VENDEDOR",  TypeName = "tinyint", Order=7 )]
        [Required]
        [FunctionalPoint("DomainName[LX_FUNCAO_VENDEDOR]")]
        public byte LX_FUNCAO_VENDEDOR { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=8 )]
        [ForeignKey("LJV_LOJA")]
        public System.Nullable<int> ID_LOJA { get; set; }

        [Column("PORCENTAGEM_PREMIO",  TypeName = "numeric", Order=9 )]
        [Required]
        [Precision(5)]
        [Scale(2)]
        public decimal PORCENTAGEM_PREMIO { get; set; }

        [Column("VALOR_PREMIO",  TypeName = "numeric", Order=10 )]
        [Precision(15)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_PREMIO { get; set; }

        [Column("ID_ATRIBUTO_1",  TypeName = "int", Order=11 )]
        [ForeignKey("ATRIBUTO_1")]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_1 { get; set; }

        [Column("ID_ATRIBUTO_2",  TypeName = "int", Order=12 )]
        [ForeignKey("ATRIBUTO_2")]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_2 { get; set; }

        [Column("ID_ATRIBUTO_3",  TypeName = "int", Order=13 )]
        [ForeignKey("ATRIBUTO_3")]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_3 { get; set; }

        [Column("ID_ATRIBUTO_4",  TypeName = "int", Order=14 )]
        [ForeignKey("ATRIBUTO_4")]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_4 { get; set; }

        [Column("DATA_ATIVACAO",  TypeName = "datetime", Order=15 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_ATIVACAO { get; set; }

        [Column("DATA_DESATIVACAO",  TypeName = "datetime", Order=16 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_DESATIVACAO { get; set; }

        [Column("DESC_REGRA_PRODUTO",  TypeName = "varchar", Order=17 )]
        [MaxLength(60)]
        public string DESC_REGRA_PRODUTO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_COMISSAO_REGRA LJV_COMISSAO_REGRA { get; set; }
        
        public virtual PRD_ARTIGO PRD_ARTIGO { get; set; }
        
        public virtual PRD_SKU_PRODUTO PRD_SKU_PRODUTO { get; set; }
        
        public virtual TCS_ATRIBUTO ATRIBUTO_1 { get; set; }
        
        public virtual TCS_ATRIBUTO ATRIBUTO_2 { get; set; }
        
        public virtual TCS_ATRIBUTO ATRIBUTO_3 { get; set; }
        
        public virtual TCS_ATRIBUTO ATRIBUTO_4 { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }
        
        public virtual LJV_VENDEDOR LJV_VENDEDOR { get; set; }
        
        public virtual LJV_COMISSAO_REGRA_BASE LJV_COMISSAO_REGRA_BASE { get; set; }


                
        //Origin Document: Comissao.bmd
        [InverseProperty("LJV_COMISSAO_REGRA_PRODUTO")]
        public virtual ICollection<LJV_COMISSAO_PERIODO_DETALHE> LJV_COMISSAO_PERIODO_DETALHE_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class LJV_COMISSAO_REGRA_PRODUTOConfiguration : EntityTypeConfiguration<LJV_COMISSAO_REGRA_PRODUTO>
    {
		partial void Init();

        public LJV_COMISSAO_REGRA_PRODUTOConfiguration()
            : base()
        {

            Property(p => p.PORCENTAGEM_PREMIO).HasPrecision(5,2);
            Property(p => p.VALOR_PREMIO).HasPrecision(15,2).IsOptional();

            Init();
        }
    }

}
