//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_CTRL", Schema = "LX_LJV")]
    public partial class LJV_CTRL : ILinx, IGpecon
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Column("ID_GPECON",  TypeName = "int", Order=1 )]
        [Required]
        [ForeignKey("TBC_GRUPO_ECONOMICO")]
        [Precision(10)]
        public int ID_GPECON { get; set; }

        [Key]
        [Column("ID_CONTROLE",  TypeName = "bigint", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public long ID_CONTROLE { get; set; }

        [Column("ID_FILIAL_PFJ",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("TBC_FILIAL")]
        public int ID_FILIAL_PFJ { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=4 )]
        [Required]
        [ForeignKey("LJV_LOJA")]
        public int ID_LOJA { get; set; }

        [Column("ID_GERENTE_LOJA",  TypeName = "int", Order=5 )]
        [Required]
        [ForeignKey("LJV_VENDEDOR")]
        public int ID_GERENTE_LOJA { get; set; }

        [Column("DATA_CTRL",  TypeName = "datetime", Order=6 )]
        [Required]
        [Precision(16)]
        public DateTime DATA_CTRL { get; set; }

        [Column("LX_STATUS_OPERACAO",  TypeName = "tinyint", Order=7 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_OPERACAO]")]
        public byte LX_STATUS_OPERACAO { get; set; }

        [Column("LX_STATUS_REGISTRO",  TypeName = "tinyint", Order=8 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_REGISTRO]")]
        public byte LX_STATUS_REGISTRO { get; set; }

        [Column("ID_STK_ROMANEIO_LOJA_VENDA",  TypeName = "bigint", Order=9 )]
        [Display(Name="Id Stk Romaneio")]
        [ForeignKey("STK_ROMANEIO")]
        public System.Nullable<long> ID_STK_ROMANEIO_LOJA_VENDA { get; set; }

		#endregion

		#region Navigation
                
        public virtual TBC_FILIAL TBC_FILIAL { get; set; }
        
        public virtual TBC_GRUPO_ECONOMICO TBC_GRUPO_ECONOMICO { get; set; }
        
        public virtual LJV_VENDEDOR LJV_VENDEDOR { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }
        
        public virtual STK_ROMANEIO STK_ROMANEIO { get; set; }


                
        //Origin Document: Caixa.bmd
        [InverseProperty("LJV_CTRL")]
        public virtual ICollection<LJV_CAIXA_CTRL> LJV_CAIXA_CTRL_LISTA { get; set; }
        
        //Origin Document: IntegracaoFinanceiraLoja.bmd
        [InverseProperty("LJV_CTRL")]
        public virtual ICollection<LJV_CTRL_CONFERENCIA> LJV_CTRL_CONFERENCIA_LISTA { get; set; }
        
        //Origin Document: Caixa.bmd
        [InverseProperty("LJV_CTRL")]
        public virtual ICollection<LJV_CTRL_LOG> LJV_CTRL_LOG_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class LJV_CTRLConfiguration : EntityTypeConfiguration<LJV_CTRL>
    {
		partial void Init();

        public LJV_CTRLConfiguration()
            : base()
        {


            Init();
        }
    }

}
