//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_ATENDIMENTO_ITEM_VENDEDOR_W", Schema = "dbo")]
    public partial class LJV_ATENDIMENTO_ITEM_VENDEDOR_W 
    {
		
		#region Query Methods
		public void RefreshComposedKeys()
        {

        }

		public static IQueryable<LJV_ATENDIMENTO_ITEM_VENDEDOR_W> GetQuery(DbContext ctx)
        {
            return GetQueryByParam(ctx, "", new System.Data.Entity.Core.Objects.ObjectParameter[] { });
        }

        public static IQueryable<LJV_ATENDIMENTO_ITEM_VENDEDOR_W> GetQueryByParam(DbContext ctx, string predicate, params System.Data.Entity.Core.Objects.ObjectParameter[] parameters)
        {
			LinxOperacional context = (LinxOperacional)ctx;
			



            
            var query = (from entity0 in context.LJV_ATENDIMENTO_VEND_AUX_W
            join entity1 in context.PRD_SKU_PRODUTO on entity0.ID_SKU equals entity1.ID_SKU
            select new 
            {
                COD_VENDEDOR = entity0.COD_VENDEDOR,
                DATA_ATENDIMENTO = entity0.DATA_ATENDIMENTO,
                DESCONTO_ITEM = entity0.DESCONTO_ITEM,
                ID_ATENDIMENTO = entity0.ID_ATENDIMENTO,
                ID_ATENDIMENTO_ITEM = entity0.ID_ATENDIMENTO_ITEM,
                ITEM_CANCELADO = entity0.ITEM_CANCELADO,
                ITEM_CANCELADO_ECF = entity0.ITEM_CANCELADO_ECF,
                NOME_VENDEDOR = entity0.NOME_VENDEDOR,
                PRECO_BRUTO_ITEM = entity0.PRECO_BRUTO_ITEM,
                QTDE_ITEM = entity0.QTDE_ITEM,
                SEQ_ITEM = entity0.SEQ_ITEM,
                VALOR_ACRESCIMO_SUBTOTAL_RATEIO = entity0.VALOR_ACRESCIMO_SUBTOTAL_RATEIO,
                VALOR_DESCONTO_SUBTOTAL_RATEIO = entity0.VALOR_DESCONTO_SUBTOTAL_RATEIO,
                VALOR_ITEM = entity0.VALOR_ITEM,
                VALOR_ITENS_VALE_PRESENTE = entity0.VALOR_ITENS_VALE_PRESENTE,
                VALOR_LIQUIDO_PAGO = entity0.VALOR_LIQUIDO_PAGO,
                COD_SKU = entity1.COD_SKU,
                DESC_SKU = entity1.DESC_SKU
            })
            ;
            
            var queryAggr = (from q in query
            group new { q } by new { COD_VENDEDOR = q.COD_VENDEDOR, DATA_ATENDIMENTO = q.DATA_ATENDIMENTO, DESCONTO_ITEM = q.DESCONTO_ITEM, ID_ATENDIMENTO = q.ID_ATENDIMENTO, ID_ATENDIMENTO_ITEM = q.ID_ATENDIMENTO_ITEM, ITEM_CANCELADO = q.ITEM_CANCELADO, ITEM_CANCELADO_ECF = q.ITEM_CANCELADO_ECF, NOME_VENDEDOR = q.NOME_VENDEDOR, PRECO_BRUTO_ITEM = q.PRECO_BRUTO_ITEM, QTDE_ITEM = q.QTDE_ITEM, SEQ_ITEM = q.SEQ_ITEM, VALOR_ACRESCIMO_SUBTOTAL_RATEIO = q.VALOR_ACRESCIMO_SUBTOTAL_RATEIO, VALOR_DESCONTO_SUBTOTAL_RATEIO = q.VALOR_DESCONTO_SUBTOTAL_RATEIO, VALOR_ITEM = q.VALOR_ITEM, VALOR_ITENS_VALE_PRESENTE = q.VALOR_ITENS_VALE_PRESENTE, VALOR_LIQUIDO_PAGO = q.VALOR_LIQUIDO_PAGO, COD_SKU = q.COD_SKU, DESC_SKU = q.DESC_SKU } into rg0
            select new LJV_ATENDIMENTO_ITEM_VENDEDOR_W()
            {
                COD_VENDEDOR = rg0.Key.COD_VENDEDOR,
                DATA_ATENDIMENTO = rg0.Key.DATA_ATENDIMENTO,
                DESCONTO_ITEM = rg0.Key.DESCONTO_ITEM,
                ID_ATENDIMENTO = rg0.Key.ID_ATENDIMENTO,
                ID_ATENDIMENTO_ITEM = rg0.Key.ID_ATENDIMENTO_ITEM,
                ITEM_CANCELADO = rg0.Key.ITEM_CANCELADO,
                ITEM_CANCELADO_ECF = rg0.Key.ITEM_CANCELADO_ECF,
                NOME_VENDEDOR = rg0.Key.NOME_VENDEDOR,
                PRECO_BRUTO_ITEM = rg0.Key.PRECO_BRUTO_ITEM,
                QTDE_ITEM = rg0.Key.QTDE_ITEM,
                SEQ_ITEM = rg0.Key.SEQ_ITEM,
                VALOR_ACRESCIMO_SUBTOTAL_RATEIO = rg0.Key.VALOR_ACRESCIMO_SUBTOTAL_RATEIO,
                VALOR_DESCONTO_SUBTOTAL_RATEIO = rg0.Key.VALOR_DESCONTO_SUBTOTAL_RATEIO,
                VALOR_ITEM = rg0.Key.VALOR_ITEM,
                VALOR_ITENS_VALE_PRESENTE = rg0.Key.VALOR_ITENS_VALE_PRESENTE,
                VALOR_LIQUIDO_PAGO = rg0.Key.VALOR_LIQUIDO_PAGO,
                COD_SKU = rg0.Key.COD_SKU,
                DESC_SKU = rg0.Key.DESC_SKU
            })
            ;


            List<object> paramValues = new List<object>();
            predicate = predicate.ToDynamicLinqExpression(typeof(LJV_ATENDIMENTO_ITEM_VENDEDOR_W), parameters, paramValues);

			return queryAggr.Where(predicate, paramValues.ToArray());
        }
		#endregion



		#region Data Properties	
        [Column("LJV_ATENDIMENTO_VEND_AUX_W.QTDE_ITEM",  TypeName = "numeric", Order=0 )]
        [Required]
        [Precision(10)]
        [Scale(3)]
        public decimal QTDE_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.ID_ATENDIMENTO_ITEM",  TypeName = "bigint", Order=1 )]
        [Required]
        public long ID_ATENDIMENTO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.ID_ATENDIMENTO",  TypeName = "bigint", Order=2 )]
        [Required]
        public long ID_ATENDIMENTO { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.PRECO_BRUTO_ITEM",  TypeName = "numeric", Order=3 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> PRECO_BRUTO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.DESCONTO_ITEM",  TypeName = "numeric", Order=4 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> DESCONTO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.VALOR_ITEM",  TypeName = "numeric", Order=5 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.VALOR_ACRESCIMO_SUBTOTAL_RATEIO",  TypeName = "numeric", Order=6 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ACRESCIMO_SUBTOTAL_RATEIO { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.VALOR_DESCONTO_SUBTOTAL_RATEIO",  TypeName = "numeric", Order=7 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_DESCONTO_SUBTOTAL_RATEIO { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.VALOR_LIQUIDO_PAGO",  TypeName = "numeric", Order=8 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_LIQUIDO_PAGO { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.COD_VENDEDOR",  TypeName = "varchar", Order=9 )]
        [MaxLength(20)]
        public string COD_VENDEDOR { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.NOME_VENDEDOR",  TypeName = "varchar", Order=10 )]
        [MaxLength(120)]
        public string NOME_VENDEDOR { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.DATA_ATENDIMENTO",  TypeName = "datetime", Order=11 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATENDIMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_SKU#false##25:0###2#true#::PRD_SKU_PRODUTO##false#false##PRD_SKU_PRODUTO#Linx.Operacional.BM#IQueryable#")]
        [Column("PRD_SKU_PRODUTO.COD_SKU",  TypeName = "varchar", Order=12 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(25)]
        public string COD_SKU { get; set; }

        [LinxPublicationField(LookUpInfo="string#DESC_SKU#false##120:0###3#true#::PRD_SKU_PRODUTO##false#false##PRD_SKU_PRODUTO#Linx.Operacional.BM#IQueryable#")]
        [Column("PRD_SKU_PRODUTO.DESC_SKU",  TypeName = "varchar", Order=13 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(120)]
        public string DESC_SKU { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.ITEM_CANCELADO",  TypeName = "bit", Order=14 )]
        [Required]
        [Precision(1)]
        public bool ITEM_CANCELADO { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.VALOR_ITENS_VALE_PRESENTE",  TypeName = "numeric", Order=15 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITENS_VALE_PRESENTE { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.SEQ_ITEM",  TypeName = "smallint", Order=16 )]
        [Required]
        [Precision(5)]
        public short SEQ_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_VEND_AUX_W.ITEM_CANCELADO_ECF",  TypeName = "bit", Order=17 )]
        [Required]
        [Precision(1)]
        public bool ITEM_CANCELADO_ECF { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class LJV_ATENDIMENTO_ITEM_VENDEDOR_WConfiguration : EntityTypeConfiguration<LJV_ATENDIMENTO_ITEM_VENDEDOR_W>
    {
		partial void Init();

        public LJV_ATENDIMENTO_ITEM_VENDEDOR_WConfiguration()
            : base()
        {

            Property(p => p.QTDE_ITEM).HasPrecision(10,3);
            Property(p => p.PRECO_BRUTO_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.DESCONTO_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ACRESCIMO_SUBTOTAL_RATEIO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_DESCONTO_SUBTOTAL_RATEIO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_LIQUIDO_PAGO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITENS_VALE_PRESENTE).HasPrecision(14,2).IsOptional();

            Init();
        }
    }

}
