//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_ID_PAF_ECF", Schema = "LX_LJV")]
    public partial class LJV_ID_PAF_ECF : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PAF_ECF",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int ID_PAF_ECF { get; set; }

        [Column("VERSAO_PAF_ECF",  TypeName = "varchar", Order=2 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(20)]
        public string VERSAO_PAF_ECF { get; set; }

        [Column("NOME_COMERCIAL",  TypeName = "varchar", Order=3 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(100)]
        public string NOME_COMERCIAL { get; set; }

        [Column("PRINCIPAL_EXE_NOME",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(100)]
        public string PRINCIPAL_EXE_NOME { get; set; }

        [Column("PRINCIPAL_EXE_MD5",  TypeName = "varchar", Order=5 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(32)]
        public string PRINCIPAL_EXE_MD5 { get; set; }

        [Column("LISTA_EXE_MD5",  TypeName = "varchar", Order=6 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(32)]
        public string LISTA_EXE_MD5 { get; set; }

        [Column("VERSAO_ER_PAF_ECF",  TypeName = "varchar", Order=7 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(10)]
        public string VERSAO_ER_PAF_ECF { get; set; }

        [Column("LAUDO_PAF_ECF",  TypeName = "varchar", Order=8 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(20)]
        public string LAUDO_PAF_ECF { get; set; }

        [Column("SH_RAZAO_SOCIAL",  TypeName = "varchar", Order=9 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(90)]
        public string SH_RAZAO_SOCIAL { get; set; }

        [Column("SH_CNPJ",  TypeName = "varchar", Order=10 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(19)]
        public string SH_CNPJ { get; set; }

        [Column("SH_IE",  TypeName = "varchar", Order=11 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(19)]
        public string SH_IE { get; set; }

        [Column("SH_IM",  TypeName = "varchar", Order=12 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(19)]
        public string SH_IM { get; set; }

        [Column("SH_ENDERECO",  TypeName = "varchar", Order=13 )]
        [MaxLength(100)]
        public string SH_ENDERECO { get; set; }

        [Column("SH_TELEFONE",  TypeName = "varchar", Order=14 )]
        [MaxLength(20)]
        public string SH_TELEFONE { get; set; }

        [Column("SH_CONTATO",  TypeName = "varchar", Order=15 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(90)]
        public string SH_CONTATO { get; set; }

        [Column("LX_STATUS_REGISTRO",  TypeName = "tinyint", Order=16 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_REGISTRO]")]
        public byte LX_STATUS_REGISTRO { get; set; }

		#endregion

		#region Navigation
        

                
        //Origin Document: ReducaoZ.bmd
        [InverseProperty("LJV_ID_PAF_ECF")]
        public virtual ICollection<LJV_ID_PAF_ECF_AUTORIZADO> LJV_ID_PAF_ECF_AUTORIZADO_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class LJV_ID_PAF_ECFConfiguration : EntityTypeConfiguration<LJV_ID_PAF_ECF>
    {
		partial void Init();

        public LJV_ID_PAF_ECFConfiguration()
            : base()
        {


            Init();
        }
    }

}
