//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_ATENDIMENTO_ITEM_VEND_AUX2_W", Schema = "dbo")]
    public partial class LJV_ATENDIMENTO_ITEM_VEND_AUX2_W : ILinx
    {
		
		#region Query Methods
		public void RefreshComposedKeys()
        {

        }

		public static IQueryable<LJV_ATENDIMENTO_ITEM_VEND_AUX2_W> GetQuery(DbContext ctx)
        {
            return GetQueryByParam(ctx, "", new System.Data.Entity.Core.Objects.ObjectParameter[] { });
        }

        public static IQueryable<LJV_ATENDIMENTO_ITEM_VEND_AUX2_W> GetQueryByParam(DbContext ctx, string predicate, params System.Data.Entity.Core.Objects.ObjectParameter[] parameters)
        {
			LinxOperacional context = (LinxOperacional)ctx;
			



            
            var query = (from Atend in context.LJV_ATENDIMENTO
            join AtendItem in context.LJV_ATENDIMENTO_ITEM on Atend.ID_ATENDIMENTO equals AtendItem.ID_ATENDIMENTO
            join entity0 in context.LJV_ATENDIMENTO_ITEM_VENDEDOR on AtendItem.ID_ATENDIMENTO_ITEM equals entity0.ID_ATENDIMENTO_ITEM
            join entity1 in context.LJV_ATENDIMENTO_VENDEDOR on entity0.ID_ATENDIMENTO_VENDEDOR equals entity1.ID_ATENDIMENTO_VENDEDOR
            join entity2 in context.LJV_VENDEDOR on entity1.ID_VENDEDOR equals entity2.ID_VENDEDOR
            select new 
            {
                ATENDIMENTO_CANCELADO = Atend.ATENDIMENTO_CANCELADO,
                ATENDIMENTO_CANCELADO_ECF = Atend.ATENDIMENTO_CANCELADO_ECF,
                DATA_ATENDIMENTO = Atend.DATA_ATENDIMENTO,
                ID_CAIXA_CTRL = Atend.ID_CAIXA_CTRL,
                ID_FILIAL_PFJ = Atend.ID_FILIAL_PFJ,
                ID_LOJA = Atend.ID_LOJA,
                LX_TIPO_ATENDIMENTO = Atend.LX_TIPO_ATENDIMENTO,
                VALOR_ITENS_VALE_PRESENTE = 0,
                COD_CLASSIF_FISCAL = AtendItem.COD_CLASSIF_FISCAL,
                DESCONTO_ITEM = AtendItem.DESCONTO_ITEM,
                ID_ATENDIMENTO = AtendItem.ID_ATENDIMENTO,
                ID_ATENDIMENTO_ITEM = AtendItem.ID_ATENDIMENTO_ITEM,
                ID_ATENDIMENTO_ITEM_REF = AtendItem.ID_ATENDIMENTO_ITEM_REF,
                ID_LINX = AtendItem.ID_LINX,
                ID_MOTIVO_CANCELAMENTO = AtendItem.ID_MOTIVO_CANCELAMENTO,
                ID_NUMERO_SERIE = AtendItem.ID_NUMERO_SERIE,
                ID_PEDIDO = AtendItem.ID_PEDIDO,
                ID_SKU = AtendItem.ID_SKU,
                ID_SKU_PRECO = AtendItem.ID_SKU_PRECO,
                ID_STK_DEPOSITO = AtendItem.ID_STK_DEPOSITO,
                ITEM_CANCELADO = AtendItem.ITEM_CANCELADO,
                ITEM_CANCELADO_ECF = AtendItem.ITEM_CANCELADO_ECF,
                LX_TIPO_ITEM = AtendItem.LX_TIPO_ITEM,
                NUMERO_SERIE = AtendItem.NUMERO_SERIE,
                PRECO_BRUTO_ITEM = AtendItem.PRECO_BRUTO_ITEM,
                QTDE_ITEM = AtendItem.QTDE_ITEM,
                SEQ_ITEM = AtendItem.SEQ_ITEM,
                VALOR_ACRESCIMO_SUBTOTAL_RATEIO = AtendItem.VALOR_ACRESCIMO_SUBTOTAL_RATEIO,
                VALOR_DESCONTO_SUBTOTAL_RATEIO = AtendItem.VALOR_DESCONTO_SUBTOTAL_RATEIO,
                VALOR_ITEM = AtendItem.VALOR_ITEM,
                VALOR_LIQUIDO_PAGO = AtendItem.VALOR_LIQUIDO_PAGO,
                ID_ATENDIMENTO_VENDEDOR = entity1.ID_ATENDIMENTO_VENDEDOR,
                COD_VENDEDOR = entity2.COD_VENDEDOR,
                ID_VENDEDOR = entity2.ID_VENDEDOR,
                NOME_VENDEDOR = entity2.NOME_VENDEDOR
            })
            ;
            
            var queryAggr = (from q in query
            group new { q } by new { ATENDIMENTO_CANCELADO = q.ATENDIMENTO_CANCELADO, ATENDIMENTO_CANCELADO_ECF = q.ATENDIMENTO_CANCELADO_ECF, DATA_ATENDIMENTO = q.DATA_ATENDIMENTO, ID_CAIXA_CTRL = q.ID_CAIXA_CTRL, ID_FILIAL_PFJ = q.ID_FILIAL_PFJ, ID_LOJA = q.ID_LOJA, LX_TIPO_ATENDIMENTO = q.LX_TIPO_ATENDIMENTO, VALOR_ITENS_VALE_PRESENTE = q.VALOR_ITENS_VALE_PRESENTE, COD_CLASSIF_FISCAL = q.COD_CLASSIF_FISCAL, DESCONTO_ITEM = q.DESCONTO_ITEM, ID_ATENDIMENTO = q.ID_ATENDIMENTO, ID_ATENDIMENTO_ITEM = q.ID_ATENDIMENTO_ITEM, ID_ATENDIMENTO_ITEM_REF = q.ID_ATENDIMENTO_ITEM_REF, ID_LINX = q.ID_LINX, ID_MOTIVO_CANCELAMENTO = q.ID_MOTIVO_CANCELAMENTO, ID_NUMERO_SERIE = q.ID_NUMERO_SERIE, ID_PEDIDO = q.ID_PEDIDO, ID_SKU = q.ID_SKU, ID_SKU_PRECO = q.ID_SKU_PRECO, ID_STK_DEPOSITO = q.ID_STK_DEPOSITO, ITEM_CANCELADO = q.ITEM_CANCELADO, ITEM_CANCELADO_ECF = q.ITEM_CANCELADO_ECF, LX_TIPO_ITEM = q.LX_TIPO_ITEM, NUMERO_SERIE = q.NUMERO_SERIE, PRECO_BRUTO_ITEM = q.PRECO_BRUTO_ITEM, SEQ_ITEM = q.SEQ_ITEM, VALOR_ACRESCIMO_SUBTOTAL_RATEIO = q.VALOR_ACRESCIMO_SUBTOTAL_RATEIO, VALOR_DESCONTO_SUBTOTAL_RATEIO = q.VALOR_DESCONTO_SUBTOTAL_RATEIO, VALOR_ITEM = q.VALOR_ITEM, VALOR_LIQUIDO_PAGO = q.VALOR_LIQUIDO_PAGO, ID_ATENDIMENTO_VENDEDOR = q.ID_ATENDIMENTO_VENDEDOR, COD_VENDEDOR = q.COD_VENDEDOR, ID_VENDEDOR = q.ID_VENDEDOR, NOME_VENDEDOR = q.NOME_VENDEDOR } into rg0
            select new LJV_ATENDIMENTO_ITEM_VEND_AUX2_W()
            {
                ATENDIMENTO_CANCELADO = rg0.Key.ATENDIMENTO_CANCELADO,
                ATENDIMENTO_CANCELADO_ECF = rg0.Key.ATENDIMENTO_CANCELADO_ECF,
                DATA_ATENDIMENTO = rg0.Key.DATA_ATENDIMENTO,
                ID_CAIXA_CTRL = rg0.Key.ID_CAIXA_CTRL,
                ID_FILIAL_PFJ = rg0.Key.ID_FILIAL_PFJ,
                ID_LOJA = rg0.Key.ID_LOJA,
                LX_TIPO_ATENDIMENTO = rg0.Key.LX_TIPO_ATENDIMENTO,
                VALOR_ITENS_VALE_PRESENTE = rg0.Key.VALOR_ITENS_VALE_PRESENTE,
                COD_CLASSIF_FISCAL = rg0.Key.COD_CLASSIF_FISCAL,
                DESCONTO_ITEM = rg0.Key.DESCONTO_ITEM,
                ID_ATENDIMENTO = rg0.Key.ID_ATENDIMENTO,
                ID_ATENDIMENTO_ITEM = rg0.Key.ID_ATENDIMENTO_ITEM,
                ID_ATENDIMENTO_ITEM_REF = rg0.Key.ID_ATENDIMENTO_ITEM_REF,
                ID_LINX = rg0.Key.ID_LINX,
                ID_MOTIVO_CANCELAMENTO = rg0.Key.ID_MOTIVO_CANCELAMENTO,
                ID_NUMERO_SERIE = rg0.Key.ID_NUMERO_SERIE,
                ID_PEDIDO = rg0.Key.ID_PEDIDO,
                ID_SKU = rg0.Key.ID_SKU,
                ID_SKU_PRECO = rg0.Key.ID_SKU_PRECO,
                ID_STK_DEPOSITO = rg0.Key.ID_STK_DEPOSITO,
                ITEM_CANCELADO = rg0.Key.ITEM_CANCELADO,
                ITEM_CANCELADO_ECF = rg0.Key.ITEM_CANCELADO_ECF,
                LX_TIPO_ITEM = rg0.Key.LX_TIPO_ITEM,
                NUMERO_SERIE = rg0.Key.NUMERO_SERIE,
                PRECO_BRUTO_ITEM = rg0.Key.PRECO_BRUTO_ITEM,
                QTDE_ITEM = rg0.Sum(e => e.q.QTDE_ITEM),
                SEQ_ITEM = rg0.Key.SEQ_ITEM,
                VALOR_ACRESCIMO_SUBTOTAL_RATEIO = rg0.Key.VALOR_ACRESCIMO_SUBTOTAL_RATEIO,
                VALOR_DESCONTO_SUBTOTAL_RATEIO = rg0.Key.VALOR_DESCONTO_SUBTOTAL_RATEIO,
                VALOR_ITEM = rg0.Key.VALOR_ITEM,
                VALOR_LIQUIDO_PAGO = rg0.Key.VALOR_LIQUIDO_PAGO,
                ID_ATENDIMENTO_VENDEDOR = rg0.Key.ID_ATENDIMENTO_VENDEDOR,
                COD_VENDEDOR = rg0.Key.COD_VENDEDOR,
                ID_VENDEDOR = rg0.Key.ID_VENDEDOR,
                NOME_VENDEDOR = rg0.Key.NOME_VENDEDOR
            })
            ;


            List<object> paramValues = new List<object>();
            predicate = predicate.ToDynamicLinqExpression(typeof(LJV_ATENDIMENTO_ITEM_VEND_AUX2_W), parameters, paramValues);

			return queryAggr.Where(predicate, paramValues.ToArray());
        }
		#endregion



		#region Data Properties	
        [LinxPublicationField(LookUpInfo="string#COD_CLASSIF_FISCAL#false##15:0###30#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.COD_CLASSIF_FISCAL",  TypeName = "varchar", Order=0 )]
        [MaxLength(15)]
        public string COD_CLASSIF_FISCAL { get; set; }

        [LinxPublicationField(LookUpInfo="decimal#QTDE_ITEM#false##10:3###20#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.QTDE_ITEM",  TypeName = "numeric", Order=1 )]
        [Required]
        [Precision(10)]
        [Scale(3)]
        public decimal QTDE_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="bool#ITEM_CANCELADO#false##1:0###24#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ITEM_CANCELADO",  TypeName = "bit", Order=2 )]
        [Required]
        [Precision(1)]
        public bool ITEM_CANCELADO { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_LINX#false##0:0###0#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_LINX",  TypeName = "int", Order=3 )]
        [Required]
        public int ID_LINX { get; set; }

        [LinxPublicationField(LookUpInfo="long#ID_ATENDIMENTO_ITEM#true##0:0###1#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_ATENDIMENTO_ITEM",  TypeName = "bigint", Order=4 )]
        [Required]
        public long ID_ATENDIMENTO_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<long>#ID_ATENDIMENTO_ITEM_REF#false##0:0###2#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_ATENDIMENTO_ITEM_REF",  TypeName = "bigint", Order=5 )]
        public System.Nullable<long> ID_ATENDIMENTO_ITEM_REF { get; set; }

        [LinxPublicationField(LookUpInfo="long#ID_ATENDIMENTO#false##0:0###3#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_ATENDIMENTO",  TypeName = "bigint", Order=6 )]
        [Required]
        public long ID_ATENDIMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<int>#ID_SKU_PRECO#false##0:0##Id Prd Sku Preco#6#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_SKU_PRECO",  TypeName = "int", Order=7 )]
        [Display(Name="Id Prd Sku Preco")]
        public System.Nullable<int> ID_SKU_PRECO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<int>#ID_NUMERO_SERIE#false##10:0###7#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_NUMERO_SERIE",  TypeName = "int", Order=8 )]
        [Precision(10)]
        public System.Nullable<int> ID_NUMERO_SERIE { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<int>#ID_STK_DEPOSITO#false##10:0###8#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_STK_DEPOSITO",  TypeName = "int", Order=9 )]
        [Precision(10)]
        public System.Nullable<int> ID_STK_DEPOSITO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<short>#ID_MOTIVO_CANCELAMENTO#false##5:0###9#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_MOTIVO_CANCELAMENTO",  TypeName = "smallint", Order=10 )]
        [Precision(5)]
        public System.Nullable<short> ID_MOTIVO_CANCELAMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<long>#ID_PEDIDO#false##0:0###10#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_PEDIDO",  TypeName = "bigint", Order=11 )]
        public System.Nullable<long> ID_PEDIDO { get; set; }

        [LinxPublicationField(LookUpInfo="string#NUMERO_SERIE#false##20:0###18#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.NUMERO_SERIE",  TypeName = "varchar", Order=12 )]
        [MaxLength(20)]
        public string NUMERO_SERIE { get; set; }

        [LinxPublicationField(LookUpInfo="byte#LX_TIPO_ITEM#false##3:0#LX_TIPO_ITEM##19#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.LX_TIPO_ITEM",  TypeName = "tinyint", Order=13 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_ITEM]")]
        public byte LX_TIPO_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<decimal>#PRECO_BRUTO_ITEM#false##14:2###21#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.PRECO_BRUTO_ITEM",  TypeName = "numeric", Order=14 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> PRECO_BRUTO_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<decimal>#DESCONTO_ITEM#false##14:2###22#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.DESCONTO_ITEM",  TypeName = "numeric", Order=15 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> DESCONTO_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<decimal>#VALOR_ITEM#false##14:2###23#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.VALOR_ITEM",  TypeName = "numeric", Order=16 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<decimal>#VALOR_ACRESCIMO_SUBTOTAL_RATEIO#false##14:2###27#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.VALOR_ACRESCIMO_SUBTOTAL_RATEIO",  TypeName = "numeric", Order=17 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ACRESCIMO_SUBTOTAL_RATEIO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<decimal>#VALOR_DESCONTO_SUBTOTAL_RATEIO#false##14:2###28#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.VALOR_DESCONTO_SUBTOTAL_RATEIO",  TypeName = "numeric", Order=18 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_DESCONTO_SUBTOTAL_RATEIO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<decimal>#VALOR_LIQUIDO_PAGO#false##14:2###29#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.VALOR_LIQUIDO_PAGO",  TypeName = "numeric", Order=19 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_LIQUIDO_PAGO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<int>#ID_SKU#false##10:0###4#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ID_SKU",  TypeName = "int", Order=20 )]
        [Precision(10)]
        public System.Nullable<int> ID_SKU { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_VENDEDOR#true##10:0###1#true#::LJV_VENDEDOR##false#false##LJV_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_VENDEDOR.ID_VENDEDOR",  TypeName = "int", Order=21 )]
        [Required]
        [Precision(10)]
        public int ID_VENDEDOR { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_VENDEDOR#false##20:0###4#true#::LJV_VENDEDOR##false#false##LJV_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_VENDEDOR.COD_VENDEDOR",  TypeName = "varchar", Order=22 )]
        [MaxLength(20)]
        public string COD_VENDEDOR { get; set; }

        [LinxPublicationField(LookUpInfo="string#NOME_VENDEDOR#false##120:0###6#true#::LJV_VENDEDOR##false#false##LJV_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_VENDEDOR.NOME_VENDEDOR",  TypeName = "varchar", Order=23 )]
        [MaxLength(120)]
        public string NOME_VENDEDOR { get; set; }

        [LinxPublicationField(LookUpInfo="long#ID_ATENDIMENTO_VENDEDOR#true##0:0###1#true#::LJV_ATENDIMENTO_VENDEDOR##false#false##LJV_ATENDIMENTO_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_VENDEDOR.ID_ATENDIMENTO_VENDEDOR",  TypeName = "bigint", Order=24 )]
        [Required]
        public long ID_ATENDIMENTO_VENDEDOR { get; set; }

        [Column("LJV_ATENDIMENTO.ATENDIMENTO_CANCELADO",  TypeName = "bit", Order=25 )]
        [Required]
        [Precision(1)]
        public bool ATENDIMENTO_CANCELADO { get; set; }

        [Column("LJV_ATENDIMENTO.ID_FILIAL_PFJ",  TypeName = "int", Order=26 )]
        public System.Nullable<int> ID_FILIAL_PFJ { get; set; }

        [Column("LJV_ATENDIMENTO.ID_LOJA",  TypeName = "int", Order=27 )]
        [Required]
        [Precision(10)]
        public int ID_LOJA { get; set; }

        [Column("LJV_ATENDIMENTO.ID_CAIXA_CTRL",  TypeName = "bigint", Order=28 )]
        [Required]
        public long ID_CAIXA_CTRL { get; set; }

        [Column("LJV_ATENDIMENTO.DATA_ATENDIMENTO",  TypeName = "datetime", Order=29 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATENDIMENTO { get; set; }

        [Column("LJV_ATENDIMENTO.LX_TIPO_ATENDIMENTO",  TypeName = "tinyint", Order=30 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_ATENDIMENTO]")]
        public byte LX_TIPO_ATENDIMENTO { get; set; }

        [Column("VALOR_ITENS_VALE_PRESENTE",  TypeName = "numeric", Order=31 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITENS_VALE_PRESENTE { get; set; }

        [LinxPublicationField(LookUpInfo="short#SEQ_ITEM#false##5:0###15#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.SEQ_ITEM",  TypeName = "smallint", Order=32 )]
        [Required]
        [Precision(5)]
        public short SEQ_ITEM { get; set; }

        [LinxPublicationField(LookUpInfo="bool#ITEM_CANCELADO_ECF#false##1:0###25#true#::LJV_ATENDIMENTO_ITEM##false#false##LJV_ATENDIMENTO_ITEM#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO_ITEM.ITEM_CANCELADO_ECF",  TypeName = "bit", Order=33 )]
        [Required]
        [Precision(1)]
        public bool ITEM_CANCELADO_ECF { get; set; }

        [Column("LJV_ATENDIMENTO.ATENDIMENTO_CANCELADO_ECF",  TypeName = "bit", Order=34 )]
        [Required]
        [Precision(1)]
        public bool ATENDIMENTO_CANCELADO_ECF { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class LJV_ATENDIMENTO_ITEM_VEND_AUX2_WConfiguration : EntityTypeConfiguration<LJV_ATENDIMENTO_ITEM_VEND_AUX2_W>
    {
		partial void Init();

        public LJV_ATENDIMENTO_ITEM_VEND_AUX2_WConfiguration()
            : base()
        {

            Property(p => p.QTDE_ITEM).HasPrecision(10,3);
            Property(p => p.PRECO_BRUTO_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.DESCONTO_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ACRESCIMO_SUBTOTAL_RATEIO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_DESCONTO_SUBTOTAL_RATEIO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_LIQUIDO_PAGO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITENS_VALE_PRESENTE).HasPrecision(14,2).IsOptional();

            Init();
        }
    }

}
