//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_ECF", Schema = "LX_LJV")]
    public partial class LJV_ECF : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_ECF",  TypeName = "bigint", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public long ID_ECF { get; set; }

        [Column("ID_FILIAL_PFJ",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("TBC_FILIAL")]
        public int ID_FILIAL_PFJ { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("LJV_LOJA")]
        public int ID_LOJA { get; set; }

        [Column("NUMERO_SERIE",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(20)]
        public string NUMERO_SERIE { get; set; }

        [Column("MF_ADICIONAL",  TypeName = "char", Order=5 )]
        [MaxLength(1)]
        public string MF_ADICIONAL { get; set; }

        [Column("MODELO",  TypeName = "varchar", Order=6 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(100)]
        public string MODELO { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=7 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

        [Column("LX_STATUS_REGISTRO",  TypeName = "tinyint", Order=8 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_REGISTRO]")]
        public byte LX_STATUS_REGISTRO { get; set; }

        [Column("LX_STATUS_INTEGRACAO_FISCAL",  TypeName = "smallint", Order=9 )]
        [Required]
        [FunctionalPoint("DomainName[LX_STATUS_INTEGRACAO_FISCAL]")]
        public short LX_STATUS_INTEGRACAO_FISCAL { get; set; }

		#endregion

		#region Navigation
                
        public virtual TBC_FILIAL TBC_FILIAL { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }


                
        //Origin Document: ReducaoZ.bmd
        [InverseProperty("LJV_ECF")]
        public virtual ICollection<LJV_ECF_CONFIG> LJV_ECF_CONFIG_LISTA { get; set; }
        
        //Origin Document: ReducaoZ.bmd
        [InverseProperty("LJV_ECF")]
        public virtual ICollection<LJV_ECF_OPERACAO> LJV_ECF_OPERACAO_LISTA { get; set; }
        
        //Origin Document: ReducaoZ.bmd
        [InverseProperty("LJV_ECF")]
        public virtual ICollection<LJV_ID_PAF_ECF_AUTORIZADO> LJV_ID_PAF_ECF_AUTORIZADO_LISTA { get; set; }
        
        //Origin Document: IntegracaoFiscal.bmd
        [InverseProperty("LJV_ECF")]
        public virtual ICollection<LJV_INTEGRACAO_FISCAL> LJV_INTEGRACAO_FISCAL_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class LJV_ECFConfiguration : EntityTypeConfiguration<LJV_ECF>
    {
		partial void Init();

        public LJV_ECFConfiguration()
            : base()
        {


            Init();
        }
    }

}
