//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_REGRA_FISCAL_SKU", Schema = "LX_LJV")]
    public partial class LJV_REGRA_FISCAL_SKU : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_REGRA_FISCAL_SKU",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Ljv Imposto Regra")]
        public int ID_REGRA_FISCAL_SKU { get; set; }

        [Column("ID_REGRA_FISCAL",  TypeName = "int", Order=2 )]
        [Required]
        [Display(Name="Id Ljv Imposto Regra")]
        [ForeignKey("LJV_REGRA_FISCAL")]
        public int ID_REGRA_FISCAL { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("LJV_LOJA")]
        public int ID_LOJA { get; set; }

        [Column("ID_SKU",  TypeName = "int", Order=4 )]
        [Required]
        [ForeignKey("PRD_SKU_PRODUTO")]
        [Precision(10)]
        public int ID_SKU { get; set; }

        [Column("ID_CFOP",  TypeName = "smallint", Order=5 )]
        [ForeignKey("LCF_CODIGO_FISCAL_OPERACAO")]
        [Precision(10)]
        public System.Nullable<short> ID_CFOP { get; set; }

        [Column("ID_REGRA_FISCAL_EMBUTIDO",  TypeName = "int", Order=6 )]
        [Display(Name="Id Lcf Regra Fiscal Embutido")]
        [ForeignKey("LJV_REGRA_FISCAL_EMBUTIDO")]
        public System.Nullable<int> ID_REGRA_FISCAL_EMBUTIDO { get; set; }

        [Column("DATA_ATIVACAO",  TypeName = "datetime", Order=7 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATIVACAO { get; set; }

        [Column("DATA_DESATIVACAO",  TypeName = "datetime", Order=8 )]
        public System.Nullable<DateTime> DATA_DESATIVACAO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_REGRA_FISCAL LJV_REGRA_FISCAL { get; set; }
        
        public virtual PRD_SKU_PRODUTO PRD_SKU_PRODUTO { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }
        
        public virtual LCF_CODIGO_FISCAL_OPERACAO LCF_CODIGO_FISCAL_OPERACAO { get; set; }
        
        public virtual LJV_REGRA_FISCAL_EMBUTIDO LJV_REGRA_FISCAL_EMBUTIDO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class LJV_REGRA_FISCAL_SKUConfiguration : EntityTypeConfiguration<LJV_REGRA_FISCAL_SKU>
    {
		partial void Init();

        public LJV_REGRA_FISCAL_SKUConfiguration()
            : base()
        {


            Init();
        }
    }

}
