//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_ATENDIMENTO", Schema = "LX_LJV")]
    public partial class LJV_ATENDIMENTO : ILinx, IGpecon
    {
		
		public LJV_ATENDIMENTO()
		{
			this.LX_TIPO_FISCAL = 99;
			this.LX_PEDIDO_ORIGEM = 0;
			this.LX_ATENDIMENTO_ORIGEM = 0;
		}

		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Column("ID_GPECON",  TypeName = "int", Order=1 )]
        [Required]
        [ForeignKey("TBC_GRUPO_ECONOMICO")]
        [Precision(10)]
        public int ID_GPECON { get; set; }

        [Key]
        [Column("ID_ATENDIMENTO",  TypeName = "bigint", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public long ID_ATENDIMENTO { get; set; }

        [Column("ID_ATENDIMENTO_CARGA",  TypeName = "int", Order=3 )]
        [ForeignKey("CRM_CARGA_LOJA_VENDA")]
        public System.Nullable<int> ID_ATENDIMENTO_CARGA { get; set; }

        [Column("ID_FILIAL_PFJ",  TypeName = "int", Order=4 )]
        [ForeignKey("TBC_FILIAL")]
        public System.Nullable<int> ID_FILIAL_PFJ { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=5 )]
        [Required]
        [ForeignKey("LJV_LOJA")]
        [Precision(10)]
        public int ID_LOJA { get; set; }

        [Column("ID_CAIXA_CTRL",  TypeName = "bigint", Order=6 )]
        [Required]
        [ForeignKey("LJV_CAIXA_CTRL")]
        public long ID_CAIXA_CTRL { get; set; }

        [Column("ID_OPERACAO_VENDA",  TypeName = "int", Order=7 )]
        [ForeignKey("LJV_OPERACAO_VENDA")]
        [Precision(10)]
        public System.Nullable<int> ID_OPERACAO_VENDA { get; set; }

        [Column("ID_ECF_OPERACAO",  TypeName = "bigint", Order=8 )]
        [ForeignKey("LJV_ECF_OPERACAO")]
        public System.Nullable<long> ID_ECF_OPERACAO { get; set; }

        [Column("ID_TAB_PRECO",  TypeName = "int", Order=9 )]
        [ForeignKey("PRD_TABELA_PRECO")]
        [Precision(10)]
        public System.Nullable<int> ID_TAB_PRECO { get; set; }

        [Column("ID_MOTIVO_CANCELAMENTO",  TypeName = "smallint", Order=10 )]
        [ForeignKey("LJV_MOTIVO_CANCELAMENTO")]
        [Precision(5)]
        public System.Nullable<short> ID_MOTIVO_CANCELAMENTO { get; set; }

        [Column("ID_MOTIVO_DEVOLUCAO",  TypeName = "smallint", Order=11 )]
        [ForeignKey("LJV_MOTIVO_DEVOLUCAO")]
        [Precision(5)]
        public System.Nullable<short> ID_MOTIVO_DEVOLUCAO { get; set; }

        [Column("ID_CRM_PFJ",  TypeName = "bigint", Order=12 )]
        [Display(Name="Id Crm Pfj Dados")]
        [ForeignKey("CRM_PFJ")]
        public System.Nullable<long> ID_CRM_PFJ { get; set; }

        [Column("LX_TIPO_ATENDIMENTO",  TypeName = "tinyint", Order=13 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_ATENDIMENTO]")]
        public byte LX_TIPO_ATENDIMENTO { get; set; }

        [Column("NUMERO_ATENDIMENTO",  TypeName = "varchar", Order=14 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(12)]
        public string NUMERO_ATENDIMENTO { get; set; }

        [Column("DATA_ATENDIMENTO",  TypeName = "datetime", Order=15 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATENDIMENTO { get; set; }

        [Column("HORA_INICIO",  TypeName = "datetime", Order=16 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> HORA_INICIO { get; set; }

        [Column("HORA_FIM",  TypeName = "datetime", Order=17 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> HORA_FIM { get; set; }

        [Column("TEMPO_TOTAL",  TypeName = "int", Order=18 )]
        [Precision(10)]
        public System.Nullable<int> TEMPO_TOTAL { get; set; }

        [Column("CPF_CNPJ",  TypeName = "varchar", Order=19 )]
        [MaxLength(19)]
        public string CPF_CNPJ { get; set; }

        [Column("QTDE_MERCADORIA_SERVICO",  TypeName = "numeric", Order=20 )]
        [Precision(10)]
        [Scale(3)]
        public System.Nullable<decimal> QTDE_MERCADORIA_SERVICO { get; set; }

        [Column("VALOR_MERCADORIA_SERVICO",  TypeName = "numeric", Order=21 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_MERCADORIA_SERVICO { get; set; }

        [Column("VALOR_DESCONTO_SUBTOTAL",  TypeName = "numeric", Order=22 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_DESCONTO_SUBTOTAL { get; set; }

        [Column("VALOR_ACRESCIMO_SUBTOTAL",  TypeName = "numeric", Order=23 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ACRESCIMO_SUBTOTAL { get; set; }

        [Column("VALOR_DESCONTO_ITENS",  TypeName = "numeric", Order=24 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_DESCONTO_ITENS { get; set; }

        [Column("VALOR_CUPOM_FISCAL",  TypeName = "numeric", Order=25 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_CUPOM_FISCAL { get; set; }

        [Column("VALOR_ITENS_VALE_PRESENTE",  TypeName = "numeric", Order=26 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITENS_VALE_PRESENTE { get; set; }

        [Column("VALOR_ITENS_RECEBIMENTO",  TypeName = "numeric", Order=27 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITENS_RECEBIMENTO { get; set; }

        [Column("VALOR_ITENS_PEDIDO",  TypeName = "numeric", Order=28 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITENS_PEDIDO { get; set; }

        [Column("VALOR_IMPOSTO_AGREGADO",  TypeName = "numeric", Order=29 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_IMPOSTO_AGREGADO { get; set; }

        [Column("VALOR_TOTAL",  TypeName = "numeric", Order=30 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_TOTAL { get; set; }

        [Column("ATENDIMENTO_CANCELADO",  TypeName = "bit", Order=31 )]
        [Required]
        [Precision(1)]
        public bool ATENDIMENTO_CANCELADO { get; set; }

        [Column("ATENDIMENTO_CANCELADO_ECF",  TypeName = "bit", Order=32 )]
        [Required]
        [Precision(1)]
        public bool ATENDIMENTO_CANCELADO_ECF { get; set; }

        [Column("DATA_HORA_CANCELAMENTO",  TypeName = "datetime", Order=33 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_HORA_CANCELAMENTO { get; set; }

        [Column("LX_STATUS_ATENDIMENTO",  TypeName = "tinyint", Order=34 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_ATENDIMENTO]")]
        public byte LX_STATUS_ATENDIMENTO { get; set; }

        [Column("LX_STATUS_REGISTRO",  TypeName = "tinyint", Order=35 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_REGISTRO]")]
        public byte LX_STATUS_REGISTRO { get; set; }

        [Column("LX_TIPO_FISCAL",  TypeName = "tinyint", Order=36 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_FISCAL]")]
        public byte LX_TIPO_FISCAL { get; set; }

        [Column("DATA_HORA_ALTERACAO",  TypeName = "datetime", Order=37 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_HORA_ALTERACAO { get; set; }

        [Column("LX_PEDIDO_ORIGEM",  TypeName = "tinyint", Order=38 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_PEDIDO_ORIGEM]")]
        public byte LX_PEDIDO_ORIGEM { get; set; }

        [Column("LX_ATENDIMENTO_ORIGEM",  TypeName = "tinyint", Order=39 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_ATENDIMENTO_ORIGEM]")]
        public byte LX_ATENDIMENTO_ORIGEM { get; set; }

        [Column("DATA_HORA_INTEGRACAO",  TypeName = "datetime", Order=40 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_HORA_INTEGRACAO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_MOTIVO_CANCELAMENTO LJV_MOTIVO_CANCELAMENTO { get; set; }
        
        public virtual LJV_MOTIVO_DEVOLUCAO LJV_MOTIVO_DEVOLUCAO { get; set; }
        
        public virtual PRD_TABELA_PRECO PRD_TABELA_PRECO { get; set; }
        
        public virtual TBC_FILIAL TBC_FILIAL { get; set; }
        
        public virtual TBC_GRUPO_ECONOMICO TBC_GRUPO_ECONOMICO { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }
        
        public virtual LJV_OPERACAO_VENDA LJV_OPERACAO_VENDA { get; set; }
        
        public virtual LJV_CAIXA_CTRL LJV_CAIXA_CTRL { get; set; }
        
        public virtual LJV_ECF_OPERACAO LJV_ECF_OPERACAO { get; set; }
        
        public virtual CRM_PFJ CRM_PFJ { get; set; }
        
        public virtual CRM_CARGA_LOJA_VENDA CRM_CARGA_LOJA_VENDA { get; set; }


                
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_ACAO_PROMOCAO> LJV_ATENDIMENTO_ACAO_PROMOCAO_LISTA { get; set; }
        
        //Origin Document: VendaAtributo.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_ATRIBUTO> LJV_ATENDIMENTO_ATRIBUTO_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_DESCONTO> LJV_ATENDIMENTO_DESCONTO_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_DOC_FISCAL> LJV_ATENDIMENTO_DOC_FISCAL_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_FIDELIDADE> LJV_ATENDIMENTO_FIDELIDADE_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_ITEM> LJV_ATENDIMENTO_ITEM_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_PGTO> LJV_ATENDIMENTO_PGTO_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_ATENDIMENTO_VENDEDOR> LJV_ATENDIMENTO_VENDEDOR_LISTA { get; set; }
        
        //Origin Document: Gift.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_GIFT_CARD_TRANSACAO> LJV_GIFT_CARD_TRANSACAO_LISTA { get; set; }
        
        //Origin Document: IntegracaoFiscal.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_INTEGRACAO_FISCAL> LJV_INTEGRACAO_FISCAL_LISTA { get; set; }
        
        //Origin Document: Venda.bmd
        [InverseProperty("LJV_ATENDIMENTO")]
        public virtual ICollection<LJV_TEF_LOG> LJV_TEF_LOG_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class LJV_ATENDIMENTOConfiguration : EntityTypeConfiguration<LJV_ATENDIMENTO>
    {
		partial void Init();

        public LJV_ATENDIMENTOConfiguration()
            : base()
        {

            Property(p => p.QTDE_MERCADORIA_SERVICO).HasPrecision(10,3).IsOptional();
            Property(p => p.VALOR_MERCADORIA_SERVICO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_DESCONTO_SUBTOTAL).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ACRESCIMO_SUBTOTAL).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_DESCONTO_ITENS).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_CUPOM_FISCAL).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITENS_VALE_PRESENTE).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITENS_RECEBIMENTO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITENS_PEDIDO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_IMPOSTO_AGREGADO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_TOTAL).HasPrecision(14,2).IsOptional();

            Init();
        }
    }

}
