//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_PEDIDO_ACAO_PROMOCAO", Schema = "LX_LJV")]
    public partial class LJV_PEDIDO_ACAO_PROMOCAO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PEDIDO_ACAO_PROMOCAO",  TypeName = "bigint", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public long ID_PEDIDO_ACAO_PROMOCAO { get; set; }

        [Column("ID_PEDIDO",  TypeName = "bigint", Order=2 )]
        [Required]
        [ForeignKey("LJV_PEDIDO")]
        public long ID_PEDIDO { get; set; }

        [Column("ID_ACAO_CAMPANHA",  TypeName = "int", Order=3 )]
        [ForeignKey("CRM_CAMPANHA_ACAO")]
        public System.Nullable<int> ID_ACAO_CAMPANHA { get; set; }

        [Column("ID_PROMOCAO",  TypeName = "int", Order=4 )]
        [ForeignKey("PRM_PROMOCAO")]
        public System.Nullable<int> ID_PROMOCAO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_PEDIDO LJV_PEDIDO { get; set; }
        
        public virtual CRM_CAMPANHA_ACAO CRM_CAMPANHA_ACAO { get; set; }
        
        public virtual PRM_PROMOCAO PRM_PROMOCAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class LJV_PEDIDO_ACAO_PROMOCAOConfiguration : EntityTypeConfiguration<LJV_PEDIDO_ACAO_PROMOCAO>
    {
		partial void Init();

        public LJV_PEDIDO_ACAO_PROMOCAOConfiguration()
            : base()
        {


            Init();
        }
    }

}
