//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_MOVIMENTO_TROCA_W", Schema = "dbo")]
    public partial class LJV_MOVIMENTO_TROCA_W 
    {
		
		#region Query Methods
		public void RefreshComposedKeys()
        {

        }

		public static IQueryable<LJV_MOVIMENTO_TROCA_W> GetQuery(DbContext ctx)
        {
            return GetQueryByParam(ctx, "", new System.Data.Entity.Core.Objects.ObjectParameter[] { });
        }

        public static IQueryable<LJV_MOVIMENTO_TROCA_W> GetQueryByParam(DbContext ctx, string predicate, params System.Data.Entity.Core.Objects.ObjectParameter[] parameters)
        {
			LinxOperacional context = (LinxOperacional)ctx;
			



            
            var query = (from AtendItem in context.LJV_ATENDIMENTO_ITEM
            join Atend in context.LJV_ATENDIMENTO on AtendItem.ID_ATENDIMENTO equals Atend.ID_ATENDIMENTO
            join entity0LF in context.LJV_MOTIVO_DEVOLUCAO on Atend.ID_MOTIVO_DEVOLUCAO equals entity0LF.ID_MOTIVO_DEVOLUCAO into entity0Tmp
            from entity0 in entity0Tmp.DefaultIfEmpty()
            join entity1 in context.LJV_LOJA on Atend.ID_LOJA equals entity1.ID_LOJA
            join entity2 in context.LJV_CANAL_VENDA on entity1.ID_LJV_CANAL_VENDA equals entity2.ID_LJV_CANAL_VENDA
            join entity3 in context.LJV_CAIXA_CTRL on Atend.ID_CAIXA_CTRL equals entity3.ID_CAIXA_CTRL
            join entity4 in context.LJV_TERMINAL on entity3.ID_TERMINAL equals entity4.ID_TERMINAL
            join entity5 in context.LJV_VENDEDOR on entity3.ID_OPERADOR_CAIXA equals entity5.ID_VENDEDOR
            join entity6LF in context.LJV_ECF_OPERACAO on Atend.ID_ECF_OPERACAO equals entity6LF.ID_ECF_OPERACAO into entity6Tmp
            from entity6 in entity6Tmp.DefaultIfEmpty()
            join entity7 in context.PRD_SKU_PRODUTO on AtendItem.ID_SKU equals entity7.ID_SKU
            select new LJV_MOVIMENTO_TROCA_W()
            {
                DESCONTO_ITEM = AtendItem.DESCONTO_ITEM,
                ID_ATENDIMENTO_ITEM = AtendItem.ID_ATENDIMENTO_ITEM,
                ITEM_CANCELADO = AtendItem.ITEM_CANCELADO,
                ITEM_CANCELADO_ECF = AtendItem.ITEM_CANCELADO_ECF,
                LX_TIPO_ITEM = AtendItem.LX_TIPO_ITEM,
                PRECO_BRUTO_ITEM = AtendItem.PRECO_BRUTO_ITEM,
                QTDE_ITEM = AtendItem.QTDE_ITEM,
                VALOR_BRUTO = AtendItem.PRECO_BRUTO_ITEM *  AtendItem.QTDE_ITEM,
                VALOR_ITEM = AtendItem.VALOR_ITEM,
                VALOR_LIQUIDO_PAGO = AtendItem.VALOR_LIQUIDO_PAGO,
                ATENDIMENTO_CANCELADO = Atend.ATENDIMENTO_CANCELADO,
                ATENDIMENTO_CANCELADO_ECF = Atend.ATENDIMENTO_CANCELADO_ECF,
                DATA_ATENDIMENTO = Atend.DATA_ATENDIMENTO,
                ID_ATENDIMENTO = Atend.ID_ATENDIMENTO,
                LX_STATUS_ATENDIMENTO = Atend.LX_STATUS_ATENDIMENTO,
                LX_TIPO_ATENDIMENTO = Atend.LX_TIPO_ATENDIMENTO,
                COD_MOTIVO_DEVOLUCAO = entity0.COD_MOTIVO_DEVOLUCAO,
                DESC_MOTIVO_DEVOLUCAO = entity0.DESC_MOTIVO_DEVOLUCAO,
                ID_MOTIVO_DEVOLUCAO = entity0.ID_MOTIVO_DEVOLUCAO,
                COD_LOJA = entity1.COD_LOJA,
                DESC_LOJA = entity1.DESC_LOJA,
                ID_BANDEIRA_REDE = entity1.ID_BANDEIRA_REDE,
                ID_LOJA = entity1.ID_LOJA,
                COD_CANAL_VENDA = entity2.COD_CANAL_VENDA,
                DESC_CANAL_VENDA = entity2.DESC_CANAL_VENDA,
                ID_LJV_CANAL_VENDA = entity2.ID_LJV_CANAL_VENDA,
                COD_TERMINAL = entity4.COD_TERMINAL,
                DESC_TERMINAL = entity4.DESC_TERMINAL,
                ID_TERMINAL = entity4.ID_TERMINAL,
                COD_OPERADOR = entity5.COD_VENDEDOR,
                ID_OPERADOR = entity5.ID_VENDEDOR,
                NOME_OPERADOR = entity5.NOME_VENDEDOR,
                COO = entity6.COO,
                COD_SKU = entity7.COD_SKU,
                DESC_SKU = entity7.DESC_SKU,
                ID_SKU = entity7.ID_SKU
            })
            ;


            List<object> paramValues = new List<object>();
            predicate = predicate.ToDynamicLinqExpression(typeof(LJV_MOVIMENTO_TROCA_W), parameters, paramValues);

			return query.Where(predicate, paramValues.ToArray());
        }
		#endregion



		#region Data Properties	
        [Key]
        [Column("LJV_ATENDIMENTO_ITEM.ID_ATENDIMENTO_ITEM",  TypeName = "bigint", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public long ID_ATENDIMENTO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.LX_TIPO_ITEM",  TypeName = "tinyint", Order=1 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_ITEM]")]
        public byte LX_TIPO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.QTDE_ITEM",  TypeName = "numeric", Order=2 )]
        [Required]
        [Precision(10)]
        [Scale(3)]
        public decimal QTDE_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.DESCONTO_ITEM",  TypeName = "numeric", Order=3 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> DESCONTO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.VALOR_ITEM",  TypeName = "numeric", Order=4 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.ITEM_CANCELADO",  TypeName = "bit", Order=5 )]
        [Required]
        [Precision(1)]
        public bool ITEM_CANCELADO { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.VALOR_LIQUIDO_PAGO",  TypeName = "numeric", Order=6 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_LIQUIDO_PAGO { get; set; }

        [LinxPublicationField(LookUpInfo="long#ID_ATENDIMENTO#true##0:0###2#true#::LJV_ATENDIMENTO##false#false##LJV_ATENDIMENTO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO.ID_ATENDIMENTO",  TypeName = "bigint", Order=7 )]
        [Required]
        public long ID_ATENDIMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="byte#LX_TIPO_ATENDIMENTO#false##3:0#LX_TIPO_ATENDIMENTO##13#true#::LJV_ATENDIMENTO##false#false##LJV_ATENDIMENTO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO.LX_TIPO_ATENDIMENTO",  TypeName = "tinyint", Order=8 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_ATENDIMENTO]")]
        public byte LX_TIPO_ATENDIMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="DateTime#DATA_ATENDIMENTO#false##23:3###15#true#::LJV_ATENDIMENTO##false#false##LJV_ATENDIMENTO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO.DATA_ATENDIMENTO",  TypeName = "datetime", Order=9 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATENDIMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="bool#ATENDIMENTO_CANCELADO#false##1:0###31#true#::LJV_ATENDIMENTO##false#false##LJV_ATENDIMENTO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO.ATENDIMENTO_CANCELADO",  TypeName = "bit", Order=10 )]
        [Required]
        [Precision(1)]
        public bool ATENDIMENTO_CANCELADO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<short>#ID_MOTIVO_DEVOLUCAO#true##5:0###1#true#::LJV_MOTIVO_DEVOLUCAO##false#false##LJV_MOTIVO_DEVOLUCAO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_MOTIVO_DEVOLUCAO.ID_MOTIVO_DEVOLUCAO",  TypeName = "smallint", Order=11 )]
        [Precision(5)]
        public System.Nullable<short> ID_MOTIVO_DEVOLUCAO { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_MOTIVO_DEVOLUCAO#false##5:0###2#true#::LJV_MOTIVO_DEVOLUCAO##false#false##LJV_MOTIVO_DEVOLUCAO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_MOTIVO_DEVOLUCAO.COD_MOTIVO_DEVOLUCAO",  TypeName = "varchar", Order=12 )]
        [MaxLength(5)]
        public string COD_MOTIVO_DEVOLUCAO { get; set; }

        [LinxPublicationField(LookUpInfo="string#DESC_MOTIVO_DEVOLUCAO#false##60:0###3#true#::LJV_MOTIVO_DEVOLUCAO##false#false##LJV_MOTIVO_DEVOLUCAO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_MOTIVO_DEVOLUCAO.DESC_MOTIVO_DEVOLUCAO",  TypeName = "varchar", Order=13 )]
        [MaxLength(60)]
        public string DESC_MOTIVO_DEVOLUCAO { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_LOJA#true##0:0###1#true#::LJV_LOJA##false#false##LJV_LOJA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_LOJA.ID_LOJA",  TypeName = "int", Order=14 )]
        [Required]
        public int ID_LOJA { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_LOJA#false##20:0###4#true#::LJV_LOJA##false#false##LJV_LOJA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_LOJA.COD_LOJA",  TypeName = "char", Order=15 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(20)]
        public string COD_LOJA { get; set; }

        [LinxPublicationField(LookUpInfo="string#DESC_LOJA#false##60:0###5#true#::LJV_LOJA##false#false##LJV_LOJA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_LOJA.DESC_LOJA",  TypeName = "varchar", Order=16 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_LOJA { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<int>#ID_BANDEIRA_REDE#false##10:0###6#true#::LJV_LOJA##false#false##LJV_LOJA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_LOJA.ID_BANDEIRA_REDE",  TypeName = "int", Order=17 )]
        [Precision(10)]
        public System.Nullable<int> ID_BANDEIRA_REDE { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_LJV_CANAL_VENDA#true##0:0##Id Ljv Canal Venda#1#true#::LJV_CANAL_VENDA##false#false##LJV_CANAL_VENDA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_CANAL_VENDA.ID_LJV_CANAL_VENDA",  TypeName = "int", Order=18 )]
        [Required]
        [Display(Name="Id Ljv Canal Venda")]
        public int ID_LJV_CANAL_VENDA { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_CANAL_VENDA#false##6:0###2#true#::LJV_CANAL_VENDA##false#false##LJV_CANAL_VENDA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_CANAL_VENDA.COD_CANAL_VENDA",  TypeName = "char", Order=19 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(6)]
        public string COD_CANAL_VENDA { get; set; }

        [LinxPublicationField(LookUpInfo="string#DESC_CANAL_VENDA#false##60:0###3#true#::LJV_CANAL_VENDA##false#false##LJV_CANAL_VENDA#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_CANAL_VENDA.DESC_CANAL_VENDA",  TypeName = "varchar", Order=20 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_CANAL_VENDA { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_TERMINAL#true##10:0###1#true#::LJV_TERMINAL##false#false##LJV_TERMINAL#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_TERMINAL.ID_TERMINAL",  TypeName = "int", Order=21 )]
        [Required]
        [Precision(10)]
        public int ID_TERMINAL { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_TERMINAL#false##6:0###3#true#::LJV_TERMINAL##false#false##LJV_TERMINAL#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_TERMINAL.COD_TERMINAL",  TypeName = "char", Order=22 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(6)]
        public string COD_TERMINAL { get; set; }

        [LinxPublicationField(LookUpInfo="string#DESC_TERMINAL#false##60:0###4#true#::LJV_TERMINAL##false#false##LJV_TERMINAL#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_TERMINAL.DESC_TERMINAL",  TypeName = "varchar", Order=23 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_TERMINAL { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_VENDEDOR#true##10:0###1#true#::LJV_VENDEDOR##false#false##LJV_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_VENDEDOR.ID_VENDEDOR",  TypeName = "int", Order=24 )]
        [Required]
        [Precision(10)]
        public int ID_OPERADOR { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_VENDEDOR#false##20:0###4#true#::LJV_VENDEDOR##false#false##LJV_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_VENDEDOR.COD_VENDEDOR",  TypeName = "varchar", Order=25 )]
        [MaxLength(20)]
        public string COD_OPERADOR { get; set; }

        [LinxPublicationField(LookUpInfo="string#NOME_VENDEDOR#false##120:0###6#true#::LJV_VENDEDOR##false#false##LJV_VENDEDOR#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_VENDEDOR.NOME_VENDEDOR",  TypeName = "varchar", Order=26 )]
        [MaxLength(120)]
        public string NOME_OPERADOR { get; set; }

        [LinxPublicationField(LookUpInfo="int#ID_SKU#true##10:0###1#true#::PRD_SKU_PRODUTO##false#false##PRD_SKU_PRODUTO#Linx.Operacional.BM#IQueryable#")]
        [Column("PRD_SKU_PRODUTO.ID_SKU",  TypeName = "int", Order=27 )]
        [Required]
        [Precision(10)]
        public int ID_SKU { get; set; }

        [LinxPublicationField(LookUpInfo="string#COD_SKU#false##25:0###2#true#::PRD_SKU_PRODUTO##false#false##PRD_SKU_PRODUTO#Linx.Operacional.BM#IQueryable#")]
        [Column("PRD_SKU_PRODUTO.COD_SKU",  TypeName = "varchar", Order=28 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(25)]
        public string COD_SKU { get; set; }

        [LinxPublicationField(LookUpInfo="string#DESC_SKU#false##120:0###3#true#::PRD_SKU_PRODUTO##false#false##PRD_SKU_PRODUTO#Linx.Operacional.BM#IQueryable#")]
        [Column("PRD_SKU_PRODUTO.DESC_SKU",  TypeName = "varchar", Order=29 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(120)]
        public string DESC_SKU { get; set; }

        [LinxPublicationField(LookUpInfo="byte#LX_STATUS_ATENDIMENTO#false##3:0#LX_STATUS_ATENDIMENTO##34#true#::LJV_ATENDIMENTO##false#false##LJV_ATENDIMENTO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO.LX_STATUS_ATENDIMENTO",  TypeName = "tinyint", Order=30 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_STATUS_ATENDIMENTO]")]
        public byte LX_STATUS_ATENDIMENTO { get; set; }

        [LinxPublicationField(LookUpInfo="System.Nullable<int>#COO#false##0:0###6#true#::LJV_ECF_OPERACAO##false#false##LJV_ECF_OPERACAO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ECF_OPERACAO.COO",  TypeName = "int", Order=31 )]
        public System.Nullable<int> COO { get; set; }

        [Column("VALOR_BRUTO",  TypeName = "numeric", Order=32 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_BRUTO { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.PRECO_BRUTO_ITEM",  TypeName = "numeric", Order=33 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> PRECO_BRUTO_ITEM { get; set; }

        [Column("LJV_ATENDIMENTO_ITEM.ITEM_CANCELADO_ECF",  TypeName = "bit", Order=34 )]
        [Required]
        [Precision(1)]
        public bool ITEM_CANCELADO_ECF { get; set; }

        [LinxPublicationField(LookUpInfo="bool#ATENDIMENTO_CANCELADO_ECF#false##1:0###32#true#::LJV_ATENDIMENTO##false#false##LJV_ATENDIMENTO#Linx.Operacional.BM#IQueryable#")]
        [Column("LJV_ATENDIMENTO.ATENDIMENTO_CANCELADO_ECF",  TypeName = "bit", Order=35 )]
        [Required]
        [Precision(1)]
        public bool ATENDIMENTO_CANCELADO_ECF { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class LJV_MOVIMENTO_TROCA_WConfiguration : EntityTypeConfiguration<LJV_MOVIMENTO_TROCA_W>
    {
		partial void Init();

        public LJV_MOVIMENTO_TROCA_WConfiguration()
            : base()
        {

            Property(p => p.QTDE_ITEM).HasPrecision(10,3);
            Property(p => p.DESCONTO_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_ITEM).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_LIQUIDO_PAGO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_BRUTO).HasPrecision(14,2).IsOptional();
            Property(p => p.PRECO_BRUTO_ITEM).HasPrecision(14,2).IsOptional();

            Init();
        }
    }

}
