//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("LJV_CONDICAO_PAGAMENTO_LIMITE_LOJA", Schema = "LX_LJV")]
    public partial class LJV_CONDICAO_PAGAMENTO_LIMITE_LOJA : ILinx, IGpecon
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Column("ID_GPECON",  TypeName = "int", Order=1 )]
        [Required]
        [ForeignKey("TBC_GRUPO_ECONOMICO")]
        [Precision(10)]
        public int ID_GPECON { get; set; }

        [Key]
        [Column("ID_LJV_CONDICAO_PAGAMENTO_LIMITE_LOJA",  TypeName = "int", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Ljv Condicao Pagamento Limite Loja")]
        public int ID_LJV_CONDICAO_PAGAMENTO_LIMITE_LOJA { get; set; }

        [Column("ID_CONDICAO_PAGAMENTO",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("LJV_CONDICAO_PAGAMENTO")]
        public int ID_CONDICAO_PAGAMENTO { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=4 )]
        [ForeignKey("LJV_LOJA")]
        public System.Nullable<int> ID_LOJA { get; set; }

        [Column("VALOR_MINIMO",  TypeName = "numeric", Order=5 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_MINIMO { get; set; }

        [Column("VALOR_MAXIMO",  TypeName = "numeric", Order=6 )]
        [Precision(14)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_MAXIMO { get; set; }

        [Column("PARCELAS_MINIMO",  TypeName = "smallint", Order=7 )]
        [Precision(5)]
        public System.Nullable<short> PARCELAS_MINIMO { get; set; }

        [Column("PARCELAS_MAXIMO",  TypeName = "smallint", Order=8 )]
        [Precision(5)]
        public System.Nullable<short> PARCELAS_MAXIMO { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=9 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_CONDICAO_PAGAMENTO LJV_CONDICAO_PAGAMENTO { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }
        
        public virtual TBC_GRUPO_ECONOMICO TBC_GRUPO_ECONOMICO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class LJV_CONDICAO_PAGAMENTO_LIMITE_LOJAConfiguration : EntityTypeConfiguration<LJV_CONDICAO_PAGAMENTO_LIMITE_LOJA>
    {
		partial void Init();

        public LJV_CONDICAO_PAGAMENTO_LIMITE_LOJAConfiguration()
            : base()
        {

            Property(p => p.VALOR_MINIMO).HasPrecision(14,2).IsOptional();
            Property(p => p.VALOR_MAXIMO).HasPrecision(14,2).IsOptional();

            Init();
        }
    }

}
