//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("MVD_PONTEIRO_CONTROLE", Schema = "LX_MVD")]
    public partial class MVD_PONTEIRO_CONTROLE : ILinx
    {
		
		public MVD_PONTEIRO_CONTROLE()
		{
			this.LX_STATUS_PONTEIRO = 1;
		}

		#region Query Methods
		#endregion

        public void UpdateRelations(IEnumerable<System.Data.Entity.Infrastructure.DbEntityEntry> entries, long oldKey, long newKey)
        {
        }


		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PONTEIRO_CONTROLE",  TypeName = "bigint", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Lnf Controle Ponteiro")]
        public long ID_PONTEIRO_CONTROLE { get; set; }

        [Column("DATA_CRIACAO",  TypeName = "datetime", Order=2 )]
        [Required]
        public DateTime DATA_CRIACAO { get; set; }

        [Column("EX_ID_ORIGEM_DOCUMENTO",  TypeName = "bigint", Order=3 )]
        [Required]
        public long EX_ID_ORIGEM_DOCUMENTO { get; set; }

        [Column("ID_FILIAL_PFJ",  TypeName = "int", Order=4 )]
        [Required]
        [Precision(10)]
        public int ID_FILIAL_PFJ { get; set; }

        [Column("NF_NUMERO",  TypeName = "bigint", Order=5 )]
        public System.Nullable<long> NF_NUMERO { get; set; }

        [Column("NF_SERIE",  TypeName = "varchar", Order=6 )]
        [MaxLength(5)]
        public string NF_SERIE { get; set; }

        [Column("COO_INICIAL",  TypeName = "int", Order=7 )]
        public System.Nullable<int> COO_INICIAL { get; set; }

        [Column("LX_TIPO_PONTEIRO",  TypeName = "tinyint", Order=8 )]
        [Required]
        [FunctionalPoint("DomainName[LX_TIPO_PONTEIRO]")]
        public byte LX_TIPO_PONTEIRO { get; set; }

        [Column("LX_STATUS_PONTEIRO",  TypeName = "tinyint", Order=9 )]
        [Required]
        [FunctionalPoint("DomainName[LX_STATUS_PONTEIRO]")]
        public byte LX_STATUS_PONTEIRO { get; set; }

        [Column("DATA_PROCESSAMENTO",  TypeName = "datetime", Order=10 )]
        public System.Nullable<DateTime> DATA_PROCESSAMENTO { get; set; }

        [Column("LOG_ERRO",  TypeName = "varchar(max)", Order=11 )]
        public string LOG_ERRO { get; set; }

        [Column("EX_ID_ENTREGA",  TypeName = "bigint", Order=12 )]
        public System.Nullable<long> EX_ID_ENTREGA { get; set; }

        [Column("EX_ID_ENVIO",  TypeName = "bigint", Order=13 )]
        public System.Nullable<long> EX_ID_ENVIO { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class MVD_PONTEIRO_CONTROLEConfiguration : EntityTypeConfiguration<MVD_PONTEIRO_CONTROLE>
    {
		partial void Init();

        public MVD_PONTEIRO_CONTROLEConfiguration()
            : base()
        {


            Init();
        }
    }

}
