//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("MVD_LOG_MANUTENCAO_ITEM", Schema = "LX_MVD")]
    public partial class MVD_LOG_MANUTENCAO_ITEM : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_LOG_MANUTENCAO_ITEM",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Mvd Doc Ocorrencia Item")]
        public int ID_LOG_MANUTENCAO_ITEM { get; set; }

        [Column("ID_LOG_MANUTENCAO",  TypeName = "int", Order=2 )]
        [Required]
        [Display(Name="Id Mvd Doc Ocorrencia")]
        [ForeignKey("MVD_LOG_MANUTENCAO")]
        public int ID_LOG_MANUTENCAO { get; set; }

        [Column("ID_OCORRENCIA",  TypeName = "int", Order=3 )]
        [Required]
        [Display(Name="Id Mvd Ocorrencia")]
        [ForeignKey("MVD_OCORRENCIA")]
        public int ID_OCORRENCIA { get; set; }

        [Column("ALTERAR_PARA",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(40)]
        public string ALTERAR_PARA { get; set; }

        [Column("ID_DOCUMENTO_STATUS",  TypeName = "int", Order=5 )]
        [Required]
        [Display(Name="Id Documento Status")]
        [ForeignKey("MVD_DOCUMENTO_STATUS")]
        public int ID_DOCUMENTO_STATUS { get; set; }

        [Column("INDICA_PROCESSADO",  TypeName = "bit", Order=6 )]
        public System.Nullable<bool> INDICA_PROCESSADO { get; set; }

        [Column("OBS",  TypeName = "varchar(max)", Order=7 )]
        public string OBS { get; set; }

        [Column("DATA_MANUTENCAO_ITEM",  TypeName = "datetime", Order=8 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_MANUTENCAO_ITEM { get; set; }

        [Column("ID_USUARIO",  TypeName = "bigint", Order=9 )]
        [Required]
        [ForeignKey("TCS_USUARIO")]
        public long ID_USUARIO { get; set; }

		#endregion

		#region Navigation
                
        public virtual MVD_LOG_MANUTENCAO MVD_LOG_MANUTENCAO { get; set; }
        
        public virtual MVD_OCORRENCIA MVD_OCORRENCIA { get; set; }
        
        public virtual TCS_USUARIO TCS_USUARIO { get; set; }
        
        public virtual MVD_DOCUMENTO_STATUS MVD_DOCUMENTO_STATUS { get; set; }


        

		
		
		#endregion
    }
	

    public partial class MVD_LOG_MANUTENCAO_ITEMConfiguration : EntityTypeConfiguration<MVD_LOG_MANUTENCAO_ITEM>
    {
		partial void Init();

        public MVD_LOG_MANUTENCAO_ITEMConfiguration()
            : base()
        {


            Init();
        }
    }

}
