//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("MVD_OCORRENCIA", Schema = "LX_MVD")]
    public partial class MVD_OCORRENCIA : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_OCORRENCIA",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Mvd Ocorrencia")]
        public int ID_OCORRENCIA { get; set; }

        [Column("ID_DOCUMENTO_TIPO",  TypeName = "smallint", Order=2 )]
        [Required]
        [Display(Name="Id Mvd Documento")]
        [ForeignKey("MVD_DOCUMENTO_TIPO")]
        public short ID_DOCUMENTO_TIPO { get; set; }

        [Column("INDICA_DOCUMENTO_ITEM",  TypeName = "bit", Order=3 )]
        [Required]
        public bool INDICA_DOCUMENTO_ITEM { get; set; }

        [Column("LX_TIPO_OCORRENCIA",  TypeName = "int", Order=4 )]
        [Required]
        public int LX_TIPO_OCORRENCIA { get; set; }

        [Column("NUMERO_PEDIDO_ENTRADA",  TypeName = "int", Order=5 )]
        [Required]
        [Precision(10)]
        public int NUMERO_ORDEM { get; set; }

        [Column("DESC_OCORRENCIA",  TypeName = "varchar", Order=6 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(80)]
        public string DESC_OCORRENCIA { get; set; }

        [Column("TABELA",  TypeName = "varchar", Order=7 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(80)]
        public string TABELA { get; set; }

        [Column("COLUNA",  TypeName = "varchar", Order=8 )]
        [MaxLength(80)]
        public string COLUNA { get; set; }

        [Column("LX_TYPE_COLUNA",  TypeName = "int", Order=9 )]
        [Required]
        public int LX_TYPE_COLUNA { get; set; }

        [Column("ID_OCORRENCIA_MESTRE",  TypeName = "int", Order=10 )]
        [Required]
        [Display(Name="Id Mvd Ocorrencia")]
        [ForeignKey("MVD_OCORRENCIA1")]
        public int ID_OCORRENCIA_MESTRE { get; set; }

		#endregion

		#region Navigation
                
        public virtual MVD_DOCUMENTO_TIPO MVD_DOCUMENTO_TIPO { get; set; }
        
        public virtual MVD_OCORRENCIA MVD_OCORRENCIA1 { get; set; }


                
        //Origin Document: LogManutencaoDocumento.bmd
        [InverseProperty("MVD_OCORRENCIA")]
        public virtual ICollection<MVD_LOG_MANUTENCAO_ITEM> MVD_LOG_MANUTENCAO_ITEM_LISTA { get; set; }
        
        //Origin Document: LogManutencaoDocumento.bmd
        [InverseProperty("MVD_OCORRENCIA")]
        public virtual ICollection<MVD_LOG_MANUTENCAO> MVD_LOG_MANUTENCAO_LISTA { get; set; }
        
        //Origin Document: LogManutencaoDocumento.bmd
        public virtual ICollection<MVD_OCORRENCIA> MVD_OCORRENCIA_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class MVD_OCORRENCIAConfiguration : EntityTypeConfiguration<MVD_OCORRENCIA>
    {
		partial void Init();

        public MVD_OCORRENCIAConfiguration()
            : base()
        {


            Init();
        }
    }

}
