//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRD_ARTIGO_VARIANTE", Schema = "LX_PRD")]
    public partial class PRD_ARTIGO_VARIANTE : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PRD_VARIANTE",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_PRD_VARIANTE { get; set; }

        [Column("ID_ARTIGO",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("PRD_ARTIGO")]
        [Precision(10)]
        public int ID_ARTIGO { get; set; }

        [Column("COD_PRD_VARIANTE",  TypeName = "char", Order=3 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(40)]
        public string COD_PRD_VARIANTE { get; set; }

        [Column("DESC_PRD_VARIANTE",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(250)]
        public string DESC_PRD_VARIANTE { get; set; }

        [Column("ID_PRD_VARIANTE_VALOR_01",  TypeName = "int", Order=5 )]
        [ForeignKey("PRD_VARIANTE_VALOR_01")]
        [Precision(10)]
        public System.Nullable<int> ID_PRD_VARIANTE_VALOR_01 { get; set; }

        [Column("ID_PRD_VARIANTE_VALOR_02",  TypeName = "int", Order=6 )]
        [ForeignKey("PRD_VARIANTE_VALOR_02")]
        [Precision(10)]
        public System.Nullable<int> ID_PRD_VARIANTE_VALOR_02 { get; set; }

        [Column("ID_PRD_VARIANTE_VALOR_03",  TypeName = "int", Order=7 )]
        [ForeignKey("PRD_VARIANTE_VALOR_03")]
        [Precision(10)]
        public System.Nullable<int> ID_PRD_VARIANTE_VALOR_03 { get; set; }

        [Column("ID_PRD_VARIANTE_VALOR_04",  TypeName = "int", Order=8 )]
        [ForeignKey("PRD_VARIANTE_VALOR_04")]
        [Precision(10)]
        public System.Nullable<int> ID_PRD_VARIANTE_VALOR_04 { get; set; }

        [Column("ID_PRD_VARIANTE_VALOR_05",  TypeName = "int", Order=9 )]
        [ForeignKey("PRD_VARIANTE_VALOR_05")]
        [Precision(10)]
        public System.Nullable<int> ID_PRD_VARIANTE_VALOR_05 { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=10 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

		#endregion

		#region Navigation
                
        public virtual PRD_ARTIGO PRD_ARTIGO { get; set; }
        
        public virtual PRD_ARTIGO_VARIANTE_VALOR PRD_VARIANTE_VALOR_05 { get; set; }
        
        public virtual PRD_ARTIGO_VARIANTE_VALOR PRD_VARIANTE_VALOR_04 { get; set; }
        
        public virtual PRD_ARTIGO_VARIANTE_VALOR PRD_VARIANTE_VALOR_01 { get; set; }
        
        public virtual PRD_ARTIGO_VARIANTE_VALOR PRD_VARIANTE_VALOR_02 { get; set; }
        
        public virtual PRD_ARTIGO_VARIANTE_VALOR PRD_VARIANTE_VALOR_03 { get; set; }


                
        //Origin Document: Sku.bmd
        [InverseProperty("PRD_ARTIGO_VARIANTE")]
        public virtual ICollection<PRD_SKU_PRODUTO> PRD_SKU_PRODUTO_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class PRD_ARTIGO_VARIANTEConfiguration : EntityTypeConfiguration<PRD_ARTIGO_VARIANTE>
    {
		partial void Init();

        public PRD_ARTIGO_VARIANTEConfiguration()
            : base()
        {


            Init();
        }
    }

}
