//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRD_MARCA_FABRICANTE", Schema = "LX_PRD")]
    public partial class PRD_MARCA_FABRICANTE : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_MARCA_FABRICANTE_ATRIBUTO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("MARCA_FABRICANTE_ATRIBUTO")]
        [Precision(10)]
        public int ID_MARCA_FABRICANTE_ATRIBUTO { get; set; }

        [Column("INDICA_MARCA_PROPRIA",  TypeName = "bit", Order=2 )]
        [Required]
        [Precision(1)]
        public bool INDICA_MARCA_PROPRIA { get; set; }

		#endregion

		#region Navigation
                
        public virtual TCS_ATRIBUTO MARCA_FABRICANTE_ATRIBUTO { get; set; }


                
        //Origin Document: Artigo.bmd
        [InverseProperty("PRD_MARCA_FABRICANTE")]
        public virtual ICollection<PRD_ARTIGO> PRD_ARTIGO_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class PRD_MARCA_FABRICANTEConfiguration : EntityTypeConfiguration<PRD_MARCA_FABRICANTE>
    {
		partial void Init();

        public PRD_MARCA_FABRICANTEConfiguration()
            : base()
        {

            Property(e => e.ID_MARCA_FABRICANTE_ATRIBUTO).HasColumnName("ID_MARCA_FABRICANTE_ATRIBUTO");

            Init();
        }
    }

}
