//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRD_SKU_PRECO_STK", Schema = "LX_PRD")]
    public partial class PRD_SKU_PRECO_STK : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PRD_SKU_PRECO_STK",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Prd Sku Preco Stk")]
        public int ID_PRD_SKU_PRECO_STK { get; set; }

        [Column("ID_TAB_PRECO",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("PRD_TABELA_PRECO")]
        [Precision(10)]
        public int ID_TAB_PRECO { get; set; }

        [Column("ID_REMARCACAO",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("PRD_REMARCACAO")]
        [Precision(10)]
        public int ID_REMARCACAO { get; set; }

        [Column("PRECO",  TypeName = "numeric", Order=4 )]
        [Required]
        [Precision(15)]
        [Scale(3)]
        public decimal PRECO { get; set; }

        [Column("LIMITE_DESCONTO",  TypeName = "numeric", Order=5 )]
        [Precision(8)]
        [Scale(5)]
        public System.Nullable<decimal> LIMITE_DESCONTO { get; set; }

        [Column("PRECO_ORIGINAL",  TypeName = "numeric", Order=6 )]
        [Required]
        [Precision(15)]
        [Scale(3)]
        public decimal PRECO_ORIGINAL { get; set; }

		#endregion

		#region Navigation
                
        public virtual PRD_TABELA_PRECO PRD_TABELA_PRECO { get; set; }
        
        public virtual PRD_REMARCACAO PRD_REMARCACAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class PRD_SKU_PRECO_STKConfiguration : EntityTypeConfiguration<PRD_SKU_PRECO_STK>
    {
		partial void Init();

        public PRD_SKU_PRECO_STKConfiguration()
            : base()
        {

            Property(p => p.PRECO).HasPrecision(15,3);
            Property(p => p.LIMITE_DESCONTO).HasPrecision(8,5).IsOptional();
            Property(p => p.PRECO_ORIGINAL).HasPrecision(15,3);

            Init();
        }
    }

}
