//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRD_CLASSE_ATRIBUTO_FILTRO", Schema = "LX_PRD")]
    public partial class PRD_CLASSE_ATRIBUTO_FILTRO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_ATRIBUTO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("TCS_ATRIBUTO")]
        [Precision(10)]
        public int ID_ATRIBUTO { get; set; }

        [Key]
        [Column("ID_CLASSE",  TypeName = "smallint", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("PRD_CLASSE_ATRIBUTO")]
        [Precision(5)]
        public short ID_CLASSE { get; set; }

        [Key]
        [Column("ID_ATRIBUTO_DEFINICAO",  TypeName = "int", Order=3 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("PRD_CLASSE_ATRIBUTO")]
        [Precision(10)]
        public int ID_ATRIBUTO_DEFINICAO { get; set; }

		#endregion

		#region Navigation
                
        public virtual PRD_CLASSE_ATRIBUTO PRD_CLASSE_ATRIBUTO { get; set; }
        
        public virtual TCS_ATRIBUTO TCS_ATRIBUTO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class PRD_CLASSE_ATRIBUTO_FILTROConfiguration : EntityTypeConfiguration<PRD_CLASSE_ATRIBUTO_FILTRO>
    {
		partial void Init();

        public PRD_CLASSE_ATRIBUTO_FILTROConfiguration()
            : base()
        {


            Init();
        }
    }

}
