//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRD_SKU_PRECO", Schema = "LX_PRD")]
    public partial class PRD_SKU_PRECO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_SKU_PRECO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Prd Sku Preco")]
        public int ID_SKU_PRECO { get; set; }

        [Column("ID_TAB_PRECO",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("PRD_TABELA_PRECO")]
        [Precision(10)]
        public int ID_TAB_PRECO { get; set; }

        [Column("ID_FILIAL_PFJ",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("TBC_FILIAL")]
        [Precision(10)]
        public int ID_FILIAL_PFJ { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=4 )]
        [ForeignKey("LJV_LOJA")]
        [Precision(10)]
        public System.Nullable<int> ID_LOJA { get; set; }

        [Column("ID_ARTIGO",  TypeName = "int", Order=5 )]
        [Required]
        [ForeignKey("PRD_ARTIGO")]
        [Precision(10)]
        public int ID_ARTIGO { get; set; }

        [Column("ID_SKU",  TypeName = "int", Order=6 )]
        [ForeignKey("PRD_SKU_PRODUTO")]
        [Precision(10)]
        public System.Nullable<int> ID_SKU { get; set; }

        [Column("ID_SKU_MENOR",  TypeName = "int", Order=7 )]
        [ForeignKey("SKU_MENOR")]
        [Precision(10)]
        public System.Nullable<int> ID_SKU_MENOR { get; set; }

        [Column("ID_PRD_SKU_REMARCACAO",  TypeName = "int", Order=8 )]
        [Display(Name="Id Prd Sku Remarcacao")]
        [ForeignKey("PRD_SKU_REMARCACAO")]
        public System.Nullable<int> ID_PRD_SKU_REMARCACAO { get; set; }

        [Column("ID_SKU_REMARCACAO_ANT",  TypeName = "int", Order=9 )]
        [Display(Name="Id Prd Sku Remarcacao")]
        [ForeignKey("PRD_SKU_REMARCACAO_ANTERIOR")]
        public System.Nullable<int> ID_SKU_REMARCACAO_ANT { get; set; }

        [Column("PRECO",  TypeName = "numeric", Order=10 )]
        [Required]
        [Precision(15)]
        [Scale(3)]
        public decimal PRECO { get; set; }

        [Column("PRECO_ORIGINAL",  TypeName = "numeric", Order=11 )]
        [Required]
        [Precision(15)]
        [Scale(3)]
        public decimal PRECO_ORIGINAL { get; set; }

        [Column("BLOQ_TABELA_PRECO",  TypeName = "bit", Order=12 )]
        [Required]
        [Precision(1)]
        public bool BLOQ_TABELA_PRECO { get; set; }

        [Column("FATOR_PRECO_TABELA",  TypeName = "numeric", Order=13 )]
        [Precision(13)]
        [Scale(10)]
        public System.Nullable<decimal> FATOR_PRECO_TABELA { get; set; }

        [Column("MARKUP",  TypeName = "numeric", Order=14 )]
        [Required]
        [Precision(8)]
        [Scale(2)]
        public decimal MARKUP { get; set; }

        [Column("LIMITE_DESCONTO",  TypeName = "numeric", Order=15 )]
        [Required]
        [Precision(8)]
        [Scale(5)]
        public decimal LIMITE_DESCONTO { get; set; }

        [Column("DATA_INI_VIGENCIA",  TypeName = "date", Order=16 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_INI_VIGENCIA { get; set; }

        [Column("DATA_FIM_VIGENCIA",  TypeName = "date", Order=17 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_FIM_VIGENCIA { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=18 )]
        [Required]
        public bool INATIVO { get; set; }

        [Column("LX_TIPO_REMARCACAO",  TypeName = "tinyint", Order=19 )]
        [Required]
        [FunctionalPoint("DomainName[LX_TIPO_REMARCACAO]")]
        public byte LX_TIPO_REMARCACAO { get; set; }

		#endregion

		#region Navigation
                
        public virtual PRD_TABELA_PRECO PRD_TABELA_PRECO { get; set; }
        
        public virtual PRD_SKU_REMARCACAO PRD_SKU_REMARCACAO { get; set; }
        
        public virtual PRD_SKU_REMARCACAO PRD_SKU_REMARCACAO_ANTERIOR { get; set; }
        
        public virtual LJV_LOJA LJV_LOJA { get; set; }
        
        public virtual PRD_SKU_PRODUTO PRD_SKU_PRODUTO { get; set; }
        
        public virtual PRD_SKU_PRODUTO SKU_MENOR { get; set; }
        
        public virtual TBC_FILIAL TBC_FILIAL { get; set; }
        
        public virtual PRD_ARTIGO PRD_ARTIGO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class PRD_SKU_PRECOConfiguration : EntityTypeConfiguration<PRD_SKU_PRECO>
    {
		partial void Init();

        public PRD_SKU_PRECOConfiguration()
            : base()
        {

            Property(p => p.PRECO).HasPrecision(15,3);
            Property(p => p.PRECO_ORIGINAL).HasPrecision(15,3);
            Property(p => p.FATOR_PRECO_TABELA).HasPrecision(13,10).IsOptional();
            Property(p => p.MARKUP).HasPrecision(8,2);
            Property(p => p.LIMITE_DESCONTO).HasPrecision(8,5);

            Init();
        }
    }

}
