//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRD_CLASSE_VARIANTE_NIVEL", Schema = "LX_PRD")]
    public partial class PRD_CLASSE_VARIANTE_NIVEL : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PRD_CLASSE_VARIANTE_NIVEL",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Prd Classe Variante Nivel")]
        public int ID_PRD_CLASSE_VARIANTE_NIVEL { get; set; }

        [Column("ID_CLASSE_VARIANTE",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("PRD_CLASSE_VARIANTE")]
        [Precision(10)]
        public int ID_CLASSE_VARIANTE { get; set; }

        [Column("ID_ATRIBUTO_DEFINICAO",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("TCS_ATRIBUTO_DEFINICAO")]
        [Precision(10)]
        public int ID_ATRIBUTO_DEFINICAO { get; set; }

        [Column("NIVEL_CLASSE_VARIANTE",  TypeName = "tinyint", Order=4 )]
        [Required]
        [Precision(3)]
        public byte NIVEL_CLASSE_VARIANTE { get; set; }

        [Column("INDICA_VARIANTE_HORIZONTAL",  TypeName = "tinyint", Order=5 )]
        [Required]
        [Precision(3)]
        public byte INDICA_VARIANTE_HORIZONTAL { get; set; }

        [Column("INDICA_ITEM_FISCAL_VARIANTE",  TypeName = "bit", Order=6 )]
        [Required]
        [Precision(1)]
        public bool INDICA_ITEM_FISCAL_VARIANTE { get; set; }

        [Column("INDICA_VARIANTE_SOBMEDIDA",  TypeName = "bit", Order=7 )]
        [Required]
        [Precision(1)]
        public bool INDICA_VARIANTE_SOBMEDIDA { get; set; }

		#endregion

		#region Navigation
                
        public virtual PRD_CLASSE_VARIANTE PRD_CLASSE_VARIANTE { get; set; }
        
        public virtual TCS_ATRIBUTO_DEFINICAO TCS_ATRIBUTO_DEFINICAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class PRD_CLASSE_VARIANTE_NIVELConfiguration : EntityTypeConfiguration<PRD_CLASSE_VARIANTE_NIVEL>
    {
		partial void Init();

        public PRD_CLASSE_VARIANTE_NIVELConfiguration()
            : base()
        {


            Init();
        }
    }

}
