//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("PRM_TIPO_OFERTA", Schema = "LX_PRM")]
    public partial class PRM_TIPO_OFERTA : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_TIPO_OFERTA",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_TIPO_OFERTA { get; set; }

        [Column("COD_TIPO_OFERTA",  TypeName = "varchar", Order=2 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(10)]
        public string COD_TIPO_OFERTA { get; set; }

        [Column("DESC_TIPO_OFERTA",  TypeName = "varchar", Order=3 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(120)]
        public string DESC_TIPO_OFERTA { get; set; }

        [Column("LX_TIPO_OFERTA",  TypeName = "tinyint", Order=4 )]
        [Required]
        [Precision(3)]
        [FunctionalPoint("DomainName[LX_TIPO_OFERTA]")]
        public byte LX_TIPO_OFERTA { get; set; }

		#endregion

		#region Navigation
        

                
        //Origin Document: Promocao.bmd
        [InverseProperty("PRM_TIPO_OFERTA")]
        public virtual ICollection<PRM_PROMOCAO_TIPO_OFERTA> PRM_PROMOCAO_TIPO_OFERTA_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class PRM_TIPO_OFERTAConfiguration : EntityTypeConfiguration<PRM_TIPO_OFERTA>
    {
		partial void Init();

        public PRM_TIPO_OFERTAConfiguration()
            : base()
        {


            Init();
        }
    }

}
