//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("STK_LOCALIZACAO", Schema = "LX_STK")]
    public partial class STK_LOCALIZACAO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_STK_LOCALIZACAO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_STK_LOCALIZACAO { get; set; }

        [Column("ID_STK_DEPOSITO",  TypeName = "int", Order=2 )]
        [ForeignKey("STK_DEPOSITO")]
        [Precision(10)]
        public System.Nullable<int> ID_STK_DEPOSITO { get; set; }

        [Column("ID_STK_LOCALIZACAO_SUPERIOR",  TypeName = "int", Order=3 )]
        [ForeignKey("LOCALIZACAO_SUPERIOR")]
        [Precision(10)]
        public System.Nullable<int> ID_STK_LOCALIZACAO_SUPERIOR { get; set; }

        [Column("DESC_LOCALIZACAO",  TypeName = "varchar", Order=4 )]
        [MaxLength(60)]
        public string DESC_LOCALIZACAO { get; set; }

        [Column("LOCALIZACAO_MOVEL",  TypeName = "bit", Order=5 )]
        [Required]
        [Precision(1)]
        public bool LOCALIZACAO_MOVEL { get; set; }

        [Column("SEQUENCIA_DE_SEPARACAO",  TypeName = "varchar", Order=6 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(12)]
        public string SEQUENCIA_DE_SEPARACAO { get; set; }

        [Column("COORDENADA_A",  TypeName = "varchar", Order=7 )]
        [MaxLength(12)]
        public string COORDENADA_A { get; set; }

        [Column("COORDENADA_B",  TypeName = "varchar", Order=8 )]
        [MaxLength(5)]
        public string COORDENADA_B { get; set; }

        [Column("COORDENADA_C",  TypeName = "varchar", Order=9 )]
        [MaxLength(5)]
        public string COORDENADA_C { get; set; }

        [Column("COORDENADA_D",  TypeName = "varchar", Order=10 )]
        [MaxLength(5)]
        public string COORDENADA_D { get; set; }

		#endregion

		#region Navigation
                
        public virtual STK_LOCALIZACAO LOCALIZACAO_SUPERIOR { get; set; }
        
        public virtual STK_DEPOSITO STK_DEPOSITO { get; set; }


                
        //Origin Document: Coleta.bmd
        [InverseProperty("STK_LOCALIZACAO")]
        public virtual ICollection<STK_COLETA_ITEM_DETALHE> STK_COLETA_ITEM_DETALHE_LISTA { get; set; }
        
        //Origin Document: DepositoLocalizacao.bmd
        [InverseProperty("LOCALIZACAO_SUPERIOR")]
        public virtual ICollection<STK_LOCALIZACAO> STK_LOCALIZACAO_LISTA { get; set; }
        
        //Origin Document: RomaneioAjuste.bmd
        [InverseProperty("STK_LOCALIZACAO")]
        public virtual ICollection<STK_ROMANEIO_AJUSTE_DETALHE> STK_ROMANEIO_AJUSTE_DETALHE_LISTA { get; set; }
        
        //Origin Document: RomaneioAjuste.bmd
        [InverseProperty("STK_LOCALIZACAO")]
        public virtual ICollection<STK_ROMANEIO_DETALHE> STK_ROMANEIO_DETALHE_LISTA { get; set; }
        
        //Origin Document: EstoqueSaldo.bmd
        [InverseProperty("STK_LOCALIZACAO")]
        public virtual ICollection<STK_SALDO_DETALHE> STK_SALDO_DETALHE_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class STK_LOCALIZACAOConfiguration : EntityTypeConfiguration<STK_LOCALIZACAO>
    {
		partial void Init();

        public STK_LOCALIZACAOConfiguration()
            : base()
        {


            Init();
        }
    }

}
