//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("STK_COLETA_ITEM", Schema = "LX_STK")]
    public partial class STK_COLETA_ITEM : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_COLETA_ITEM",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Ljv Contagem Item")]
        public int ID_COLETA_ITEM { get; set; }

        [Column("ID_COLETA",  TypeName = "int", Order=2 )]
        [Required]
        [Display(Name="Id Ljv Contagem")]
        [ForeignKey("STK_COLETA")]
        public int ID_COLETA { get; set; }

        [Column("ID_SKU",  TypeName = "int", Order=3 )]
        [Required]
        [ForeignKey("PRD_SKU_PRODUTO")]
        [Precision(10)]
        public int ID_SKU { get; set; }

        [Column("QTDE_COLETADA",  TypeName = "numeric", Order=4 )]
        [Required]
        [Precision(15)]
        [Scale(5)]
        public decimal QTDE_COLETADA { get; set; }

        [Column("LX_STATUS_COLETA_ITEM",  TypeName = "smallint", Order=5 )]
        [Required]
        public short LX_STATUS_COLETA_ITEM { get; set; }

		#endregion

		#region Navigation
                
        public virtual STK_COLETA STK_COLETA { get; set; }
        
        public virtual PRD_SKU_PRODUTO PRD_SKU_PRODUTO { get; set; }


                
        //Origin Document: Coleta.bmd
        [InverseProperty("STK_COLETA_ITEM")]
        public virtual STK_COLETA_ITEM_DETALHE STK_COLETA_ITEM_DETALHE_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class STK_COLETA_ITEMConfiguration : EntityTypeConfiguration<STK_COLETA_ITEM>
    {
		partial void Init();

        public STK_COLETA_ITEMConfiguration()
            : base()
        {

            Property(p => p.QTDE_COLETADA).HasPrecision(15,5);

            Init();
        }
    }

}
