//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("STK_ROMANEIO_NF", Schema = "LX_STK")]
    public partial class STK_ROMANEIO_NF : ILinx
    {
		
		public STK_ROMANEIO_NF()
		{
			this.INDICA_EMISSAO_AGRUPADA = false;
			this.LX_INDICADOR_PRESENCA = 9;
		}

		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_STK_ROMANEIO",  TypeName = "bigint", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Display(Name="Id Stk Romaneio")]
        [ForeignKey("STK_ROMANEIO")]
        public long ID_STK_ROMANEIO { get; set; }

        [Column("LX_TIPO_EMISSAO",  TypeName = "tinyint", Order=2 )]
        [Required]
        [FunctionalPoint("DomainName[LX_TIPO_EMISSAO]")]
        public byte LX_TIPO_EMISSAO { get; set; }

        [Column("ID_PFJ",  TypeName = "int", Order=3 )]
        [ForeignKey("TBC_PFJ")]
        [Precision(10)]
        public System.Nullable<int> ID_PFJ { get; set; }

        [Column("ID_CRM_PFJ",  TypeName = "bigint", Order=4 )]
        [Display(Name="Id Crm Pfj Dados")]
        [ForeignKey("CRM_PFJ")]
        public System.Nullable<long> ID_CRM_PFJ { get; set; }

        [Column("ID_TRANSPORTADORA",  TypeName = "int", Order=5 )]
        [ForeignKey("TBC_TRANSPORTADORA")]
        [Precision(10)]
        public System.Nullable<int> ID_TRANSPORTADORA { get; set; }

        [Column("ID_CONDICAO_PAGAMENTO",  TypeName = "int", Order=7 )]
        [ForeignKey("LNF_CONDICAO_PAGAMENTO")]
        [Precision(10)]
        public System.Nullable<int> ID_CONDICAO_PAGAMENTO { get; set; }

        [Column("DATA_EMISSAO",  TypeName = "datetime", Order=8 )]
        public System.Nullable<DateTime> DATA_EMISSAO { get; set; }

        [Column("NATUREZA_OPERACAO",  TypeName = "varchar", Order=9 )]
        [MaxLength(60)]
        public string NATUREZA_OPERACAO { get; set; }

        [Column("INDICA_CONSUMO_FINAL",  TypeName = "bit", Order=10 )]
        [Required]
        public bool INDICA_CONSUMO_FINAL { get; set; }

        [Column("LX_MODALIDADE_FRETE",  TypeName = "tinyint", Order=11 )]
        [Required]
        public byte LX_MODALIDADE_FRETE { get; set; }

        [Column("VALOR_FRETE",  TypeName = "numeric", Order=12 )]
        [Precision(15)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_FRETE { get; set; }

        [Column("VALOR_SEGURO",  TypeName = "numeric", Order=13 )]
        [Precision(15)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_SEGURO { get; set; }

        [Column("VALOR_DESPESA",  TypeName = "numeric", Order=14 )]
        [Precision(15)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_DESPESA { get; set; }

        [Column("VALOR_DESCONTO_NF",  TypeName = "numeric", Order=15 )]
        [Precision(15)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_DESCONTO_NF { get; set; }

        [Column("VALOR_ACRESCIMO_NF",  TypeName = "numeric", Order=16 )]
        [Precision(15)]
        [Scale(2)]
        public System.Nullable<decimal> VALOR_ACRESCIMO_NF { get; set; }

        [Column("QTDE_VOLUMES",  TypeName = "int", Order=17 )]
        [Precision(5)]
        public System.Nullable<int> QTDE_VOLUMES { get; set; }

        [Column("ESPECIE_VOLUMES",  TypeName = "varchar", Order=18 )]
        [MaxLength(60)]
        public string ESPECIE_VOLUMES { get; set; }

        [Column("NUMERO_VOLUMES",  TypeName = "varchar", Order=19 )]
        [MaxLength(60)]
        public string NUMERO_VOLUMES { get; set; }

        [Column("MARCA_VOLUMES",  TypeName = "varchar", Order=20 )]
        [MaxLength(60)]
        public string MARCA_VOLUMES { get; set; }

        [Column("PLACA_VEICULO",  TypeName = "varchar", Order=21 )]
        [MaxLength(10)]
        public string PLACA_VEICULO { get; set; }

        [Column("UF_PLACA_VEICULO",  TypeName = "varchar", Order=22 )]
        [MaxLength(2)]
        public string UF_PLACA_VEICULO { get; set; }

        [Column("OBS_NOTA_FISCAL",  TypeName = "varchar(max)", Order=23 )]
        public string OBS_NOTA_FISCAL { get; set; }

        [Column("LX_STATUS_NFE",  TypeName = "smallint", Order=24 )]
        [FunctionalPoint("DomainName[LX_STATUS_NFE]")]
        public System.Nullable<short> LX_STATUS_NFE { get; set; }

        [Column("NF_NUMERO",  TypeName = "bigint", Order=25 )]
        public System.Nullable<long> NF_NUMERO { get; set; }

        [Column("NR_AVISO_RECEBTO",  TypeName = "varchar", Order=26 )]
        [MaxLength(25)]
        public string NR_AVISO_RECEBTO { get; set; }

        [Column("EX_ID_MVD_DOCUMENTO_SERIE_FILIAL",  TypeName = "int", Order=27 )]
        [Display(Name="Id Mvd Documento Serie Filial")]
        public System.Nullable<int> EX_ID_MVD_DOCUMENTO_SERIE_FILIAL { get; set; }

        [Column("NF_SERIE",  TypeName = "varchar", Order=28 )]
        [MaxLength(5)]
        public string NF_SERIE { get; set; }

        [Column("NF_DANFE_CHAVE",  TypeName = "varchar", Order=29 )]
        [MaxLength(50)]
        public string NF_DANFE_CHAVE { get; set; }

        [Column("EX_ID_NOTA_FISCAL_SAIDA",  TypeName = "bigint", Order=30 )]
        public System.Nullable<long> EX_ID_NOTA_FISCAL_SAIDA { get; set; }

        [Column("EX_ID_NOTA_FISCAL_ENTRADA",  TypeName = "bigint", Order=31 )]
        public System.Nullable<long> EX_ID_NOTA_FISCAL_ENTRADA { get; set; }

        [Column("INDICA_EMISSAO_AGRUPADA",  TypeName = "bit", Order=32 )]
        public System.Nullable<bool> INDICA_EMISSAO_AGRUPADA { get; set; }

        [Column("LX_INDICADOR_PRESENCA",  TypeName = "smallint", Order=33 )]
        [Required]
        [FunctionalPoint("DomainName[LX_INDICADOR_PRESENCA]")]
        public short LX_INDICADOR_PRESENCA { get; set; }

        [Column("LOCAL_EMBARQUE",  TypeName = "varchar", Order=34 )]
        [Display(Name="Local de Embarque")]
        [MaxLength(60)]
        public string LOCAL_EMBARQUE { get; set; }

        [Column("LOCAL_DESPACHO",  TypeName = "varchar", Order=35 )]
        [Display(Name="Local de Despacho")]
        [MaxLength(60)]
        public string LOCAL_DESPACHO { get; set; }

        [Column("ID_UF_EMBARQUE",  TypeName = "smallint", Order=36 )]
        [Display(Name="Sigla UF Embarque")]
        [ForeignKey("GEO_UNIDADE_FEDERACAO")]
        [Precision(5)]
        public System.Nullable<short> ID_UF_EMBARQUE { get; set; }

		#endregion

		#region Navigation
                
        public virtual STK_ROMANEIO STK_ROMANEIO { get; set; }
        
        public virtual TBC_PFJ TBC_PFJ { get; set; }
        
        public virtual TBC_TRANSPORTADORA TBC_TRANSPORTADORA { get; set; }
        
        public virtual LNF_CONDICAO_PAGAMENTO LNF_CONDICAO_PAGAMENTO { get; set; }
        
        public virtual CRM_PFJ CRM_PFJ { get; set; }
        
        public virtual GEO_UNIDADE_FEDERACAO GEO_UNIDADE_FEDERACAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class STK_ROMANEIO_NFConfiguration : EntityTypeConfiguration<STK_ROMANEIO_NF>
    {
		partial void Init();

        public STK_ROMANEIO_NFConfiguration()
            : base()
        {

            Property(p => p.VALOR_FRETE).HasPrecision(15,2).IsOptional();
            Property(p => p.VALOR_SEGURO).HasPrecision(15,2).IsOptional();
            Property(p => p.VALOR_DESPESA).HasPrecision(15,2).IsOptional();
            Property(p => p.VALOR_DESCONTO_NF).HasPrecision(15,2).IsOptional();
            Property(p => p.VALOR_ACRESCIMO_NF).HasPrecision(15,2).IsOptional();

            Init();
        }
    }

}
