//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("STK_ROMANEIO_AJUSTE_DETALHE", Schema = "LX_STK")]
    public partial class STK_ROMANEIO_AJUSTE_DETALHE : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_STK_ROMANEIO_AJUSTE_ITEM",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Display(Name="Id Stk Romaneio Ajuste Item")]
        [ForeignKey("STK_ROMANEIO_AJUSTE_ITEM")]
        public int ID_STK_ROMANEIO_AJUSTE_ITEM { get; set; }

        [Column("ID_STK_LOTE",  TypeName = "int", Order=2 )]
        [Display(Name="Id Stk Lote")]
        [ForeignKey("STK_LOTE")]
        public System.Nullable<int> ID_STK_LOTE { get; set; }

        [Column("ID_STK_LOCALIZACAO",  TypeName = "int", Order=3 )]
        [ForeignKey("STK_LOCALIZACAO")]
        [Precision(10)]
        public System.Nullable<int> ID_STK_LOCALIZACAO { get; set; }

        [Column("NUMERO_SERIE",  TypeName = "varchar", Order=4 )]
        [MaxLength(40)]
        public string NUMERO_SERIE { get; set; }

		#endregion

		#region Navigation
                
        public virtual STK_ROMANEIO_AJUSTE_ITEM STK_ROMANEIO_AJUSTE_ITEM { get; set; }
        
        public virtual STK_LOTE STK_LOTE { get; set; }
        
        public virtual STK_LOCALIZACAO STK_LOCALIZACAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class STK_ROMANEIO_AJUSTE_DETALHEConfiguration : EntityTypeConfiguration<STK_ROMANEIO_AJUSTE_DETALHE>
    {
		partial void Init();

        public STK_ROMANEIO_AJUSTE_DETALHEConfiguration()
            : base()
        {


            Init();
        }
    }

}
