//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("TBC_PFJ_ATRIBUTO_ESPECIALISTA", Schema = "LX_TBC")]
    public partial class TBC_PFJ_ATRIBUTO_ESPECIALISTA : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PFJ",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [ForeignKey("TBC_PFJ")]
        [Precision(10)]
        public int ID_PFJ { get; set; }

        [Key]
        [Column("ID_PFJ_CHAVE_SK",  TypeName = "int", Order=2 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Precision(10)]
        public int ID_PFJ_CHAVE_SK { get; set; }

        [Column("ID_PFJ_ATRIBUTO_01",  TypeName = "smallint", Order=3 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_01 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_02",  TypeName = "smallint", Order=4 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_02 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_03",  TypeName = "smallint", Order=5 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_03 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_04",  TypeName = "smallint", Order=6 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_04 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_05",  TypeName = "smallint", Order=7 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_05 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_06",  TypeName = "smallint", Order=8 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_06 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_07",  TypeName = "smallint", Order=9 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_07 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_08",  TypeName = "smallint", Order=10 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_08 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_09",  TypeName = "smallint", Order=11 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_09 { get; set; }

        [Column("ID_PFJ_ATRIBUTO_10",  TypeName = "smallint", Order=12 )]
        [Precision(5)]
        public System.Nullable<short> ID_PFJ_ATRIBUTO_10 { get; set; }

        [Column("UID_TABELA",  TypeName = "uniqueidentifier", Order=13 )]
        public System.Nullable<Guid> UID_TABELA { get; set; }

		#endregion

		#region Navigation
                
        public virtual TBC_PFJ TBC_PFJ { get; set; }


        

		
		
		#endregion
    }
	

    public partial class TBC_PFJ_ATRIBUTO_ESPECIALISTAConfiguration : EntityTypeConfiguration<TBC_PFJ_ATRIBUTO_ESPECIALISTA>
    {
		partial void Init();

        public TBC_PFJ_ATRIBUTO_ESPECIALISTAConfiguration()
            : base()
        {


            Init();
        }
    }

}
