//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("TBC_PFJ_END_ELETRONICO", Schema = "LX_TBC")]
    public partial class TBC_PFJ_END_ELETRONICO : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        public int ID_LINX { get; set; }

        [Key]
        [Column("ID_PFJ_END_ELETRONICO",  TypeName = "int", Order=1 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_PFJ_END_ELETRONICO { get; set; }

        [Column("ID_PFJ",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("TBC_PFJ")]
        [Precision(10)]
        public int ID_PFJ { get; set; }

        [Column("LX_TIPO_END_ELETRONICO",  TypeName = "tinyint", Order=3 )]
        [Required]
        [Precision(3)]
        public byte LX_TIPO_END_ELETRONICO { get; set; }

        [Column("ENDERECO_ELETRONICO",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(250)]
        public string ENDERECO_ELETRONICO { get; set; }

        [Column("OBS_END_ELETRONICO",  TypeName = "varchar", Order=5 )]
        [MaxLength(250)]
        public string OBS_END_ELETRONICO { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=6 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

		#endregion

		#region Navigation
                
        public virtual TBC_PFJ TBC_PFJ { get; set; }


        

		
		
		#endregion
    }
	

    public partial class TBC_PFJ_END_ELETRONICOConfiguration : EntityTypeConfiguration<TBC_PFJ_END_ELETRONICO>
    {
		partial void Init();

        public TBC_PFJ_END_ELETRONICOConfiguration()
            : base()
        {


            Init();
        }
    }

}
