//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("TCS_USUARIO", Schema = "LX_TCS")]
    public partial class TCS_USUARIO 
    {
		
		public TCS_USUARIO()
		{
			this.UID_USUARIO = Guid.NewGuid();
		}

		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_USUARIO",  TypeName = "bigint", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        public long ID_USUARIO { get; set; }

        [Column("UID_USUARIO",  TypeName = "uniqueidentifier", Order=1 )]
        [Required]
        public Guid UID_USUARIO { get; set; }

        [Column("NOME_USUARIO",  TypeName = "varchar", Order=2 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(250)]
        public string NOME_USUARIO { get; set; }

        [Column("ID_LINX",  TypeName = "int", Order=3 )]
        [Required]
        public int ID_LINX { get; set; }

        [Column("EMAIL",  TypeName = "varchar", Order=4 )]
        [MaxLength(250)]
        public string EMAIL { get; set; }

        [Column("LX_PFJ_FISICA_JURIDICA",  TypeName = "tinyint", Order=5 )]
        [FunctionalPoint("DomainName[LX_PFJ_FISICA_JURIDICA]")]
        public System.Nullable<byte> LX_PFJ_FISICA_JURIDICA { get; set; }

        [Column("CNPJ_CPF",  TypeName = "varchar", Order=6 )]
        [MaxLength(20)]
        public string CNPJ_CPF { get; set; }

        [Column("INSCR_ESTADUAL_RG",  TypeName = "varchar", Order=7 )]
        [MaxLength(20)]
        public string INSCR_ESTADUAL_RG { get; set; }

        [Column("LX_TIPO_LOGRADOURO",  TypeName = "tinyint", Order=8 )]
        [FunctionalPoint("DomainName[LxTipoLogradouro]")]
        public System.Nullable<byte> LX_TIPO_LOGRADOURO { get; set; }

        [Column("LOGRADOURO",  TypeName = "varchar", Order=9 )]
        [MaxLength(60)]
        public string LOGRADOURO { get; set; }

        [Column("NUMERO",  TypeName = "varchar", Order=10 )]
        [MaxLength(60)]
        public string NUMERO { get; set; }

        [Column("COMPLEMENTO",  TypeName = "varchar", Order=11 )]
        [MaxLength(60)]
        public string COMPLEMENTO { get; set; }

        [Column("BAIRRO",  TypeName = "varchar", Order=12 )]
        [MaxLength(60)]
        public string BAIRRO { get; set; }

        [Column("MUNICIPIO",  TypeName = "varchar", Order=13 )]
        [MaxLength(60)]
        public string MUNICIPIO { get; set; }

        [Column("UF",  TypeName = "varchar", Order=14 )]
        [MaxLength(4)]
        public string UF { get; set; }

        [Column("CEP",  TypeName = "varchar", Order=15 )]
        [MaxLength(10)]
        public string CEP { get; set; }

        [Column("OBS_ENDERECO",  TypeName = "varchar", Order=16 )]
        [MaxLength(250)]
        public string OBS_ENDERECO { get; set; }

        [Column("FONE_CELULAR",  TypeName = "varchar", Order=17 )]
        [MaxLength(20)]
        public string FONE_CELULAR { get; set; }

        [Column("FONE_FIXO",  TypeName = "varchar", Order=18 )]
        [MaxLength(20)]
        public string FONE_FIXO { get; set; }

        [Column("RAMAL",  TypeName = "varchar", Order=19 )]
        [MaxLength(6)]
        public string RAMAL { get; set; }

        [Column("DATA_CADASTRO",  TypeName = "datetime", Order=20 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_CADASTRO { get; set; }

        [Column("DATA_ALTERACAO",  TypeName = "datetime", Order=21 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA_ALTERACAO { get; set; }

		#endregion

		#region Navigation
        

                
        //Origin Document: LogAuditoria.bmd
        [InverseProperty("TCS_USUARIO")]
        public virtual ICollection<ADT_LOG_OCORRENCIA> ADT_LOG_OCORRENCIA_LISTA { get; set; }
        
        //Origin Document: Vendedor.bmd
        [InverseProperty("TCS_USUARIO")]
        public virtual ICollection<LJV_VENDEDOR> LJV_VENDEDOR_LISTA { get; set; }
        
        //Origin Document: LogManutencaoDocumento.bmd
        [InverseProperty("TCS_USUARIO")]
        public virtual ICollection<MVD_LOG_MANUTENCAO_ITEM> MVD_LOG_MANUTENCAO_ITEM_LISTA { get; set; }
        
        //Origin Document: OperacaoFinalidadePerfil.bmd
        [InverseProperty("TCS_USUARIO")]
        public virtual ICollection<TCS_USUARIO_PERFIL> TCS_USUARIO_PERFIL_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class TCS_USUARIOConfiguration : EntityTypeConfiguration<TCS_USUARIO>
    {
		partial void Init();

        public TCS_USUARIOConfiguration()
            : base()
        {


            Init();
        }
    }

}
