//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("TCS_PERFIL", Schema = "LX_TCS")]
    public partial class TCS_PERFIL : ILinx
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_PERFIL",  TypeName = "bigint", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public long ID_PERFIL { get; set; }

        [Column("DESC_PERFIL",  TypeName = "varchar", Order=1 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_PERFIL { get; set; }

        [Column("INDICA_PERFIL_LINX",  TypeName = "bit", Order=2 )]
        [Required]
        [Precision(1)]
        public bool INDICA_PERFIL_LINX { get; set; }

        [Column("PERFIL_AUTENTICACAO",  TypeName = "varchar", Order=3 )]
        [MaxLength(250)]
        public string PERFIL_AUTENTICACAO { get; set; }

        [Column("INATIVO",  TypeName = "bit", Order=4 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

        [Column("ID_LINX",  TypeName = "int", Order=5 )]
        [Required]
        public int ID_LINX { get; set; }

		#endregion

		#region Navigation
        

                
        //Origin Document: OperacaoFinalidadePerfil.bmd
        [InverseProperty("TCS_PERFIL")]
        public virtual ICollection<LCF_OPERACAO_PERFIL> LCF_OPERACAO_PERFIL_LISTA { get; set; }
        
        //Origin Document: OperacaoFinalidadePerfil.bmd
        [InverseProperty("TCS_PERFIL")]
        public virtual ICollection<TCS_USUARIO_PERFIL> TCS_USUARIO_PERFIL_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class TCS_PERFILConfiguration : EntityTypeConfiguration<TCS_PERFIL>
    {
		partial void Init();

        public TCS_PERFILConfiguration()
            : base()
        {


            Init();
        }
    }

}
