//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("V_ATENDIMENTO_ITEM_PEDIDO", Schema = "LX_LJV")]
    public partial class V_ATENDIMENTO_ITEM_PEDIDO : ILinx, IGpecon
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("ID_LINX",  TypeName = "int", Order=0 )]
        [Required]
        [Precision(10)]
        public int ID_LINX { get; set; }

        [Column("ID_GPECON",  TypeName = "int", Order=1 )]
        [Required]
        [Precision(10)]
        public int ID_GPECON { get; set; }

        [Column("DATA",  TypeName = "datetime", Order=2 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> DATA { get; set; }

        [Key]
        [Column("ID_LOJA",  TypeName = "int", Order=3 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Precision(10)]
        public int ID_LOJA { get; set; }

        [Column("COD_LOJA",  TypeName = "char", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(20)]
        public string COD_LOJA { get; set; }

        [Column("DESC_LOJA",  TypeName = "varchar", Order=5 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_LOJA { get; set; }

        [Column("ID_BANDEIRA_REDE",  TypeName = "int", Order=6 )]
        [Precision(10)]
        public System.Nullable<int> ID_BANDEIRA_REDE { get; set; }

        [Column("ID_LJV_CANAL_VENDA",  TypeName = "int", Order=7 )]
        [Required]
        [Precision(10)]
        public int ID_LJV_CANAL_VENDA { get; set; }

        [Column("COD_CANAL_VENDA",  TypeName = "char", Order=8 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(6)]
        public string COD_CANAL_VENDA { get; set; }

        [Column("DESC_CANAL_VENDA",  TypeName = "varchar", Order=9 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_CANAL_VENDA { get; set; }

        [Column("ID_SKU",  TypeName = "int", Order=10 )]
        [Required]
        [Precision(10)]
        public int ID_SKU { get; set; }

        [Column("COD_SKU",  TypeName = "varchar", Order=11 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(25)]
        public string COD_SKU { get; set; }

        [Column("DESC_SKU",  TypeName = "varchar", Order=12 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(120)]
        public string DESC_SKU { get; set; }

        [Column("ID_ARTIGO",  TypeName = "int", Order=13 )]
        [Required]
        [Precision(10)]
        public int ID_ARTIGO { get; set; }

        [Column("COD_ARTIGO",  TypeName = "char", Order=14 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(15)]
        public string COD_ARTIGO { get; set; }

        [Column("DESC_ARTIGO",  TypeName = "varchar", Order=15 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_ARTIGO { get; set; }

        [Column("ID_ATRIBUTO_01",  TypeName = "int", Order=16 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_01 { get; set; }

        [Column("COD_ATRIBUTO_01",  TypeName = "char", Order=17 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_01 { get; set; }

        [Column("DESC_ATRIBUTO_01",  TypeName = "varchar", Order=18 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_01 { get; set; }

        [Column("ID_ATRIBUTO_02",  TypeName = "int", Order=19 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_02 { get; set; }

        [Column("COD_ATRIBUTO_02",  TypeName = "char", Order=20 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(10)]
        public string COD_ATRIBUTO_02 { get; set; }

        [Column("DESC_ATRIBUTO_02",  TypeName = "varchar", Order=21 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_02 { get; set; }

        [Column("ID_ATRIBUTO_03",  TypeName = "int", Order=22 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_03 { get; set; }

        [Column("COD_ATRIBUTO_03",  TypeName = "char", Order=23 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(10)]
        public string COD_ATRIBUTO_03 { get; set; }

        [Column("DESC_ATRIBUTO_03",  TypeName = "varchar", Order=24 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_03 { get; set; }

        [Column("ID_ATRIBUTO_04",  TypeName = "int", Order=25 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_04 { get; set; }

        [Column("COD_ATRIBUTO_04",  TypeName = "char", Order=26 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(10)]
        public string COD_ATRIBUTO_04 { get; set; }

        [Column("DESC_ATRIBUTO_04",  TypeName = "varchar", Order=27 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_04 { get; set; }

        [Column("ID_ATRIBUTO_05",  TypeName = "int", Order=28 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_05 { get; set; }

        [Column("COD_ATRIBUTO_05",  TypeName = "char", Order=29 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_05 { get; set; }

        [Column("DESC_ATRIBUTO_05",  TypeName = "varchar", Order=30 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_05 { get; set; }

        [Column("ID_ATRIBUTO_06",  TypeName = "int", Order=31 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_06 { get; set; }

        [Column("COD_ATRIBUTO_06",  TypeName = "char", Order=32 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_06 { get; set; }

        [Column("DESC_ATRIBUTO_06",  TypeName = "varchar", Order=33 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_06 { get; set; }

        [Column("ID_ATRIBUTO_07",  TypeName = "int", Order=34 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_07 { get; set; }

        [Column("COD_ATRIBUTO_07",  TypeName = "char", Order=35 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_07 { get; set; }

        [Column("DESC_ATRIBUTO_07",  TypeName = "varchar", Order=36 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_07 { get; set; }

        [Column("ID_ATRIBUTO_08",  TypeName = "int", Order=37 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_08 { get; set; }

        [Column("COD_ATRIBUTO_08",  TypeName = "char", Order=38 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_08 { get; set; }

        [Column("DESC_ATRIBUTO_08",  TypeName = "varchar", Order=39 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_08 { get; set; }

        [Column("ID_ATRIBUTO_09",  TypeName = "int", Order=40 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_09 { get; set; }

        [Column("COD_ATRIBUTO_09",  TypeName = "char", Order=41 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_09 { get; set; }

        [Column("DESC_ATRIBUTO_09",  TypeName = "varchar", Order=42 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_09 { get; set; }

        [Column("ID_ATRIBUTO_10",  TypeName = "int", Order=43 )]
        [Precision(10)]
        public System.Nullable<int> ID_ATRIBUTO_10 { get; set; }

        [Column("COD_ATRIBUTO_10",  TypeName = "char", Order=44 )]
        [MaxLength(10)]
        public string COD_ATRIBUTO_10 { get; set; }

        [Column("DESC_ATRIBUTO_10",  TypeName = "varchar", Order=45 )]
        [MaxLength(60)]
        public string DESC_ATRIBUTO_10 { get; set; }

        [Column("QTDE_ITEM_TABELA_PRINCIPAL",  TypeName = "numeric", Order=46 )]
        [Required]
        [Precision(10)]
        [Scale(3)]
        public decimal QTDE_ITEM_TABELA_PRINCIPAL { get; set; }

        [Column("PRECO_BRUTO_ITEM_TABELA_PRINCIPAL",  TypeName = "numeric", Order=47 )]
        [Required]
        [Precision(15)]
        [Scale(3)]
        public decimal PRECO_BRUTO_ITEM_TABELA_PRINCIPAL { get; set; }

        [Column("VALOR_TOTAL_ITEM_TABELA_PRINCIPAL",  TypeName = "numeric", Order=48 )]
        [Precision(26)]
        [Scale(6)]
        public System.Nullable<decimal> VALOR_TOTAL_ITEM_TABELA_PRINCIPAL { get; set; }

        [Column("QTDE_ITEM_TABELA_SECUNDARIA",  TypeName = "numeric", Order=49 )]
        [Required]
        [Precision(10)]
        [Scale(3)]
        public decimal QTDE_ITEM_TABELA_SECUNDARIA { get; set; }

        [Column("PRECO_BRUTO_ITEM_TABELA_SECUNDARIA",  TypeName = "numeric", Order=50 )]
        [Required]
        [Precision(15)]
        [Scale(3)]
        public decimal PRECO_BRUTO_ITEM_TABELA_SECUNDARIA { get; set; }

        [Column("VALOR_TOTAL_ITEM_TABELA_SECUNDARIA",  TypeName = "numeric", Order=51 )]
        [Precision(26)]
        [Scale(6)]
        public System.Nullable<decimal> VALOR_TOTAL_ITEM_TABELA_SECUNDARIA { get; set; }

        [Column("QTDE_PEDIDO",  TypeName = "numeric", Order=52 )]
        [Required]
        [Precision(15)]
        [Scale(5)]
        public decimal QTDE_PEDIDO { get; set; }

        [Column("QTDE_ENTREGAR",  TypeName = "numeric", Order=53 )]
        [Required]
        [Precision(15)]
        [Scale(5)]
        public decimal QTDE_ENTREGAR { get; set; }

        [Column("VALOR_TOTAL_PEDIDO",  TypeName = "numeric", Order=54 )]
        [Precision(31)]
        [Scale(8)]
        public System.Nullable<decimal> VALOR_TOTAL_PEDIDO { get; set; }

        [Column("VALOR_TOTAL_ENTREGAR",  TypeName = "numeric", Order=55 )]
        [Precision(31)]
        [Scale(8)]
        public System.Nullable<decimal> VALOR_TOTAL_ENTREGAR { get; set; }

        [Column("QTDE_ESTOQUE",  TypeName = "numeric", Order=56 )]
        [Precision(38)]
        [Scale(5)]
        public System.Nullable<decimal> QTDE_ESTOQUE { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class V_ATENDIMENTO_ITEM_PEDIDOConfiguration : EntityTypeConfiguration<V_ATENDIMENTO_ITEM_PEDIDO>
    {
		partial void Init();

        public V_ATENDIMENTO_ITEM_PEDIDOConfiguration()
            : base()
        {

            Property(p => p.QTDE_ITEM_TABELA_PRINCIPAL).HasPrecision(10,3);
            Property(p => p.PRECO_BRUTO_ITEM_TABELA_PRINCIPAL).HasPrecision(15,3);
            Property(p => p.VALOR_TOTAL_ITEM_TABELA_PRINCIPAL).HasPrecision(26,6).IsOptional();
            Property(p => p.QTDE_ITEM_TABELA_SECUNDARIA).HasPrecision(10,3);
            Property(p => p.PRECO_BRUTO_ITEM_TABELA_SECUNDARIA).HasPrecision(15,3);
            Property(p => p.VALOR_TOTAL_ITEM_TABELA_SECUNDARIA).HasPrecision(26,6).IsOptional();
            Property(p => p.QTDE_PEDIDO).HasPrecision(15,5);
            Property(p => p.QTDE_ENTREGAR).HasPrecision(15,5);
            Property(p => p.VALOR_TOTAL_PEDIDO).HasPrecision(31,8).IsOptional();
            Property(p => p.VALOR_TOTAL_ENTREGAR).HasPrecision(31,8).IsOptional();
            Property(p => p.QTDE_ESTOQUE).HasPrecision(38,5).IsOptional();

            Init();
        }
    }

}
