//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Operacional.BM
{

    [Table("VW_DESCONTO_ATENDIMENTO_ITEM", Schema = "LX_LJV")]
    public partial class VW_DESCONTO_ATENDIMENTO_ITEM : ILinx, IGpecon
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Column("LX_DESCONTO",  TypeName = "varchar", Order=0 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(26)]
        public string LX_DESCONTO { get; set; }

        [Column("ID_LINX",  TypeName = "int", Order=1 )]
        [Required]
        [Precision(10)]
        public int ID_LINX { get; set; }

        [Column("ID_GPECON",  TypeName = "int", Order=2 )]
        [Required]
        [Precision(10)]
        public int ID_GPECON { get; set; }

        [Column("ID_ATENDIMENTO",  TypeName = "bigint", Order=3 )]
        [Required]
        [Precision(19)]
        public long ID_ATENDIMENTO { get; set; }

        [Column("NUMERO_ATENDIMENTO",  TypeName = "varchar", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(12)]
        public string NUMERO_ATENDIMENTO { get; set; }

        [Column("DATA_ATENDIMENTO",  TypeName = "datetime", Order=5 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime DATA_ATENDIMENTO { get; set; }

        [Column("HORA_FIM",  TypeName = "datetime", Order=6 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> HORA_FIM { get; set; }

        [Column("LX_TIPO_ATENDIMENTO",  TypeName = "tinyint", Order=7 )]
        [Required]
        [Precision(3)]
        public byte LX_TIPO_ATENDIMENTO { get; set; }

        [Column("ID_CAIXA_CTRL",  TypeName = "bigint", Order=8 )]
        [Required]
        [Precision(19)]
        public long ID_CAIXA_CTRL { get; set; }

        [Column("ID_FILIAL_PFJ",  TypeName = "int", Order=9 )]
        [Precision(10)]
        public System.Nullable<int> ID_FILIAL_PFJ { get; set; }

        [Column("ID_LOJA",  TypeName = "int", Order=10 )]
        [Required]
        [Precision(10)]
        public int ID_LOJA { get; set; }

        [Key]
        [Column("ID_ATENDIMENTO_ITEM",  TypeName = "bigint", Order=11 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Precision(19)]
        public long ID_ATENDIMENTO_ITEM { get; set; }

        [Column("ID_MOTIVO_DESCONTO",  TypeName = "smallint", Order=12 )]
        [Precision(5)]
        public System.Nullable<short> ID_MOTIVO_DESCONTO { get; set; }

        [Column("LX_ORIGEM_DESCONTO",  TypeName = "int", Order=13 )]
        [Precision(10)]
        public System.Nullable<int> LX_ORIGEM_DESCONTO { get; set; }

        [Column("VALOR_DESCONTO_TOTAL",  TypeName = "numeric", Order=14 )]
        [Precision(38)]
        [Scale(6)]
        public System.Nullable<decimal> VALOR_DESCONTO_TOTAL { get; set; }

		#endregion

		#region Navigation
        

        

		
		
		#endregion
    }
	

    public partial class VW_DESCONTO_ATENDIMENTO_ITEMConfiguration : EntityTypeConfiguration<VW_DESCONTO_ATENDIMENTO_ITEM>
    {
		partial void Init();

        public VW_DESCONTO_ATENDIMENTO_ITEMConfiguration()
            : base()
        {

            Property(p => p.VALOR_DESCONTO_TOTAL).HasPrecision(38,6).IsOptional();

            Init();
        }
    }

}
