var langToolbar = function () {
    return "en-us";
};

var langPropsToolbar = function () {
    return Labels = {
        // Menu
        CONNECT: "Connect",
        CONNECT_LOCAL_CSV: "To local CSV",
        CONNECT_LOCAL_OCSV: "To local OCSV",
        CONNECT_REMOTE_CSV: "To remote CSV",
        CONNECT_REMOTE_CSV_MOBILE: "CSV",
        CONNECT_OLAP: "To OLAP (XMLA)",
        CONNECT_OLAP_MOBILE: "OLAP",
        OPEN: "Open",
        LOCAL_REPORT: "Local report",
        REMOTE_REPORT: "Remote report",
        REMOTE_REPORT_MOBILE: "Report",
        SAVE: "Save",
        GRID: "Grid",
        CHARTS: "Charts",
        CHARTS_BAR: "Bar",
        CHARTS_LINE: "Line",
        CHARTS_SCATTER: "Scatter",
        CHARTS_PIE: "Pie",
        CHARTS_BAR_STACK: "Bar stack",
        CHARTS_BAR_LINE: "Bar line",
        CHARTS_MULTIPLE: "Multiple values",
        SPLIT_VIEW: "Grid and Graph",
        SPLIT_RIGHT: "Right",			
        SPLIT_LEFT: "Left",			
        SPLIT_TOP: "Top",			
        SPLIT_BOTTOM: "Bottom",
        FORMAT: "Format",
        FORMAT_CELLS: "Format cells",
        FORMAT_CELLS_MOBILE: "Format",
        CONDITIONAL_FORMATTING: "Conditional formatting",
        CONDITIONAL_FORMATTING_MOBILE: "Conditional",
        OPTIONS: "Options",
        STYLES: "Styles",
        STYLES_BLUEBERRY: "Blueberry",
        STYLES_ASPHALT: "Asphalt",
        STYLES_NAVY: "Navy",
        STYLES_EMERALD: "Emerald",
        STYLES_COCOA: "Cocoa",
        STYLES_RASPBERRY: "Raspberry",
        FULLSCREEN: "Fullscreen",
        ZOOM: "Zoom",
        EXPORT: "Export",
        EXPORT_PRINT: "Print",
        EXPORT_HTML: "To HTML",
        EXPORT_CSV: "To CSV",
        EXPORT_EXCEL: "To Excel",
        EXPORT_IMAGE: "To Image",
        EXPORT_PDF: "To PDF",
        FIELDS: "Fields",

        // General
        OK: "OK",
        APPLY: "Apply",
        CANCEL: "Cancel",
        VALUE: "Value",
        // Connect
        OPEN_REMOTE_CSV: "Open remote CSV",
        OLAP_CONNECTION_TOOL: "OLAP connection tool",
        SELECT_DATA_SOURCE: "Select data source",
        SELECT_CATALOG: "Select catalog",
        SELECT_CUBE: "Select cube",
        PROXY_URL: "Proxy URL",
        DATA_SOURCE_INFO: "Data Source Info",
        CATALOG: "Catalog",
        CUBE: "Cube",
        CREDENTIALS: "credentials",
        USERNAME: "Username",
        PASSWORD: "Password",
        // Report
        OPEN_REMOTE_REPORT: "Open remote report",
        // Custom labels			
        LABELS: "Titles",			
        LABEL_NAME: "Name",			
        LABEL_VALUE: "Value",
        // Format
        TEXT_ALIGN: "Text align",
        ALIGN_LEFT: "left",
        ALIGN_RIGHT: "right",
        NONE: "None",
        SPACE: "(Space)",
        THOUSAND_SEPARATOR: "Thousand separator",
        DECIMAL_SEPARATOR: "Decimal separator",
        DECIMAL_PLACES: "Decimal places",
        CURRENCY_SYMBOL: "Currency symbol",
        CURRENCY_ALIGN: "Currency align",
        NULL_VALUE: "Null value",
        // Conditional
        ADD_CONDITION: "+ Add condition",
        LESS_THAN: "Less than",
        LESS_THAN_OR_EQUAL: "Less than or equal to",
        GREATER_THAN: "Greater than",
        GREATER_THAN_OR_EQUAL: "Greater than or equal to",
        EQUAL_TO: "Equal to",
        NOT_EQUAL_TO: "Not equal to",
        BETWEEN: "Between",
        ALL_VALUES: "All values",
        AND: "and",
        // Options
        LAYOUT_OPTIONS: "Layout options",
        GRAND_TOTALS: "Grand totals",
        SUBTOTALS: "subTotals",
        CHARTS_OPTIONS: "Charts",
        VIEW_TYPE: "Display Type",
        OFF_FOR_ROWS_AND_COLUMNS: "Off for rows and columns",
        ON_FOR_ROWS_AND_COLUMNS: "On for rows and columns",
        ON_FOR_ROWS: "On for rows only",
        ON_FOR_COLUMNS: "On for columns only",
        DO_NOT_SHOW_SUBTOTALS: "Do not show subtotals",
        SHOW_ALL_SUBTOTALS: "Show all subtotals",
        CLASSIC_VIEW: "Classic view",
        REVERSE_CHARTS: "Invert rows and columns",
        // Export PDF
        CHOOSE_PAGE_ORIENTATION: "Choose page orientation",
        LANDSCAPE: "Landscape",
        PORTRAIT: "Portrait",
        CUSTOM_LABELS: "Titles",
        //PERMISSIONS:			
        PERMISSIONS: "Permissions",


        //LINX
        SAVE_AS_LINX: "Salvar Como",
        DELETE_LAYOUT_LINX: "Delete layout"
    }
};