//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Framework.Loja.BM
{

    [Table("LJV_MODULO_MENU", Schema = "dbo")]
    public partial class LJV_MODULO_MENU 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_MODULO_MENU", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required]
        [Display(Name="Id Ljv Modulo Menu")]
        public long ID_MODULO_MENU { get; set; }

        [Column("ID_MODULO_MENU_SUPERIOR", Order=1 )]
        [Display(Name="Id Ljv Modulo Menu")]
        [ForeignKey("LJV_MODULO_MENU1")]
        public System.Nullable<long> ID_MODULO_MENU_SUPERIOR { get; set; }

        [Column("ID_MODULO", Order=2 )]
        [Required]
        [Display(Name="ID LjvModulo")]
        [ForeignKey("LJV_MODULO")]
        public long ID_MODULO { get; set; }

        [Column("DESC_MODULO_MENU", Order=3 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(100)]
        public string DESC_MODULO_MENU { get; set; }

        [Column("NOME_CURTO", Order=4 )]
        [Required(AllowEmptyStrings=true)]
        [MaxLength(40)]
        public string NOME_CURTO { get; set; }

        [Column("ORDEM_NAVEGACAO", Order=5 )]
        [Required]
        [Precision(3)]
        public byte ORDEM_NAVEGACAO { get; set; }

        [Column("ICONE", Order=6 )]
        [MaxLength(40)]
        public string ICONE { get; set; }

        [Column("LX_COR_FUNDO", Order=7 )]
        public System.Nullable<int> LX_COR_FUNDO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_MODULO LJV_MODULO { get; set; }
        
        public virtual LJV_MODULO_MENU LJV_MODULO_MENU1 { get; set; }


                
        //Origin Document: ModuloTransacao.bmd
        public virtual ICollection<LJV_MODULO_MENU> LJV_MODULO_MENU_LISTA { get; set; }
        
        //Origin Document: ModuloTransacao.bmd
        [InverseProperty("LJV_MODULO_MENU")]
        public virtual ICollection<LJV_TRANSACAO_MENU> LJV_TRANSACAO_MENU_LISTA { get; set; }


		
		
		#endregion
    }
	

    public partial class LJV_MODULO_MENUConfiguration : EntityTypeConfiguration<LJV_MODULO_MENU>
    {
		partial void Init();

        public LJV_MODULO_MENUConfiguration()
            : base()
        {


            Init();
        }
    }

}
