//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace Linx.Framework.Loja.BM
{

    [Table("LJV_TRANSACAO_MENU", Schema = "dbo")]
    public partial class LJV_TRANSACAO_MENU 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_TRANSACAO_MENU", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="Id Ljv Transacao Menu Autorizacao")]
        public long ID_TRANSACAO_MENU { get; set; }

        [Column("ID_MODULO_MENU", Order=1 )]
        [Required]
        [Display(Name="Id Ljv Modulo Menu")]
        [ForeignKey("LJV_MODULO_MENU")]
        public long ID_MODULO_MENU { get; set; }

        [Column("ID_TRANSACAO", Order=2 )]
        [Required]
        [Display(Name="Id Ljv Transacao")]
        [ForeignKey("LJV_TRANSACAO")]
        public long ID_TRANSACAO { get; set; }

        [Column("ORDEM_NAVEGACAO", Order=3 )]
        [Required]
        [Precision(3)]
        public byte ORDEM_NAVEGACAO { get; set; }

        [Column("INATIVO", Order=4 )]
        [Required]
        [Precision(1)]
        public bool INATIVO { get; set; }

		#endregion

		#region Navigation
                
        public virtual LJV_MODULO_MENU LJV_MODULO_MENU { get; set; }
        
        public virtual LJV_TRANSACAO LJV_TRANSACAO { get; set; }


        

		
		
		#endregion
    }
	

    public partial class LJV_TRANSACAO_MENUConfiguration : EntityTypeConfiguration<LJV_TRANSACAO_MENU>
    {
		partial void Init();

        public LJV_TRANSACAO_MENUConfiguration()
            : base()
        {


            Init();
        }
    }

}
