<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>LinxHostCore</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>LinxHostCore</PackageId>
    <NetStandardImplicitPackageVersion>1.6.0</NetStandardImplicitPackageVersion>
	<PostBuildEvent />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\swagger\ui\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\**\*;Views;Areas\**\Views">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.0-beta1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.9-dmr" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.1-beta1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.1.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.7.12" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Data\Linx.Data.Core\Linx.Data.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Data\Linx.DataService\Linx.DataService.Core\Linx.DataService.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Data\Linx.DataService\Linx.DomainService.Core\Linx.DomainService.Core.csproj" />
    <ProjectReference Include="..\..\..\Linx.LinqExtensions.Library\Desktop\Linx.LinqExtensions.Core\Linx.LinqExtensions.Core.csproj" />
    <ProjectReference Include="..\..\..\Linx.Security.Core\Linx.Security.Core.csproj" />
    <ProjectReference Include="..\..\..\Linx.Tools.Library\Desktop\Linx.Tools.Core\Linx.Tools.Core.csproj" />
    <ProjectReference Include="..\Core\Modular.Core\Modular.Core.csproj" />
    <ProjectReference Include="..\OData\Microsoft.AspNetCore.OData\Microsoft.AspNetCore.OData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AppSettings.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BusinessModules\BM\" />
    <Folder Include="BusinessModules\BV\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="StartService.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>


</Project>
