//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace LinxTraining003.BM
{

    [Table("VENDA", Schema = "dbo")]
    public partial class VENDA 
    {
		
		#region Query Methods
		#endregion

		#region Data Properties	
        [Key]
        [Column("ID_VENDA",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int ID_VENDA { get; set; }

        [Column("EMISSAO",  TypeName = "datetime", Order=1 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime EMISSAO { get; set; }

        [Column("ID_CLIENTE",  TypeName = "int", Order=2 )]
        [Required]
        [ForeignKey("CLIENTE")]
        [Precision(10)]
        public int ID_CLIENTE { get; set; }

        [Column("QTDE_TOTAL",  TypeName = "int", Order=3 )]
        [Required]
        [Precision(10)]
        public int QTDE_TOTAL { get; set; }

        [Column("VALOR_TOTAL",  TypeName = "numeric", Order=4 )]
        [Required]
        [Precision(13)]
        [Scale(2)]
        public decimal VALOR_TOTAL { get; set; }

		#endregion

		#region Navigation
                
        public virtual CLIENTE CLIENTE { get; set; }


                
        //Origin Document: ProdutoClienteVenda.bmd
        [InverseProperty("VENDA")]
        public virtual ICollection<VENDA_ITEM> VENDA_ITEM_LISTA { get; set; }

		#endregion
    }
	

    public class VENDAConfiguration : EntityTypeConfiguration<VENDA>
    {
        public VENDAConfiguration()
            : base()
        {

            Property(p => p.VALOR_TOTAL).HasPrecision(13,2);
        }
    }

}
