-- Auth access audit (success + denial) with sliding-window lockout support.
-- Schema: LX_TCS

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'LX_TCS')
    EXEC(N'CREATE SCHEMA [LX_TCS]');
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.tables t
    INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = N'LX_TCS' AND t.name = N'TCS_LOG_ACESSO_AUTH'
)
BEGIN 
    CREATE TABLE [LX_TCS].[TCS_LOG_ACESSO_AUTH]
    (
        [ID_TCS_LOG_ACESSO_AUTH] INT IDENTITY(1,1) NOT NULL,
        [DATA_HORA] DATETIME NOT NULL,
        [TIPO_EVENTO] CHAR(1) NOT NULL, -- S = success, F = failure, U = unlock, P = password change (self-service)
        [NOME_USUARIO] NVARCHAR(256) NOT NULL,
        [ID_USUARIO] BIGINT NULL,
        [ID_LINX] INT NULL,
        [CODIGO_ERRO] NVARCHAR(20) NULL,
        [DESCRICAO] NVARCHAR(500) NULL,
        [QTD_TENTATIVAS] INT NOT NULL CONSTRAINT [DF_TCS_LOG_ACESSO_AUTH_QTD] DEFAULT ((0)),
        [ENDERECO_IP] NVARCHAR(64) NULL,
        [NOME_MAQUINA] NVARCHAR(128) NULL,
        [CANAL] NVARCHAR(50) NULL,
        [INDICA_CONTA_TENTATIVA] BIT NOT NULL CONSTRAINT [DF_TCS_LOG_ACESSO_AUTH_CONTA] DEFAULT ((0)),
        [INDICA_BLOQUEIO] BIT NOT NULL CONSTRAINT [DF_TCS_LOG_ACESSO_AUTH_BLOQ] DEFAULT ((0)),
        [INDICA_USUARIO_SERVICO] BIT NOT NULL CONSTRAINT [DF_TCS_LOG_ACESSO_AUTH_INDICA_USUARIO_SERVICO] DEFAULT ((0)),
        CONSTRAINT [XPK_TCS_LOG_ACESSO_AUTH] PRIMARY KEY CLUSTERED ([ID_TCS_LOG_ACESSO_AUTH] ASC)
    );

    CREATE NONCLUSTERED INDEX [IX_TCS_LOG_ACESSO_AUTH_USUARIO_DATA]
        ON [LX_TCS].[TCS_LOG_ACESSO_AUTH] ([NOME_USUARIO], [DATA_HORA] DESC);
END
GO

IF COL_LENGTH(N'LX_TCS.TCS_LOG_ACESSO_AUTH', N'INDICA_USUARIO_SERVICO') IS NULL
BEGIN
    ALTER TABLE [LX_TCS].[TCS_LOG_ACESSO_AUTH]
        ADD [INDICA_USUARIO_SERVICO] BIT NOT NULL
            CONSTRAINT [DF_TCS_LOG_ACESSO_AUTH_INDICA_USUARIO_SERVICO] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'LX_TCS.TCS_LOG_ACESSO_AUTH', N'ID_LINX') IS NULL
BEGIN
    ALTER TABLE [LX_TCS].[TCS_LOG_ACESSO_AUTH]
        ADD [ID_LINX] INT NULL;
END
GO
