-- Linx MFA (TOTP) tables. Schema: LX_TCS
-- TABLE_ORIGIN stores API codes: UX | PDV | CLIENTE_CONNECT
-- Company: no row = MFA enabled. Row with INDICA_MFA_HABILITADO = 0 = off.

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'LX_TCS')
    EXEC(N'CREATE SCHEMA [LX_TCS]');
GO

IF COL_LENGTH(N'LX_TCS.TCS_USUARIO_AUTENTICACAO', N'INDICA_UTILIZA_SSO') IS NULL
BEGIN
    ALTER TABLE [LX_TCS].[TCS_USUARIO_AUTENTICACAO]
        ADD [INDICA_UTILIZA_SSO] BIT NOT NULL CONSTRAINT [DF_TCS_USUARIO_AUT_SSO] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'LX_TCS.TCS_USUARIO_AUTENTICACAO', N'INDICA_UTILIZA_MFA') IS NULL
BEGIN
    ALTER TABLE [LX_TCS].[TCS_USUARIO_AUTENTICACAO]
        ADD [INDICA_UTILIZA_MFA] BIT NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t
    INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = N'LX_TCS' AND t.name = N'TCS_GPECON_MFA')
BEGIN
    CREATE TABLE [LX_TCS].[TCS_GPECON_MFA]
    (
        [ID_GPCON] INT NOT NULL,
        [INDICA_MFA_HABILITADO] BIT NOT NULL CONSTRAINT [DF_TCS_GPECON_MFA_HAB] DEFAULT ((1)),
        [INDICA_DISPOSITIVO_CONFIAVEL] BIT NOT NULL CONSTRAINT [DF_TCS_GPECON_MFA_DEV] DEFAULT ((0)),
        [QTD_DIAS_CONFIANCA] INT NOT NULL CONSTRAINT [DF_TCS_GPECON_MFA_DIAS] DEFAULT ((0)),
        [CREATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TCS_GPECON_MFA_CRT] DEFAULT (GETDATE()),
        [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TCS_GPECON_MFA_UPD] DEFAULT (GETDATE()),
        CONSTRAINT [XPK_TCS_GPECON_MFA] PRIMARY KEY CLUSTERED ([ID_GPCON] ASC)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t
    INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = N'LX_TCS' AND t.name = N'TCS_USUARIO_MFA')
BEGIN
    CREATE TABLE [LX_TCS].[TCS_USUARIO_MFA]
    (
        [TABLE_ORIGIN] VARCHAR(32) NOT NULL,
        [ID_GPCON] INT NOT NULL,
        [ID_USER_MFA] BIGINT NOT NULL,
        [ATIVO] BIT NOT NULL CONSTRAINT [DF_TCS_USUARIO_MFA_ATIVO] DEFAULT ((0)),
        [ACCESS_SECRET] NVARCHAR(512) NULL,
        [QTD_TENTATIVAS_TOTP] INT NOT NULL CONSTRAINT [DF_TCS_USUARIO_MFA_QTD] DEFAULT ((0)),
        [DATA_BLOQUEIO_ATE] DATETIME NULL,
        [CREATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TCS_USUARIO_MFA_CRT] DEFAULT (GETDATE()),
        [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TCS_USUARIO_MFA_UPD] DEFAULT (GETDATE()),
        CONSTRAINT [XPK_TCS_USUARIO_MFA] PRIMARY KEY CLUSTERED ([TABLE_ORIGIN] ASC, [ID_GPCON] ASC, [ID_USER_MFA] ASC)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t
    INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = N'LX_TCS' AND t.name = N'TCS_USUARIO_MFA_DISPOSITIVO')
BEGIN
    CREATE TABLE [LX_TCS].[TCS_USUARIO_MFA_DISPOSITIVO]
    (
        [ID_DISPOSITIVO] BIGINT IDENTITY(1,1) NOT NULL,
        [TABLE_ORIGIN] VARCHAR(32) NOT NULL,
        [ID_GPCON] INT NOT NULL,
        [ID_USER_MFA] BIGINT NOT NULL,
        [TOKEN_HASH] NVARCHAR(128) NOT NULL,
        [USER_AGENT] NVARCHAR(256) NULL,
        [DATA_EXPIRACAO] DATETIME NOT NULL,
        [CREATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TCS_USUARIO_MFA_DEV_CRT] DEFAULT (GETDATE()),
        [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TCS_USUARIO_MFA_DEV_UPD] DEFAULT (GETDATE()),
        CONSTRAINT [XPK_TCS_USUARIO_MFA_DISPOSITIVO] PRIMARY KEY CLUSTERED ([ID_DISPOSITIVO] ASC)
    );
    CREATE NONCLUSTERED INDEX [IX_TCS_USUARIO_MFA_DISPOSITIVO_KEY]
        ON [LX_TCS].[TCS_USUARIO_MFA_DISPOSITIVO] ([TABLE_ORIGIN], [ID_GPCON], [ID_USER_MFA], [TOKEN_HASH]);
END
GO
