//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace LinxTraining002.BM
{

    [Table("Loja", Schema = "dbo")]
    public partial class Loja 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_Loja",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="ID Loja")]
        public int ID_Loja { get; set; }

        [Column("DescLoja",  TypeName = "varchar", Order=1 )]
        [MaxLength(100)]
        public string DescLoja { get; set; }

        [Column("LojaFisica",  TypeName = "bit", Order=2 )]
        public System.Nullable<bool> LojaFisica { get; set; }

        [Column("DataAbertura",  TypeName = "datetime", Order=3 )]
        public System.Nullable<DateTime> DataAbertura { get; set; }

        [Column("ID_Cidade",  TypeName = "int", Order=4 )]
        [Required]
        [Display(Name="ID Cidade")]
        [ForeignKey("Cidade")]
        public int ID_Cidade { get; set; }

        [Column("ID_Estado",  TypeName = "int", Order=5 )]
        [Required]
        [Display(Name="ID Estado")]
        [ForeignKey("Estado")]
        public int ID_Estado { get; set; }

		#endregion

		#region Navigation
                
        public virtual Estado Estado { get; set; }
        
        public virtual Cidade Cidade { get; set; }


        

		
		
		#endregion
    }
	

    public class LojaConfiguration : EntityTypeConfiguration<Loja>
    {
        public LojaConfiguration()
            : base()
        {

        }
    }

}
