//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace LinxTraining002.BM
{

    [Table("VendaDetalhe", Schema = "dbo")]
    public partial class VendaDetalhe 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("ID_VendaDetalhe",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Display(Name="ID VendaDetalhe")]
        public int ID_VendaDetalhe { get; set; }

        [Column("ID_Vendas",  TypeName = "int", Order=1 )]
        [Required]
        [ForeignKey("Vendas")]
        [Precision(10)]
        public int ID_Vendas { get; set; }

        [Column("Produto",  TypeName = "varchar", Order=2 )]
        [MaxLength(10)]
        public string Produto { get; set; }

        [Column("Preco",  TypeName = "numeric", Order=3 )]
        [Precision(10)]
        [Scale(2)]
        public System.Nullable<decimal> Preco { get; set; }

        [Column("Quantidade",  TypeName = "int", Order=4 )]
        public System.Nullable<int> Quantidade { get; set; }

        [Column("Hora",  TypeName = "datetime", Order=5 )]
        public System.Nullable<DateTime> Hora { get; set; }

		#endregion

		#region Navigation
                
        public virtual Vendas Vendas { get; set; }


        

		
		
		#endregion
    }
	

    public class VendaDetalheConfiguration : EntityTypeConfiguration<VendaDetalhe>
    {
        public VendaDetalheConfiguration()
            : base()
        {

            Property(p => p.Preco).HasPrecision(10,2).IsOptional();
        }
    }

}
