//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace Linx.Internet.Application.Framework.Web
//{
//    using System.Web.Mvc;

//    /// <summary>
//    /// Provides view engine support for imported areas.
//    /// </summary>
//    public class AreaViewEngine : RazorViewEngine
//    {
//        #region Constructor
//        /// <summary>
//        /// Initialises a new instance of <see cref="AreaViewEngine" />.
//        /// </summary>
//        public AreaViewEngine()
//        { 
//            MasterLocationFormats = new[]
//                                    {
//                                        "~/Areas/{1}/Views/{0}.master",
//                                        "~/Views/{1}/{0}.master",
//                                        "~/Views/Shared/{0}.master"
//                                    };

//            ViewLocationFormats = new[]
//                                    {
//                                        "~/Areas/{1}/Views/{0}.aspx",
//                                        "~/Views/{1}/{0}.aspx",
//                                        "~/Views/Shared/{0}.aspx"
//                                    };

//            AreaPartialViewLocationFormats = new[]
//                                    {
//                                        "~/Areas/{1}/Views/{0}.ascx",
//                                        "~/Views/{1}/{0}.ascx",
//                                        "~/Views/Shared/{0}.ascx"
//                                    };
//        }
//        #endregion
//    }
//}
