//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace LinxTraining001.BM
{

    [Table("CurrencyRate", Schema = "Sales")]
    public partial class CurrencyRate 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("CurrencyRateID",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int CurrencyRateID { get; set; }

        [Column("CurrencyRateDate",  TypeName = "datetime", Order=1 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime CurrencyRateDate { get; set; }

        [Column("FromCurrencyCode",  TypeName = "char", Order=2 )]
        [Required(AllowEmptyStrings=true)]
        [ForeignKey("Currency")]
        [MaxLength(3)]
        public string FromCurrencyCode { get; set; }

        [Column("ToCurrencyCode",  TypeName = "char", Order=3 )]
        [Required(AllowEmptyStrings=true)]
        [ForeignKey("Currency1")]
        [MaxLength(3)]
        public string ToCurrencyCode { get; set; }

        [Column("AverageRate",  TypeName = "numeric", Order=4 )]
        [Required]
        [Precision(19)]
        [Scale(4)]
        public decimal AverageRate { get; set; }

        [Column("EndOfDayRate",  TypeName = "numeric", Order=5 )]
        [Required]
        [Precision(19)]
        [Scale(4)]
        public decimal EndOfDayRate { get; set; }

        [Column("ModifiedDate",  TypeName = "datetime", Order=6 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime ModifiedDate { get; set; }

		#endregion

		#region Navigation
                
        public virtual Currency Currency { get; set; }
        
        public virtual Currency Currency1 { get; set; }


                
        //Origin Document: ModelLFW001.bmd
        [InverseProperty("CurrencyRate")]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader_LISTA { get; set; }


		
		
		#endregion
    }
	

    public class CurrencyRateConfiguration : EntityTypeConfiguration<CurrencyRate>
    {
        public CurrencyRateConfiguration()
            : base()
        {

            Property(p => p.AverageRate).HasPrecision(19,4);
            Property(p => p.EndOfDayRate).HasPrecision(19,4);
        }
    }

}
