//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Linx.Tools;
using System.Linq;
using Linx.LinqExtensions.Dynamic;
using Linx.LinqExtensions.Query;

namespace LinxTraining001.BM
{

    [Table("PurchaseOrderHeader", Schema = "Purchasing")]
    public partial class PurchaseOrderHeader 
    {
		
		#region Query Methods
		#endregion



		#region Data Properties	
        [Key]
        [Column("PurchaseOrderID",  TypeName = "int", Order=0 )]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Precision(10)]
        public int PurchaseOrderID { get; set; }

        [Column("RevisionNumber",  TypeName = "tinyint", Order=1 )]
        [Required]
        [Precision(3)]
        public byte RevisionNumber { get; set; }

        [Column("Status",  TypeName = "tinyint", Order=2 )]
        [Required]
        [Precision(3)]
        public byte Status { get; set; }

        [Column("EmployeeID",  TypeName = "int", Order=3 )]
        [Required]
        [Precision(10)]
        public int EmployeeID { get; set; }

        [Column("VendorID",  TypeName = "int", Order=4 )]
        [Required]
        [ForeignKey("Vendor")]
        [Precision(10)]
        public int VendorID { get; set; }

        [Column("ShipMethodID",  TypeName = "int", Order=5 )]
        [Required]
        [ForeignKey("ShipMethod")]
        [Precision(10)]
        public int ShipMethodID { get; set; }

        [Column("OrderDate",  TypeName = "datetime", Order=6 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime OrderDate { get; set; }

        [Column("ShipDate",  TypeName = "datetime", Order=7 )]
        [Precision(23)]
        [Scale(3)]
        public System.Nullable<DateTime> ShipDate { get; set; }

        [Column("SubTotal",  TypeName = "numeric", Order=8 )]
        [Required]
        [Precision(19)]
        [Scale(4)]
        public decimal SubTotal { get; set; }

        [Column("TaxAmt",  TypeName = "numeric", Order=9 )]
        [Required]
        [Precision(19)]
        [Scale(4)]
        public decimal TaxAmt { get; set; }

        [Column("Freight",  TypeName = "numeric", Order=10 )]
        [Required]
        [Precision(19)]
        [Scale(4)]
        public decimal Freight { get; set; }

        [Column("TotalDue",  TypeName = "numeric", Order=11 )]
        [Required]
        [Precision(19)]
        [Scale(4)]
        public decimal TotalDue { get; set; }

        [Column("ModifiedDate",  TypeName = "datetime", Order=12 )]
        [Required]
        [Precision(23)]
        [Scale(3)]
        public DateTime ModifiedDate { get; set; }

		#endregion

		#region Navigation
                
        public virtual ShipMethod ShipMethod { get; set; }
        
        public virtual Vendor Vendor { get; set; }


                
        //Origin Document: ModelLFW001.bmd
        [InverseProperty("PurchaseOrderHeader")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetail_LISTA { get; set; }


		
		
		#endregion
    }
	

    public class PurchaseOrderHeaderConfiguration : EntityTypeConfiguration<PurchaseOrderHeader>
    {
        public PurchaseOrderHeaderConfiguration()
            : base()
        {

            Property(p => p.SubTotal).HasPrecision(19,4);
            Property(p => p.TaxAmt).HasPrecision(19,4);
            Property(p => p.Freight).HasPrecision(19,4);
            Property(p => p.TotalDue).HasPrecision(19,4);
        }
    }

}
