-- Service-user flag on authentication users.
-- Schema: LX_TCS / Table: TCS_USUARIO_AUTENTICACAO

IF COL_LENGTH(N'LX_TCS.TCS_USUARIO_AUTENTICACAO', N'INDICA_USUARIO_SERVICO') IS NULL
BEGIN
    ALTER TABLE [LX_TCS].[TCS_USUARIO_AUTENTICACAO]
        ADD [INDICA_USUARIO_SERVICO] BIT NOT NULL
            CONSTRAINT [DF_TCS_USUARIO_AUTENTICACAO_INDICA_USUARIO_SERVICO] DEFAULT ((0));
END
GO
